# Topic 2 — Pandas DataFrame Basics: Comprehensive Learning & Practice — 📖 Lesson

This notebook is a complete practice guide for the major Pandas DataFrame topics.

## How to use this notebook

For every topic you will get:

1. **Explanation**
2. **Working example**
3. **Practice problem**
4. **Empty code cell** for your own solution

Try the practice cells yourself before searching for an answer.

## Topics covered

- DataFrame and Series fundamentals
- Creating DataFrames
- CSV / Excel / JSON / SQL input
- Inspection and statistics
- Columns, rows, `loc`, `iloc`
- Filtering and conditions
- `isin`, `query`, string filtering
- Adding, updating, renaming and deleting
- Sorting and indexing
- Copying DataFrames
- Missing values
- Duplicates
- Data types and conversion
- String operations
- Date/time operations
- `apply`, `map`, `replace`, `assign`
- NumPy conditional operations
- Aggregation
- `groupby` and `agg`
- `merge`, `join`, `concat`
- `pivot`, `pivot_table`, `melt`
- `stack`, `unstack`
- MultiIndex
- `where`, `clip`
- `value_counts`, `nunique`, `unique`
- Ranking
- `rolling`, `cumsum`, `cummax`
- `shift` and percentage change
- `explode`
- `json_normalize`
- Correlation
- Memory usage and categorical data
- Large CSV files and chunks
- Exporting data
- A complete data-cleaning workflow
- A final capstone challenge

> 📚 **Course navigation** — you are in **Topic 02: Pandas DataFrame Basics**
> ⬅️ Previous: [Topic 01 — Python Basics](../Topic_01_Python_Basics/Topic_01_Lesson.ipynb)  ·  ➡️ Next: [Topic 03 — Handling Missing Values](../Topic_03_Handling_Missing_Values/Topic_03_Lesson.ipynb)  ·  🗂️ [All topics](../Topic_00_All_Topics_Index.ipynb)

<details><summary>Full course sequence (click to expand)</summary>

| # | Topic | Lesson | Practice & Solutions |
|---|---|---|---|
| 01 | Python Basics | [📖 Lesson](../Topic_01_Python_Basics/Topic_01_Lesson.ipynb) | [✍️ Practice](../Topic_01_Python_Basics/Topic_01_Practice_Solutions.ipynb) |
| **▶ 02 ◀** | **Pandas DataFrame Basics** | [📖 Lesson](../Topic_02_Pandas_DataFrame_Basics/Topic_02_Lesson.ipynb) | [✍️ Practice](../Topic_02_Pandas_DataFrame_Basics/Topic_02_Practice_Solutions.ipynb) |
| 03 | Handling Missing Values | [📖 Lesson](../Topic_03_Handling_Missing_Values/Topic_03_Lesson.ipynb) | [✍️ Practice](../Topic_03_Handling_Missing_Values/Topic_03_Practice_Solutions.ipynb) |
| 04 | Normalization & Standardization | [📖 Lesson](../Topic_04_Normalization_Standardization/Topic_04_Lesson.ipynb) | [✍️ Practice](../Topic_04_Normalization_Standardization/Topic_04_Practice_Solutions.ipynb) |
| 05 | Detecting & Treating Outliers | [📖 Lesson](../Topic_05_Outliers/Topic_05_Lesson.ipynb) | [✍️ Practice](../Topic_05_Outliers/Topic_05_Practice_Solutions.ipynb) |
| 06 | Encoding Techniques | [📖 Lesson](../Topic_06_Encoding_Techniques/Topic_06_Lesson.ipynb) | [✍️ Practice](../Topic_06_Encoding_Techniques/Topic_06_Practice_Solutions.ipynb) |
| 07 | Exploratory Data Analysis (EDA) | [📖 Lesson](../Topic_07_Exploratory_Data_Analysis/Topic_07_Lesson.ipynb) | [✍️ Practice](../Topic_07_Exploratory_Data_Analysis/Topic_07_Practice_Solutions.ipynb) |
| 08 | Data Visualization | [📖 Lesson](../Topic_08_Data_Visualization/Topic_08_Lesson.ipynb) | [✍️ Practice](../Topic_08_Data_Visualization/Topic_08_Practice_Solutions.ipynb) |
| 09 | Pandas Data Manipulation | [📖 Lesson](../Topic_09_Pandas_Data_Manipulation/Topic_09_Lesson.ipynb) | [✍️ Practice](../Topic_09_Pandas_Data_Manipulation/Topic_09_Practice_Solutions.ipynb) |
| 10 | Combining DataFrames | [📖 Lesson](../Topic_10_Combining_DataFrames/Topic_10_Lesson.ipynb) | [✍️ Practice](../Topic_10_Combining_DataFrames/Topic_10_Practice_Solutions.ipynb) |
| 11 | Feature Engineering | [📖 Lesson](../Topic_11_Feature_Engineering/Topic_11_Lesson.ipynb) | [✍️ Practice](../Topic_11_Feature_Engineering/Topic_11_Practice_Solutions.ipynb) |
| 11b | KBinsDiscretizer (Discretization) | [📖 Lesson](../Topic_11b_KBinsDiscretizer/Topic_11b_Lesson.ipynb) | [✍️ Practice](../Topic_11b_KBinsDiscretizer/Topic_11b_Practice_Solutions.ipynb) |
| 12 | Correlation & Multicollinearity | [📖 Lesson](../Topic_12_Correlation_Multicollinearity/Topic_12_Lesson.ipynb) | [✍️ Practice](../Topic_12_Correlation_Multicollinearity/Topic_12_Practice_Solutions.ipynb) |
| 13 | Data Transformation & Skewness | [📖 Lesson](../Topic_13_Data_Transformation_Skewness/Topic_13_Lesson.ipynb) | [✍️ Practice](../Topic_13_Data_Transformation_Skewness/Topic_13_Practice_Solutions.ipynb) |
| 14 | Statistics for Data Science | [📖 Lesson](../Topic_14_Statistics_for_Data_Science/Topic_14_Lesson.ipynb) | [✍️ Practice](../Topic_14_Statistics_for_Data_Science/Topic_14_Practice_Solutions.ipynb) |
| 15 | Probability for Data Science & ML | [📖 Lesson](../Topic_15_Probability_for_Data_Science_ML/Topic_15_Lesson.ipynb) | [✍️ Practice](../Topic_15_Probability_for_Data_Science_ML/Topic_15_Practice_Solutions.ipynb) |
| 16 | Feature Selection | [📖 Lesson](../Topic_16_Feature_Selection/Topic_16_Lesson.ipynb) | [✍️ Practice](../Topic_16_Feature_Selection/Topic_16_Practice_Solutions.ipynb) |
| 17 | Machine Learning | [📖 Lesson](../Topic_17_Machine_Learning/Topic_17_Lesson.ipynb) | [✍️ Practice](../Topic_17_Machine_Learning/Topic_17_Practice_Solutions.ipynb) |

</details>

## 📋 Lesson Index — What This Lesson Covers

This lesson has **53 sections**. Click any one to jump to it.

- [1. Setup](#sec-1)
- [2. DataFrame and Series](#sec-2)
- [3. Creating DataFrames in Different Ways](#sec-3)
- [4. Reading Data](#sec-4)
- [5. Inspection](#sec-5)
- [6. Selecting Columns](#sec-6)
- [7. `iloc`](#sec-7)
- [8. `loc`](#sec-8)
- [9. Filtering](#sec-9)
- [10. `isin()` and `query()`](#sec-10)
- [11. Adding and Updating Columns](#sec-11)
- [12. Conditional Columns with NumPy](#sec-12)
- [13. Renaming and Dropping](#sec-13)
- [14. Sorting](#sec-14)
- [15. Indexes](#sec-15)
- [16. Copying](#sec-16)
- [17. Missing Values](#sec-17)
- [18. Duplicates](#sec-18)
- [19. Data Type Conversion](#sec-19)
- [20. String Operations](#sec-20)
- [21. Date and Time](#sec-21)
- [22. `apply()`](#sec-22)
- [23. `map()`](#sec-23)
- [24. `replace()`](#sec-24)
- [25. `assign()`](#sec-25)
- [26. Aggregation](#sec-26)
- [27. `unique()`, `nunique()`, `value_counts()`](#sec-27)
- [28. GroupBy](#sec-28)
- [29. Multiple Aggregations](#sec-29)
- [30. `reset_index()`](#sec-30)
- [31. `concat()`](#sec-31)
- [32. `merge()`](#sec-32)
- [33. `join()`](#sec-33)
- [34. Pivot Tables](#sec-34)
- [35. `pivot()`](#sec-35)
- [36. `melt()`](#sec-36)
- [37. `stack()` and `unstack()`](#sec-37)
- [38. MultiIndex](#sec-38)
- [39. `where()` and `mask`](#sec-39)
- [40. `clip()`](#sec-40)
- [41. Ranking](#sec-41)
- [42. Cumulative Calculations](#sec-42)
- [43. `shift()`](#sec-43)
- [44. Rolling Windows](#sec-44)
- [45. `explode()`](#sec-45)
- [46. `json_normalize()`](#sec-46)
- [47. Correlation](#sec-47)
- [48. Memory Usage](#sec-48)
- [49. Categorical Data](#sec-49)
- [50. Large CSV Files and Chunks](#sec-50)
- [51. Exporting Data](#sec-51)
- [52. A Professional Data-Cleaning Workflow](#sec-52)
- [55. Quick Reference / Cheat Sheet](#sec-53)

> ✍️ Practice problems with solutions: [Topic_02_Practice_Solutions.ipynb](Topic_02_Practice_Solutions.ipynb)  ·  🗂️ [All topics](../Topic_00_All_Topics_Index.ipynb)

> 🔗 **How this notebook connects to the rest of the course (FIX-2026-09-27)**
>
> This is the *broad tour* of Pandas — every tool once, briefly. Several sections are taught in much more depth later:
>
> | Sections here | Deep dive |
> |---|---|
> | 17 Missing values | **Topic 3 — Handling Missing Values** |
> | 40 `clip()` | **Topic 5 — Outliers** (capping / winsorizing) |
> | 49 Categorical data | **Topic 6 — Encoding Techniques** |
> | 11–15, 20–30, 34–46 (columns, strings, dates, apply/map, groupby, pivot/melt, window functions, explode, json) | **Topic 9 — Pandas Data Manipulation** |
> | 31–33 `concat` / `merge` / `join` | **Topic 10 — Combining DataFrames** |
> | 47 Correlation | **Topic 12 — Correlation & Multicollinearity** |
>
> Reference solutions for all practices, the mini project and the capstone are at the end, in **Practice Solutions**.

<a id="sec-1"></a>
# 1. Setup

In [1]:
import pandas as pd
import numpy as np

print("Pandas version:", pd.__version__)

Pandas version: 3.0.3

<a id="sec-2"></a>
# 2. DataFrame and Series

A **DataFrame** is a two-dimensional table.

A **Series** is a one-dimensional labeled array, commonly representing one DataFrame column.

Think:

- DataFrame = complete table
- Series = one column
- Index = row labels
- Columns = named fields

In [2]:
data = {
    "Name": ["Ali", "Ahmed", "Sara", "Hamza"],
    "Age": [25, 30, 28, 35],
    "City": ["Lahore", "Karachi", "Lahore", "Islamabad"],
    "Salary": [80000, 90000, 95000, 120000]
}

df = pd.DataFrame(data)
df

    Name  Age       City  Salary
0    Ali   25     Lahore   80000
1  Ahmed   30    Karachi   90000
2   Sara   28     Lahore   95000
3  Hamza   35  Islamabad  120000

In [3]:
print(type(df))
print(type(df["Name"]))
print(type(df[["Name"]]))

<class 'pandas.DataFrame'>
<class 'pandas.Series'>
<class 'pandas.DataFrame'>

> ✍️ **Practice time:** Practice 1 — open [Topic_02_Practice_Solutions.ipynb](Topic_02_Practice_Solutions.ipynb) to solve it and see the solution.

<a id="sec-3"></a>
# 3. Creating DataFrames in Different Ways

Common approaches:

- Dictionary of lists
- List of lists
- List of dictionaries
- Empty DataFrame

In [4]:
import pandas as pd

# ============================================
# 1. Dictionary of Lists
# ============================================

data = {
    "Name": ["Ali", "Ahmed", "Sara"],
    "Age": [20, 21, 19],
    "Score": [85, 92, 78]
}

df1 = pd.DataFrame(data)

print("1. Dictionary of Lists:")
print(df1)


# ============================================
# 2. List of Lists
# ============================================

data = [
    ["Ali", 20, 85],
    ["Ahmed", 21, 92],
    ["Sara", 19, 78]
]

df2 = pd.DataFrame(
    data,
    columns=["Name", "Age", "Score"]
)

print("\n2. List of Lists:")
print(df2)


# ============================================
# 3. List of Dictionaries
# ============================================

data = [
    {"Name": "Ali", "Age": 20, "Score": 85},
    {"Name": "Ahmed", "Age": 21, "Score": 92},
    {"Name": "Sara", "Age": 19, "Score": 78}
]

df3 = pd.DataFrame(data)

print("\n3. List of Dictionaries:")
print(df3)


# ============================================
# 4. Empty DataFrame
# ============================================

df4 = pd.DataFrame()

print("\n4. Empty DataFrame:")
print(df4)


# ============================================
# Empty DataFrame with Columns
# ============================================

df5 = pd.DataFrame(columns=["Name", "Age", "Score"])

print("\n5. Empty DataFrame with Columns:")
print(df5)

1. Dictionary of Lists:
    Name  Age  Score
0    Ali   20     85
1  Ahmed   21     92
2   Sara   19     78

2. List of Lists:
    Name  Age  Score
0    Ali   20     85
1  Ahmed   21     92
2   Sara   19     78

3. List of Dictionaries:
    Name  Age  Score
0    Ali   20     85
1  Ahmed   21     92
2   Sara   19     78

4. Empty DataFrame:
Empty DataFrame
Columns: []
Index: []

5. Empty DataFrame with Columns:
Empty DataFrame
Columns: [Name, Age, Score]
Index: []

> ✍️ **Practice time:** Practice 2 — open [Topic_02_Practice_Solutions.ipynb](Topic_02_Practice_Solutions.ipynb) to solve it and see the solution.

> 🧩 **Data used by the next sections** — this code comes from *Practice 2* (in the practice notebook). Run it so the examples below work.

In [5]:
# Your solution
data = [{"product":"Books", "price":20,"quantity":3,"category":"Urdu"},
        {"product":"Books", "price":20,"quantity":3,"category":"Urdu"},
        {"product":"Books", "price":20,"quantity":3,"category":"Urdu"},
        {"product":"Books", "price":20,"quantity":3,"category":"Urdu"},
        {"product":"Books", "price":20,"quantity":3,"category":"Urdu"}
        ]
df =pd.DataFrame(data)
df

  product  price  quantity category
0   Books     20         3     Urdu
1   Books     20         3     Urdu
2   Books     20         3     Urdu
3   Books     20         3     Urdu
4   Books     20         3     Urdu

<a id="sec-4"></a>
# 4. Reading Data

Important input functions:

```python
pd.read_csv()
pd.read_excel()
pd.read_json()
pd.read_sql()
```

The examples below show syntax. Replace filenames or database connections with your own resources when needed.

In [6]:
# CSV
# sales = pd.read_csv("sales.csv")

# Excel
# sales = pd.read_excel("sales.xlsx", sheet_name="Sheet1")

# JSON
# sales = pd.read_json("sales.json")

# SQL
# sales = pd.read_sql("SELECT * FROM sales", connection)

> ✍️ **Practice time:** Practice 3 — open [Topic_02_Practice_Solutions.ipynb](Topic_02_Practice_Solutions.ipynb) to solve it and see the solution.

> 🧩 **Data used by the next sections** — this code comes from *Practice 3* (in the practice notebook). Run it so the examples below work.

In [7]:
# Your solution
winequality = pd.read_csv("../data/winequality-red.csv")
winequality.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,9.8,5
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,9.8,5
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,9.8,6
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5

<a id="sec-5"></a>
# 5. Inspection

These are among the first methods to use when receiving a dataset:

- `head()`
- `tail()`
- `shape`
- `columns`
- `index`
- `dtypes`
- `info()`
- `describe()`

In [8]:
print("Shape:", winequality.shape)
print("Columns:", winequality.columns.tolist())
print("Index:", winequality.index)
print()

winequality.head()

Shape: (1599, 12)
Columns: ['fixed acidity', 'volatile acidity', 'citric acid', 'residual sugar', 'chlorides', 'free sulfur dioxide', 'total sulfur dioxide', 'density', 'pH', 'sulphates', 'alcohol', 'quality']
Index: RangeIndex(start=0, stop=1599, step=1)

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,9.8,5
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,9.8,5
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,9.8,6
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5

In [9]:
df.tail(2)

  product  price  quantity category
3   Books     20         3     Urdu
4   Books     20         3     Urdu

In [10]:
print(winequality.dtypes)
print()
winequality.info()

fixed acidity           float64
volatile acidity        float64
citric acid             float64
residual sugar          float64
chlorides               float64
free sulfur dioxide     float64
total sulfur dioxide    float64
density                 float64
pH                      float64
sulphates               float64
alcohol                 float64
quality                   int64
dtype: object

<class 'pandas.DataFrame'>
RangeIndex: 1599 entries, 0 to 1598
Data columns (total 12 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   fixed acidity         1599 non-null   float64
 1   volatile acidity      1599 non-null   float64
 2   citric acid           1599 non-null   float64
 3   residual sugar        1599 non-null   float64
 4   chlorides             1599 non-null   float64
 5   free sulfur dioxide   1599 non-null   float64
 6   total sulfur dioxide  1599 non-null   float64
 7   density               1599 non-null   float64
 8   pH                    1599 non-null   float64
 9   sulphates             1599 non-null   float64
 10  alcohol               1599 non-null   float64
 11  quality               1599 non-null   int64
dtypes: float64(11), int64(1)
memory usage: 150.0 KB

In [11]:
winequality.describe()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
count,1599.000000,1599.000000,1599.000000,1599.000000,1599.000000,1599.000000,1599.000000,1599.000000,1599.000000,1599.000000,1599.000000,1599.000000
mean,8.319637,0.527821,0.270976,2.538806,0.087467,15.874922,46.467792,0.996747,3.311113,0.658149,10.422983,5.636023
std,1.741096,0.179060,0.194801,1.409928,0.047065,10.460157,32.895324,0.001887,0.154386,0.169507,1.065668,0.807569
min,4.600000,0.120000,0.000000,0.900000,0.012000,1.000000,6.000000,0.990070,2.740000,0.330000,8.400000,3.000000
25%,7.100000,0.390000,0.090000,1.900000,0.070000,7.000000,22.000000,0.995600,3.210000,0.550000,9.500000,5.000000
50%,7.900000,0.520000,0.260000,2.200000,0.079000,14.000000,38.000000,0.996750,3.310000,0.620000,10.200000,6.000000
75%,9.200000,0.640000,0.420000,2.600000,0.090000,21.000000,62.000000,0.997835,3.400000,0.730000,11.100000,6.000000
max,15.900000,1.580000,1.000000,15.500000,0.611000,72.000000,289.000000,1.003690,4.010000,2.000000,14.900000,8.000000

> ✍️ **Practice time:** Practice 4 — open [Topic_02_Practice_Solutions.ipynb](Topic_02_Practice_Solutions.ipynb) to solve it and see the solution.

<a id="sec-6"></a>
# 6. Selecting Columns

Single column:

```python
df["Name"]
```

Multiple columns:

```python
df[["Name", "Salary"]]
```

In [12]:
data = {
    "Name": ["Ali", "Ahmed", "Sara", "Hamza"],
    "Age": [25, 30, 28, 35],
    "City": ["Lahore", "Karachi", "Lahore", "Islamabad"],
    "Salary": [80000, 90000, 95000, 120000]
}

df = pd.DataFrame(data)

print(df["Name"])
print()
print(df[["Name", "Age"]])

0      Ali
1    Ahmed
2     Sara
3    Hamza
Name: Name, dtype: str

    Name  Age
0    Ali   25
1  Ahmed   30
2   Sara   28
3  Hamza   35

> ✍️ **Practice time:** Practice 5 — open [Topic_02_Practice_Solutions.ipynb](Topic_02_Practice_Solutions.ipynb) to solve it and see the solution.

<a id="sec-7"></a>
# 7. `iloc`

`iloc` selects using integer positions.

Examples:

```python
df.iloc[0]
df.iloc[0:3]
df.iloc[0, 1]
df.iloc[[0, 2]]
df.iloc[0:3, 0:2]
```

In [13]:
print(df)
print(df.iloc[0])
print()
print(df.iloc[0:3])
print()
print(df.iloc[0, 1])
print()
print(df.iloc[0:3, 0:2])

    Name  Age       City  Salary
0    Ali   25     Lahore   80000
1  Ahmed   30    Karachi   90000
2   Sara   28     Lahore   95000
3  Hamza   35  Islamabad  120000
Name         Ali
Age           25
City      Lahore
Salary     80000
Name: 0, dtype: object

    Name  Age     City  Salary
0    Ali   25   Lahore   80000
1  Ahmed   30  Karachi   90000
2   Sara   28   Lahore   95000

25

    Name  Age
0    Ali   25
1  Ahmed   30
2   Sara   28

> ✍️ **Practice time:** Practice 6 — open [Topic_02_Practice_Solutions.ipynb](Topic_02_Practice_Solutions.ipynb) to solve it and see the solution.

<a id="sec-8"></a>
# 8. `loc`

`loc` selects using labels.

Examples:

```python
df.loc[0]
df.loc[0, "Name"]
df.loc[0:2, ["Name", "Age"]]
```

In [14]:
print(df.loc[0])
print()
print(df.loc[0, "Name"])
print()
print(df.loc[0:3, ["Name", "Age"]])

Name         Ali
Age           25
City      Lahore
Salary     80000
Name: 0, dtype: object

Ali

    Name  Age
0    Ali   25
1  Ahmed   30
2   Sara   28
3  Hamza   35

> ✍️ **Practice time:** Practice 7 — open [Topic_02_Practice_Solutions.ipynb](Topic_02_Practice_Solutions.ipynb) to solve it and see the solution.

<a id="sec-9"></a>
# 9. Filtering

Filtering creates a Boolean condition and uses it to select rows.

```python
df[df["Age"] > 25]
```

For multiple conditions:

- `&` = AND
- `|` = OR
- `~` = NOT

Always put individual conditions in parentheses.

In [15]:
print(df[df["Age"] > 25])
print()
print(df[(df["Age"] > 25) & (df["Salary"] > 80000)])
print()
print(df[(df["City"] == "Lahore") | (df["City"] == "Karachi")])

    Name  Age       City  Salary
1  Ahmed   30    Karachi   90000
2   Sara   28     Lahore   95000
3  Hamza   35  Islamabad  120000

    Name  Age       City  Salary
1  Ahmed   30    Karachi   90000
2   Sara   28     Lahore   95000
3  Hamza   35  Islamabad  120000

    Name  Age     City  Salary
0    Ali   25   Lahore   80000
1  Ahmed   30  Karachi   90000
2   Sara   28   Lahore   95000

> ✍️ **Practice time:** Practice 8 — open [Topic_02_Practice_Solutions.ipynb](Topic_02_Practice_Solutions.ipynb) to solve it and see the solution.

<a id="sec-10"></a>
# 10. `isin()` and `query()`

`isin()` is useful when comparing against a list.

```python
df[df["City"].isin(["Lahore", "Karachi"])]
```

`query()` can make conditions easier to read:

```python
df.query("Age > 25 and Salary > 80000")
```

In [16]:
print(df[df["City"].isin(["Lahore", "Karachi"])])
print()
print(df[~df["City"].isin(["Lahore", "Karachi"])])
print()
print(df.query("Age > 25 and Salary > 80000"))

    Name  Age     City  Salary
0    Ali   25   Lahore   80000
1  Ahmed   30  Karachi   90000
2   Sara   28   Lahore   95000

    Name  Age       City  Salary
3  Hamza   35  Islamabad  120000

    Name  Age       City  Salary
1  Ahmed   30    Karachi   90000
2   Sara   28     Lahore   95000
3  Hamza   35  Islamabad  120000

> ✍️ **Practice time:** Practice 9 — open [Topic_02_Practice_Solutions.ipynb](Topic_02_Practice_Solutions.ipynb) to solve it and see the solution.

<a id="sec-11"></a>
# 11. Adding and Updating Columns

Columns can be created from existing values.

```python
df["AnnualSalary"] = df["Salary"] * 12
df["Bonus"] = df["Salary"] * 0.10
```

In [17]:
work_df = df.copy()

work_df["AnnualSalary"] = work_df["Salary"] * 12
work_df["Bonus"] = work_df["Salary"] * 0.10

work_df

    Name  Age       City  Salary  AnnualSalary    Bonus
0    Ali   25     Lahore   80000        960000   8000.0
1  Ahmed   30    Karachi   90000       1080000   9000.0
2   Sara   28     Lahore   95000       1140000   9500.0
3  Hamza   35  Islamabad  120000       1440000  12000.0

> ✍️ **Practice time:** Practice 10 — open [Topic_02_Practice_Solutions.ipynb](Topic_02_Practice_Solutions.ipynb) to solve it and see the solution.

<a id="sec-12"></a>
# 12. Conditional Columns with NumPy

`np.where()` is useful for two outcomes.

```python
np.where(condition, value_if_true, value_if_false)
```

`np.select()` is useful for multiple conditions.

In [18]:
employees = df.copy()

work_df["SalaryLevel"] = np.where(
    work_df["Salary"] >= 100000,
    "High",
    "Normal"
)

print(np.where(
    work_df["Salary"] >= 100000,
    "High",
    "Normal"
))

conditions = [
    work_df["Age"] < 30,
    work_df["Age"].between(30, 39),
    work_df["Age"] >= 40
]

choices = ["Young", "Middle", "Senior"]

work_df["AgeGroup"] = np.select(
    conditions,
    choices,
    default="Unknown"
)

work_df

['Normal' 'Normal' 'Normal' 'High']

    Name  Age       City  Salary  AnnualSalary    Bonus SalaryLevel AgeGroup
0    Ali   25     Lahore   80000        960000   8000.0      Normal    Young
1  Ahmed   30    Karachi   90000       1080000   9000.0      Normal   Middle
2   Sara   28     Lahore   95000       1140000   9500.0      Normal    Young
3  Hamza   35  Islamabad  120000       1440000  12000.0        High   Middle

> ✍️ **Practice time:** Practice 11 — open [Topic_02_Practice_Solutions.ipynb](Topic_02_Practice_Solutions.ipynb) to solve it and see the solution.

<a id="sec-13"></a>
# 13. Renaming and Dropping

Rename:

```python
df.rename(columns={"Name": "EmployeeName"})
```

Drop columns:

```python
df.drop(columns=["Bonus"])
```

Drop rows:

```python
df.drop(index=[0, 1])
```

In [19]:
renamed = work_df.rename(columns={"Name": "EmployeeName"})
renamed = renamed.drop(columns=["Bonus"])
renamed

  EmployeeName  Age       City  Salary  AnnualSalary SalaryLevel AgeGroup
0          Ali   25     Lahore   80000        960000      Normal    Young
1        Ahmed   30    Karachi   90000       1080000      Normal   Middle
2         Sara   28     Lahore   95000       1140000      Normal    Young
3        Hamza   35  Islamabad  120000       1440000        High   Middle

> ✍️ **Practice time:** Practice 12 — open [Topic_02_Practice_Solutions.ipynb](Topic_02_Practice_Solutions.ipynb) to solve it and see the solution.

<a id="sec-14"></a>
# 14. Sorting

Sort by one or more columns:

```python
df.sort_values("Salary")
df.sort_values("Salary", ascending=False)
df.sort_values(["City", "Salary"])
```

Sort by index:

```python
df.sort_index()
```

In [20]:
print(df.sort_values("Salary", ascending=False))
print()
print(df.sort_values(["City", "Salary"], ascending=[True, False]))

    Name  Age       City  Salary
3  Hamza   35  Islamabad  120000
2   Sara   28     Lahore   95000
1  Ahmed   30    Karachi   90000
0    Ali   25     Lahore   80000

    Name  Age       City  Salary
3  Hamza   35  Islamabad  120000
1  Ahmed   30    Karachi   90000
2   Sara   28     Lahore   95000
0    Ali   25     Lahore   80000

> ✍️ **Practice time:** Practice 13 — open [Topic_02_Practice_Solutions.ipynb](Topic_02_Practice_Solutions.ipynb) to solve it and see the solution.

<a id="sec-15"></a>
# 15. Indexes

Set an existing column as an index:

```python
df.set_index("Name")
```

Restore it:

```python
df.reset_index()
```

In [21]:
indexed_df = df.set_index("Name")
print(indexed_df)

print()
print(indexed_df.reset_index())

       Age       City  Salary
Name
Ali     25     Lahore   80000
Ahmed   30    Karachi   90000
Sara    28     Lahore   95000
Hamza   35  Islamabad  120000

    Name  Age       City  Salary
0    Ali   25     Lahore   80000
1  Ahmed   30    Karachi   90000
2   Sara   28     Lahore   95000
3  Hamza   35  Islamabad  120000

> ✍️ **Practice time:** Practice 14 — open [Topic_02_Practice_Solutions.ipynb](Topic_02_Practice_Solutions.ipynb) to solve it and see the solution.

<a id="sec-16"></a>
# 16. Copying

Use:

```python
df2 = df.copy()
```

when you need an independent DataFrame.

This is safer than:

```python
df2 = df
```

In [22]:
df2 = df.copy()
df2["Test"] = 123

print("Test in original:", "Test" in df.columns)
print("Test in copy:", "Test" in df2.columns)

Test in original: False
Test in copy: True

<a id="sec-17"></a>
# 17. Missing Values

Important tools:

- `isna()`
- `notna()`
- `dropna()`
- `fillna()`
- `ffill()`
- `bfill()`

In [23]:
missing_df = pd.DataFrame({
    "Name": ["Ali", "Ahmed", "Sara", "Hamza", "Zara"],
    "Age": [25, np.nan, 28, 35, np.nan],
    "Salary": [80000, 90000, np.nan, 120000, 95000],
    "City": ["Lahore", "Karachi", None, "Islamabad", "Lahore"]
})

print(missing_df)
print()
print(missing_df.isna())
print()
print(missing_df.isna().sum())

    Name   Age    Salary       City
0    Ali  25.0   80000.0     Lahore
1  Ahmed   NaN   90000.0    Karachi
2   Sara  28.0       NaN        NaN
3  Hamza  35.0  120000.0  Islamabad
4   Zara   NaN   95000.0     Lahore

    Name    Age  Salary   City
0  False  False   False  False
1  False   True   False  False
2  False  False    True   True
3  False  False   False  False
4  False   True   False  False

Name      0
Age       2
Salary    1
City      1
dtype: int64

In [24]:
filled = missing_df.copy()

filled["Age"] = filled["Age"].fillna(filled["Age"].median())
filled["Salary"] = filled["Salary"].fillna(filled["Salary"].mean())
filled["City"] = filled["City"].fillna("Unknown")

filled

    Name   Age    Salary       City
0    Ali  25.0   80000.0     Lahore
1  Ahmed  28.0   90000.0    Karachi
2   Sara  28.0   96250.0    Unknown
3  Hamza  35.0  120000.0  Islamabad
4   Zara  28.0   95000.0     Lahore

In [25]:
print("Drop rows:")
print(missing_df.dropna())

print()
print("Forward fill:")
print(missing_df.ffill())

print()
print("Backward fill:")
print(missing_df.bfill())

Drop rows:
    Name   Age    Salary       City
0    Ali  25.0   80000.0     Lahore
3  Hamza  35.0  120000.0  Islamabad

Forward fill:
    Name   Age    Salary       City
0    Ali  25.0   80000.0     Lahore
1  Ahmed  25.0   90000.0    Karachi
2   Sara  28.0   90000.0    Karachi
3  Hamza  35.0  120000.0  Islamabad
4   Zara  35.0   95000.0     Lahore

Backward fill:
    Name   Age    Salary       City
0    Ali  25.0   80000.0     Lahore
1  Ahmed  28.0   90000.0    Karachi
2   Sara  28.0  120000.0  Islamabad
3  Hamza  35.0  120000.0  Islamabad
4   Zara   NaN   95000.0     Lahore

> ✍️ **Practice time:** Practice 15 — open [Topic_02_Practice_Solutions.ipynb](Topic_02_Practice_Solutions.ipynb) to solve it and see the solution.

<a id="sec-18"></a>
# 18. Duplicates

Use:

```python
df.duplicated()
df.duplicated().sum()
df.drop_duplicates()
```

You can specify columns with `subset=`.

In [26]:
duplicate_df = pd.concat(
    [df, df.iloc[[0, 1]]],
    ignore_index=True
)

print("Duplicate count:", duplicate_df.duplicated().sum())
print(duplicate_df[duplicate_df.duplicated()])
print()
print(duplicate_df.drop_duplicates())

Duplicate count: 2
    Name  Age     City  Salary
4    Ali   25   Lahore   80000
5  Ahmed   30  Karachi   90000

    Name  Age       City  Salary
0    Ali   25     Lahore   80000
1  Ahmed   30    Karachi   90000
2   Sara   28     Lahore   95000
3  Hamza   35  Islamabad  120000

> ✍️ **Practice time:** Practice 16 — open [Topic_02_Practice_Solutions.ipynb](Topic_02_Practice_Solutions.ipynb) to solve it and see the solution.

<a id="sec-19"></a>
# 19. Data Type Conversion

Useful tools:

```python
astype()
pd.to_numeric()
pd.to_datetime()
```

`errors="coerce"` converts invalid values into missing values instead of raising an error.

In [27]:
types_df = pd.DataFrame({
    "Age": ["25", "30", "invalid", "40"],
    "Salary": ["80000", "90000", "100000", "bad"]
})

types_df["Age"] = pd.to_numeric(types_df["Age"], errors="coerce")
types_df["Salary"] = pd.to_numeric(types_df["Salary"], errors="coerce")

print(types_df)
print()
print(types_df.dtypes)

    Age    Salary
0  25.0   80000.0
1  30.0   90000.0
2   NaN  100000.0
3  40.0       NaN

Age       float64
Salary    float64
dtype: object

> ✍️ **Practice time:** Practice 17 — open [Topic_02_Practice_Solutions.ipynb](Topic_02_Practice_Solutions.ipynb) to solve it and see the solution.

<a id="sec-20"></a>
# 20. String Operations

Pandas string methods use `.str`.

Common operations:

```python
.str.lower()
.str.upper()
.str.strip()
.str.contains()
.str.replace()
.str.len()
.str.startswith()
.str.endswith()
.str.split()
```

In [28]:
names_df = pd.DataFrame({
    "Name": [" Ali ", "AHMED", "Sara Khan", "Muhammad Usman"],
    "Email": ["ALI@example.com", "ahmed@example.com", "sara@test.com", "usman@example.com"]
})

names_df["CleanName"] = names_df["Name"].str.strip().str.title()
names_df["EmailLower"] = names_df["Email"].str.lower()
names_df["NameLength"] = names_df["CleanName"].str.len()

print(names_df)
print()
print(names_df[names_df["Email"].str.contains("example", case=False, na=False)])

             Name              Email       CleanName         EmailLower  \
0            Ali     ALI@example.com             Ali    ali@example.com
1           AHMED  ahmed@example.com           Ahmed  ahmed@example.com
2       Sara Khan      sara@test.com       Sara Khan      sara@test.com
3  Muhammad Usman  usman@example.com  Muhammad Usman  usman@example.com

   NameLength
0           3
1           5
2           9
3          14

             Name              Email       CleanName         EmailLower  \
0            Ali     ALI@example.com             Ali    ali@example.com
1           AHMED  ahmed@example.com           Ahmed  ahmed@example.com
3  Muhammad Usman  usman@example.com  Muhammad Usman  usman@example.com

   NameLength
0           3
1           5
3          14

> ✍️ **Practice time:** Practice 18 — open [Topic_02_Practice_Solutions.ipynb](Topic_02_Practice_Solutions.ipynb) to solve it and see the solution.

<a id="sec-21"></a>
# 21. Date and Time

Convert strings to datetime:

```python
pd.to_datetime()
```

Then use `.dt`:

```python
.dt.year
.dt.month
.dt.day
.dt.day_name()
.dt.hour
```

In [29]:
date_df = pd.DataFrame({
    "Date": [
        "2026-01-15",
        "2026-02-20",
        "2026-03-10",
        "2026-04-25"
    ],
    "Sales": [100, 150, 120, 200]
})

date_df["Date"] = pd.to_datetime(date_df["Date"])

date_df["Year"] = date_df["Date"].dt.year
date_df["Month"] = date_df["Date"].dt.month
date_df["DayName"] = date_df["Date"].dt.day_name()

date_df

        Date  Sales  Year  Month   DayName
0 2026-01-15    100  2026      1  Thursday
1 2026-02-20    150  2026      2    Friday
2 2026-03-10    120  2026      3   Tuesday
3 2026-04-25    200  2026      4  Saturday

> ✍️ **Practice time:** Practice 19 — open [Topic_02_Practice_Solutions.ipynb](Topic_02_Practice_Solutions.ipynb) to solve it and see the solution.

<a id="sec-22"></a>
# 22. `apply()`

`apply()` lets you apply a function to values.

Example:

In [30]:
def salary_bonus(salary):
    return salary * 0.10

df["ApplyBonus"] = df["Salary"].apply(salary_bonus)

df["LambdaBonus"] = df["Salary"].apply(
    lambda x: x * 0.05
)

df[["Name", "Salary", "ApplyBonus", "LambdaBonus"]]

    Name  Salary  ApplyBonus  LambdaBonus
0    Ali   80000      8000.0       4000.0
1  Ahmed   90000      9000.0       4500.0
2   Sara   95000      9500.0       4750.0
3  Hamza  120000     12000.0       6000.0

> ✍️ **Practice time:** Practice 20 — open [Topic_02_Practice_Solutions.ipynb](Topic_02_Practice_Solutions.ipynb) to solve it and see the solution.

<a id="sec-23"></a>
# 23. `map()`

`map()` is useful for mapping values to new values.

Example:

In [31]:
city_to_province = {
    "Lahore": "Punjab",
    "Karachi": "Sindh",
    "Islamabad": "Capital"
}

df["Province"] = df["City"].map(city_to_province)

df[["Name", "City", "Province"]]

    Name       City Province
0    Ali     Lahore   Punjab
1  Ahmed    Karachi    Sindh
2   Sara     Lahore   Punjab
3  Hamza  Islamabad  Capital

> ✍️ **Practice time:** Practice 21 — open [Topic_02_Practice_Solutions.ipynb](Topic_02_Practice_Solutions.ipynb) to solve it and see the solution.

<a id="sec-24"></a>
# 24. `replace()`

`replace()` is useful when you want to replace existing values.

In [32]:
replace_demo = df.copy()

replace_demo["City"] = replace_demo["City"].replace({
    "Lahore": "LHR",
    "Karachi": "KHI",
    "Islamabad": "ISB"
})

replace_demo

    Name  Age City  Salary  ApplyBonus  LambdaBonus Province
0    Ali   25  LHR   80000      8000.0       4000.0   Punjab
1  Ahmed   30  KHI   90000      9000.0       4500.0    Sindh
2   Sara   28  LHR   95000      9500.0       4750.0   Punjab
3  Hamza   35  ISB  120000     12000.0       6000.0  Capital

> ✍️ **Practice time:** Practice 22 — open [Topic_02_Practice_Solutions.ipynb](Topic_02_Practice_Solutions.ipynb) to solve it and see the solution.

<a id="sec-25"></a>
# 25. `assign()`

`assign()` is useful for creating transformed DataFrames.

In [33]:
assigned = df.assign(
    AnnualSalary=df["Salary"] * 12,
    Bonus=df["Salary"] * 0.10
)

assigned

,Name,Age,City,Salary,ApplyBonus,LambdaBonus,Province,AnnualSalary,Bonus
0,Ali,25,Lahore,80000,8000.0,4000.0,Punjab,960000,8000.0
1,Ahmed,30,Karachi,90000,9000.0,4500.0,Sindh,1080000,9000.0
2,Sara,28,Lahore,95000,9500.0,4750.0,Punjab,1140000,9500.0
3,Hamza,35,Islamabad,120000,12000.0,6000.0,Capital,1440000,12000.0

> ✍️ **Practice time:** Practice 23 — open [Topic_02_Practice_Solutions.ipynb](Topic_02_Practice_Solutions.ipynb) to solve it and see the solution.

<a id="sec-26"></a>
# 26. Aggregation

Important statistical operations:

```python
sum()
mean()
median()
min()
max()
count()
std()
var()
```

In [34]:
salary = df["Salary"]

print("Sum:", salary.sum())
print("Mean:", salary.mean())
print("Median:", salary.median())
print("Min:", salary.min())
print("Max:", salary.max())
print("Count:", salary.count())
print("Std:", salary.std())
print("Variance:", salary.var())

Sum: 385000
Mean: 96250.0
Median: 92500.0
Min: 80000
Max: 120000
Count: 4
Std: 17017.148213885113
Variance: 289583333.3333333

> ✍️ **Practice time:** Practice 24 — open [Topic_02_Practice_Solutions.ipynb](Topic_02_Practice_Solutions.ipynb) to solve it and see the solution.

<a id="sec-27"></a>
# 27. `unique()`, `nunique()`, `value_counts()`

These are extremely useful for categorical analysis.

In [35]:
print("Unique cities:", df["City"].unique())
print()
print("Number of unique cities:", df["City"].nunique())
print()
print("City counts:")
print(df["City"].value_counts())
print()
print("City percentages:")
print(df["City"].value_counts(normalize=True))

Unique cities: <ArrowStringArray>
['Lahore', 'Karachi', 'Islamabad']
Length: 3, dtype: str

Number of unique cities: 3

City counts:
City
Lahore       2
Karachi      1
Islamabad    1
Name: count, dtype: int64

City percentages:
City
Lahore       0.50
Karachi      0.25
Islamabad    0.25
Name: proportion, dtype: float64

> ✍️ **Practice time:** Practice 25 — open [Topic_02_Practice_Solutions.ipynb](Topic_02_Practice_Solutions.ipynb) to solve it and see the solution.

<a id="sec-28"></a>
# 28. GroupBy

`groupby()` is one of the most important Pandas concepts.

Think:

**split → calculate → combine**

Example:

In [36]:
df["Department"] = ["IT","Admin","Hr","IT"]

print(df.groupby("City")["Salary"].sum())
print()
print(df.groupby("Department")["Salary"].sum())

City
Islamabad    120000
Karachi       90000
Lahore       175000
Name: Salary, dtype: int64

Department
Admin     90000
Hr        95000
IT       200000
Name: Salary, dtype: int64

<a id="sec-29"></a>
# 29. Multiple Aggregations

Use `agg()` when you need several calculations.

In [37]:
department_summary = df.groupby("Department")["Salary"].agg(
    ["mean", "sum", "min", "max", "count"]
)

department_summary

                mean     sum    min     max  count
Department
Admin        90000.0   90000  90000   90000      1
Hr           95000.0   95000  95000   95000      1
IT          100000.0  200000  80000  120000      2

## Named aggregations are often clearer:

In [38]:
summary = df.groupby("City").agg(
    average_salary=("Salary", "mean"),
    total_salary=("Salary", "sum"),
    highest_salary=("Salary", "max"),
    employees=("Name", "count")
).reset_index()

summary

        City  average_salary  total_salary  highest_salary  employees
0  Islamabad        120000.0        120000          120000          1
1    Karachi         90000.0         90000           90000          1
2     Lahore         87500.0        175000           95000          2

> ✍️ **Practice time:** Practice 26 — GroupBy — open [Topic_02_Practice_Solutions.ipynb](Topic_02_Practice_Solutions.ipynb) to solve it and see the solution.

<a id="sec-30"></a>
# 30. `reset_index()`

GroupBy often creates an index from the grouping column.

Use `reset_index()` to turn it back into a regular column.

In [39]:
grouped = df.groupby("City")["Salary"].mean()
print(grouped)
print()
print(grouped.reset_index())

City
Islamabad    120000.0
Karachi       90000.0
Lahore        87500.0
Name: Salary, dtype: float64

        City    Salary
0  Islamabad  120000.0
1    Karachi   90000.0
2     Lahore   87500.0

> ✍️ **Practice time:** Practice 27 — open [Topic_02_Practice_Solutions.ipynb](Topic_02_Practice_Solutions.ipynb) to solve it and see the solution.

<a id="sec-31"></a>
# 31. `concat()`

`concat()` combines DataFrames.

Vertical:
```python
pd.concat([df1, df2])
```

Horizontal:
```python
pd.concat([df1, df2], axis=1)
```

In [40]:
df1 = pd.DataFrame({
    "Name": ["Ali", "Sara"],
    "Salary": [80000, 95000]
})

df2 = pd.DataFrame({
    "Name": ["Ahmed", "Hamza"],
    "Salary": [90000, 120000]
})

combined = pd.concat([df1, df2], ignore_index=True)
combined

    Name  Salary
0    Ali   80000
1   Sara   95000
2  Ahmed   90000
3  Hamza  120000

> ✍️ **Practice time:** Practice 28 — open [Topic_02_Practice_Solutions.ipynb](Topic_02_Practice_Solutions.ipynb) to solve it and see the solution.

<a id="sec-32"></a>
# 32. `merge()`

`merge()` is similar to SQL JOIN.

Common types:

- `inner`
- `left`
- `right`
- `outer`

In [41]:
employees = pd.DataFrame({
    "employee_id": [1, 2, 3, 4],
    "Name": ["Ali", "Ahmed", "Sara", "Hamza"]
})

salaries = pd.DataFrame({
    "employee_id": [1, 2, 3, 5],
    "Salary": [80000, 90000, 95000, 70000]
})

print("Inner:")
print(pd.merge(employees, salaries, on="employee_id", how="inner"))

print()
print("Left:")
print(pd.merge(employees, salaries, on="employee_id", how="left"))

print()
print("Outer:")
print(pd.merge(employees, salaries, on="employee_id", how="outer"))

Inner:
   employee_id   Name  Salary
0            1    Ali   80000
1            2  Ahmed   90000
2            3   Sara   95000

Left:
   employee_id   Name   Salary
0            1    Ali  80000.0
1            2  Ahmed  90000.0
2            3   Sara  95000.0
3            4  Hamza      NaN

Outer:
   employee_id   Name   Salary
0            1    Ali  80000.0
1            2  Ahmed  90000.0
2            3   Sara  95000.0
3            4  Hamza      NaN
4            5    NaN  70000.0

> ✍️ **Practice time:** Practice 29 — Merge — open [Topic_02_Practice_Solutions.ipynb](Topic_02_Practice_Solutions.ipynb) to solve it and see the solution.

<a id="sec-33"></a>
# 33. `join()`

`join()` is particularly useful when working with indexes.

In [42]:
left = pd.DataFrame(
    {"Name": ["Ali", "Sara", "Ahmed"]},
    index=[1, 2, 3]
)

right = pd.DataFrame(
    {"Salary": [80000, 95000, 90000]},
    index=[1, 2, 3]
)

left.join(right)

    Name  Salary
1    Ali   80000
2   Sara   95000
3  Ahmed   90000

> ✍️ **Practice time:** Practice 30 — open [Topic_02_Practice_Solutions.ipynb](Topic_02_Practice_Solutions.ipynb) to solve it and see the solution.

<a id="sec-34"></a>
# 34. Pivot Tables

`pivot_table()` summarizes data.

Example:

In [43]:
sales = pd.DataFrame({
    "Department": ["IT", "IT", "HR", "HR", "Finance", "Finance"],
    "Gender": ["M", "F", "M", "F", "M", "F"],
    "Salary": [80000, 95000, 70000, 75000, 120000, 110000]
})

pivot = pd.pivot_table(
    sales,
    values="Salary",
    index="Department",
    columns="Gender",
    aggfunc="mean"
)

pivot

Gender             F         M
Department
Finance     110000.0  120000.0
HR           75000.0   70000.0
IT           95000.0   80000.0

> ✍️ **Practice time:** Practice 31 — open [Topic_02_Practice_Solutions.ipynb](Topic_02_Practice_Solutions.ipynb) to solve it and see the solution.

<a id="sec-35"></a>
# 35. `pivot()`

`pivot()` reshapes data when combinations are unique.

In [44]:
pivot_source = pd.DataFrame({
    "Name": ["Ali", "Ali", "Sara", "Sara"],
    "Subject": ["Math", "English", "Math", "English"],
    "Score": [90, 85, 95, 88]
})

pivot_source.pivot(
    index="Name",
    columns="Subject",
    values="Score"
)

Subject  English  Math
Name
Ali           85    90
Sara          88    95

<a id="sec-36"></a>
# 36. `melt()`

`melt()` transforms wide data into long format.

It is useful before many visualization and analysis tasks.

In [45]:
wide = pd.DataFrame({
    "Name": ["Ali", "Sara"],
    "Math": [90, 95],
    "English": [85, 88]
})

long = wide.melt(
    id_vars=["Name"],
    var_name="Subject",
    value_name="Score"
)

long

   Name  Subject  Score
0   Ali     Math     90
1  Sara     Math     95
2   Ali  English     85
3  Sara  English     88

> ✍️ **Practice time:** Practice 32 — open [Topic_02_Practice_Solutions.ipynb](Topic_02_Practice_Solutions.ipynb) to solve it and see the solution.

<a id="sec-37"></a>
# 37. `stack()` and `unstack()`

These are advanced reshaping operations.

`stack()` moves columns into the index.

`unstack()` moves an index level back into columns.

In [46]:
multi = pd.DataFrame({
    "Math": [90, 95],
    "English": [85, 88]
}, index=["Ali", "Sara"])

stacked = multi.stack()
print(stacked)

print()
print(stacked.unstack())

Ali   Math       90
      English    85
Sara  Math       95
      English    88
dtype: int64

      Math  English
Ali     90       85
Sara    95       88

> ✍️ **Practice time:** Practice 33 — open [Topic_02_Practice_Solutions.ipynb](Topic_02_Practice_Solutions.ipynb) to solve it and see the solution.

<a id="sec-38"></a>
# 38. MultiIndex

A MultiIndex has more than one index level.

It can be created with:

```python
df.set_index(["City", "Department"])
```

In [47]:
multi_df = df.set_index(["City", "Department"])
multi_df

                       Name  Age  Salary  ApplyBonus  LambdaBonus Province
City      Department
Lahore    IT            Ali   25   80000      8000.0       4000.0   Punjab
Karachi   Admin       Ahmed   30   90000      9000.0       4500.0    Sindh
Lahore    Hr           Sara   28   95000      9500.0       4750.0   Punjab
Islamabad IT          Hamza   35  120000     12000.0       6000.0  Capital

In [48]:
print(multi_df.index)
print()
print(multi_df.reset_index())

MultiIndex([(   'Lahore',    'IT'),
            (  'Karachi', 'Admin'),
            (   'Lahore',    'Hr'),
            ('Islamabad',    'IT')],
           names=['City', 'Department'])

        City Department   Name  Age  Salary  ApplyBonus  LambdaBonus Province
0     Lahore         IT    Ali   25   80000      8000.0       4000.0   Punjab
1    Karachi      Admin  Ahmed   30   90000      9000.0       4500.0    Sindh
2     Lahore         Hr   Sara   28   95000      9500.0       4750.0   Punjab
3  Islamabad         IT  Hamza   35  120000     12000.0       6000.0  Capital

> ✍️ **Practice time:** Practice 34 — open [Topic_02_Practice_Solutions.ipynb](Topic_02_Practice_Solutions.ipynb) to solve it and see the solution.

<a id="sec-39"></a>
# 39. `where()` and `mask`

`where()` keeps values where the condition is true.

`mask()` replaces values where the condition is true.

In [49]:
numbers = pd.Series([10, 20, 30, 40, 50])

print(numbers.where(numbers >= 30))
print()
print(numbers.mask(numbers >= 30))

0     NaN
1     NaN
2    30.0
3    40.0
4    50.0
dtype: float64

0    10.0
1    20.0
2     NaN
3     NaN
4     NaN
dtype: float64

> ✍️ **Practice time:** Practice 35 — open [Topic_02_Practice_Solutions.ipynb](Topic_02_Practice_Solutions.ipynb) to solve it and see the solution.

<a id="sec-40"></a>
# 40. `clip()`

`clip()` limits values to a range.

Example:

```python
series.clip(lower=18, upper=60)
```

In [50]:
ages = pd.Series([12, 20, 35, 70, 90])
ages.clip(lower=18, upper=60)

0    18
1    20
2    35
3    60
4    60
dtype: int64

> ✍️ **Practice time:** Practice 36 — open [Topic_02_Practice_Solutions.ipynb](Topic_02_Practice_Solutions.ipynb) to solve it and see the solution.

<a id="sec-41"></a>
# 41. Ranking

Use `rank()` to rank values.

For highest salary as rank 1:

```python
df["Salary"].rank(ascending=False)
```

In [51]:
rank_df = df.copy()
rank_df["SalaryRank"] = rank_df["Salary"].rank(
    ascending=False,
    method="dense"
)

rank_df[["Name", "Salary", "SalaryRank"]]

    Name  Salary  SalaryRank
0    Ali   80000         4.0
1  Ahmed   90000         3.0
2   Sara   95000         2.0
3  Hamza  120000         1.0

> ✍️ **Practice time:** Practice 37 — open [Topic_02_Practice_Solutions.ipynb](Topic_02_Practice_Solutions.ipynb) to solve it and see the solution.

<a id="sec-42"></a>
# 42. Cumulative Calculations

Useful functions:

- `cumsum()`
- `cummax()`
- `cummin()`
- `cumprod()`

In [52]:
sales_series = pd.Series([100, 150, 80, 200, 120])

print("Cumulative sum:")
print(sales_series.cumsum())

print()
print("Cumulative maximum:")
print(sales_series.cummax())

Cumulative sum:
0    100
1    250
2    330
3    530
4    650
dtype: int64

Cumulative maximum:
0    100
1    150
2    150
3    200
4    200
dtype: int64

> ✍️ **Practice time:** Practice 38 — open [Topic_02_Practice_Solutions.ipynb](Topic_02_Practice_Solutions.ipynb) to solve it and see the solution.

<a id="sec-43"></a>
# 43. `shift()`

`shift(1)` moves values down by one row.

It is useful for comparing the current value with the previous value.

In [53]:
time_df = pd.DataFrame({
    "Date": pd.date_range("2026-01-01", periods=5),
    "Sales": [100, 130, 120, 180, 160]
})

time_df["PreviousSales"] = time_df["Sales"].shift(1)
time_df["Change"] = time_df["Sales"] - time_df["PreviousSales"]
time_df["PercentChange"] = time_df["Sales"].pct_change() * 100

time_df

        Date  Sales  PreviousSales  Change  PercentChange
0 2026-01-01    100            NaN     NaN            NaN
1 2026-01-02    130          100.0    30.0      30.000000
2 2026-01-03    120          130.0   -10.0      -7.692308
3 2026-01-04    180          120.0    60.0      50.000000
4 2026-01-05    160          180.0   -20.0     -11.111111

> ✍️ **Practice time:** Practice 39 — open [Topic_02_Practice_Solutions.ipynb](Topic_02_Practice_Solutions.ipynb) to solve it and see the solution.

<a id="sec-44"></a>
# 44. Rolling Windows

`rolling()` is commonly used for moving averages and time-series analysis.

Example:

```python
series.rolling(3).mean()
```

In [54]:
rolling_df = pd.DataFrame({
    "Day": range(1, 8),
    "Sales": [100, 120, 90, 150, 180, 160, 200]
})

rolling_df["MovingAverage3"] = (
    rolling_df["Sales"].rolling(3).mean()
)

rolling_df

   Day  Sales  MovingAverage3
0    1    100             NaN
1    2    120             NaN
2    3     90      103.333333
3    4    150      120.000000
4    5    180      140.000000
5    6    160      163.333333
6    7    200      180.000000

> ✍️ **Practice time:** Practice 40 — open [Topic_02_Practice_Solutions.ipynb](Topic_02_Practice_Solutions.ipynb) to solve it and see the solution.

<a id="sec-45"></a>
# 45. `explode()`

`explode()` turns list-like values into separate rows.

In [55]:
skills_df = pd.DataFrame({
    "Name": ["Ali", "Sara", "Ahmed"],
    "Skills": [
        ["Python", "Pandas"],
        ["React", "JavaScript"],
        ["SQL", "Python"]
    ]
})

skills_df.explode("Skills")

    Name      Skills
0    Ali      Python
0    Ali      Pandas
1   Sara       React
1   Sara  JavaScript
2  Ahmed         SQL
2  Ahmed      Python

> ✍️ **Practice time:** Practice 41 — open [Topic_02_Practice_Solutions.ipynb](Topic_02_Practice_Solutions.ipynb) to solve it and see the solution.

<a id="sec-46"></a>
# 46. `json_normalize()`

API responses often contain nested JSON.

`pd.json_normalize()` helps flatten nested structures.

In [56]:
api_data = [
    {
        "id": 1,
        "name": "Ali",
        "address": {
            "city": "Lahore",
            "country": "Pakistan"
        }
    },
    {
        "id": 2,
        "name": "Sara",
        "address": {
            "city": "Karachi",
            "country": "Pakistan"
        }
    }
]

normalized = pd.json_normalize(api_data)
normalized

   id  name address.city address.country
0   1   Ali       Lahore        Pakistan
1   2  Sara      Karachi        Pakistan

> ✍️ **Practice time:** Practice 42 — open [Topic_02_Practice_Solutions.ipynb](Topic_02_Practice_Solutions.ipynb) to solve it and see the solution.

<a id="sec-47"></a>
# 47. Correlation

`corr()` calculates correlation between numeric columns.

A value closer to:

- `1` → strong positive relationship
- `-1` → strong negative relationship
- `0` → weak/linear relationship

Correlation does not prove causation.

In [57]:
print(df[["Age","Salary"]])
numeric_df = df[["Age", "Salary"]]
numeric_df.corr()

   Age  Salary
0   25   80000
1   30   90000
2   28   95000
3   35  120000

             Age    Salary
Age     1.000000  0.943712
Salary  0.943712  1.000000

> ✍️ **Practice time:** Practice 43 — open [Topic_02_Practice_Solutions.ipynb](Topic_02_Practice_Solutions.ipynb) to solve it and see the solution.

<a id="sec-48"></a>
# 48. Memory Usage

For larger datasets, memory matters.

Use:

```python
df.memory_usage(deep=True)
```

and:

```python
df.memory_usage(deep=True).sum()
```

In [58]:
print(df.memory_usage(deep=True))
print()
print("Total bytes:", df.memory_usage(deep=True).sum())

Index          132
Name            49
Age             32
City            60
Salary          32
ApplyBonus      32
LambdaBonus     32
Province        57
Department      43
dtype: int64

Total bytes: 469

<a id="sec-49"></a>
# 49. Categorical Data

If a column contains repeated categories, `category` can reduce memory usage and represent the data more accurately.

Example:

```python
df["City"] = df["City"].astype("category")
```

In [59]:
category_df = df.copy()

print("Before:")
print(category_df["City"].dtype)

category_df["City"] = category_df["City"].astype("category")

print("After:")
print(category_df["City"].dtype)

Before:
str
After:
category

> ✍️ **Practice time:** Practice 44 — open [Topic_02_Practice_Solutions.ipynb](Topic_02_Practice_Solutions.ipynb) to solve it and see the solution.

<a id="sec-50"></a>
# 50. Large CSV Files and Chunks

If a CSV is too large to fit comfortably in memory, process it in chunks:

```python
for chunk in pd.read_csv("large.csv", chunksize=10000):
    ...
```

You can also reduce memory by selecting only needed columns with `usecols`.

In [60]:
# Example syntax:

# for chunk in pd.read_csv(
#     "large.csv",
#     chunksize=10000,
#     usecols=["Date", "Product", "Sales"]
# ):
#     print(chunk.shape)

> ✍️ **Practice time:** Practice 45 — open [Topic_02_Practice_Solutions.ipynb](Topic_02_Practice_Solutions.ipynb) to solve it and see the solution.

<a id="sec-51"></a>
# 51. Exporting Data

Common output methods:

```python
df.to_csv("output.csv", index=False)
df.to_excel("output.xlsx", index=False)
df.to_json("output.json")
```

In [61]:
# Examples:
# df.to_csv("output.csv", index=False)
# df.to_excel("output.xlsx", index=False)
# df.to_json("output.json")

> ✍️ **Practice time:** Practice 46 — open [Topic_02_Practice_Solutions.ipynb](Topic_02_Practice_Solutions.ipynb) to solve it and see the solution.

<a id="sec-52"></a>
# 52. A Professional Data-Cleaning Workflow

A common real-world process is:

1. Load data
2. Inspect shape/types
3. Check missing values
4. Check duplicates
5. Fix data types
6. Clean strings
7. Handle missing values
8. Validate ranges
9. Create useful columns
10. Analyze/group
11. Export clean data

In [62]:
import pandas as pd

# ==========================================
# 1. Load data
# ==========================================

data = pd.read_csv("../data/customer_sales_dirty.csv")

print(data.head())


# ==========================================
# 2. Inspect shape and data types
# ==========================================

print("Shape:", data.shape)

print("\nData types:")
print(data.dtypes)

print("\nBasic information:")
print(data.info())


# ==========================================
# 3. Check missing values
# ==========================================

print("\nMissing values:")
print(data.isna().sum())


# ==========================================
# 4. Check duplicates
# ==========================================

print("\nNumber of duplicate rows:")
print(data.duplicated().sum())

print("\nDuplicate rows:")
print(data[data.duplicated()])


# Remove duplicates
data = data.drop_duplicates()


# ==========================================
# 5. Fix data types
# ==========================================

# Age contains "abc", so convert invalid values to NaN
data["Age"] = pd.to_numeric(data["Age"], errors="coerce")

# Convert numeric columns
data["Quantity"] = pd.to_numeric(data["Quantity"], errors="coerce")
data["Unit_Price"] = pd.to_numeric(data["Unit_Price"], errors="coerce")
data["Rating"] = pd.to_numeric(data["Rating"], errors="coerce")

# Convert date
data["Order_Date"] = pd.to_datetime(
    data["Order_Date"],
    errors="coerce"
)

print("\nData types after conversion:")
print(data.dtypes)


# ==========================================
# 6. Clean strings
# ==========================================

# Remove extra spaces and make names consistent
data["Name"] = data["Name"].str.strip()

data["City"] = data["City"].str.strip().str.title()

data["Product"] = data["Product"].str.strip().str.title()

data["Email"] = data["Email"].str.strip().str.lower()


# ==========================================
# 7. Handle missing values
# ==========================================

# Age → median
data["Age"] = data["Age"].fillna(data["Age"].median())


# Unit_Price → median of the SAME product
data["Unit_Price"] = (
    data.groupby("Product")["Unit_Price"]
    .transform(lambda x: x.fillna(x.median()))
)


# Rating → median
data["Rating"] = data["Rating"].fillna(data["Rating"].median())


# Email → unknown
data["Email"] = data["Email"].fillna("unknown")


# ==========================================
# 8. Validate ranges
# ==========================================

# Find invalid ages
invalid_age = data[
    (data["Age"] < 18) |
    (data["Age"] > 100)
]

print("\nInvalid ages:")
print(invalid_age)


# Find invalid quantities
invalid_quantity = data[
    data["Quantity"] < 0
]

print("\nInvalid quantities:")
print(invalid_quantity)


# Find invalid ratings
invalid_rating = data[
    (data["Rating"] < 1) |
    (data["Rating"] > 5)
]

print("\nInvalid ratings:")
print(invalid_rating)


# Find invalid prices
invalid_price = data[
    data["Unit_Price"] < 0
]

print("\nInvalid prices:")
print(invalid_price)


# Fix invalid values
data.loc[
    (data["Age"] < 18) | (data["Age"] > 100),
    "Age"
] = data["Age"].median()


data.loc[
    data["Quantity"] < 0,
    "Quantity"
] = data.loc[
    data["Quantity"] >= 0,
    "Quantity"
].median()


data.loc[
    (data["Rating"] < 1) | (data["Rating"] > 5),
    "Rating"
] = data["Rating"].median()


# ==========================================
# 9. Create useful columns
# ==========================================

# Total sales
data["Total_Sales"] = (
    data["Quantity"] * data["Unit_Price"]
)


# Age group
conditions = [
    data["Age"] < 25,
    (data["Age"] >= 25) & (data["Age"] < 40),
    data["Age"] >= 40
]

choices = [
    "Young",
    "Adult",
    "Senior"
]

data["Age_Group"] = np.select(
    conditions,
    choices,
    default="Unknown"
)


# Order month
data["Order_Month"] = data["Order_Date"].dt.month_name()


print("\nNew columns:")
print(
    data[
        [
            "Product",
            "Quantity",
            "Unit_Price",
            "Total_Sales",
            "Age_Group",
            "Order_Month"
        ]
    ].head()
)


# ==========================================
# 10. Analyze / Group
# ==========================================

# Total sales by product
sales_by_product = (
    data.groupby("Product")["Total_Sales"]
    .sum()
)

print("\nTotal sales by product:")
print(sales_by_product)


# Average price by product
average_price = (
    data.groupby("Product")["Unit_Price"]
    .mean()
)

print("\nAverage price by product:")
print(average_price)


# Number of orders by city
orders_by_city = (
    data.groupby("City")["Customer_ID"]
    .count()
)

print("\nOrders by city:")
print(orders_by_city)


# ==========================================
# 11. Export clean data
# ==========================================

data.to_csv(
    "../data/customer_sales_clean.csv",
    index=False
)

print("\nClean data exported successfully!")

   Customer_ID          Name             Email  Age       City   Product  \
0         1001      Ali Khan     ali@gmail.com   25     Lahore    Laptop
1         1002    Sara Ahmed    sara@gmail.com   31    lahore      Mouse
2         1003    Usman Raza   usman@gmail.com   17    Karachi  Keyboard
3         1004  Ayesha Malik               NaN   29  Islamabad    Laptop
4         1005    Hassan Ali  hassan@gmail.com  NaN    Karachi   Monitor

   Quantity  Unit_Price  Order_Date  Rating
0         2    120000.0  2026-01-05     5.0
1         5      2500.0  2026-01-06     4.0
2         3      5000.0  2026-01-07     3.0
3         1    125000.0  2026-01-08     5.0
4         2     45000.0  2026-01-09     4.0
Shape: (30, 10)

Data types:
Customer_ID      int64
Name               str
Email              str
Age                str
City               str
Product            str
Quantity         int64
Unit_Price     float64
Order_Date         str
Rating         float64
dtype: object

Basic information:
<class 'pandas.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 10 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Customer_ID  30 non-null     int64
 1   Name         30 non-null     str
 2   Email        29 non-null     str
 3   Age          29 non-null     str
 4   City         30 non-null     str
 5   Product      30 non-null     str
 6   Quantity     30 non-null     int64
 7   Unit_Price   29 non-null     float64
 8   Order_Date   30 non-null     str
 9   Rating       29 non-null     float64
dtypes: float64(2), int64(2), str(6)
memory usage: 4.0 KB
None

Missing values:
Customer_ID    0
Name           0
Email          1
Age            1
City           0
Product        0
Quantity       0
Unit_Price     1
Order_Date     0
Rating         1
dtype: int64

Number of duplicate rows:
0

Duplicate rows:
Empty DataFrame
Columns: [Customer_ID, Name, Email, Age, City, Product, Quantity, Unit_Price, Order_Date, Rating]
Index: []

Data types after conversion:
Customer_ID             int64
Name                      str
Email                     str
Age                   float64
City                      str
Product                   str
Quantity                int64
Unit_Price            float64
Order_Date     datetime64[us]
Rating                float64
dtype: object

Invalid ages:
    Customer_ID         Name            Email    Age       City   Product  \
2          1003   Usman Raza  usman@gmail.com   17.0    Karachi  Keyboard
6          1007  Bilal Ahmed  bilal@gmail.com  150.0  Islamabad  Keyboard
14         1015   Usman Raza  usman@gmail.com   17.0    Karachi  Keyboard

    Quantity  Unit_Price Order_Date  Rating
2          3      5000.0 2026-01-07     3.0
6          2      5500.0 2026-01-11     4.0
14         3      5000.0 2026-01-07     3.0

Invalid quantities:
    Customer_ID        Name             Email   Age    City Product  Quantity  \
15         1016  Kamran Ali  kamran@gmail.com  22.0  Lahore  Laptop        -2

    Unit_Price Order_Date  Rating
15    120000.0 2026-01-19     4.0

Invalid ratings:
   Customer_ID         Name             Email   Age    City Product  Quantity  \
5         1006  Fatima Noor  fatima@gmail.com  42.0  Lahore   Mouse        10

   Unit_Price Order_Date  Rating
5      2500.0 2026-01-10     6.0

Invalid prices:
Empty DataFrame
Columns: [Customer_ID, Name, Email, Age, City, Product, Quantity, Unit_Price, Order_Date, Rating]
Index: []

New columns:
    Product  Quantity  Unit_Price  Total_Sales Age_Group Order_Month
0    Laptop         2    120000.0     240000.0     Adult     January
1     Mouse         5      2500.0      12500.0     Adult     January
2  Keyboard         3      5000.0      15000.0     Adult     January
3    Laptop         1    125000.0     125000.0     Adult     January
4   Monitor         2     45000.0      90000.0     Adult     January

Total sales by product:
Product
Keyboard     104000.0
Laptop      2080000.0
Monitor      450000.0
Mouse        107500.0
Name: Total_Sales, dtype: float64

Average price by product:
Product
Keyboard      5214.285714
Laptop      123181.818182
Monitor      45000.000000
Mouse         2500.000000
Name: Unit_Price, dtype: float64

Orders by city:
City
Islamabad     7
Karachi      12
Lahore       11
Name: Customer_ID, dtype: int64

Clean data exported successfully!

> ✍️ **Practice time:** Practice 47 — Complete Cleaning Workflow, 53. Mini Analysis Project, Mini Project Questions, 54. Final Capstone Challenge 🔥🔥🔥, Capstone Tasks — open [Topic_02_Practice_Solutions.ipynb](Topic_02_Practice_Solutions.ipynb) to solve it and see the solution.

<a id="sec-53"></a>
# 55. Quick Reference / Cheat Sheet

## Inspect

```python
df.head()
df.tail()
df.shape
df.columns
df.index
df.dtypes
df.info()
df.describe()
```

## Select

```python
df["column"]
df[["col1", "col2"]]
df.iloc[0]
df.iloc[0:3]
df.loc[0]
df.loc[0, "column"]
```

## Filter

```python
df[df["Age"] > 25]
df[(df["Age"] > 25) & (df["Salary"] > 80000)]
df[df["City"].isin(["Lahore", "Karachi"])]
df.query("Age > 25")
```

## Clean

```python
df.isna()
df.isna().sum()
df.dropna()
df.fillna()
df.ffill()
df.bfill()
df.duplicated()
df.drop_duplicates()
```

## Transform

```python
df["New"] = df["Salary"] * 12
df.rename()
df.drop()
df.sort_values()
df.astype()
pd.to_numeric()
pd.to_datetime()
df.apply()
df.map()
df.replace()
df.assign()
```

## Analyze

```python
df.sum()
df.mean()
df.median()
df.min()
df.max()
df.count()
df.std()
df.nunique()
df.value_counts()
df.groupby()
df.agg()
df.corr()
```

## Combine

```python
pd.concat()
pd.merge()
df.join()
```

## Reshape

```python
df.pivot()
pd.pivot_table()
df.melt()
df.stack()
df.unstack()
df.explode()
```

## Time Series

```python
df["Date"].dt.year
df["Date"].dt.month
df["Date"].dt.day
df["Sales"].shift()
df["Sales"].pct_change()
df["Sales"].rolling(3).mean()
df["Sales"].cumsum()
```

## Export

```python
df.to_csv("file.csv", index=False)
df.to_excel("file.xlsx", index=False)
df.to_json("file.json")
```

# Final Goal

After completing this notebook, you should be comfortable taking a raw table and performing the typical Pandas workflow:

**Load → Inspect → Clean → Transform → Filter → Group → Combine → Reshape → Analyze → Export**

Do not worry about memorizing every method. Focus on understanding what problem each operation solves and practice writing the code yourself.