# Topic 02 — Pandas DataFrame Basics — ✍️ Practice & Solutions

This notebook has every **practice problem** for Topic 02, each followed by its **✅ solution**.

**How to use it**
1. Read the lesson first: [Topic_02_Lesson.ipynb](Topic_02_Lesson.ipynb).
2. Read a problem and write your answer in the code cell under it.
3. Only then scroll down to the ✅ solution and compare.
4. Stuck or confused? Go back to the matching lesson section — every solution uses only what the lesson teaches.

> 📚 **Course navigation** — you are in **Topic 02: Pandas DataFrame Basics**
> ⬅️ Previous: [Topic 01 — Python Basics](../Topic_01_Python_Basics/Topic_01_Lesson.ipynb)  ·  ➡️ Next: [Topic 03 — Handling Missing Values](../Topic_03_Handling_Missing_Values/Topic_03_Lesson.ipynb)  ·  🗂️ [All topics](../Topic_00_All_Topics_Index.ipynb)

<details><summary>Full course sequence (click to expand)</summary>

| # | Topic | Lesson | Practice & Solutions |
|---|---|---|---|
| 01 | Python Basics | [📖 Lesson](../Topic_01_Python_Basics/Topic_01_Lesson.ipynb) | [✍️ Practice](../Topic_01_Python_Basics/Topic_01_Practice_Solutions.ipynb) |
| **▶ 02 ◀** | **Pandas DataFrame Basics** | [📖 Lesson](../Topic_02_Pandas_DataFrame_Basics/Topic_02_Lesson.ipynb) | [✍️ Practice](../Topic_02_Pandas_DataFrame_Basics/Topic_02_Practice_Solutions.ipynb) |
| 03 | Handling Missing Values | [📖 Lesson](../Topic_03_Handling_Missing_Values/Topic_03_Lesson.ipynb) | [✍️ Practice](../Topic_03_Handling_Missing_Values/Topic_03_Practice_Solutions.ipynb) |
| 04 | Normalization & Standardization | [📖 Lesson](../Topic_04_Normalization_Standardization/Topic_04_Lesson.ipynb) | [✍️ Practice](../Topic_04_Normalization_Standardization/Topic_04_Practice_Solutions.ipynb) |
| 05 | Detecting & Treating Outliers | [📖 Lesson](../Topic_05_Outliers/Topic_05_Lesson.ipynb) | [✍️ Practice](../Topic_05_Outliers/Topic_05_Practice_Solutions.ipynb) |
| 🎯 | *🎯 Quiz 1 — Topics 01–05* | [🎯 Quiz 1](../Quiz_1_Topics_01-05/Quiz_1.ipynb) | |
| 06 | Encoding Techniques | [📖 Lesson](../Topic_06_Encoding_Techniques/Topic_06_Lesson.ipynb) | [✍️ Practice](../Topic_06_Encoding_Techniques/Topic_06_Practice_Solutions.ipynb) |
| 07 | Exploratory Data Analysis (EDA) | [📖 Lesson](../Topic_07_Exploratory_Data_Analysis/Topic_07_Lesson.ipynb) | [✍️ Practice](../Topic_07_Exploratory_Data_Analysis/Topic_07_Practice_Solutions.ipynb) |
| 08 | Data Visualization | [📖 Lesson](../Topic_08_Data_Visualization/Topic_08_Lesson.ipynb) | [✍️ Practice](../Topic_08_Data_Visualization/Topic_08_Practice_Solutions.ipynb) |
| 09 | Pandas Data Manipulation | [📖 Lesson](../Topic_09_Pandas_Data_Manipulation/Topic_09_Lesson.ipynb) | [✍️ Practice](../Topic_09_Pandas_Data_Manipulation/Topic_09_Practice_Solutions.ipynb) |
| 10 | Combining DataFrames | [📖 Lesson](../Topic_10_Combining_DataFrames/Topic_10_Lesson.ipynb) | [✍️ Practice](../Topic_10_Combining_DataFrames/Topic_10_Practice_Solutions.ipynb) |
| 🎯 | *🎯 Quiz 2 — Topics 06–10* | [🎯 Quiz 2](../Quiz_2_Topics_06-10/Quiz_2.ipynb) | |
| 11 | Feature Engineering | [📖 Lesson](../Topic_11_Feature_Engineering/Topic_11_Lesson.ipynb) | [✍️ Practice](../Topic_11_Feature_Engineering/Topic_11_Practice_Solutions.ipynb) |
| 11b | KBinsDiscretizer (Discretization) | [📖 Lesson](../Topic_11b_KBinsDiscretizer/Topic_11b_Lesson.ipynb) | [✍️ Practice](../Topic_11b_KBinsDiscretizer/Topic_11b_Practice_Solutions.ipynb) |
| 12 | Correlation & Multicollinearity | [📖 Lesson](../Topic_12_Correlation_Multicollinearity/Topic_12_Lesson.ipynb) | [✍️ Practice](../Topic_12_Correlation_Multicollinearity/Topic_12_Practice_Solutions.ipynb) |
| 13 | Data Transformation & Skewness | [📖 Lesson](../Topic_13_Data_Transformation_Skewness/Topic_13_Lesson.ipynb) | [✍️ Practice](../Topic_13_Data_Transformation_Skewness/Topic_13_Practice_Solutions.ipynb) |
| 14 | Statistics for Data Science | [📖 Lesson](../Topic_14_Statistics_for_Data_Science/Topic_14_Lesson.ipynb) | [✍️ Practice](../Topic_14_Statistics_for_Data_Science/Topic_14_Practice_Solutions.ipynb) |
| 🎯 | *🎯 Quiz 3 — Topics 11–14* | [🎯 Quiz 3](../Quiz_3_Topics_11-14/Quiz_3.ipynb) | |
| 15 | Probability for Data Science & ML | [📖 Lesson](../Topic_15_Probability_for_Data_Science_ML/Topic_15_Lesson.ipynb) | [✍️ Practice](../Topic_15_Probability_for_Data_Science_ML/Topic_15_Practice_Solutions.ipynb) |
| 16 | Feature Selection | [📖 Lesson](../Topic_16_Feature_Selection/Topic_16_Lesson.ipynb) | [✍️ Practice](../Topic_16_Feature_Selection/Topic_16_Practice_Solutions.ipynb) |
| 17 | Machine Learning | [📖 Lesson](../Topic_17_Machine_Learning/Topic_17_Lesson.ipynb) | [✍️ Practice](../Topic_17_Machine_Learning/Topic_17_Practice_Solutions.ipynb) |
| 🎯 | *🏁 Final Quiz — Topics 15–17* | [🏁 Final Quiz](../Quiz_4_Topics_15-17/Quiz_4.ipynb) | |

</details>

## 📋 Practice Index

**51 problems** — each one is followed by your answer cell and then its ✅ solution. Click a problem to jump to it.

- [Practice 1](#p-1)
- [Practice 2](#p-2)
- [Practice 3](#p-3)
- [Practice 4](#p-4)
- [Practice 5](#p-5)
- [Practice 6](#p-6)
- [Practice 7](#p-7)
- [Practice 8](#p-8)
- [Practice 9](#p-9)
- [Practice 10](#p-10)
- [Practice 11](#p-11)
- [Practice 12](#p-12)
- [Practice 13](#p-13)
- [Practice 14](#p-14)
- [Practice 15](#p-15)
- [Practice 16](#p-16)
- [Practice 17](#p-17)
- [Practice 18](#p-18)
- [Practice 19](#p-19)
- [Practice 20](#p-20)
- [Practice 21](#p-21)
- [Practice 22](#p-22)
- [Practice 23](#p-23)
- [Practice 24](#p-24)
- [Practice 25](#p-25)
- [Practice 26 — GroupBy](#p-26)
- [Practice 27](#p-27)
- [Practice 28](#p-28)
- [Practice 29 — Merge](#p-29)
- [Practice 30](#p-30)
- [Practice 31](#p-31)
- [Practice 32](#p-32)
- [Practice 33](#p-33)
- [Practice 34](#p-34)
- [Practice 35](#p-35)
- [Practice 36](#p-36)
- [Practice 37](#p-37)
- [Practice 38](#p-38)
- [Practice 39](#p-39)
- [Practice 40](#p-40)
- [Practice 41](#p-41)
- [Practice 42](#p-42)
- [Practice 43](#p-43)
- [Practice 44](#p-44)
- [Practice 45](#p-45)
- [Practice 46](#p-46)
- [Practice 47 — Complete Cleaning Workflow](#p-47)
- [53. Mini Analysis Project](#p-48)
- [Mini Project Questions](#p-49)
- [54. Final Capstone Challenge 🔥🔥🔥](#p-50)
- [Capstone Tasks](#p-51)

> 📖 Lesson for this topic: [Topic_02_Lesson.ipynb](Topic_02_Lesson.ipynb)

### ⚙️ Setup — run this cell first

Some problems use data, variables and functions created in the lesson. This cell quietly runs the whole lesson notebook so they all exist here.

In [1]:
%%capture
# Runs the lesson notebook (output hidden) so its variables exist here
%run ./Topic_02_Lesson.ipynb

<a id="p-1"></a>
## Practice 1

Create a DataFrame named `students` with:

- Name
- Age
- Course
- Marks

Add at least 5 students.

In [2]:
# Your solution
data = {
    "Name": ["Ali", "Ahmed", "Sara", "Hamza"],
    "Age": [25, 30, 28, 35],
    "Course": ["BSCS", "BSCS", "BSAI", "BSAI"],
    "Marks": [80, 90, 95, 92]
}
df= pd.DataFrame(data)
df

    Name  Age Course  Marks
0    Ali   25   BSCS     80
1  Ahmed   30   BSCS     90
2   Sara   28   BSAI     95
3  Hamza   35   BSAI     92

<a id="p-2"></a>
## Practice 2

Create a DataFrame from a list of dictionaries containing:

`product`, `price`, `quantity`, `category`.

Use at least 5 products.

In [3]:
# Your solution
data = [{"product":"Books", "price":20,"quantity":3,"category":"Urdu"},
        {"product":"Books", "price":20,"quantity":3,"category":"Urdu"},
        {"product":"Books", "price":20,"quantity":3,"category":"Urdu"},
        {"product":"Books", "price":20,"quantity":3,"category":"Urdu"},
        {"product":"Books", "price":20,"quantity":3,"category":"Urdu"}
        ]
df =pd.DataFrame(data)
df

  product  price  quantity category
0   Books     20         3     Urdu
1   Books     20         3     Urdu
2   Books     20         3     Urdu
3   Books     20         3     Urdu
4   Books     20         3     Urdu

# Practice Solutions (FIX-2026-09-27)

Try every practice yourself **first** — your answers above are kept exactly as you wrote them.

Some of the lesson cells change `df` as you go (for example the GroupBy section adds `Department`), so every solution
below starts from a **fresh copy** of the lesson data to give the same result no matter which cells you ran before.

In [4]:
import pandas as pd
import numpy as np
import os, tempfile

def fresh_df():
    """The lesson DataFrame, plus Department/Gender/Experience for the later practices."""
    return pd.DataFrame({
        "Name": ["Ali", "Ahmed", "Sara", "Hamza"],
        "Age": [25, 30, 28, 35],
        "City": ["Lahore", "Karachi", "Lahore", "Islamabad"],
        "Salary": [80000, 90000, 95000, 120000],
        "Department": ["IT", "HR", "IT", "Finance"],
        "Gender": ["Male", "Male", "Female", "Male"],
        "Experience": [2, 5, 4, 9],
    })

OUT = tempfile.mkdtemp()      # files written by the solutions go to a temp folder, not next to the notebook
fresh_df()

    Name  Age       City  Salary Department  Gender  Experience
0    Ali   25     Lahore   80000         IT    Male           2
1  Ahmed   30    Karachi   90000         HR    Male           5
2   Sara   28     Lahore   95000         IT  Female           4
3  Hamza   35  Islamabad  120000    Finance    Male           9

## ✅ Solution — Practice 1 & 2 — Creating DataFrames

In [5]:
students = pd.DataFrame({
    "Name": ["Ali", "Sara", "Ahmed", "Ayesha", "Usman"],
    "Age": [20, 21, 19, 22, 20],
    "Course": ["Python", "SQL", "Python", "ML", "SQL"],
    "Marks": [85, 92, 72, 64, 58],
})
print(students, "\n")

products = pd.DataFrame([
    {"product": "Book",     "price": 1200,   "quantity": 3, "category": "Stationery"},
    {"product": "Pen",      "price": 50,     "quantity": 20, "category": "Stationery"},
    {"product": "Laptop",   "price": 150000, "quantity": 1, "category": "Electronics"},
    {"product": "Mouse",    "price": 2500,   "quantity": 4, "category": "Electronics"},
    {"product": "Backpack", "price": 4000,   "quantity": 2, "category": "Accessories"},
])
products

     Name  Age  Course  Marks
0     Ali   20  Python     85
1    Sara   21     SQL     92
2   Ahmed   19  Python     72
3  Ayesha   22      ML     64
4   Usman   20     SQL     58

    product   price  quantity     category
0      Book    1200         3   Stationery
1       Pen      50        20   Stationery
2    Laptop  150000         1  Electronics
3     Mouse    2500         4  Electronics
4  Backpack    4000         2  Accessories

<a id="p-3"></a>
## Practice 3

Write the code you would use to read:

1. `employees.csv`
2. `employees.xlsx`, sheet `"Employees"`
3. `employees.json`

In [6]:
# Your solution
winequality = pd.read_csv("../data/winequality-red.csv")
winequality.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,9.8,5
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,9.8,5
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,9.8,6
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5

## ✅ Solution — Practice 3 — Reading files

```python
emp_csv  = pd.read_csv("employees.csv")
emp_xlsx = pd.read_excel("employees.xlsx", sheet_name="Employees")   # needs openpyxl
emp_json = pd.read_json("employees.json")
```

<a id="p-4"></a>
## Practice 4

Using `df`:

1. Show the first 3 rows.
2. Show the last 2 rows.
3. Find its shape.
4. List its columns.
5. Show data types.
6. Generate statistical information.

In [7]:
# Your solution
# print(winequality.head(3))

# print(winequality.tail(2))
print(winequality.shape)
print(winequality.columns)
print(winequality.dtypes)
print(winequality.describe())

(1599, 12)
Index(['fixed acidity', 'volatile acidity', 'citric acid', 'residual sugar',
       'chlorides', 'free sulfur dioxide', 'total sulfur dioxide', 'density',
       'pH', 'sulphates', 'alcohol', 'quality'],
      dtype='str')
fixed acidity           float64
volatile acidity        float64
citric acid             float64
residual sugar          float64
chlorides               float64
free sulfur dioxide     float64
total sulfur dioxide    float64
density                 float64
pH                      float64
sulphates               float64
alcohol                 float64
quality                   int64
dtype: object
       fixed acidity  volatile acidity  citric acid  residual sugar  \
count    1599.000000       1599.000000  1599.000000     1599.000000
mean        8.319637          0.527821     0.270976        2.538806
std         1.741096          0.179060     0.194801        1.409928
min         4.600000          0.120000     0.000000        0.900000
25%         7.100000          0.390000     0.090000        1.900000
50%         7.900000          0.520000     0.260000        2.200000
75%         9.200000          0.640000     0.420000        2.600000
max        15.900000          1.580000     1.000000       15.500000

         chlorides  free sulfur dioxide  total sulfur dioxide      density  \
count  1599.000000          1599.000000           1599.000000  1599.000000
mean      0.087467            15.874922             46.467792     0.996747
std       0.047065            10.460157             32.895324     0.001887
min       0.012000             1.000000              6.000000     0.990070
25%       0.070000             7.000000             22.000000     0.995600
50%       0.079000            14.000000             38.000000     0.996750
75%       0.090000            21.000000             62.000000     0.997835
max       0.611000            72.000000            289.000000     1.003690

                pH    sulphates      alcohol      quality
count  1599.000000  1599.000000  1599.000000  1599.000000
mean      3.311113     0.658149    10.422983     5.636023
std       0.154386     0.169507     1.065668     0.807569
min       2.740000     0.330000     8.400000     3.000000
25%       3.210000     0.550000     9.500000     5.000000
50%       3.310000     0.620000    10.200000     6.000000
75%       3.400000     0.730000    11.100000     6.000000
max       4.010000     2.000000    14.900000     8.000000

<a id="p-5"></a>
## Practice 5

Select:

1. Only `Age`.
2. `Name` and `City`.
3. `Name`, `Age`, and `Salary`.

> 🧩 *Re-creates the data this problem uses (exactly as it was at this point of the lesson).*

In [8]:
data = {
    "Name": ["Ali", "Ahmed", "Sara", "Hamza"],
    "Age": [25, 30, 28, 35],
    "City": ["Lahore", "Karachi", "Lahore", "Islamabad"],
    "Salary": [80000, 90000, 95000, 120000]
}

df = pd.DataFrame(data)

print(df["Name"])
print()
print(df[["Name", "Age"]])

0      Ali
1    Ahmed
2     Sara
3    Hamza
Name: Name, dtype: str

    Name  Age
0    Ali   25
1  Ahmed   30
2   Sara   28
3  Hamza   35

In [9]:
# Your solution
print(df["Age"])

print(df[["Name","City"]])

df

0    25
1    30
2    28
3    35
Name: Age, dtype: int64
    Name       City
0    Ali     Lahore
1  Ahmed    Karachi
2   Sara     Lahore
3  Hamza  Islamabad

    Name  Age       City  Salary
0    Ali   25     Lahore   80000
1  Ahmed   30    Karachi   90000
2   Sara   28     Lahore   95000
3  Hamza   35  Islamabad  120000

## ✅ Solution — Practice 4 & 5 — Inspection and selecting columns

In [10]:
df = fresh_df()[["Name", "Age", "City", "Salary"]]
print(df.head(3), "\n")
print(df.tail(2), "\n")
print("shape:", df.shape)
print("columns:", df.columns.tolist())
print(df.dtypes, "\n")
print(df.describe(), "\n")

print(df["Age"], "\n")                    # a Series
print(df[["Name", "City"]], "\n")         # a DataFrame (double brackets)
print(df[["Name", "Age", "Salary"]])

    Name  Age     City  Salary
0    Ali   25   Lahore   80000
1  Ahmed   30  Karachi   90000
2   Sara   28   Lahore   95000

    Name  Age       City  Salary
2   Sara   28     Lahore   95000
3  Hamza   35  Islamabad  120000

shape: (4, 4)
columns: ['Name', 'Age', 'City', 'Salary']
Name        str
Age       int64
City        str
Salary    int64
dtype: object

             Age         Salary
count   4.000000       4.000000
mean   29.500000   96250.000000
std     4.203173   17017.148214
min    25.000000   80000.000000
25%    27.250000   87500.000000
50%    29.000000   92500.000000
75%    31.250000  101250.000000
max    35.000000  120000.000000

0    25
1    30
2    28
3    35
Name: Age, dtype: int64

    Name       City
0    Ali     Lahore
1  Ahmed    Karachi
2   Sara     Lahore
3  Hamza  Islamabad

    Name  Age  Salary
0    Ali   25   80000
1  Ahmed   30   90000
2   Sara   28   95000
3  Hamza   35  120000

<a id="p-6"></a>
## Practice 6

Using `iloc`:

1. Select the first row.
2. Select the last row.
3. Select rows 1–3.
4. Select the first two columns of the first three rows.
5. Select rows 0 and 2.

> 🧩 *Re-creates the data this problem uses (exactly as it was at this point of the lesson).*

In [11]:
data = {
    "Name": ["Ali", "Ahmed", "Sara", "Hamza"],
    "Age": [25, 30, 28, 35],
    "City": ["Lahore", "Karachi", "Lahore", "Islamabad"],
    "Salary": [80000, 90000, 95000, 120000]
}

df = pd.DataFrame(data)

print(df["Name"])
print()
print(df[["Name", "Age"]])

0      Ali
1    Ahmed
2     Sara
3    Hamza
Name: Name, dtype: str

    Name  Age
0    Ali   25
1  Ahmed   30
2   Sara   28
3  Hamza   35

In [12]:
# 1. Select the first row
df.iloc[0]


# 2. Select the last row
df.iloc[-1]


# 3. Select rows 1–3
df.iloc[1:4]


# 4. Select the first two columns of the first three rows
df.iloc[0:3, 0:2]


# 5. Select rows 0 and 2
df.iloc[[0, 2]]

   Name  Age    City  Salary
0   Ali   25  Lahore   80000
2  Sara   28  Lahore   95000

<a id="p-7"></a>
## Practice 7

Using `loc`:

1. Select row 2.
2. Select the name from row 1.
3. Select rows 0–2 and columns `Name` and `Salary`.

In [13]:
# Your solution
df.loc[2]
df.loc[1,"Name"]
df.loc[0:2,["Name","Salary"]]

    Name  Salary
0    Ali   80000
1  Ahmed   90000
2   Sara   95000

## ✅ Solution — Practice 6 & 7 — `iloc` (positions) vs `loc` (labels)

In [14]:
df = fresh_df()
print(df.iloc[0], "\n")          # 1 first row
print(df.iloc[-1], "\n")         # 2 last row
print(df.iloc[1:4], "\n")        # 3 rows 1-3 (stop is excluded)
print(df.iloc[:3, :2], "\n")     # 4 first 2 columns of first 3 rows
print(df.iloc[[0, 2]], "\n")     # 5 rows 0 and 2

print(df.loc[2], "\n")                         # row with label 2
print(df.loc[1, "Name"], "\n")                 # single value
print(df.loc[0:2, ["Name", "Salary"]])          # loc slices INCLUDE the end label

Name             Ali
Age               25
City          Lahore
Salary         80000
Department        IT
Gender          Male
Experience         2
Name: 0, dtype: object

Name              Hamza
Age                  35
City          Islamabad
Salary           120000
Department      Finance
Gender             Male
Experience            9
Name: 3, dtype: object

    Name  Age       City  Salary Department  Gender  Experience
1  Ahmed   30    Karachi   90000         HR    Male           5
2   Sara   28     Lahore   95000         IT  Female           4
3  Hamza   35  Islamabad  120000    Finance    Male           9

    Name  Age
0    Ali   25
1  Ahmed   30
2   Sara   28

   Name  Age    City  Salary Department  Gender  Experience
0   Ali   25  Lahore   80000         IT    Male           2
2  Sara   28  Lahore   95000         IT  Female           4

Name            Sara
Age               28
City          Lahore
Salary         95000
Department        IT
Gender        Female
Experience         4
Name: 2, dtype: object

Ahmed

    Name  Salary
0    Ali   80000
1  Ahmed   90000
2   Sara   95000

<a id="p-8"></a>
## Practice 8

Find:

1. Employees older than 27.
2. Employees earning more than 90,000.
3. Employees from Lahore AND earning more than 80,000.
4. Employees from Lahore OR Karachi.
5. Employees younger than 30 AND salary above 80,000.

<a id="p-9"></a>
## Practice 9

Using `isin()` and `query()`:

1. Find employees in Lahore or Islamabad.
2. Find employees not in Karachi.
3. Find employees with age >= 28 and salary < 110000.

> 🧩 *Re-creates the data this problem uses (exactly as it was at this point of the lesson).*

In [15]:
data = {
    "Name": ["Ali", "Ahmed", "Sara", "Hamza"],
    "Age": [25, 30, 28, 35],
    "City": ["Lahore", "Karachi", "Lahore", "Islamabad"],
    "Salary": [80000, 90000, 95000, 120000]
}

df = pd.DataFrame(data)

print(df["Name"])
print()
print(df[["Name", "Age"]])

0      Ali
1    Ahmed
2     Sara
3    Hamza
Name: Name, dtype: str

    Name  Age
0    Ali   25
1  Ahmed   30
2   Sara   28
3  Hamza   35

In [16]:
# Your solution
# df[df["City"].isin(["Lahore","Karachi"])]

# df[~df["City"].isin(["Lahore","Karachi"])]

# df[df["City"].isin(["Lahore","Karachi"])]
df.query("Age >=28 and Salary < 110000")

    Name  Age     City  Salary
1  Ahmed   30  Karachi   90000
2   Sara   28   Lahore   95000

## ✅ Solution — Practice 8 & 9 — Filtering, `isin()` and `query()`

In [17]:
df = fresh_df()
print(df[df["Age"] > 27], "\n")
print(df[df["Salary"] > 90000], "\n")
print(df[(df["City"] == "Lahore") & (df["Salary"] > 80000)], "\n")    # use & | with brackets
print(df[(df["City"] == "Lahore") | (df["City"] == "Karachi")], "\n")
print(df[(df["Age"] < 30) & (df["Salary"] > 80000)], "\n")

print(df[df["City"].isin(["Lahore", "Islamabad"])], "\n")
print(df[~df["City"].isin(["Karachi"])], "\n")
print(df.query("Age >= 28 and Salary < 110000"))

    Name  Age       City  Salary Department  Gender  Experience
1  Ahmed   30    Karachi   90000         HR    Male           5
2   Sara   28     Lahore   95000         IT  Female           4
3  Hamza   35  Islamabad  120000    Finance    Male           9

    Name  Age       City  Salary Department  Gender  Experience
2   Sara   28     Lahore   95000         IT  Female           4
3  Hamza   35  Islamabad  120000    Finance    Male           9

   Name  Age    City  Salary Department  Gender  Experience
2  Sara   28  Lahore   95000         IT  Female           4

    Name  Age     City  Salary Department  Gender  Experience
0    Ali   25   Lahore   80000         IT    Male           2
1  Ahmed   30  Karachi   90000         HR    Male           5
2   Sara   28   Lahore   95000         IT  Female           4

   Name  Age    City  Salary Department  Gender  Experience
2  Sara   28  Lahore   95000         IT  Female           4

    Name  Age       City  Salary Department  Gender  Experience
0    Ali   25     Lahore   80000         IT    Male           2
2   Sara   28     Lahore   95000         IT  Female           4
3  Hamza   35  Islamabad  120000    Finance    Male           9

    Name  Age       City  Salary Department  Gender  Experience
0    Ali   25     Lahore   80000         IT    Male           2
2   Sara   28     Lahore   95000         IT  Female           4
3  Hamza   35  Islamabad  120000    Finance    Male           9

    Name  Age     City  Salary Department  Gender  Experience
1  Ahmed   30  Karachi   90000         HR    Male           5
2   Sara   28   Lahore   95000         IT  Female           4

<a id="p-10"></a>
## Practice 10

Using `work_df`:

1. Add `Tax` equal to 5% of Salary.
2. Add `NetSalary` equal to Salary - Tax.
3. Add `MonthlyBonus` equal to 2% of Salary.

> 🧩 *Re-creates the data this problem uses (exactly as it was at this point of the lesson).*

In [18]:
data = {
    "Name": ["Ali", "Ahmed", "Sara", "Hamza"],
    "Age": [25, 30, 28, 35],
    "City": ["Lahore", "Karachi", "Lahore", "Islamabad"],
    "Salary": [80000, 90000, 95000, 120000]
}

df = pd.DataFrame(data)

print(df["Name"])
print()
print(df[["Name", "Age"]])

0      Ali
1    Ahmed
2     Sara
3    Hamza
Name: Name, dtype: str

    Name  Age
0    Ali   25
1  Ahmed   30
2   Sara   28
3  Hamza   35

In [19]:
# Your solution
employees = df.copy()

employees["Tax"] = employees["Salary"] * 0.05
employees["Net "] = employees["Salary"] - employees["Tax"]
employees["Monthly Bonus"] =employees["Salary"] * 0.02
employees

    Name  Age       City  Salary     Tax      Net   Monthly Bonus
0    Ali   25     Lahore   80000  4000.0   76000.0         1600.0
1  Ahmed   30    Karachi   90000  4500.0   85500.0         1800.0
2   Sara   28     Lahore   95000  4750.0   90250.0         1900.0
3  Hamza   35  Islamabad  120000  6000.0  114000.0         2400.0

<a id="p-11"></a>
## Practice 11

Create `ExperienceLevel` using:

- Experience < 3 → Junior
- Experience 3–7 → Mid
- Experience > 7 → Senior

Use `np.select()` or another appropriate Pandas method.

In [20]:
# Your solution
work_df["experience"] =[2,5,6,9]

conditions = [work_df["experience"] < 3,
                 work_df["experience"].between(3,7) ,
               work_df["experience"] > 7]
values =["Junior","Mid","Senior"]

work_df["ExperienceLevel"] =np.select(conditions,values, default="Unknown")

work_df

,Name,Age,City,Salary,AnnualSalary,Bonus,SalaryLevel,AgeGroup,experience,ExperienceLevel
0,Ali,25,Lahore,80000,960000,8000.0,Normal,Young,2,Junior
1,Ahmed,30,Karachi,90000,1080000,9000.0,Normal,Middle,5,Mid
2,Sara,28,Lahore,95000,1140000,9500.0,Normal,Young,6,Mid
3,Hamza,35,Islamabad,120000,1440000,12000.0,High,Middle,9,Senior

## ✅ Solution — Practice 10 & 11 — New columns and `np.select()`

In [21]:
work_df = fresh_df()
work_df["Tax"] = work_df["Salary"] * 0.05
work_df["NetSalary"] = work_df["Salary"] - work_df["Tax"]
work_df["MonthlyBonus"] = work_df["Salary"] * 0.02

conditions = [work_df["Experience"] < 3,
              work_df["Experience"].between(3, 7),
              work_df["Experience"] > 7]
work_df["ExperienceLevel"] = np.select(conditions, ["Junior", "Mid", "Senior"], default="Unknown")
work_df[["Name", "Salary", "Tax", "NetSalary", "MonthlyBonus", "Experience", "ExperienceLevel"]]

    Name  Salary     Tax  NetSalary  MonthlyBonus  Experience ExperienceLevel
0    Ali   80000  4000.0    76000.0        1600.0           2          Junior
1  Ahmed   90000  4500.0    85500.0        1800.0           5             Mid
2   Sara   95000  4750.0    90250.0        1900.0           4             Mid
3  Hamza  120000  6000.0   114000.0        2400.0           9          Senior

<a id="p-12"></a>
## Practice 12

Create a copy of `df` and:

1. Rename `Name` to `EmployeeName`.
2. Rename `Salary` to `MonthlySalary`.
3. Remove `City`.
4. Remove row index 0.

> 🧩 *Re-creates the data this problem uses (exactly as it was at this point of the lesson).*

In [22]:
work_df = df.copy()

work_df["AnnualSalary"] = work_df["Salary"] * 12
work_df["Bonus"] = work_df["Salary"] * 0.10

work_df

    Name  Age       City  Salary  AnnualSalary    Bonus
0    Ali   25     Lahore   80000        960000   8000.0
1  Ahmed   30    Karachi   90000       1080000   9000.0
2   Sara   28     Lahore   95000       1140000   9500.0
3  Hamza   35  Islamabad  120000       1440000  12000.0

In [23]:
# Your solution
renamed = work_df.rename(columns={"Name": "EmployeeName"})
renamed = renamed.rename(columns={"Salary": "MonthSalary"})
renamed = renamed.drop(columns=["City"])
renamed= renamed.drop(0)
renamed

  EmployeeName  Age  MonthSalary  AnnualSalary    Bonus
1        Ahmed   30        90000       1080000   9000.0
2         Sara   28        95000       1140000   9500.0
3        Hamza   35       120000       1440000  12000.0

<a id="p-13"></a>
## Practice 13

1. Sort by Age ascending.
2. Sort by Salary descending.
3. Sort by City ascending and Salary descending.

In [24]:
# Your solution
print(df.sort_values("Age",ascending=True))
print(df.sort_values("Salary",ascending=False))
print(df.sort_values(["City","Salary"],ascending=[True,False]))

    Name  Age       City  Salary
0    Ali   25     Lahore   80000
2   Sara   28     Lahore   95000
1  Ahmed   30    Karachi   90000
3  Hamza   35  Islamabad  120000
    Name  Age       City  Salary
3  Hamza   35  Islamabad  120000
2   Sara   28     Lahore   95000
1  Ahmed   30    Karachi   90000
0    Ali   25     Lahore   80000
    Name  Age       City  Salary
3  Hamza   35  Islamabad  120000
1  Ahmed   30    Karachi   90000
2   Sara   28     Lahore   95000
0    Ali   25     Lahore   80000

<a id="p-14"></a>
## Practice 14

Create a copy of `df`, set `Name` as the index, inspect it, then reset the index.

In [25]:
# Your solution
indexed_df = df.set_index("Name")

print(indexed_df)
indexed_df.reset_index()
print(indexed_df.reset_index())

       Age       City  Salary
Name
Ali     25     Lahore   80000
Ahmed   30    Karachi   90000
Sara    28     Lahore   95000
Hamza   35  Islamabad  120000
    Name  Age       City  Salary
0    Ali   25     Lahore   80000
1  Ahmed   30    Karachi   90000
2   Sara   28     Lahore   95000
3  Hamza   35  Islamabad  120000

## ✅ Solution — Practice 12, 13 & 14 — Rename/drop, sort, index

In [26]:
df = fresh_df()
p12 = (df.copy()
         .rename(columns={"Name": "EmployeeName", "Salary": "MonthlySalary"})
         .drop(columns="City")
         .drop(index=0))
print(p12, "\n")

print(df.sort_values("Age"), "\n")
print(df.sort_values("Salary", ascending=False), "\n")
print(df.sort_values(["City", "Salary"], ascending=[True, False]), "\n")

p14 = df.copy().set_index("Name")
print(p14.loc["Sara"], "\n")      # label lookup by name
print(p14.reset_index().head(2))

  EmployeeName  Age  MonthlySalary Department  Gender  Experience
1        Ahmed   30          90000         HR    Male           5
2         Sara   28          95000         IT  Female           4
3        Hamza   35         120000    Finance    Male           9

    Name  Age       City  Salary Department  Gender  Experience
0    Ali   25     Lahore   80000         IT    Male           2
2   Sara   28     Lahore   95000         IT  Female           4
1  Ahmed   30    Karachi   90000         HR    Male           5
3  Hamza   35  Islamabad  120000    Finance    Male           9

    Name  Age       City  Salary Department  Gender  Experience
3  Hamza   35  Islamabad  120000    Finance    Male           9
2   Sara   28     Lahore   95000         IT  Female           4
1  Ahmed   30    Karachi   90000         HR    Male           5
0    Ali   25     Lahore   80000         IT    Male           2

    Name  Age       City  Salary Department  Gender  Experience
3  Hamza   35  Islamabad  120000    Finance    Male           9
1  Ahmed   30    Karachi   90000         HR    Male           5
2   Sara   28     Lahore   95000         IT  Female           4
0    Ali   25     Lahore   80000         IT    Male           2

Age               28
City          Lahore
Salary         95000
Department        IT
Gender        Female
Experience         4
Name: Sara, dtype: object

    Name  Age     City  Salary Department Gender  Experience
0    Ali   25   Lahore   80000         IT   Male           2
1  Ahmed   30  Karachi   90000         HR   Male           5

<a id="p-15"></a>
## Practice 15

Using `missing_df`:

1. Count missing values per column.
2. Fill Age with its median.
3. Fill Salary with its mean.
4. Fill City with `"Unknown"`.
5. Remove rows containing any missing value.

In [27]:
# Your solution

print(missing_df.isna().sum())
filled["Age"] = filled["Age"].fillna(filled["Age"].median())
filled["Salary"] = filled["Salary"].fillna(filled["Salary"].mean())
filled["City"] = filled["City"].fillna("UnKnow")
filled

Name      0
Age       2
Salary    1
City      1
dtype: int64

    Name   Age    Salary       City
0    Ali  25.0   80000.0     Lahore
1  Ahmed  28.0   90000.0    Karachi
2   Sara  28.0   96250.0    Unknown
3  Hamza  35.0  120000.0  Islamabad
4   Zara  28.0   95000.0     Lahore

<a id="p-16"></a>
## Practice 16

Using `duplicate_df`:

1. Find duplicate rows.
2. Count duplicates.
3. Remove duplicates.
4. Check duplicates based only on `Name`.

> 🧩 *Re-creates the data this problem uses (exactly as it was at this point of the lesson).*

In [28]:
data = {
    "Name": ["Ali", "Ahmed", "Sara", "Hamza"],
    "Age": [25, 30, 28, 35],
    "City": ["Lahore", "Karachi", "Lahore", "Islamabad"],
    "Salary": [80000, 90000, 95000, 120000]
}

df = pd.DataFrame(data)

print(df["Name"])
print()
print(df[["Name", "Age"]])

0      Ali
1    Ahmed
2     Sara
3    Hamza
Name: Name, dtype: str

    Name  Age
0    Ali   25
1  Ahmed   30
2   Sara   28
3  Hamza   35

In [29]:
# Your solution
duplicate_df = pd.concat(
    [df, df.iloc[[0, 1]]],
    ignore_index=True
)
print(duplicate_df.duplicated().sum())

print(duplicate_df[duplicate_df.duplicated])

print(duplicate_df.drop_duplicates())

2
    Name  Age     City  Salary
4    Ali   25   Lahore   80000
5  Ahmed   30  Karachi   90000
    Name  Age       City  Salary
0    Ali   25     Lahore   80000
1  Ahmed   30    Karachi   90000
2   Sara   28     Lahore   95000
3  Hamza   35  Islamabad  120000

## ✅ Solution — Practice 15 & 16 — Missing values and duplicates

In [30]:
missing_df = pd.DataFrame({
    "Name": ["Ali", "Ahmed", "Sara", "Hamza", "Zara"],
    "Age": [25, np.nan, 28, 35, np.nan],
    "Salary": [80000, 90000, np.nan, 120000, 95000],
    "City": ["Lahore", "Karachi", None, "Islamabad", "Lahore"]
})
print(missing_df.isna().sum(), "\n")

filled = missing_df.copy()
filled["Age"] = filled["Age"].fillna(filled["Age"].median())
filled["Salary"] = filled["Salary"].fillna(filled["Salary"].mean())
filled["City"] = filled["City"].fillna("Unknown")
print(filled, "\n")
print(missing_df.dropna(), "\n")          # 5. only rows with no missing values

df = fresh_df()
duplicate_df = pd.concat([df, df.iloc[[0, 1]]], ignore_index=True)
print(duplicate_df[duplicate_df.duplicated()], "\n")
print("count:", duplicate_df.duplicated().sum())
print(duplicate_df.drop_duplicates().shape)
print(duplicate_df.duplicated(subset=["Name"]).sum(), "duplicates by Name only")

Name      0
Age       2
Salary    1
City      1
dtype: int64

    Name   Age    Salary       City
0    Ali  25.0   80000.0     Lahore
1  Ahmed  28.0   90000.0    Karachi
2   Sara  28.0   96250.0    Unknown
3  Hamza  35.0  120000.0  Islamabad
4   Zara  28.0   95000.0     Lahore

    Name   Age    Salary       City
0    Ali  25.0   80000.0     Lahore
3  Hamza  35.0  120000.0  Islamabad

    Name  Age     City  Salary Department Gender  Experience
4    Ali   25   Lahore   80000         IT   Male           2
5  Ahmed   30  Karachi   90000         HR   Male           5

count: 2
(4, 7)
2 duplicates by Name only

<a id="p-17"></a>
## Practice 17

Create a DataFrame with numeric values stored as strings and convert them to numbers.

Then use `errors="coerce"` on at least one invalid value.

In [31]:
# Your solution
types_df["Age"] = pd.to_numeric(types_df["Age"], errors="coerce")

<a id="p-18"></a>
## Practice 18

Using `names_df`:

1. Remove whitespace from Name.
2. Convert names to lowercase.
3. Find names containing `"sara"`, case-insensitive.
4. Extract the email domain.
5. Create a column containing name length.

In [32]:
# Your solution
# print(names_df["Name"].str.strip().str.lower())
print(names_df[names_df["Name"].str.startswith("Sara") ])

        Name          Email  CleanName     EmailLower  NameLength
2  Sara Khan  sara@test.com  Sara Khan  sara@test.com           9

## ✅ Solution — Practice 17 & 18 — Type conversion and string operations

In [33]:
types_demo = pd.DataFrame({"Age": ["25", "30", "abc", "41"], "Price": ["10.5", "20", "7.25", "n/a"]})
types_demo["Age"] = pd.to_numeric(types_demo["Age"], errors="coerce")       # "abc" -> NaN
types_demo["Price"] = pd.to_numeric(types_demo["Price"], errors="coerce")   # "n/a" -> NaN
print(types_demo, "\n", types_demo.dtypes, "\n")

names_df = pd.DataFrame({
    "Name": [" Ali ", "AHMED", "Sara Khan", "Muhammad Usman"],
    "Email": ["ALI@example.com", "ahmed@example.com", "sara@test.com", "usman@example.com"]
})
names_df["Name"] = names_df["Name"].str.strip()                                    # 1
names_df["NameLower"] = names_df["Name"].str.lower()                               # 2
print(names_df[names_df["Name"].str.contains("sara", case=False)], "\n")          # 3
names_df["Domain"] = names_df["Email"].str.split("@").str[1].str.lower()           # 4
names_df["NameLength"] = names_df["Name"].str.len()                                # 5
names_df

    Age  Price
0  25.0  10.50
1  30.0  20.00
2   NaN   7.25
3  41.0    NaN
 Age      float64
Price    float64
dtype: object

        Name          Email  NameLower
2  Sara Khan  sara@test.com  sara khan

             Name              Email       NameLower       Domain  NameLength
0             Ali    ALI@example.com             ali  example.com           3
1           AHMED  ahmed@example.com           ahmed  example.com           5
2       Sara Khan      sara@test.com       sara khan     test.com           9
3  Muhammad Usman  usman@example.com  muhammad usman  example.com          14

<a id="p-19"></a>
## Practice 19

Using `date_df`:

1. Add a month name column.
2. Add a day column.
3. Filter records after `2026-02-01`.
4. Find the month with the highest sales.

In [34]:
# Your solution
date_df["Date"] = pd.to_datetime(date_df["Date"])

date_df["Year"] = date_df["Date"].dt.year
date_df["Month"] = date_df["Date"].dt.month
date_df["DayName"] = date_df["Date"].dt.day_name()
date_df

        Date  Sales  Year  Month   DayName
0 2026-01-15    100  2026      1  Thursday
1 2026-02-20    150  2026      2    Friday
2 2026-03-10    120  2026      3   Tuesday
3 2026-04-25    200  2026      4  Saturday

## ✅ Solution — Practice 19 — Dates

In [35]:
date_df = pd.DataFrame({
    "Date": pd.to_datetime(["2026-01-15", "2026-02-20", "2026-03-10", "2026-04-25"]),
    "Sales": [100, 150, 120, 200]
})
date_df["MonthName"] = date_df["Date"].dt.month_name()
date_df["Day"] = date_df["Date"].dt.day
print(date_df[date_df["Date"] > "2026-02-01"], "\n")
monthly = date_df.groupby("MonthName")["Sales"].sum()
print("Best month:", monthly.idxmax(), monthly.max())

        Date  Sales MonthName  Day
1 2026-02-20    150  February   20
2 2026-03-10    120     March   10
3 2026-04-25    200     April   25

Best month: April 200

<a id="p-20"></a>
## Practice 20

Create a function that takes Age and returns:

- `"Adult"` if age >= 18
- `"Minor"` otherwise

Use `apply()` to create an `AgeStatus` column.

> 🧩 *Re-creates the data this problem uses (exactly as it was at this point of the lesson).*

In [36]:
data = {
    "Name": ["Ali", "Ahmed", "Sara", "Hamza"],
    "Age": [25, 30, 28, 35],
    "City": ["Lahore", "Karachi", "Lahore", "Islamabad"],
    "Salary": [80000, 90000, 95000, 120000]
}

df = pd.DataFrame(data)

print(df["Name"])
print()
print(df[["Name", "Age"]])

0      Ali
1    Ahmed
2     Sara
3    Hamza
Name: Name, dtype: str

    Name  Age
0    Ali   25
1  Ahmed   30
2   Sara   28
3  Hamza   35

In [37]:
# Your solution
def ageStatus(age):
    if(age >= 18):
        return "Adult"
    else:
        return "Minor"

df["AgeStatus"] = df["Age"].apply(ageStatus)
df

    Name  Age       City  Salary AgeStatus
0    Ali   25     Lahore   80000     Adult
1  Ahmed   30    Karachi   90000     Adult
2   Sara   28     Lahore   95000     Adult
3  Hamza   35  Islamabad  120000     Adult

<a id="p-21"></a>
## Practice 21

Create a mapping:

- IT → Technology
- HR → Human Resources
- Finance → Finance

Create a new `DepartmentGroup` column.

In [38]:
# Your solution

<a id="p-22"></a>
## Practice 22

Replace city names with abbreviations:

- Lahore → LHR
- Karachi → KHI
- Islamabad → ISB

Do not modify the original `df`.

In [39]:
# Your solution

<a id="p-23"></a>
## Practice 23

Use `assign()` to create:

- `AnnualSalary`
- `Bonus`
- `Tax`

Return a new DataFrame.

In [40]:
# Your solution
assigned = df.assign(
    AnnualSalary=df["Salary"] * 12,
    Bonus=df["Salary"] * 0.10,
    Tax=df["Salary"] * 0.05
)
assigned

    Name  Age       City  Salary AgeStatus  AnnualSalary    Bonus     Tax
0    Ali   25     Lahore   80000     Adult        960000   8000.0  4000.0
1  Ahmed   30    Karachi   90000     Adult       1080000   9000.0  4500.0
2   Sara   28     Lahore   95000     Adult       1140000   9500.0  4750.0
3  Hamza   35  Islamabad  120000     Adult       1440000  12000.0  6000.0

## ✅ Solution — Practice 20, 21, 22 & 23 — `apply()`, `map()`, `replace()`, `assign()`

In [41]:
df = fresh_df()

def age_status(age):
    return "Adult" if age >= 18 else "Minor"

p20 = df.copy()
p20["AgeStatus"] = p20["Age"].apply(age_status)

group = {"IT": "Technology", "HR": "Human Resources", "Finance": "Finance"}
p20["DepartmentGroup"] = p20["Department"].map(group)
print(p20[["Name", "Age", "AgeStatus", "Department", "DepartmentGroup"]], "\n")

abbrev = df.replace({"City": {"Lahore": "LHR", "Karachi": "KHI", "Islamabad": "ISB"}})   # returns a NEW frame
print(abbrev[["Name", "City"]])
print("original unchanged:", df["City"].tolist(), "\n")

p23 = df.assign(AnnualSalary=df["Salary"] * 12,
                Bonus=df["Salary"] * 0.10,
                Tax=lambda d: d["AnnualSalary"] * 0.05)       # lambda can use columns created just before
p23[["Name", "Salary", "AnnualSalary", "Bonus", "Tax"]]

    Name  Age AgeStatus Department  DepartmentGroup
0    Ali   25     Adult         IT       Technology
1  Ahmed   30     Adult         HR  Human Resources
2   Sara   28     Adult         IT       Technology
3  Hamza   35     Adult    Finance          Finance

    Name City
0    Ali  LHR
1  Ahmed  KHI
2   Sara  LHR
3  Hamza  ISB
original unchanged: ['Lahore', 'Karachi', 'Lahore', 'Islamabad']

    Name  Salary  AnnualSalary    Bonus      Tax
0    Ali   80000        960000   8000.0  48000.0
1  Ahmed   90000       1080000   9000.0  54000.0
2   Sara   95000       1140000   9500.0  57000.0
3  Hamza  120000       1440000  12000.0  72000.0

<a id="p-24"></a>
## Practice 24

Calculate:

1. Total salary
2. Average salary
3. Median salary
4. Highest salary
5. Lowest salary
6. Salary standard deviation

In [42]:
# Your solution
print("Sum:", salary.sum())
print("Sum:", salary.mean())
print("Sum:", salary.median())
print("Sum:", salary.max())
print("Sum:", salary.min())
print("Sum:", salary.std())

Sum: 385000
Sum: 96250.0
Sum: 92500.0
Sum: 120000
Sum: 80000
Sum: 17017.148213885113

<a id="p-25"></a>
## Practice 25

Using `df["City"]`:

1. Get unique cities.
2. Count unique cities.
3. Count each city.
4. Calculate the percentage of employees from each city.

> 🧩 *Re-creates the data this problem uses (exactly as it was at this point of the lesson).*

In [43]:
data = {
    "Name": ["Ali", "Ahmed", "Sara", "Hamza"],
    "Age": [25, 30, 28, 35],
    "City": ["Lahore", "Karachi", "Lahore", "Islamabad"],
    "Salary": [80000, 90000, 95000, 120000]
}

df = pd.DataFrame(data)

print(df["Name"])
print()
print(df[["Name", "Age"]])

0      Ali
1    Ahmed
2     Sara
3    Hamza
Name: Name, dtype: str

    Name  Age
0    Ali   25
1  Ahmed   30
2   Sara   28
3  Hamza   35

In [44]:
# Your solution
print("Unique cities:", df["City"].unique())

print("Unique cities:", df["City"].nunique())

print(df["City"].value_counts())

print(df["City"].value_counts(normalize=True))

Unique cities: <ArrowStringArray>
['Lahore', 'Karachi', 'Islamabad']
Length: 3, dtype: str
Unique cities: 3
City
Lahore       2
Karachi      1
Islamabad    1
Name: count, dtype: int64
City
Lahore       0.50
Karachi      0.25
Islamabad    0.25
Name: proportion, dtype: float64

## ✅ Solution — Practice 24 & 25 — Aggregation and counting

In [45]:
df = fresh_df()
s = df["Salary"]
print("Total :", s.sum())
print("Mean  :", s.mean())
print("Median:", s.median())
print("Max   :", s.max())
print("Min   :", s.min())
print("Std   :", round(s.std(), 2), "\n")

print("Unique cities:", df["City"].unique().tolist())
print("How many     :", df["City"].nunique())
print(df["City"].value_counts())
print((df["City"].value_counts(normalize=True) * 100).round(1))

Total : 385000
Mean  : 96250.0
Median: 92500.0
Max   : 120000
Min   : 80000
Std   : 17017.15

Unique cities: ['Lahore', 'Karachi', 'Islamabad']
How many     : 3
City
Lahore       2
Karachi      1
Islamabad    1
Name: count, dtype: int64
City
Lahore       50.0
Karachi      25.0
Islamabad    25.0
Name: proportion, dtype: float64

<a id="p-26"></a>
## Practice 26 — GroupBy

Calculate by Department:

1. Average salary
2. Total salary
3. Maximum salary
4. Minimum salary
5. Number of employees

Then calculate average salary by City.

> 🧩 *Re-creates the data this problem uses (exactly as it was at this point of the lesson).*

In [46]:
data = {
    "Name": ["Ali", "Ahmed", "Sara", "Hamza"],
    "Age": [25, 30, 28, 35],
    "City": ["Lahore", "Karachi", "Lahore", "Islamabad"],
    "Salary": [80000, 90000, 95000, 120000]
}

df = pd.DataFrame(data)

print(df["Name"])
print()
print(df[["Name", "Age"]])

0      Ali
1    Ahmed
2     Sara
3    Hamza
Name: Name, dtype: str

    Name  Age
0    Ali   25
1  Ahmed   30
2   Sara   28
3  Hamza   35

In [47]:
# Your solution
print(df.groupby("City")["Salary"].agg(["mean","sum","max","min"] ))


print(df.groupby("City").agg(Average=("Salary","mean"),Total=("Salary","sum"),Max=("Salary","max"),Min=("Salary","min"),Employees=("Name","count")))

               mean     sum     max     min
City
Islamabad  120000.0  120000  120000  120000
Karachi     90000.0   90000   90000   90000
Lahore      87500.0  175000   95000   80000
            Average   Total     Max     Min  Employees
City
Islamabad  120000.0  120000  120000  120000          1
Karachi     90000.0   90000   90000   90000          1
Lahore      87500.0  175000   95000   80000          2

<a id="p-27"></a>
## Practice 27

Create a DataFrame containing average salary by Department and reset its index.

In [48]:
# Your solution
grouped = df.groupby("City")["Salary"].agg("mean")

grouped.reset_index()

        City    Salary
0  Islamabad  120000.0
1    Karachi   90000.0
2     Lahore   87500.0

## ✅ Solution — Practice 26 & 27 — GroupBy

In [49]:
df = fresh_df()
print(df.groupby("Department")["Salary"].agg(["mean", "sum", "max", "min", "count"]), "\n")
print(df.groupby("City")["Salary"].mean(), "\n")

avg_by_dept = df.groupby("Department")["Salary"].mean().reset_index()
avg_by_dept

                mean     sum     max     min  count
Department
Finance     120000.0  120000  120000  120000      1
HR           90000.0   90000   90000   90000      1
IT           87500.0  175000   95000   80000      2

City
Islamabad    120000.0
Karachi       90000.0
Lahore        87500.0
Name: Salary, dtype: float64

  Department    Salary
0    Finance  120000.0
1         HR   90000.0
2         IT   87500.0

<a id="p-28"></a>
## Practice 28

Create two DataFrames representing two teams and combine them vertically with `concat()`.

In [50]:
df1 = pd.DataFrame({
    "Name": ["Ali", "Sara"],
    "Salary": [80000, 95000]
})

df2 = pd.DataFrame({
    "Name": ["Ahmed", "Hamza"],
    "Salary": [90000, 120000]
})

combined = pd.concat([df1, df2], ignore_index=True)
combined

    Name  Salary
0    Ali   80000
1   Sara   95000
2  Ahmed   90000
3  Hamza  120000

<a id="p-29"></a>
## Practice 29 — Merge

Create:

`employees`: employee_id, Name, Department

`performance`: employee_id, Rating

Merge them using:

1. Inner join
2. Left join
3. Outer join

Explain to yourself what happens to unmatched IDs.

In [51]:
employees = pd.DataFrame({
    "employee_id": [1, 2, 3, 4],
    "Name": ["Ali", "Ahmed", "Sara", "Hamza"],
    "Department":["Dev","Hr","Business","Dev"]
})

performance = pd.DataFrame({
    "employee_id": [1, 2, 3, 5],
    "ratting": [6, 7, 8, 9]
})

print(pd.merge(employees, performance, on="employee_id", how="inner"))

print(pd.merge(employees, performance, on="employee_id", how="left"))

print(pd.merge(employees, performance, on="employee_id", how="outer"))

   employee_id   Name Department  ratting
0            1    Ali        Dev        6
1            2  Ahmed         Hr        7
2            3   Sara   Business        8
   employee_id   Name Department  ratting
0            1    Ali        Dev      6.0
1            2  Ahmed         Hr      7.0
2            3   Sara   Business      8.0
3            4  Hamza        Dev      NaN
   employee_id   Name Department  ratting
0            1    Ali        Dev      6.0
1            2  Ahmed         Hr      7.0
2            3   Sara   Business      8.0
3            4  Hamza        Dev      NaN
4            5    NaN        NaN      9.0

<a id="p-30"></a>
## Practice 30

Create two DataFrames with the same employee IDs as indexes and join them.

In [52]:
left = pd.DataFrame(
    {"Name": ["Ali", "Sara", "Ahmed"]},
    index=[1, 2, 3]
)

right = pd.DataFrame(
    {"Salary": [80000, 95000, 90000]},
    index=[1, 2, 3]
)

left.join(right)

    Name  Salary
1    Ali   80000
2   Sara   95000
3  Ahmed   90000

## ✅ Solution — Practice 28, 29 & 30 — `concat`, `merge`, `join` (more in Topic 10)

In [53]:
team_a = pd.DataFrame({"Name": ["Ali", "Sara"], "Team": ["A", "A"]})
team_b = pd.DataFrame({"Name": ["Ahmed", "Zara"], "Team": ["B", "B"]})
print(pd.concat([team_a, team_b], ignore_index=True), "\n")

employees = pd.DataFrame({"employee_id": [1, 2, 3, 4],
                          "Name": ["Ali", "Sara", "Ahmed", "Zara"],
                          "Department": ["IT", "HR", "IT", "Finance"]})
performance = pd.DataFrame({"employee_id": [2, 3, 4, 5], "Rating": [4.5, 3.8, 4.1, 4.9]})
for how in ["inner", "left", "outer"]:
    print(how.upper()); print(employees.merge(performance, on="employee_id", how=how), "\n")

    Name Team
0    Ali    A
1   Sara    A
2  Ahmed    B
3   Zara    B

INNER
   employee_id   Name Department  Rating
0            2   Sara         HR     4.5
1            3  Ahmed         IT     3.8
2            4   Zara    Finance     4.1

LEFT
   employee_id   Name Department  Rating
0            1    Ali         IT     NaN
1            2   Sara         HR     4.5
2            3  Ahmed         IT     3.8
3            4   Zara    Finance     4.1

OUTER
   employee_id   Name Department  Rating
0            1    Ali         IT     NaN
1            2   Sara         HR     4.5
2            3  Ahmed         IT     3.8
3            4   Zara    Finance     4.1
4            5    NaN        NaN     4.9

Unmatched IDs: **inner** keeps only IDs 2–4. **left** keeps all employees; ID 1 gets `NaN` rating.
**outer** keeps everything; ID 1 has no rating and ID 5 has no name/department.

In [54]:
info = pd.DataFrame({"Name": ["Ali", "Sara", "Ahmed"]}, index=[101, 102, 103])
pay = pd.DataFrame({"Salary": [80000, 95000, 90000]}, index=[101, 102, 103])
info.join(pay)                       # join matches on the index

      Name  Salary
101    Ali   80000
102   Sara   95000
103  Ahmed   90000

<a id="p-31"></a>
## Practice 31

Create a pivot table that shows average Salary by Department and Gender.
Then create another pivot table showing total Salary.

In [55]:
# Your solution
sales = pd.DataFrame({
    "Department": ["IT", "IT", "HR", "HR", "Finance", "Finance"],
    "Gender": ["M", "F", "M", "F", "M", "F"],
    "Salary": [80000, 95000, 70000, 75000, 120000, 110000]
})

pivot = pd.pivot_table(
    sales,
    values="Salary",
    index="Department",
    columns="Gender",
    aggfunc="mean"
)

# pivot

total = pd.pivot_table(
    sales,
    values="Salary",
    index="Department",
    columns="Gender",
    aggfunc="sum"
)

pivot

Gender             F         M
Department
Finance     110000.0  120000.0
HR           75000.0   70000.0
IT           95000.0   80000.0

<a id="p-32"></a>
## Practice 32

Create a wide DataFrame with student names and three subjects.

Use `melt()` to convert it into:

`Name | Subject | Score`

In [56]:
# Your solution

wide = pd.DataFrame({
    "Name": ["Ali", "Sara"],
    "Math": [90, 95],
    "English": [85, 88]
})

wide.melt(id_vars=["Name"],var_name="Subject",value_name="Score")

   Name  Subject  Score
0   Ali     Math     90
1  Sara     Math     95
2   Ali  English     85
3  Sara  English     88

<a id="p-33"></a>
## Practice 33

Use a small DataFrame with students and subjects to practice:

1. `stack()`
2. `unstack()`

In [57]:
# Your solution
multi = pd.DataFrame({
    "Math": [90, 95],
    "English": [85, 88]
}, index=["Ali", "Sara"])

stacked = multi.stack()
print(stacked)

print()
print(stacked.unstack())

Ali   Math       90
      English    85
Sara  Math       95
      English    88
dtype: int64

      Math  English
Ali     90       85
Sara    95       88

## ✅ Solution — Practice 31, 32 & 33 — Pivot, melt, stack/unstack

In [58]:
df = fresh_df()
print(df.pivot_table(values="Salary", index="Department", columns="Gender", aggfunc="mean"), "\n")
print(df.pivot_table(values="Salary", index="Department", columns="Gender", aggfunc="sum", fill_value=0), "\n")

wide = pd.DataFrame({"Name": ["Ali", "Sara", "Ahmed"],
                     "Math": [90, 85, 70], "Physics": [80, 95, 65], "English": [75, 88, 92]})
long = wide.melt(id_vars="Name", var_name="Subject", value_name="Score")
print(long, "\n")

scores = wide.set_index("Name")
stacked = scores.stack()           # columns -> inner row level (a Series)
print(stacked.head(4), "\n")
print(stacked.unstack())           # back to wide

Gender       Female      Male
Department
Finance         NaN  120000.0
HR              NaN   90000.0
IT          95000.0   80000.0

Gender      Female    Male
Department
Finance          0  120000
HR               0   90000
IT           95000   80000

    Name  Subject  Score
0    Ali     Math     90
1   Sara     Math     85
2  Ahmed     Math     70
3    Ali  Physics     80
4   Sara  Physics     95
5  Ahmed  Physics     65
6    Ali  English     75
7   Sara  English     88
8  Ahmed  English     92

Name
Ali   Math       90
      Physics    80
      English    75
Sara  Math       85
dtype: int64

       Math  Physics  English
Name
Ali      90       80       75
Sara     85       95       88
Ahmed    70       65       92

<a id="p-34"></a>
## Practice 34

Create a MultiIndex using:

`City` and `Department`.

Then reset the index.

In [59]:
# Your solution

<a id="p-35"></a>
## Practice 35

Using the Salary column:

1. Keep salaries >= 90000 and replace the rest with NaN using `where()`.
2. Replace salaries >= 100000 with NaN using `mask()`.

In [60]:
# Your solution

<a id="p-36"></a>
## Practice 36

Create a salary Series and limit all values to the range 70,000–110,000.

> 🧩 *Re-creates the data this problem uses (exactly as it was at this point of the lesson).*

In [61]:
data = {
    "Name": ["Ali", "Ahmed", "Sara", "Hamza"],
    "Age": [25, 30, 28, 35],
    "City": ["Lahore", "Karachi", "Lahore", "Islamabad"],
    "Salary": [80000, 90000, 95000, 120000]
}

df = pd.DataFrame(data)

print(df["Name"])
print()
print(df[["Name", "Age"]])

0      Ali
1    Ahmed
2     Sara
3    Hamza
Name: Name, dtype: str

    Name  Age
0    Ali   25
1  Ahmed   30
2   Sara   28
3  Hamza   35

In [62]:
# Your solution
df["salary"] = [30000, 40000, 50000, 1000000]

df["salary"] = df["salary"].clip(upper=100000)

df

    Name  Age       City  Salary  salary
0    Ali   25     Lahore   80000   30000
1  Ahmed   30    Karachi   90000   40000
2   Sara   28     Lahore   95000   50000
3  Hamza   35  Islamabad  120000  100000

<a id="p-37"></a>
## Practice 37

Create:

1. Salary rank, highest first.
2. Age rank, oldest first.

In [63]:
# Your solution

## ✅ Solution — Practice 34, 35, 36 & 37 — MultiIndex, `where`/`mask`, `clip`, `rank`

In [64]:
df = fresh_df()
multi = df.set_index(["City", "Department"])
print(multi, "\n")
print(multi.reset_index().head(2), "\n")

s = df["Salary"]
print(s.where(s >= 90000).tolist())      # keep >= 90000, others -> NaN
print(s.mask(s >= 100000).tolist())      # hide >= 100000
print(pd.Series([50000, 75000, 98000, 140000]).clip(70000, 110000).tolist(), "\n")

ranked = df.assign(SalaryRank=df["Salary"].rank(ascending=False).astype(int),
                   AgeRank=df["Age"].rank(ascending=False).astype(int))
ranked[["Name", "Salary", "SalaryRank", "Age", "AgeRank"]]

                       Name  Age  Salary  Gender  Experience
City      Department
Lahore    IT            Ali   25   80000    Male           2
Karachi   HR          Ahmed   30   90000    Male           5
Lahore    IT           Sara   28   95000  Female           4
Islamabad Finance     Hamza   35  120000    Male           9

      City Department   Name  Age  Salary Gender  Experience
0   Lahore         IT    Ali   25   80000   Male           2
1  Karachi         HR  Ahmed   30   90000   Male           5

[nan, 90000.0, 95000.0, 120000.0]
[80000.0, 90000.0, 95000.0, nan]
[70000, 75000, 98000, 110000]

    Name  Salary  SalaryRank  Age  AgeRank
0    Ali   80000           4   25        4
1  Ahmed   90000           3   30        2
2   Sara   95000           2   28        3
3  Hamza  120000           1   35        1

<a id="p-38"></a>
## Practice 38

Create a Sales column and calculate:

1. Cumulative sales.
2. Running maximum sales.

In [65]:
# Your solution

<a id="p-39"></a>
## Practice 39

Create a sales DataFrame and calculate:

1. Previous day's sales.
2. Daily change.
3. Daily percentage change.

In [66]:
# Your solution

<a id="p-40"></a>
## Practice 40

Create a 3-day moving average for a sales series.

In [67]:
# Your solution

## ✅ Solution — Practice 38, 39 & 40 — Cumulative, `shift`, rolling

In [68]:
sales = pd.DataFrame({"Date": pd.date_range("2026-01-01", periods=7, freq="D"),
                      "Sales": [100, 150, 80, 200, 170, 90, 220]})
sales["CumulativeSales"] = sales["Sales"].cumsum()
sales["RunningMax"] = sales["Sales"].cummax()
sales["PrevDay"] = sales["Sales"].shift(1)
sales["Change"] = sales["Sales"] - sales["PrevDay"]            # same as .diff()
sales["PctChange"] = (sales["Sales"].pct_change() * 100).round(1)
sales["MA3"] = sales["Sales"].rolling(3).mean().round(1)       # first 2 rows are NaN (not enough history)
sales

,Date,Sales,CumulativeSales,RunningMax,PrevDay,Change,PctChange,MA3
0,2026-01-01,100,100,100,NaN,NaN,NaN,NaN
1,2026-01-02,150,250,150,100.0,50.0,50.0,NaN
2,2026-01-03,80,330,150,150.0,-70.0,-46.7,110.0
3,2026-01-04,200,530,200,80.0,120.0,150.0,143.3
4,2026-01-05,170,700,200,200.0,-30.0,-15.0,150.0
5,2026-01-06,90,790,200,170.0,-80.0,-47.1,153.3
6,2026-01-07,220,1010,220,90.0,130.0,144.4,160.0

<a id="p-41"></a>
## Practice 41

Create a DataFrame where each employee has a list of skills.

Use `explode()` to create one row per employee skill.

In [69]:
# Your solution

<a id="p-42"></a>
## Practice 42

Create nested JSON for at least 3 users containing:

- id
- name
- email
- address.city
- address.country

Use `json_normalize()` to flatten it.

In [70]:
# Your solution

## ✅ Solution — Practice 41 & 42 — `explode()` and `json_normalize()`

In [71]:
skills = pd.DataFrame({"Name": ["Ali", "Sara", "Ahmed"],
                       "Skills": [["Python", "SQL"], ["Excel"], ["Python", "ML", "SQL"]]})
print(skills.explode("Skills", ignore_index=True), "\n")

users = [
    {"id": 1, "name": "Ali",   "email": "ali@x.com",   "address": {"city": "Lahore",  "country": "Pakistan"}},
    {"id": 2, "name": "Sara",  "email": "sara@x.com",  "address": {"city": "Karachi", "country": "Pakistan"}},
    {"id": 3, "name": "John",  "email": "john@x.com",  "address": {"city": "London",  "country": "UK"}},
]
pd.json_normalize(users)

    Name  Skills
0    Ali  Python
1    Ali     SQL
2   Sara   Excel
3  Ahmed  Python
4  Ahmed      ML
5  Ahmed     SQL

   id  name       email address.city address.country
0   1   Ali   ali@x.com       Lahore        Pakistan
1   2  Sara  sara@x.com      Karachi        Pakistan
2   3  John  john@x.com       London              UK

<a id="p-43"></a>
## Practice 43

Using a DataFrame with at least three numeric columns, calculate its correlation matrix.

Then identify which pair has the strongest absolute correlation.

In [72]:
# Your solution

<a id="p-44"></a>
## Practice 44

Make the `Department` column categorical and compare the memory usage before and after.

In [73]:
# Your solution

## ✅ Solution — Practice 43 & 44 — Correlation and memory

In [74]:
nums = pd.DataFrame({"Age": [25, 30, 28, 35, 41, 23],
                     "Experience": [2, 6, 4, 9, 15, 1],
                     "Salary": [80, 90, 95, 120, 150, 70]})
corr = nums.corr()
print(corr.round(3), "\n")

pairs = corr.where(np.triu(np.ones(corr.shape, dtype=bool), k=1)).stack()   # upper triangle only, no self-pairs
print("Strongest pair:", pairs.abs().idxmax(), round(pairs[pairs.abs().idxmax()], 3), "\n")

big = pd.DataFrame({"Department": np.random.default_rng(0).choice(["IT", "HR", "Finance"], 10_000)})
before = big["Department"].memory_usage(deep=True)
after = big["Department"].astype("category").memory_usage(deep=True)
print(f"before: {before:,} bytes   after: {after:,} bytes   ({before / after:.0f}x smaller)")

              Age  Experience  Salary
Age         1.000       0.995   0.986
Experience  0.995       1.000   0.982
Salary      0.986       0.982   1.000

Strongest pair: ('Age', 'Experience') 0.995

before: 116,847 bytes   after: 10,168 bytes   (11x smaller)

<a id="p-45"></a>
## Practice 45

Write code that would read `large_sales.csv` in chunks of 5,000 rows and print the shape of each chunk.

Do not actually need a large file to solve this.

In [75]:
# Your solution

<a id="p-46"></a>
## Practice 46

Write code to export a DataFrame to:

1. CSV
2. Excel
3. JSON

Use `index=False` where appropriate.

In [76]:
# Your solution

## ✅ Solution — Practice 45 & 46 — Chunks and export

In [77]:
# create a demo "large" file so the code actually runs
path = os.path.join(OUT, "large_sales.csv")
pd.DataFrame({"order": range(12_000), "amount": np.arange(12_000) % 97}).to_csv(path, index=False)

for i, chunk in enumerate(pd.read_csv(path, chunksize=5000), start=1):
    print(f"chunk {i}: {chunk.shape}")

df = fresh_df()
df.to_csv(os.path.join(OUT, "employees.csv"), index=False)
df.to_excel(os.path.join(OUT, "employees.xlsx"), index=False, sheet_name="Employees")
df.to_json(os.path.join(OUT, "employees.json"), orient="records", indent=2)
print(sorted(os.listdir(OUT)))

chunk 1: (5000, 2)
chunk 2: (5000, 2)
chunk 3: (2000, 2)

['employees.csv', 'employees.json', 'employees.xlsx', 'large_sales.csv']

<a id="p-47"></a>
## Practice 47 — Complete Cleaning Workflow

Using `workflow_df`:

1. Clean whitespace from names.
2. Convert Age to numeric.
3. Convert Salary to numeric using `errors="coerce"`.
4. Fill missing names with `"Unknown"`.
5. Fill missing Salary with the median.
6. Remove duplicate rows.
7. Add `AnnualSalary`.
8. Verify the cleaned result with `info()` and `describe()`.

In [78]:
# Your solution
workflow_df = pd.DataFrame({
    "Name": [" Ali ", "Ahmed", "Sara", "Ahmed", None],
    "Age": ["25", "30", "28", "30", "35"],
    "Salary": ["80000", "90000", "bad", "90000", None],
    "City": ["Lahore", "Karachi", "Lahore", "Karachi", "Islamabad"]
})

print("data")
print(workflow_df)
workflow_df["Name"] = workflow_df["Name"].str.strip()

print(workflow_df)

workflow_df["Age"]= pd.to_numeric(workflow_df["Age"])

workflow_df["Salary"]= pd.to_numeric(workflow_df["Salary"],errors="coerce")

workflow_df["Name"] =workflow_df["Name"].fillna("Unknown")
workflow_df["Salary"]= workflow_df["Salary"].fillna(workflow_df["Salary"].median())

workflow_df["Annual Salary"] = workflow_df["Salary"]* 12

print("final data")
workflow_df.drop_duplicates()

workflow_df.info()

workflow_df.describe()

data
    Name Age Salary       City
0   Ali   25  80000     Lahore
1  Ahmed  30  90000    Karachi
2   Sara  28    bad     Lahore
3  Ahmed  30  90000    Karachi
4    NaN  35    NaN  Islamabad
    Name Age Salary       City
0    Ali  25  80000     Lahore
1  Ahmed  30  90000    Karachi
2   Sara  28    bad     Lahore
3  Ahmed  30  90000    Karachi
4    NaN  35    NaN  Islamabad
final data
<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Name           5 non-null      str
 1   Age            5 non-null      int64
 2   Salary         5 non-null      float64
 3   City           5 non-null      str
 4   Annual Salary  5 non-null      float64
dtypes: float64(2), int64(1), str(2)
memory usage: 391.0 bytes

             Age        Salary  Annual Salary
count   5.000000      5.000000   5.000000e+00
mean   29.600000  88000.000000   1.056000e+06
std     3.646917   4472.135955   5.366563e+04
min    25.000000  80000.000000   9.600000e+05
25%    28.000000  90000.000000   1.080000e+06
50%    30.000000  90000.000000   1.080000e+06
75%    30.000000  90000.000000   1.080000e+06
max    35.000000  90000.000000   1.080000e+06

## ✅ Solution — Practice 47 — Complete cleaning workflow

In [79]:
workflow_df = pd.DataFrame({
    "Name": [" Ali ", "Ahmed", "Sara", "Ahmed", None],
    "Age": ["25", "30", "28", "30", "35"],
    "Salary": ["80000", "90000", "bad", "90000", None],
    "City": ["Lahore", "Karachi", "Lahore", "Karachi", "Islamabad"]
})

clean = workflow_df.copy()
clean["Name"] = clean["Name"].str.strip()                                   # 1
clean["Age"] = pd.to_numeric(clean["Age"])                                  # 2
clean["Salary"] = pd.to_numeric(clean["Salary"], errors="coerce")           # 3 "bad" -> NaN
clean["Name"] = clean["Name"].fillna("Unknown")                             # 4
clean["Salary"] = clean["Salary"].fillna(clean["Salary"].median())          # 5
clean = clean.drop_duplicates().reset_index(drop=True)                      # 6
clean["AnnualSalary"] = clean["Salary"] * 12                                # 7
clean.info()                                                                # 8
print(clean.describe())
clean

<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Name          4 non-null      str
 1   Age           4 non-null      int64
 2   Salary        4 non-null      float64
 3   City          4 non-null      str
 4   AnnualSalary  4 non-null      float64
dtypes: float64(2), int64(1), str(2)
memory usage: 341.0 bytes
             Age   Salary  AnnualSalary
count   4.000000      4.0           4.0
mean   29.500000  87500.0     1050000.0
std     4.203173   5000.0       60000.0
min    25.000000  80000.0      960000.0
25%    27.250000  87500.0     1050000.0
50%    29.000000  90000.0     1080000.0
75%    31.250000  90000.0     1080000.0
max    35.000000  90000.0     1080000.0

      Name  Age   Salary       City  AnnualSalary
0      Ali   25  80000.0     Lahore      960000.0
1    Ahmed   30  90000.0    Karachi     1080000.0
2     Sara   28  90000.0     Lahore     1080000.0
3  Unknown   35  90000.0  Islamabad     1080000.0

<a id="p-48"></a>
# 53. Mini Analysis Project

Use this sales dataset for a small analysis.

In [80]:
sales_df = pd.DataFrame({
    "OrderID": [101, 102, 103, 104, 105, 106, 107, 108, 109, 110],
    "Date": [
        "2026-01-05", "2026-01-07", "2026-01-10", "2026-01-12",
        "2026-02-02", "2026-02-05", "2026-02-12", "2026-02-20",
        "2026-03-01", "2026-03-05"
    ],
    "Product": [
        "Laptop", "Phone", "Laptop", "Tablet", "Phone",
        "Laptop", "Tablet", "Phone", "Laptop", "Tablet"
    ],
    "Category": [
        "Electronics", "Electronics", "Electronics", "Electronics",
        "Electronics", "Electronics", "Electronics", "Electronics",
        "Electronics", "Electronics"
    ],
    "City": [
        "Lahore", "Karachi", "Lahore", "Islamabad", "Karachi",
        "Lahore", "Islamabad", "Karachi", "Lahore", "Islamabad"
    ],
    "Quantity": [2, 3, 1, 4, 2, 3, 2, 5, 2, 3],
    "UnitPrice": [150000, 80000, 150000, 60000, 80000,
                  150000, 60000, 80000, 150000, 60000]
})

sales_df["Date"] = pd.to_datetime(sales_df["Date"])
sales_df["Revenue"] = sales_df["Quantity"] * sales_df["UnitPrice"]

sales_df

,OrderID,Date,Product,Category,City,Quantity,UnitPrice,Revenue
0,101,2026-01-05,Laptop,Electronics,Lahore,2,150000,300000
1,102,2026-01-07,Phone,Electronics,Karachi,3,80000,240000
2,103,2026-01-10,Laptop,Electronics,Lahore,1,150000,150000
3,104,2026-01-12,Tablet,Electronics,Islamabad,4,60000,240000
4,105,2026-02-02,Phone,Electronics,Karachi,2,80000,160000
5,106,2026-02-05,Laptop,Electronics,Lahore,3,150000,450000
6,107,2026-02-12,Tablet,Electronics,Islamabad,2,60000,120000
7,108,2026-02-20,Phone,Electronics,Karachi,5,80000,400000
8,109,2026-03-01,Laptop,Electronics,Lahore,2,150000,300000
9,110,2026-03-05,Tablet,Electronics,Islamabad,3,60000,180000

<a id="p-49"></a>
## Mini Project Questions

Solve these without looking up the answer:

1. How many orders are there?
2. What is total revenue?
3. What is average order revenue?
4. Which product generated the most revenue?
5. Which city generated the most revenue?
6. Which product sold the highest quantity?
7. What is monthly revenue?
8. What is average revenue by city?
9. Sort orders from highest to lowest revenue.
10. Find the top 3 orders.
11. Create a pivot table of revenue by City and Product.
12. Calculate cumulative revenue by date.
13. Calculate a 3-order moving average of revenue.

In [81]:
# Your solution
print(sales_df["OrderID"].count())

print(sales_df["Revenue"].sum())

print(sales_df["Revenue"].mean())

revenue_by_product = sales_df.groupby("Product")["Revenue"].sum()

print(revenue_by_product.idxmax())

revenue_by_product = sales_df.groupby("City")["Revenue"].sum()

print(revenue_by_product.idxmax())

revenue_by_product = sales_df.groupby("Product")["Quantity"].max()

print(revenue_by_product.max())

sales_df["Cumulative_Revenue"] = sales_df[["Revenue"]].cumsum()

sales_df["Month"] = sales_df["Date"].dt.month_name()
revenue_by_product = sales_df.groupby("Month")["Revenue"].sum()
print(revenue_by_product.max())
revenue_by_product = sales_df.groupby("City")["Revenue"].mean()
sales_df.max()

# sales_df.head(3)



pivot = sales_df.pivot_table(
    index="City",
    columns="Product",
    values="Revenue",
    aggfunc="sum"
)
pivot

# sales_df["Moving_Average_3"] = sales_df["Revenue"].rolling(window=3).mean()
# sales_df

10
2540000
254000.0
Laptop
Lahore
5
1130000

Product       Laptop     Phone    Tablet
City
Islamabad        NaN       NaN  540000.0
Karachi          NaN  800000.0       NaN
Lahore     1200000.0       NaN       NaN

## Mini Project — answers

In [82]:
sales_df = pd.DataFrame({
    "OrderID": range(101, 111),
    "Date": pd.to_datetime(["2026-01-05", "2026-01-07", "2026-01-10", "2026-01-12", "2026-02-02",
                            "2026-02-05", "2026-02-12", "2026-02-20", "2026-03-01", "2026-03-05"]),
    "Product": ["Laptop", "Phone", "Laptop", "Tablet", "Phone", "Laptop", "Tablet", "Phone", "Laptop", "Tablet"],
    "City": ["Lahore", "Karachi", "Lahore", "Islamabad", "Karachi", "Lahore", "Islamabad", "Karachi", "Lahore", "Islamabad"],
    "Quantity": [2, 3, 1, 4, 2, 3, 2, 5, 2, 3],
    "UnitPrice": [150000, 80000, 150000, 60000, 80000, 150000, 60000, 80000, 150000, 60000],
})
sales_df["Revenue"] = sales_df["Quantity"] * sales_df["UnitPrice"]

print("1 orders           :", sales_df["OrderID"].nunique())
print("2 total revenue    :", sales_df["Revenue"].sum())
print("3 avg order revenue:", sales_df["Revenue"].mean())
print("4 top product      :", sales_df.groupby("Product")["Revenue"].sum().idxmax())
print("5 top city         :", sales_df.groupby("City")["Revenue"].sum().idxmax())
print("6 most units       :", sales_df.groupby("Product")["Quantity"].sum().idxmax())
print("\n7 monthly revenue:\n", sales_df.groupby(sales_df["Date"].dt.to_period("M"))["Revenue"].sum())
print("\n8 avg revenue by city:\n", sales_df.groupby("City")["Revenue"].mean())

1 orders           : 10
2 total revenue    : 2540000
3 avg order revenue: 254000.0
4 top product      : Laptop
5 top city         : Lahore
6 most units       : Phone

7 monthly revenue:
 Date
2026-01     930000
2026-02    1130000
2026-03     480000
Freq: M, Name: Revenue, dtype: int64

8 avg revenue by city:
 City
Islamabad    180000.000000
Karachi      266666.666667
Lahore       300000.000000
Name: Revenue, dtype: float64

In [83]:
by_rev = sales_df.sort_values("Revenue", ascending=False)                     # 9
print(by_rev[["OrderID", "Product", "Revenue"]].head(3), "\n")                 # 10 top 3
print(sales_df.pivot_table(values="Revenue", index="City", columns="Product",
                           aggfunc="sum", fill_value=0), "\n")                  # 11
timeline = sales_df.sort_values("Date").copy()
timeline["CumRevenue"] = timeline["Revenue"].cumsum()                            # 12
timeline["MA3"] = timeline["Revenue"].rolling(3).mean()                          # 13
timeline[["Date", "Revenue", "CumRevenue", "MA3"]]

   OrderID Product  Revenue
5      106  Laptop   450000
7      108   Phone   400000
0      101  Laptop   300000

Product     Laptop   Phone  Tablet
City
Islamabad        0       0  540000
Karachi          0  800000       0
Lahore     1200000       0       0

        Date  Revenue  CumRevenue            MA3
0 2026-01-05   300000      300000            NaN
1 2026-01-07   240000      540000            NaN
2 2026-01-10   150000      690000  230000.000000
3 2026-01-12   240000      930000  210000.000000
4 2026-02-02   160000     1090000  183333.333333
5 2026-02-05   450000     1540000  283333.333333
6 2026-02-12   120000     1660000  243333.333333
7 2026-02-20   400000     2060000  323333.333333
8 2026-03-01   300000     2360000  273333.333333
9 2026-03-05   180000     2540000  293333.333333

<a id="p-50"></a>
# 54. Final Capstone Challenge 🔥🔥🔥

Create this employee dataset and solve the complete analysis without following a solution.

Required skills:

- DataFrame creation
- Inspection
- Filtering
- Missing values
- Data types
- String cleaning
- Conditional columns
- Sorting
- GroupBy
- Aggregation
- Merge
- Pivot table
- Date operations
- Ranking
- Export

In [84]:
employees_capstone = pd.DataFrame({
    "EmployeeID": [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
    "Name": [
        " Ali ", "Ahmed", "Sara", "Hamza", "Ayesha",
        "Bilal", "Zara", "Usman", "Hina", "Omar"
    ],
    "Department": [
        "IT", "HR", "IT", "Finance", "HR",
        "IT", "Finance", "IT", "HR", "Finance"
    ],
    "City": [
        "Lahore", "Karachi", "Lahore", "Islamabad", "Karachi",
        "Lahore", "Islamabad", "Lahore", "Karachi", "Islamabad"
    ],
    "Age": [25, 32, 28, 41, 24, 35, 29, 38, 27, 34],
    "Salary": [
        80000, 65000, 95000, 120000, 70000,
        110000, 90000, 105000, 72000, 115000
    ],
    "Experience": [2, 6, 4, 12, 2, 8, 5, 10, 3, 9],
    "JoinDate": [
        "2024-01-10", "2020-05-12", "2022-03-15", "2014-07-01",
        "2024-02-20", "2018-09-10", "2021-01-05", "2016-11-20",
        "2023-06-10", "2017-04-18"
    ]
})

employees_capstone

,EmployeeID,Name,Department,City,Age,Salary,Experience,JoinDate
0,1,Ali,IT,Lahore,25,80000,2,2024-01-10
1,2,Ahmed,HR,Karachi,32,65000,6,2020-05-12
2,3,Sara,IT,Lahore,28,95000,4,2022-03-15
3,4,Hamza,Finance,Islamabad,41,120000,12,2014-07-01
4,5,Ayesha,HR,Karachi,24,70000,2,2024-02-20
5,6,Bilal,IT,Lahore,35,110000,8,2018-09-10
6,7,Zara,Finance,Islamabad,29,90000,5,2021-01-05
7,8,Usman,IT,Lahore,38,105000,10,2016-11-20
8,9,Hina,HR,Karachi,27,72000,3,2023-06-10
9,10,Omar,Finance,Islamabad,34,115000,9,2017-04-18

<a id="p-51"></a>
## Capstone Tasks

### Part A — Inspect
1. Show shape.
2. Show columns.
3. Show dtypes.
4. Show `info()`.
5. Show descriptive statistics.

### Part B — Clean
6. Remove whitespace from names.
7. Convert JoinDate to datetime.
8. Check for missing values.
9. Check duplicates.

### Part C — Create columns
10. Create AnnualSalary.
11. Create Bonus = 10% of Salary.
12. Create ExperienceLevel:
   - < 3 = Junior
   - 3–7 = Mid
   - > 7 = Senior
13. Extract JoinYear.

### Part D — Filter
14. Find IT employees.
15. Find employees earning > 100,000.
16. Find Lahore employees with > 5 years experience.
17. Find Senior employees earning > 100,000.

### Part E — Analysis
18. Average salary by department.
19. Total salary by department.
20. Employee count by city.
21. Highest-paid employee.
22. Salary ranking.

### Part F — Reshaping
23. Create a pivot table showing average salary by Department and City.
24. Create a second pivot table showing employee count.

### Part G — Final report
25. Sort employees by Salary descending.
26. Display the top 3 highest-paid employees.
27. Export the cleaned final DataFrame to CSV.

Try to solve the entire challenge independently.

> 🧩 *Re-creates the data this problem uses (exactly as it was at this point of the lesson).*

In [85]:
employees = pd.DataFrame({
    "employee_id": [1, 2, 3, 4],
    "Name": ["Ali", "Ahmed", "Sara", "Hamza"],
    "Department":["Dev","Hr","Business","Dev"]
})

performance = pd.DataFrame({
    "employee_id": [1, 2, 3, 5],
    "ratting": [6, 7, 8, 9]
})

print(pd.merge(employees, performance, on="employee_id", how="inner"))

print(pd.merge(employees, performance, on="employee_id", how="left"))

print(pd.merge(employees, performance, on="employee_id", how="outer"))

   employee_id   Name Department  ratting
0            1    Ali        Dev        6
1            2  Ahmed         Hr        7
2            3   Sara   Business        8

   employee_id   Name Department  ratting
0            1    Ali        Dev      6.0
1            2  Ahmed         Hr      7.0
2            3   Sara   Business      8.0
3            4  Hamza        Dev      NaN
   employee_id   Name Department  ratting
0            1    Ali        Dev      6.0
1            2  Ahmed         Hr      7.0
2            3   Sara   Business      8.0
3            4  Hamza        Dev      NaN
4            5    NaN        NaN      9.0

In [86]:
# print(employees_capstone.dtypes)
# print(employees_capstone.shape)
# print(employees_capstone.columns)
# print(employees_capstone.info)
# print(employees_capstone.describe)

employees_capstone["JoinDate"] = pd.to_datetime(employees_capstone['JoinDate'])
employees_capstone["Name"] = employees_capstone["Name"].str.strip()

# print(employees_capstone.isna().sum())
print(employees[employees_capstone.duplicated()])



# YOUR CAPSTONE SOLUTION
#
# Write your complete solution below.
#
# Tip: Break the problem into small sections.

Empty DataFrame
Columns: [employee_id, Name, Department]
Index: []

/var/folders/t1/znbmvwnj0v5cp4hsygpt8gsm0000gn/T/ipykernel_52096/3502128221.py:11: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  print(employees[employees_capstone.duplicated()])

## Capstone — full solution

In [87]:
cap = pd.DataFrame({
    "EmployeeID": range(1, 11),
    "Name": [" Ali ", "Ahmed", "Sara", "Hamza", "Ayesha", "Bilal", "Zara", "Usman", "Hina", "Omar"],
    "Department": ["IT", "HR", "IT", "Finance", "HR", "IT", "Finance", "IT", "HR", "Finance"],
    "City": ["Lahore", "Karachi", "Lahore", "Islamabad", "Karachi", "Lahore", "Islamabad", "Lahore", "Karachi", "Islamabad"],
    "Age": [25, 32, 28, 41, 24, 35, 29, 38, 27, 34],
    "Salary": [80000, 65000, 95000, 120000, 70000, 110000, 90000, 105000, 72000, 115000],
    "Experience": [2, 6, 4, 12, 2, 8, 5, 10, 3, 9],
    "JoinDate": ["2024-01-10", "2020-05-12", "2022-03-15", "2014-07-01", "2024-02-20",
                 "2018-09-10", "2021-01-05", "2016-11-20", "2023-06-10", "2017-04-18"],
})

# Part A — inspect
print(cap.shape, cap.columns.tolist(), sep="\n")
print(cap.dtypes)
cap.info()
print(cap.describe())

# Part B — clean
cap["Name"] = cap["Name"].str.strip()
cap["JoinDate"] = pd.to_datetime(cap["JoinDate"])
print("missing:", cap.isna().sum().sum(), "| duplicates:", cap.duplicated().sum())

# Part C — new columns
cap["AnnualSalary"] = cap["Salary"] * 12
cap["Bonus"] = cap["Salary"] * 0.10
cap["ExperienceLevel"] = np.select([cap["Experience"] < 3, cap["Experience"] <= 7],
                                   ["Junior", "Mid"], default="Senior")
cap["JoinYear"] = cap["JoinDate"].dt.year
cap.head()

(10, 8)
['EmployeeID', 'Name', 'Department', 'City', 'Age', 'Salary', 'Experience', 'JoinDate']
EmployeeID    int64
Name            str
Department      str
City            str
Age           int64
Salary        int64
Experience    int64
JoinDate        str
dtype: object

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   EmployeeID  10 non-null     int64
 1   Name        10 non-null     str
 2   Department  10 non-null     str
 3   City        10 non-null     str
 4   Age         10 non-null     int64
 5   Salary      10 non-null     int64
 6   Experience  10 non-null     int64
 7   JoinDate    10 non-null     str
dtypes: int64(4), str(4)
memory usage: 1.0 KB
       EmployeeID        Age         Salary  Experience
count    10.00000  10.000000      10.000000   10.000000
mean      5.50000  31.300000   92200.000000    6.100000
std       3.02765   5.657836   19932.106986    3.510302
min       1.00000  24.000000   65000.000000    2.000000
25%       3.25000  27.250000   74000.000000    3.250000
50%       5.50000  30.500000   92500.000000    5.500000
75%       7.75000  34.750000  108750.000000    8.750000
max      10.00000  41.000000  120000.000000   12.000000
missing: 0 | duplicates: 0

,EmployeeID,Name,Department,City,Age,Salary,Experience,JoinDate,AnnualSalary,Bonus,ExperienceLevel,JoinYear
0,1,Ali,IT,Lahore,25,80000,2,2024-01-10,960000,8000.0,Junior,2024
1,2,Ahmed,HR,Karachi,32,65000,6,2020-05-12,780000,6500.0,Mid,2020
2,3,Sara,IT,Lahore,28,95000,4,2022-03-15,1140000,9500.0,Mid,2022
3,4,Hamza,Finance,Islamabad,41,120000,12,2014-07-01,1440000,12000.0,Senior,2014
4,5,Ayesha,HR,Karachi,24,70000,2,2024-02-20,840000,7000.0,Junior,2024

In [88]:
# Part D — filter
print(cap[cap["Department"] == "IT"]["Name"].tolist())
print(cap[cap["Salary"] > 100000]["Name"].tolist())
print(cap[(cap["City"] == "Lahore") & (cap["Experience"] > 5)]["Name"].tolist())
print(cap[(cap["ExperienceLevel"] == "Senior") & (cap["Salary"] > 100000)]["Name"].tolist(), "\n")

# Part E — analysis
print(cap.groupby("Department")["Salary"].agg(["mean", "sum"]), "\n")
print(cap["City"].value_counts(), "\n")
print("Highest paid:", cap.loc[cap["Salary"].idxmax(), "Name"])
cap["SalaryRank"] = cap["Salary"].rank(ascending=False).astype(int)

# Part F — reshaping
print(cap.pivot_table(values="Salary", index="Department", columns="City", aggfunc="mean"), "\n")
print(cap.pivot_table(values="EmployeeID", index="Department", columns="City", aggfunc="count", fill_value=0), "\n")

# Part G — final report
report = cap.sort_values("Salary", ascending=False)
print(report[["Name", "Department", "Salary", "SalaryRank"]].head(3))
report.to_csv(os.path.join(OUT, "employees_clean.csv"), index=False)
print("saved to", os.path.join(OUT, "employees_clean.csv"))

['Ali', 'Sara', 'Bilal', 'Usman']
['Hamza', 'Bilal', 'Usman', 'Omar']
['Bilal', 'Usman']
['Hamza', 'Bilal', 'Usman', 'Omar']

                     mean     sum
Department
Finance     108333.333333  325000
HR           69000.000000  207000
IT           97500.000000  390000

City
Lahore       4
Karachi      3
Islamabad    3
Name: count, dtype: int64

Highest paid: Hamza
City            Islamabad  Karachi   Lahore
Department
Finance     108333.333333      NaN      NaN
HR                    NaN  69000.0      NaN
IT                    NaN      NaN  97500.0

City        Islamabad  Karachi  Lahore
Department
Finance             3        0       0
HR                  0        3       0
IT                  0        0       4

    Name Department  Salary  SalaryRank
3  Hamza    Finance  120000           1
9   Omar    Finance  115000           2
5  Bilal         IT  110000           3
saved to /var/folders/t1/znbmvwnj0v5cp4hsygpt8gsm0000gn/T/tmpfc2vi1bo/employees_clean.csv