# Topic 6 — Encoding Techniques in Python Pandas

## Zero to Advanced

This notebook teaches categorical data encoding from beginner to advanced level.

### What you will learn

- What encoding is and why it is needed
- Categorical data
- Nominal vs ordinal categorical data
- Binary encoding using Pandas
- Label encoding
- `map()` and `replace()`
- Pandas categorical dtype
- `cat.codes`
- Ordinal encoding
- One-Hot Encoding
- `pd.get_dummies()`
- `drop_first`
- Encoding multiple columns
- Frequency encoding
- Count encoding
- Target encoding
- Data leakage
- Multi-hot encoding
- Rare-category encoding
- Unknown categories
- Binary encoding
- Hash encoding
- Scikit-learn `OneHotEncoder`
- `fit()` vs `transform()`
- `ColumnTransformer`
- Machine-learning pipelines
- Complete encoding project

---

## Important idea

Machine-learning algorithms generally work with numerical values. Encoding converts categorical values such as `Male`, `Female`, `Lahore`, and `Karachi` into numerical representations that a model can use.

> 📚 **Course navigation** — you are in **Topic 6: Encoding Techniques**
> ⬅️ Previous: Topic 5 — Detecting & Treating Outliers  ·  ➡️ Next: Topic 7 — Exploratory Data Analysis (EDA)

<details><summary>Full course sequence (click to expand)</summary>

| # | Topic | Notebook |
|---|---|---|
| 01 | Python Basics | `Topic_01_Python_Basics.ipynb` |
| 02 | Pandas DataFrame Basics | `Topic_02_Pandas_DataFrame_Basics.ipynb` |
| 03 | Handling Missing Values | `Topic_03_Handling_Missing_Values.ipynb` |
| 04 | Normalization & Standardization | `Topic_04_Normalization_Standardization.ipynb` |
| 05 | Detecting & Treating Outliers | `Topic_05_Outliers.ipynb` |
| **▶ 06 ◀** | **Encoding Techniques** | `Topic_06_Encoding_Techniques.ipynb` |
| 07 | Exploratory Data Analysis (EDA) | `Topic_07_Exploratory_Data_Analysis.ipynb` |
| 08 | Data Visualization | `Topic_08_Data_Visualization.ipynb` |
| 09 | Pandas Data Manipulation | `Topic_09_Pandas_Data_Manipulation.ipynb` |
| 10 | Combining DataFrames | `Topic_10_Combining_DataFrames.ipynb` |
| 11 | Feature Engineering | `Topic_11_Feature_Engineering.ipynb` |
| 11b | KBinsDiscretizer (Discretization) | `Topic_11b_KBinsDiscretizer.ipynb` |
| 12 | Correlation & Multicollinearity | `Topic_12_Correlation_Multicollinearity.ipynb` |
| 13 | Data Transformation & Skewness | `Topic_13_Data_Transformation_Skewness.ipynb` |
| 14 | Statistics for Data Science | `Topic_14_Statistics_for_Data_Science.ipynb` |
| 15 | Probability for Data Science & ML | `Topic_15_Probability_for_Data_Science_ML.ipynb` |
| 16 | Feature Selection | `Topic_16_Feature_Selection.ipynb` |
| 17 | Machine Learning | `Topic_17_Machine_Learning.ipynb` |

</details>

## 📋 Lesson Index — What This Lesson Covers

This lesson has **45 sections**. Click any one to jump to it.

- [1. What Is Encoding?](#sec-1)
- [2. What Is Categorical Data?](#sec-2)
- [3. Binary Categories](#sec-3)
- [4. Encoding with `map()`](#sec-4)
- [5. Encoding with `replace()`](#sec-5)
- [6. Pandas `category` Data Type](#sec-6)
- [7. `cat.codes`](#sec-7)
- [8. Ordinal Encoding](#sec-8)
- [9. One-Hot Encoding](#sec-9)
- [10. `drop_first=True`](#sec-10)
- [11. Encoding Multiple Columns](#sec-11)
- [12. Automatically Finding Categorical Columns](#sec-12)
- [13. Frequency Encoding](#sec-13)
- [14. Frequency as a Percentage](#sec-14)
- [15. Count Encoding](#sec-15)
- [16. Target Encoding](#sec-16)
- [17. Data Leakage in Target Encoding](#sec-17)
- [18. Multi-Hot Encoding](#sec-18)
- [19. Rare Categories](#sec-19)
- [20. Unknown Categories](#sec-20)
- [21. Binary Encoding](#sec-21)
- [22. Hash Encoding](#sec-22)
- [23. Scikit-learn `OneHotEncoder`](#sec-23)
- [24. `fit()` vs `transform()`](#sec-24)
- [25. Encoding With `ColumnTransformer`](#sec-25)
- [26. Pipeline](#sec-26)
- [27. Encoding Numerical-Looking Categories](#sec-27)
- [28. Choosing the Correct Encoding Technique](#sec-28)
- [29. Complete Encoding Example](#sec-29)
- [30. Advanced Exercise — Train/Test Encoding](#sec-30)
- [31. Advanced Exercise — Target Encoding](#sec-31)
- [32. Advanced Exercise — High Cardinality](#sec-32)
- [33. Final Project — Customer Purchase Prediction](#sec-33)
- [Part 1 — Data inspection](#sec-34)
- [Part 2 — Binary encoding](#sec-35)
- [Part 3 — Ordinal encoding](#sec-36)
- [Part 4 — One-hot encoding](#sec-37)
- [Part 5 — Train/test split](#sec-38)
- [Part 6 — ColumnTransformer](#sec-39)
- [Part 7 — Pipeline](#sec-40)
- [Part 8 — Model](#sec-41)
- [Part 9 — Evaluation](#sec-42)
- [Part 10 — Explanation](#sec-43)
- [34. Interview Questions](#sec-44)
- [35. Final Revision Cheat Sheet](#sec-45)

> 🗂️ Full course list: [Topic_00_All_Topics_Index.ipynb](Topic_00_All_Topics_Index.ipynb)

<a id="sec-1"></a>
# 1. What Is Encoding?

Suppose we have:

| Name | Gender | City |
|---|---|---|
| Ali | Male | Lahore |
| Sara | Female | Karachi |
| Ahmed | Male | Islamabad |

The values `Male`, `Female`, `Lahore`, `Karachi`, and `Islamabad` are categorical values.

A machine-learning model usually needs numerical input.

Encoding converts categorical information into numerical representation.

Conceptually:

```text
Categorical data
       ↓
    Encoding
       ↓
Numerical representation
       ↓
Machine-learning model
```

Encoding does NOT mean that the original category itself becomes mathematically ordered. The correct encoding technique depends on the type of categorical variable.

In [1]:
import pandas as pd
import numpy as np

df = pd.DataFrame({
    'Name': ['Ali', 'Sara', 'Ahmed', 'John'],
    'Gender': ['Male', 'Female', 'Male', 'Male'],
    'City': ['Lahore', 'Karachi', 'Islamabad', 'Lahore']
})

df

    Name  Gender       City
0    Ali    Male     Lahore
1   Sara  Female    Karachi
2  Ahmed    Male  Islamabad
3   John    Male     Lahore

# Practice Problem 1

Create a DataFrame containing:

- `Name`
- `Gender`
- `City`
- `Purchased`

Use at least 6 rows.

Do not encode anything yet. First identify which columns are categorical.

In [2]:
data = pd.DataFrame({
    "Name": ["Ali", "Sara", "Ahmed", "Ayesha", "Usman", "Fatima"],
    "Gender": ["Male", "Female", "Male", "Female", "Male", "Female"],
    "City": ["Lahore", "Karachi", "Islamabad", "Lahore", "Karachi", "Islamabad"],
    "Purchased": ["Yes", "No", "Yes", "Yes", "No", "Yes"]
})
data

     Name  Gender       City Purchased
0     Ali    Male     Lahore       Yes
1    Sara  Female    Karachi        No
2   Ahmed    Male  Islamabad       Yes
3  Ayesha  Female     Lahore       Yes
4   Usman    Male    Karachi        No
5  Fatima  Female  Islamabad       Yes

<a id="sec-2"></a>
# 2. What Is Categorical Data?

A categorical column contains values that represent groups or categories.

Examples:

```text
Gender: Male, Female
City: Lahore, Karachi, Islamabad
Color: Red, Blue, Green
Browser: Chrome, Safari, Firefox
```

There are two important types:

## Nominal categorical data

There is no meaningful order.

Example:

```text
Lahore
Karachi
Islamabad
```

There is no mathematical meaning to saying one city is greater than another.

## Ordinal categorical data

There is a meaningful order.

Example:

```text
School < Bachelor < Master < PhD
```

Another example:

```text
Low < Medium < High
```

This distinction is one of the most important ideas when choosing an encoding method.

<a id="sec-3"></a>
# 3. Binary Categories

A binary categorical variable has only two possible categories.

Examples:

```text
Male / Female
Yes / No
True / False
Pass / Fail
```

A simple representation is:

```text
No  → 0
Yes → 1
```

For binary variables, mapping to 0 and 1 is often straightforward.

In [3]:
df = pd.DataFrame({
    'Gender': ['Male', 'Female', 'Male', 'Female', 'Male']
})

df['Gender_encoded'] = df['Gender'].map({
    'Female': 0,
    'Male': 1
})

df

   Gender  Gender_encoded
0    Male               1
1  Female               0
2    Male               1
3  Female               0
4    Male               1

# Practice Problem 2

Create a `Purchased` column containing `Yes` and `No`.

Encode it so that:

```text
No  → 0
Yes → 1
```

Use `map()`.

In [4]:
data["Purchased"] = data["Purchased"].map({
    "Yes":1,
    "No":0
})
data

     Name  Gender       City  Purchased
0     Ali    Male     Lahore          1
1    Sara  Female    Karachi          0
2   Ahmed    Male  Islamabad          1
3  Ayesha  Female     Lahore          1
4   Usman    Male    Karachi          0
5  Fatima  Female  Islamabad          1

<a id="sec-4"></a>
# 4. Encoding with `map()`

`map()` is very useful when you explicitly know the mapping you want.

Example:

```python
df['Gender'].map({'Female': 0, 'Male': 1})
```

Advantages:

- Easy to understand
- Explicit mapping
- Good for binary categories
- Good for ordinal categories when you define the correct order

Be careful: if a value does not exist in the mapping dictionary, `map()` can produce `NaN`.

In [5]:
df = pd.DataFrame({
    'Status': ['Active', 'Inactive', 'Active', 'Active']
})

df['Status_encoded'] = df['Status'].map({
    'Inactive': 0,
    'Active': 1
})

df

     Status  Status_encoded
0    Active               1
1  Inactive               0
2    Active               1
3    Active               1

# Practice Problem 3

Create an `Employment` column:

```text
Unemployed
Employed
Employed
Unemployed
```

Encode it using:

```text
Unemployed → 0
Employed   → 1
```

In [6]:
employee_list = pd.DataFrame({
    "employment":["Unemployed","Employed","Employed","Unemployed","Unemployed","Unemployed"],
       "Name": ["Ali", "Sara", "Ahmed", "Ayesha", "Usman", "Fatima"],

})
employee_list["employment"].map({
    "Unemployed":0,
    "Employed":1
})
employee_list

   employment    Name
0  Unemployed     Ali
1    Employed    Sara
2    Employed   Ahmed
3  Unemployed  Ayesha
4  Unemployed   Usman
5  Unemployed  Fatima

<a id="sec-5"></a>
# 5. Encoding with `replace()`

`replace()` can also replace category names with numerical values.

Example:

```python
df['Gender'] = df['Gender'].replace({
    'Male': 1,
    'Female': 0
})
```

Difference in idea:

- `map()` is commonly used to create a transformed Series from a mapping.
- `replace()` is a more general replacement operation and can work across DataFrame values.

In [7]:
df = pd.DataFrame({
    'Gender': ['Male', 'Female', 'Male', 'Female']
})

df['Gender_encoded'] = df['Gender'].replace({
    'Male': 1,
    'Female': 0
})

df

   Gender Gender_encoded
0    Male              1
1  Female              0
2    Male              1
3  Female              0

# Practice Problem 4

Use `replace()` to encode:

```text
Pass → 1
Fail → 0
```

Do not use `map()`.

In [8]:


data = {
    "Name": ["Ali", "Sara", "Ahmed", "Ayesha", "Usman", "Fatima"],
    "Gender": ["Male", "Female", "Male", "Female", "Male", "Female"],
   "ReMarks":["Pass","Fail","Pass","Fail","Pass","Fail"]
}

df = pd.DataFrame(data)
df["ReMarks"] = df["ReMarks"].replace({ "Pass":1,"Fail":0 })
print(df)

     Name  Gender ReMarks
0     Ali    Male       1
1    Sara  Female       0
2   Ahmed    Male       1
3  Ayesha  Female       0
4   Usman    Male       1
5  Fatima  Female       0

<a id="sec-6"></a>
# 6. Pandas `category` Data Type

Pandas provides a special categorical data type.

You can convert a column using:

```python
df['City'] = df['City'].astype('category')
```

This is useful when a column contains repeated categorical values.

Categorical dtype can also provide a structured list of categories and can save memory in appropriate datasets.

In [9]:
df = pd.DataFrame({
    'City': ['Lahore', 'Karachi', 'Lahore', 'Islamabad', 'Karachi']
})

df['City'] = df['City'].astype('category')

print(df)
print(df['City'].cat.categories)

        City
0     Lahore
1    Karachi
2     Lahore
3  Islamabad
4    Karachi
Index(['Islamabad', 'Karachi', 'Lahore'], dtype='str')

# Practice Problem 5

Create a `Department` column containing:

```text
IT
HR
IT
Finance
HR
```

Convert it to Pandas `category` dtype and display its categories.

In [10]:
df = pd.DataFrame({
    'Department': ['IT', 'HR', 'IT', 'Finance', 'HR']
})

df["Department"] = df["Department"].astype("category")

print(df["Department"].dtype)
print(df["Department"].cat.categories)

category
Index(['Finance', 'HR', 'IT'], dtype='str')

<a id="sec-7"></a>
# 7. `cat.codes`

After converting a Series to categorical dtype, Pandas provides category codes.

Example:

```python
df['City'].astype('category').cat.codes
```

Important warning:

`cat.codes` assigns integer codes to categories, but those codes should not automatically be interpreted as meaningful numerical order.

For example:

```text
Lahore     → 1
Karachi    → 0
Islamabad  → 2
```

does NOT mean:

```text
Islamabad > Lahore > Karachi
```

For nominal categories, one-hot encoding is often safer.

In [11]:
df = pd.DataFrame({
    'City': ['Lahore', 'Karachi', 'Islamabad', 'Lahore']
})

df['City_category'] = df['City'].astype('category')
df['City_code'] = df['City_category'].cat.codes

df

        City City_category  City_code
0     Lahore        Lahore          2
1    Karachi       Karachi          1
2  Islamabad     Islamabad          0
3     Lahore        Lahore          2

# Practice Problem 6

Create a categorical `Color` column containing:

```text
Red
Blue
Green
Red
Blue
```

Convert it to category dtype and inspect `cat.codes`.

Then explain why these numerical codes do not necessarily represent an order between colors.

In [12]:
df = pd.DataFrame({
    'color': ["Red","Blue","Green","Red","Blue"]
})

df['color'] = df['color'].astype('category')
df["color-code"] = df["color"].cat.codes
df

   color  color-code
0    Red           2
1   Blue           0
2  Green           1
3    Red           2
4   Blue           0

<a id="sec-8"></a>
# 8. Ordinal Encoding

Ordinal encoding is appropriate when categories have a meaningful order.

Example:

```text
School
Bachelor
Master
PhD
```

We can encode:

```text
School   → 0
Bachelor → 1
Master   → 2
PhD      → 3
```

The numerical order represents the real-world order.

In [13]:
df = pd.DataFrame({
    'Education': [
        'Bachelor',
        'Master',
        'School',
        'PhD',
        'Master'
    ]
})

education_map = {
    'School': 0,
    'Bachelor': 1,
    'Master': 2,
    'PhD': 3
}

df['Education_encoded'] = df['Education'].map(education_map)

df

  Education  Education_encoded
0  Bachelor                  1
1    Master                  2
2    School                  0
3       PhD                  3
4    Master                  2

# Practice Problem 7

Encode this ordinal variable:

```text
Low
Medium
High
Very High
```

Use:

```text
Low       → 0
Medium    → 1
High      → 2
Very High → 3
```

Create the encoded column using `map()`.

In [14]:
# ✍️ Your answer here

<a id="sec-9"></a>
# 9. One-Hot Encoding

One-Hot Encoding creates a separate binary column for each category.

Suppose:

```text
City
Lahore
Karachi
Islamabad
```

One-hot representation:

```text
City        Lahore  Karachi  Islamabad
Lahore         1       0         0
Karachi        0       1         0
Islamabad      0       0         1
```

This avoids creating an artificial numerical order between nominal categories.

In [15]:
df = pd.DataFrame({
    'City': ['Lahore', 'Karachi', 'Islamabad', 'Lahore']
})

encoded = pd.get_dummies(
    df,
    columns=['City'],
    dtype=int
)

encoded

   City_Islamabad  City_Karachi  City_Lahore
0               0             0            1
1               0             1            0
2               1             0            0
3               0             0            1

# Practice Problem 8

Create a DataFrame with a `Color` column:

```text
Red
Blue
Green
Red
Green
```

Use `pd.get_dummies()` to create one-hot encoded columns.

In [16]:
df =pd.DataFrame({
    "colors":["Red","Blue","Green","Red","Green"]
})
encoded_data = pd.get_dummies(df,columns=["colors"],dtype=int)
encoded_data

   colors_Blue  colors_Green  colors_Red
0            0             0           1
1            1             0           0
2            0             1           0
3            0             0           1
4            0             1           0

<a id="sec-10"></a>
# 10. `drop_first=True`

Pandas allows you to remove one dummy column:

```python
pd.get_dummies(
    df,
    columns=['City'],
    drop_first=True,
    dtype=int
)
```

If there are three categories, two dummy columns can be enough for many linear-model setups because the omitted category can be represented by all zeros.

However, `drop_first=True` should not be treated as a universal rule. The appropriate representation depends on the model and preprocessing design.

In [17]:
df = pd.DataFrame({
    'City': ['Lahore', 'Karachi', 'Islamabad', 'Lahore']
})

encoded = pd.get_dummies(
    df,
    columns=['City'],
    drop_first=True,
    dtype=int
)

encoded

   City_Karachi  City_Lahore
0             0            1
1             1            0
2             0            0
3             0            1

# Practice Problem 9

Create one-hot encoding for:

```text
Browser
Chrome
Firefox
    Safari
Chrome
```

First use all dummy columns.

Then repeat using `drop_first=True`.

Compare the number of resulting columns.

In [18]:
df = pd.DataFrame({
    'browser': ["Chrome","Firefox","Safari","Chrome"]
})

encoded = pd.get_dummies(
    df,
    columns=['browser'],

    dtype=int
)

print(encoded)

encoded_data = pd.get_dummies(
    df,
    columns=['browser'],
    drop_first=True,
    dtype=int
)
encoded_data

   browser_Chrome  browser_Firefox  browser_Safari
0               1                0               0
1               0                1               0
2               0                0               1
3               1                0               0

   browser_Firefox  browser_Safari
0                0               0
1                1               0
2                0               1
3                0               0

<a id="sec-11"></a>
# 11. Encoding Multiple Columns

A DataFrame can contain several categorical columns.

Example:

```text
Gender
City
Department
```

We can encode several columns at once with `get_dummies()`.

In [19]:
df = pd.DataFrame({
    'Age': [25, 30, 28, 35],
    'Gender': ['Male', 'Female', 'Male', 'Female'],
    'City': ['Lahore', 'Karachi', 'Islamabad', 'Lahore']
})

encoded = pd.get_dummies(
    df,
    columns=['Gender', 'City'],
    dtype=int
)

encoded

   Age  Gender_Female  Gender_Male  City_Islamabad  City_Karachi  City_Lahore
0   25              0            1               0             0            1
1   30              1            0               0             1            0
2   28              0            1               1             0            0
3   35              1            0               0             0            1

# Practice Problem 10

Create a DataFrame containing:

- `Age`
- `Gender`
- `City`
- `Department`

One-hot encode all three categorical columns while keeping `Age` unchanged.

In [20]:
df = pd.DataFrame({
    'Age': [25, 30, 28, 35],
    'Gender': ['Male', 'Female', 'Male', 'Female'],
    'City': ['Lahore', 'Karachi', 'Islamabad', 'Lahore'],
    "Department":["Hr","IT","Finance","IT"]
})

encoded = pd.get_dummies(
    df,
    columns=['Gender', 'City',"Department"],
    dtype=int
)

encoded

,Age,Gender_Female,Gender_Male,City_Islamabad,City_Karachi,City_Lahore,Department_Finance,Department_Hr,Department_IT
0,25,0,1,0,0,1,0,1,0
1,30,1,0,0,1,0,0,0,1
2,28,0,1,1,0,0,1,0,0
3,35,1,0,0,0,1,0,0,1

<a id="sec-12"></a>
# 12. Automatically Finding Categorical Columns

In a real dataset, you may have many columns.

You can find text/categorical columns using:

```python
df.select_dtypes(include=['object', 'string', 'category']).columns
```

> **pandas 3 note:** since pandas 3.0, text columns get the new `str` dtype by default instead of `object`.
> `select_dtypes(include='object')` still finds them, but prints a `Pandas4Warning` saying this will stop
> working in pandas 4. Listing `'string'` (and `'category'` for categorical columns) is the future-proof way.

This is useful when preprocessing large datasets.

In [21]:
df = pd.DataFrame({
    'Age': [25, 30, 28],
    'Gender': ['Male', 'Female', 'Male'],
    'City': ['Lahore', 'Karachi', 'Lahore'],
    'Salary': [50000, 70000, 60000]
})

categorical_columns = df.select_dtypes(
    include=['object', 'string', 'category']
).columns

print(categorical_columns)

Index(['Gender', 'City'], dtype='str')

# Practice Problem 11

Create a DataFrame with at least five columns, including at least three categorical columns.

Use `select_dtypes()` to automatically find all categorical columns.

In [22]:
data = {
    "Name": ["Ali", "Sara", "Ahmed", "Ayesha", "Usman", "Fatima"],
    "Gender": ["Male", "Female", "Male", "Female", "Male", "Female"],
    "City": ["Lahore", "Karachi", "Islamabad", "Lahore", "Karachi", "Islamabad"],
    "Education": ["Bachelor", "Master", "Bachelor", "PhD", "Master", "Bachelor"],
    "Age": [22, 28, 25, 35, 30, 24],
    "Purchased": ["Yes", "No", "Yes", "Yes", "No", "Yes"]
}

df = pd.DataFrame(data)

print(df)

categorical_columns = df.select_dtypes(include="object").columns

     Name  Gender       City Education  Age Purchased
0     Ali    Male     Lahore  Bachelor   22       Yes
1    Sara  Female    Karachi    Master   28        No
2   Ahmed    Male  Islamabad  Bachelor   25       Yes
3  Ayesha  Female     Lahore       PhD   35       Yes
4   Usman    Male    Karachi    Master   30        No
5  Fatima  Female  Islamabad  Bachelor   24       Yes

/var/folders/t1/znbmvwnj0v5cp4hsygpt8gsm0000gn/T/ipykernel_24363/27761180.py:14: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categorical_columns = df.select_dtypes(include="object").columns

> 💡 **Note on the answer above (FIX-2026-09-27):** in pandas 3 `include="object"` still works but shows a
> `Pandas4Warning`. Use `include=["object", "string", "category"]` to be future-proof, and add
> `print(categorical_columns)` so the result is displayed.

<a id="sec-13"></a>
# 13. Frequency Encoding

Frequency encoding replaces each category with how frequently it appears.

Example:

```text
Lahore      appears 3 times
Karachi     appears 2 times
Islamabad   appears 1 time
```

Frequency encoding:

```text
Lahore     → 3
Karachi    → 2
Islamabad  → 1
```

This can be useful for high-cardinality categorical variables.

In [23]:
df = pd.DataFrame({
    'City': [
        'Lahore',
        'Lahore',
        'Lahore',
        'Karachi',
        'Karachi',
        'Islamabad'
    ]
})

frequency = df['City'].value_counts()

df['City_frequency'] = df['City'].map(frequency)

df

        City  City_frequency
0     Lahore               3
1     Lahore               3
2     Lahore               3
3    Karachi               2
4    Karachi               2
5  Islamabad               1

# Practice Problem 12

Create a `Product` column with repeated values.

Calculate the frequency of each product and map that frequency back into the DataFrame.

In [24]:


data = {
    "Name": ["Ali", "Sara", "Ahmed", "Ayesha", "Usman", "Fatima"],
    "Gender": ["Male", "Female", "Male", "Female", "Male", "Female"],
    "City": ["Lahore", "Karachi", "Islamabad", "Lahore", "Karachi", "Islamabad"],
    "Education": ["Bachelor", "Master", "Bachelor", "PhD", "Master", "Bachelor"],
    "Age": [22, 28, 25, 35, 30, 24],
    "Purchased": ["Yes", "No", "Yes", "Yes", "No", "Yes"],
    "Product": ["Laptop", "Phone", "Laptop", "Tablet", "Phone", "Laptop"]
}

df = pd.DataFrame(data)
freq= df["Product"].value_counts();


df["Product-Feq"] = df["Product"].map(freq)
df

     Name  Gender       City Education  Age Purchased Product  Product-Feq
0     Ali    Male     Lahore  Bachelor   22       Yes  Laptop            3
1    Sara  Female    Karachi    Master   28        No   Phone            2
2   Ahmed    Male  Islamabad  Bachelor   25       Yes  Laptop            3
3  Ayesha  Female     Lahore       PhD   35       Yes  Tablet            1
4   Usman    Male    Karachi    Master   30        No   Phone            2
5  Fatima  Female  Islamabad  Bachelor   24       Yes  Laptop            3

<a id="sec-14"></a>
# 14. Frequency as a Percentage

You can calculate relative frequency with:

```python
value_counts(normalize=True)
```

For example, if a category appears in 50% of the rows, its frequency encoding becomes `0.50`.

In [25]:
frequency_percentage = df['City'].value_counts(normalize=True)

print(frequency_percentage)
df['City_frequency_percentage'] = df['City'].map(
    frequency_percentage
)

df

City
Lahore       0.333333
Karachi      0.333333
Islamabad    0.333333
Name: proportion, dtype: float64

,Name,Gender,City,Education,Age,Purchased,Product,Product-Feq,City_frequency_percentage
0,Ali,Male,Lahore,Bachelor,22,Yes,Laptop,3,0.333333
1,Sara,Female,Karachi,Master,28,No,Phone,2,0.333333
2,Ahmed,Male,Islamabad,Bachelor,25,Yes,Laptop,3,0.333333
3,Ayesha,Female,Lahore,PhD,35,Yes,Tablet,1,0.333333
4,Usman,Male,Karachi,Master,30,No,Phone,2,0.333333
5,Fatima,Female,Islamabad,Bachelor,24,Yes,Laptop,3,0.333333

# Practice Problem 13

Create a `Department` column with at least 8 rows (for example IT, HR, Finance, IT, IT, HR, Sales, IT).

1. Calculate the **raw** count of each department.
2. Calculate the **relative frequency** (percentage) with `value_counts(normalize=True)`.
3. Map the relative frequency back into a new column `Department_freq_pct`.

*(Problem added FIX-2026-09-27 — it was in the original outline but missing from the notebook.)*

In [26]:
# ✍️ Your answer here

<a id="sec-15"></a>
# 15. Count Encoding

Count encoding is closely related to frequency encoding.

Instead of representing the category itself, we represent how many times that category appears.

Example:

```text
Chrome → 500
Safari → 300
Firefox → 200
```

The key idea is:

```python
counts = df['Browser'].value_counts()
df['Browser_count'] = df['Browser'].map(counts)
```

In [27]:
df = pd.DataFrame({
    'Browser': [
        'Chrome', 'Chrome', 'Safari',
        'Firefox', 'Chrome', 'Safari'
    ]
})

counts = df['Browser'].value_counts()

df['Browser_count'] = df['Browser'].map(counts)

df

   Browser  Browser_count
0   Chrome              3
1   Chrome              3
2   Safari              2
3  Firefox              1
4   Chrome              3
5   Safari              2

# Practice Problem 14

Create a `Country` column with at least 10 rows and repeated values.

1. Count-encode it into `Country_count`.
2. Sort the DataFrame by `Country_count` in **descending** order.
3. Which country is the most common?

In [28]:
# ✍️ Your answer here

<a id="sec-16"></a>
# 16. Target Encoding

Target encoding replaces each category with a statistic calculated from the target variable, commonly the mean target value for that category.

Example:

| City | Purchased |
|---|---:|
| Lahore | 1 |
| Lahore | 1 |
| Lahore | 0 |
| Karachi | 0 |
| Karachi | 0 |
| Islamabad | 1 |

Mean purchase rate:

```text
Lahore     → (1 + 1 + 0) / 3 = 0.67
Karachi    → (0 + 0) / 2 = 0.00
Islamabad  → 1 / 1 = 1.00
```

The category is therefore represented using information about the target.

In [29]:
df = pd.DataFrame({
    'City': [
        'Lahore', 'Lahore', 'Lahore',
        'Karachi', 'Karachi', 'Islamabad'
    ],
    'Purchased': [1, 1, 0, 0, 0, 1]
})

target_mean = df.groupby('City')['Purchased'].mean()

df['City_target_encoded'] = df['City'].map(target_mean)

df

        City  Purchased  City_target_encoded
0     Lahore          1             0.666667
1     Lahore          1             0.666667
2     Lahore          0             0.666667
3    Karachi          0             0.000000
4    Karachi          0             0.000000
5  Islamabad          1             1.000000

# Practice Problem 15

Create a dataset with:

- `Department`
- `Purchased`

Calculate the average purchase rate for every department.

Map the result back to the original DataFrame.

Do this manually with Pandas. Do not use a specialized encoding library.

In [30]:
# ✍️ Your answer here

<a id="sec-17"></a>
# 17. Data Leakage in Target Encoding

Target encoding has an important risk: **data leakage**.

If you calculate target statistics using the entire dataset before splitting into training and test data, information from the test set can influence the features.

This is especially dangerous when the category has few observations.

Correct high-level workflow:

```text
Raw data
   ↓
Train/Test split
   ↓
Learn encoding from training data
   ↓
Transform training data
   ↓
Transform test data using training mapping
```

Never allow test-target information to influence training preprocessing.

# Practice Problem 16 — Leakage Detection

Suppose you have 10,000 rows.

You calculate target encoding using all 10,000 rows and only afterward split the data into train and test.

Answer:

1. Is this safe?
2. Why or why not?
3. What should you do instead?

In [31]:
# ✍️ Your answer here

<a id="sec-18"></a>
# 18. Multi-Hot Encoding

Sometimes one row can contain multiple categories.

Example:

| User | Skills |
|---|---|
| Ali | Python,SQL |
| Sara | Python,Java |
| John | Java,React |

A user can have multiple skills, so each row can contain multiple `1` values.

Result:

```text
User   Python  SQL  Java  React
Ali       1      1     0      0
Sara      1      0     1      0
John      0      0     1      1
```

This is commonly called multi-hot encoding.

In [32]:
df = pd.DataFrame({
    'User': ['Ali', 'Sara', 'John'],
    'Skills': [
        'Python,SQL',
        'Python,Java',
        'Java,React'
    ]
})

skills_encoded = df['Skills'].str.get_dummies(sep=',')

skills_encoded

   Java  Python  React  SQL
0     0       1      0    1
1     1       1      0    0
2     1       0      1    0

# Practice Problem 17

Create a DataFrame with a `Languages` column where each person speaks one or more languages:

```text
Ali    → Urdu,English
Sara   → English
Ahmed  → Urdu,Punjabi,English
Ayesha → Urdu
```

Use `str.get_dummies(sep=',')` to multi-hot encode it, then join the result back to the names.
How many languages does each person speak? (Hint: sum across the row.)

In [33]:
# ✍️ Your answer here

<a id="sec-19"></a>
# 19. Rare Categories

Imagine a dataset contains:

```text
Lahore      5000
Karachi     4000
Islamabad   3000
Multan        20
Quetta        10
Peshawar       5
```

If there are hundreds or thousands of rare categories, one-hot encoding may create many columns.

A common strategy is to group rare categories into `Other`.

For example:

```text
Multan   → Other
Quetta   → Other
Peshawar → Other
```

In [34]:
df = pd.DataFrame({
    'City': [
        'Lahore', 'Lahore', 'Lahore', 'Lahore',
        'Karachi', 'Karachi',
        'Islamabad',
        'Multan',
        'Quetta'
    ]
})

counts = df['City'].value_counts()

threshold = 2

rare_categories = counts[counts < threshold].index

# Create a copy so the original category column is preserved.
df['City_grouped'] = df['City'].where(
    ~df['City'].isin(rare_categories),
    'Other'
)

print(df)

        City City_grouped
0     Lahore       Lahore
1     Lahore       Lahore
2     Lahore       Lahore
3     Lahore       Lahore
4    Karachi      Karachi
5    Karachi      Karachi
6  Islamabad        Other
7     Multan        Other
8     Quetta        Other

# Practice Problem 18

Create a dataset with at least 10 rows and a categorical column containing common and rare categories.

Group categories that appear fewer than 3 times into `Other`.

In [35]:
# ✍️ Your answer here

<a id="sec-20"></a>
# 20. Unknown Categories

A common real-world problem occurs when training data contains:

```text
Lahore
Karachi
Islamabad
```

but future data contains:

```text
Multan
```

The encoder needs a strategy for unseen categories.

In machine-learning workflows, Scikit-learn's `OneHotEncoder` supports:

```python
handle_unknown='ignore'
```

This prevents an unseen category from causing an error during transformation.

# Practice Problem 19

Imagine your training cities are:

```text
Lahore
Karachi
Islamabad
```

Your test data contains:

```text
Lahore
Multan
```

Explain why an encoder must handle unknown categories and what `handle_unknown='ignore'` does.

In [36]:
# ✍️ Your answer here

<a id="sec-21"></a>
# 21. Binary Encoding

Binary encoding represents categories using binary digits.

Suppose there are eight categories:

```text
A → 000
B → 001
C → 010
D → 011
E → 100
F → 101
G → 110
H → 111
```

One-hot encoding would need eight columns.

Binary encoding needs only three binary columns for eight categories.

Binary encoding is especially useful when categorical cardinality is large.

For practical implementation, libraries such as `category_encoders` can be used.

# Practice Problem 20

Suppose a categorical feature contains 16 unique categories.

1. How many columns would one-hot encoding require?
2. Approximately how many binary digits are needed to represent 16 unique values?
3. Explain why binary encoding can reduce dimensionality.

In [37]:
# ✍️ Your answer here

<a id="sec-22"></a>
# 22. Hash Encoding

Hash encoding maps categories to a fixed number of columns using a hashing function.

Conceptually:

```text
100,000 unique categories
          ↓
     Hash encoding
          ↓
      100 columns
```

The main advantage is controlling the number of output features.

The trade-off is that different categories can sometimes map to the same location. This is called a hash collision.

# Practice Problem 21

Explain in your own words:

1. What is hash encoding?
2. Why is it useful for very high-cardinality data?
3. What is a hash collision?

In [38]:
# ✍️ Your answer here

<a id="sec-23"></a>
# 23. Scikit-learn `OneHotEncoder`

For production machine-learning pipelines, Scikit-learn's `OneHotEncoder` is often more suitable than manually encoding train and test data independently.

Important parameters include:

- `handle_unknown='ignore'`
- `sparse_output=False`

The encoder learns categories from the training data and then transforms new data using the learned representation.

In [39]:
from sklearn.preprocessing import OneHotEncoder

train = pd.DataFrame({
    'City': ['Lahore', 'Karachi', 'Islamabad', 'Lahore']
})

encoder = OneHotEncoder(
    handle_unknown='ignore',
    sparse_output=False
)

train_encoded = encoder.fit_transform(train[['City']])

train_encoded

array([[0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.]])

<a id="sec-24"></a>
# 24. `fit()` vs `transform()`

This distinction is critical in machine learning.

### `fit()`

The encoder learns information from data.

For one-hot encoding, it learns the available categories.

### `transform()`

The encoder applies what it already learned to new data.

Correct workflow:

```python
encoder.fit(X_train)
X_train_encoded = encoder.transform(X_train)
X_test_encoded = encoder.transform(X_test)
```

Shortcut for training data:

```python
X_train_encoded = encoder.fit_transform(X_train)
```

Do NOT fit a separate encoder on the test data.

In [40]:
train = pd.DataFrame({
    'City': ['Lahore', 'Karachi', 'Islamabad', 'Lahore']
})

test = pd.DataFrame({
    'City': ['Lahore', 'Multan']
})

encoder = OneHotEncoder(
    handle_unknown='ignore',
    sparse_output=False
)

X_train = encoder.fit_transform(train[['City']])
X_test = encoder.transform(test[['City']])

print('Train:')
print(X_train)

print('\nTest:')
print(X_test)

Train:
[[0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]]

Test:
[[0. 0. 1.]
 [0. 0. 0.]]

# Practice Problem 22

Create separate train and test DataFrames with a `Color` column.

Make sure the test set contains at least one category that does not exist in the training set.

Use `OneHotEncoder(handle_unknown='ignore')`.

Verify that transforming the test data does not raise an error.

In [41]:
# ✍️ Your answer here

<a id="sec-25"></a>
# 25. Encoding With `ColumnTransformer`

Real datasets contain both numerical and categorical columns.

Example:

```text
Age       → numerical
Salary    → numerical
Gender    → categorical
City      → categorical
```

We can apply different preprocessing to different columns using `ColumnTransformer`.

In [42]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler, OneHotEncoder

X = pd.DataFrame({
    'Age': [25, 30, 28, 35],
    'Salary': [50000, 70000, 60000, 90000],
    'Gender': ['Male', 'Female', 'Male', 'Female'],
    'City': ['Lahore', 'Karachi', 'Islamabad', 'Lahore']
})

numeric_features = ['Age', 'Salary']
categorical_features = ['Gender', 'City']

preprocessor = ColumnTransformer(
    transformers=[
        (
            'num',
            StandardScaler(),
            numeric_features
        ),
        (
            'cat',
            OneHotEncoder(handle_unknown='ignore'),
            categorical_features
        )
    ]
)

X_transformed = preprocessor.fit_transform(X)

print(X_transformed)

[[-1.23624508 -1.18321596  0.          1.          0.          0.
   1.        ]
 [ 0.13736056  0.16903085  1.          0.          0.          1.
   0.        ]
 [-0.41208169 -0.50709255  0.          1.          1.          0.
   0.        ]
 [ 1.5109662   1.52127766  1.          0.          0.          0.
   1.        ]]

# Practice Problem 23

Create a DataFrame containing:

- `Age`
- `Income`
- `Gender`
- `City`
- `Department`

Use `ColumnTransformer` so that:

- Numerical columns are standardized.
- Categorical columns are one-hot encoded.

Use `handle_unknown='ignore'`.

In [43]:
# ✍️ Your answer here

<a id="sec-26"></a>
# 26. Pipeline

A Pipeline allows preprocessing and model training to be connected into one workflow.

Conceptually:

```text
Raw data
   ↓
Preprocessing
   ↓
Encoding
   ↓
Scaling
   ↓
Machine-learning model
```

This reduces the chance of accidentally applying inconsistent preprocessing.

In [44]:
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LogisticRegression

pipeline = Pipeline([
    ('preprocessor', preprocessor),
    ('model', LogisticRegression())
])

print(pipeline)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('num', StandardScaler(),
                                                  ['Age', 'Salary']),
                                                 ('cat',
                                                  OneHotEncoder(handle_unknown='ignore'),
                                                  ['Gender', 'City'])])),
                ('model', LogisticRegression())])

# Practice Problem 24

Create a complete Pipeline containing:

1. A `ColumnTransformer`
2. One-hot encoding for categorical features
3. Standard scaling for numerical features
4. A Logistic Regression model

Then fit the pipeline on a small classification dataset.

In [45]:
# ✍️ Your answer here

<a id="sec-27"></a>
# 27. Encoding Numerical-Looking Categories

Be careful with columns that look numerical but are actually categories.

For example:

```text
PostalCode
54000
44000
75000
```

If postal code is an identifier rather than a quantity, treating it as a continuous numerical feature may be inappropriate.

Always ask:

> Does this number represent a measurable quantity, or is it just a category/identifier?

# Practice Problem 25

Consider these columns:

```text
Age
Salary
PostalCode
NumberOfChildren
ProductID
```

Identify which columns are likely numerical measurements and which may represent categories or identifiers.

Explain your reasoning.

In [46]:
# ✍️ Your answer here

<a id="sec-28"></a>
# 28. Choosing the Correct Encoding Technique

Use this mental decision process.

```text
Categorical variable
        |
        v
Does it have a meaningful order?
        |
   +----+----+
   |         |
  Yes        No
   |         |
Ordinal    How many categories?
Encoding       |
          +----+----+
          |         |
         Few       Many
          |         |
       One-Hot   Consider frequency,
                 target, binary, or hash
```

Examples:

| Feature | Possible technique |
|---|---|
| Yes/No | Binary |
| Gender | Binary or one-hot |
| City | One-hot |
| Education level | Ordinal |
| Satisfaction level | Ordinal |
| Browser | One-hot |
| Very high-cardinality ID-like feature | Frequency/hash/other domain-specific strategy |
| Multiple skills per user | Multi-hot |
| Category with target relationship | Target encoding with leakage controls |

# Practice Problem 26 — Choose the Encoding

For each feature, choose an appropriate encoding strategy and explain why.

1. `Gender`: Male/Female
2. `City`: Lahore/Karachi/Islamabad
3. `Education`: School/Bachelor/Master/PhD
4. `Satisfaction`: Bad/Okay/Good/Excellent
5. `Browser`: Chrome/Firefox/Safari
6. `Skills`: Python,SQL,React
7. `Country`: 150+ unique countries
8. `ProductID`: 100,000 unique products

In [47]:
# ✍️ Your answer here

<a id="sec-29"></a>
# 29. Complete Encoding Example

Now we will combine several encoding concepts in one dataset.

In [48]:
df = pd.DataFrame({
    'Age': [22, 25, 30, 35, 28, 40, 26, 31],
    'Gender': [
        'Male', 'Female', 'Male', 'Female',
        'Male', 'Male', 'Female', 'Female'
    ],
    'Education': [
        'Bachelor', 'Master', 'PhD', 'School',
        'Master', 'PhD', 'Bachelor', 'Master'
    ],
    'City': [
        'Lahore', 'Karachi', 'Lahore', 'Islamabad',
        'Karachi', 'Lahore', 'Multan', 'Karachi'
    ],
    'Purchased': [1, 1, 0, 0, 1, 1, 0, 1]
})

print(df)

   Age  Gender Education       City  Purchased
0   22    Male  Bachelor     Lahore          1
1   25  Female    Master    Karachi          1
2   30    Male       PhD     Lahore          0
3   35  Female    School  Islamabad          0
4   28    Male    Master    Karachi          1
5   40    Male       PhD     Lahore          1
6   26  Female  Bachelor     Multan          0
7   31  Female    Master    Karachi          1

## Step 1 — Identify column types

Numerical:

```text
Age
Purchased
```

Categorical:

```text
Gender
Education
City
```

`Education` is ordinal because it has a meaningful educational progression.

`City` is nominal because cities do not have a natural numerical order.

In [49]:
df['Gender_encoded'] = df['Gender'].map({
    'Female': 0,
    'Male': 1
})

education_map = {
    'School': 0,
    'Bachelor': 1,
    'Master': 2,
    'PhD': 3
}

df['Education_encoded'] = df['Education'].map(education_map)

df

,Age,Gender,Education,City,Purchased,Gender_encoded,Education_encoded
0,22,Male,Bachelor,Lahore,1,1,1
1,25,Female,Master,Karachi,1,0,2
2,30,Male,PhD,Lahore,0,1,3
3,35,Female,School,Islamabad,0,0,0
4,28,Male,Master,Karachi,1,1,2
5,40,Male,PhD,Lahore,1,1,3
6,26,Female,Bachelor,Multan,0,0,1
7,31,Female,Master,Karachi,1,0,2

## Step 2 — One-hot encode City

City is nominal, so we avoid imposing an artificial order.

In [50]:
df_encoded = pd.get_dummies(
    df,
    columns=['City'],
    dtype=int
)

print(df_encoded)

   Age  Gender Education  Purchased  Gender_encoded  Education_encoded  \
0   22    Male  Bachelor          1               1                  1
1   25  Female    Master          1               0                  2
2   30    Male       PhD          0               1                  3
3   35  Female    School          0               0                  0
4   28    Male    Master          1               1                  2
5   40    Male       PhD          1               1                  3
6   26  Female  Bachelor          0               0                  1
7   31  Female    Master          1               0                  2

   City_Islamabad  City_Karachi  City_Lahore  City_Multan
0               0             0            1            0
1               0             1            0            0
2               0             0            1            0
3               1             0            0            0
4               0             1            0            0
5               0             0            1            0
6               0             0            0            1
7               0             1            0            0

# Practice Problem 27 — Full Manual Encoding

Create your own dataset with at least 15 rows containing:

- `Age`
- `Gender`
- `Education`
- `City`
- `Department`
- `Purchased`

Perform the following:

1. Binary encode `Gender`.
2. Ordinal encode `Education`.
3. One-hot encode `City`.
4. One-hot encode `Department`.
5. Keep `Age` unchanged.
6. Keep `Purchased` as the target.
7. Display the final DataFrame.

In [51]:
# ✍️ Your answer here

<a id="sec-30"></a>
# 30. Advanced Exercise — Train/Test Encoding

Create a dataset containing at least 30 rows.

Requirements:

1. Split the data into training and testing sets.
2. Identify numerical and categorical features.
3. Use `StandardScaler` for numerical columns.
4. Use `OneHotEncoder` for categorical columns.
5. Set `handle_unknown='ignore'`.
6. Use `ColumnTransformer`.
7. Build a `Pipeline`.
8. Train a Logistic Regression model.
9. Evaluate it on the test data.

Do not preprocess the test set independently.

In [52]:
# ✍️ Your answer here

<a id="sec-31"></a>
# 31. Advanced Exercise — Target Encoding

Create a dataset containing:

- `City`
- `Age`
- `Income`
- `Purchased`

Requirements:

1. Split the dataset into train and test.
2. Calculate city purchase rates using training data only.
3. Map those rates to training data.
4. Apply the same training mapping to test data.
5. Handle a city appearing only in the test set.
6. Explain what could go wrong if you calculate the target mean before the train/test split.

In [53]:
# ✍️ Your answer here

<a id="sec-32"></a>
# 32. Advanced Exercise — High Cardinality

Imagine you have:

```text
100,000 customers
50,000 unique ProductIDs
```

Answer:

1. Would one-hot encoding create many columns?
2. Why might this be a problem?
3. What alternatives could you investigate?
4. Would frequency encoding make sense?
5. Could target encoding be useful?
6. What leakage precautions would be necessary?

In [54]:
# ✍️ Your answer here

<a id="sec-33"></a>
# 33. Final Project — Customer Purchase Prediction

Build a complete preprocessing workflow.

Create a dataset with at least 50 rows and these columns:

```text
Age
Income
Gender
Education
City
Browser
Device
Purchased
```

### Requirements

<a id="sec-34"></a>
## Part 1 — Data inspection

- Display the DataFrame.
- Check shape.
- Check data types.
- Find categorical columns.
- Find numerical columns.

<a id="sec-35"></a>
## Part 2 — Binary encoding

Encode `Gender` appropriately.

<a id="sec-36"></a>
## Part 3 — Ordinal encoding

Encode `Education` in the correct order.

<a id="sec-37"></a>
## Part 4 — One-hot encoding

One-hot encode:

- City
- Browser
- Device

<a id="sec-38"></a>
## Part 5 — Train/test split

Split the dataset before fitting preprocessing objects.

<a id="sec-39"></a>
## Part 6 — ColumnTransformer

Build a preprocessing system that handles numerical and categorical data separately.

<a id="sec-40"></a>
## Part 7 — Pipeline

Create a machine-learning Pipeline.

<a id="sec-41"></a>
## Part 8 — Model

Use Logistic Regression or another suitable classification model.

<a id="sec-42"></a>
## Part 9 — Evaluation

Evaluate the model using appropriate classification metrics.

<a id="sec-43"></a>
## Part 10 — Explanation

Explain:

- Why Gender was encoded the way you chose.
- Why Education was treated as ordinal.
- Why City was not label encoded.
- Why train/test leakage must be avoided.
- Why unknown categories need to be handled.

In [55]:
# ✍️ Your answer here

> 🔗 **Related topics (FIX-2026-09-27)**
> - **Topic 11 — Feature Engineering**: creating new categorical features (bins, flags, date parts) that you then encode here.
> - **Topic 11b — KBinsDiscretizer**: turning numeric columns *into* categories (and one-hot encoding the bins).
> - **Topic 16 — Feature Selection**: deciding which of the many one-hot columns to keep.
> - **Topic 17 — Machine Learning**: `ColumnTransformer` + `Pipeline` with encoders inside real models.

<a id="sec-44"></a>
# 34. Interview Questions

Try answering these without looking at previous cells.

### Beginner

1. What is encoding?
2. Why does machine learning need encoded categorical data?
3. What is categorical data?
4. What is the difference between nominal and ordinal data?
5. What is binary encoding in the simple 0/1 sense?

### Intermediate

6. What is one-hot encoding?
7. Why can label encoding be dangerous for nominal categories?
8. What does `pd.get_dummies()` do?
9. What does `drop_first=True` do?
10. What is frequency encoding?
11. What is count encoding?
12. What is ordinal encoding?

### Advanced

13. What is target encoding?
14. Why can target encoding cause leakage?
15. What is the difference between `fit()` and `transform()`?
16. Why should the encoder be fitted only on training data?
17. What does `handle_unknown='ignore'` do?
18. What is `ColumnTransformer`?
19. Why use a Pipeline?
20. When might frequency encoding be preferable to one-hot encoding?
21. What is high-cardinality categorical data?
22. What is binary encoding?
23. What is hash encoding?
24. What is multi-hot encoding?
25. How would you encode a column containing multiple skills per user?

<a id="sec-45"></a>
# 35. Final Revision Cheat Sheet

## Binary

```text
Yes → 1
No  → 0
```

Use for two-category variables when a binary representation makes sense.

## Ordinal

```text
Low → 0
Medium → 1
High → 2
```

Use when there is a meaningful order.

## One-Hot

```text
Lahore → [1,0,0]
Karachi → [0,1,0]
Islamabad → [0,0,1]
```

Use commonly for nominal categories with manageable cardinality.

## Frequency

```text
Lahore → 500
Karachi → 300
```

Represent categories using their occurrence frequency.

## Target

```text
Category → target statistic
```

Powerful but requires careful leakage prevention.

## Multi-Hot

One row can contain multiple active categories.

## Binary / Hash Encoding

Useful techniques to investigate when cardinality becomes very large.

---

### Most important rule

```text
Train data
    ↓
fit preprocessing
    ↓
transform train
    ↓
transform test using the SAME learned preprocessing
```

Never independently learn preprocessing from the test set.

# Practice Solutions (FIX-2026-09-27)

Try every problem yourself **first**. These are reference solutions — your own answers above are kept exactly as you wrote them.

Each solution cell is self-contained (it creates its own data), so you can run them in any order.

## Solution 1 & 2 — Identify categorical columns, then encode `Purchased` with `map()`

In [56]:
import pandas as pd
import numpy as np

data = pd.DataFrame({
    'Name': ['Ali', 'Sara', 'Ahmed', 'Ayesha', 'Usman', 'Fatima'],
    'Gender': ['Male', 'Female', 'Male', 'Female', 'Male', 'Female'],
    'City': ['Lahore', 'Karachi', 'Islamabad', 'Lahore', 'Karachi', 'Islamabad'],
    'Purchased': ['Yes', 'No', 'Yes', 'Yes', 'No', 'Yes']
})

# P1: Gender, City, Purchased are categorical. Name is an identifier -> never encode it as a feature.
print(data.dtypes)

# P2
data['Purchased'] = data['Purchased'].map({'No': 0, 'Yes': 1})
data

Name         str
Gender       str
City         str
Purchased    str
dtype: object

     Name  Gender       City  Purchased
0     Ali    Male     Lahore          1
1    Sara  Female    Karachi          0
2   Ahmed    Male  Islamabad          1
3  Ayesha  Female     Lahore          1
4   Usman    Male    Karachi          0
5  Fatima  Female  Islamabad          1

## Solution 3 — `Employment` with `map()`

⚠️ Common mistake: `df['col'].map({...})` **returns a new Series** — it does not change the DataFrame.
You must assign it back (or to a new column), otherwise the DataFrame still shows the text values.

In [57]:
emp = pd.DataFrame({'Employment': ['Unemployed', 'Employed', 'Employed', 'Unemployed']})
emp['Employment_encoded'] = emp['Employment'].map({'Unemployed': 0, 'Employed': 1})
emp

   Employment  Employment_encoded
0  Unemployed                   0
1    Employed                   1
2    Employed                   1
3  Unemployed                   0

## Solution 4 — `replace()` for Pass/Fail

In [58]:
res = pd.DataFrame({'Result': ['Pass', 'Fail', 'Pass', 'Pass', 'Fail']})
res['Result_encoded'] = res['Result'].replace({'Pass': 1, 'Fail': 0})
res

  Result Result_encoded
0   Pass              1
1   Fail              0
2   Pass              1
3   Pass              1
4   Fail              0

## Solution 5 & 6 — `category` dtype and `cat.codes`

In [59]:
dept = pd.DataFrame({'Department': ['IT', 'HR', 'IT', 'Finance', 'HR']})
dept['Department'] = dept['Department'].astype('category')
print(dept['Department'].dtype)
print(dept['Department'].cat.categories)

colors = pd.DataFrame({'Color': ['Red', 'Blue', 'Green', 'Red', 'Blue']})
colors['Color_code'] = colors['Color'].astype('category').cat.codes
colors

category
Index(['Finance', 'HR', 'IT'], dtype='str')

   Color  Color_code
0    Red           2
1   Blue           0
2  Green           1
3    Red           2
4   Blue           0

**P6 explanation:** categories are sorted alphabetically (Blue=0, Green=1, Red=2).
The numbers only come from alphabetical order — Red is not "twice" Green. A model reading `Color_code` as a number
would learn a fake order, which is why nominal columns are usually one-hot encoded instead.

## Solution 7 — Ordinal encoding with `map()`

In [60]:
level = pd.DataFrame({'Level': ['Low', 'High', 'Medium', 'Very High', 'Low']})
level_map = {'Low': 0, 'Medium': 1, 'High': 2, 'Very High': 3}
level['Level_encoded'] = level['Level'].map(level_map)
level

       Level  Level_encoded
0        Low              0
1       High              2
2     Medium              1
3  Very High              3
4        Low              0

## Solution 8 & 9 — `get_dummies()` with and without `drop_first`

In [61]:
colors = pd.DataFrame({'Color': ['Red', 'Blue', 'Green', 'Red', 'Green']})
print(pd.get_dummies(colors, columns=['Color'], dtype=int))

browser = pd.DataFrame({'Browser': ['Chrome', 'Firefox', 'Safari', 'Chrome']})
full = pd.get_dummies(browser, columns=['Browser'], dtype=int)
dropped = pd.get_dummies(browser, columns=['Browser'], drop_first=True, dtype=int)
print('\nAll dummies :', full.shape[1], 'columns ->', list(full.columns))
print('drop_first  :', dropped.shape[1], 'columns ->', list(dropped.columns))

   Color_Blue  Color_Green  Color_Red
0           0            0          1
1           1            0          0
2           0            1          0
3           0            0          1
4           0            1          0

All dummies : 3 columns -> ['Browser_Chrome', 'Browser_Firefox', 'Browser_Safari']
drop_first  : 2 columns -> ['Browser_Firefox', 'Browser_Safari']

`drop_first=True` removes the first category (Chrome); a row of all zeros now means "Chrome".

## Solution 10 & 11 — Several columns + automatic detection

In [62]:
people = pd.DataFrame({
    'Age': [25, 30, 28, 35],
    'Gender': ['Male', 'Female', 'Male', 'Female'],
    'City': ['Lahore', 'Karachi', 'Islamabad', 'Lahore'],
    'Department': ['HR', 'IT', 'Finance', 'IT'],
    'Salary': [50000, 70000, 60000, 90000]
})

cat_cols = people.select_dtypes(include=['object', 'string', 'category']).columns.tolist()
print('Categorical columns:', cat_cols)

pd.get_dummies(people, columns=cat_cols, dtype=int)

Categorical columns: ['Gender', 'City', 'Department']

,Age,Salary,Gender_Female,Gender_Male,City_Islamabad,City_Karachi,City_Lahore,Department_Finance,Department_HR,Department_IT
0,25,50000,0,1,0,0,1,0,1,0
1,30,70000,1,0,0,1,0,0,0,1
2,28,60000,0,1,1,0,0,1,0,0
3,35,90000,1,0,0,0,1,0,0,1

## Solution 12 & 13 — Frequency (count) and relative frequency

In [63]:
products = pd.DataFrame({'Product': ['Laptop', 'Phone', 'Laptop', 'Tablet', 'Phone', 'Laptop']})
products['Product_freq'] = products['Product'].map(products['Product'].value_counts())
print(products, '\n')

dept = pd.DataFrame({'Department': ['IT', 'HR', 'Finance', 'IT', 'IT', 'HR', 'Sales', 'IT']})
print(dept['Department'].value_counts())                      # raw counts
pct = dept['Department'].value_counts(normalize=True)
print(pct)                                                    # relative frequency
dept['Department_freq_pct'] = dept['Department'].map(pct)
dept

  Product  Product_freq
0  Laptop             3
1   Phone             2
2  Laptop             3
3  Tablet             1
4   Phone             2
5  Laptop             3

Department
IT         4
HR         2
Finance    1
Sales      1
Name: count, dtype: int64
Department
IT         0.500
HR         0.250
Finance    0.125
Sales      0.125
Name: proportion, dtype: float64

  Department  Department_freq_pct
0         IT                0.500
1         HR                0.250
2    Finance                0.125
3         IT                0.500
4         IT                0.500
5         HR                0.250
6      Sales                0.125
7         IT                0.500

## Solution 14 — Count encoding + sort

In [64]:
country = pd.DataFrame({'Country': ['Pakistan', 'India', 'Pakistan', 'UAE', 'Pakistan',
                                    'India', 'UK', 'Pakistan', 'UAE', 'India']})
country['Country_count'] = country['Country'].map(country['Country'].value_counts())
country = country.sort_values('Country_count', ascending=False)
print(country)
print('\nMost common:', country['Country'].iloc[0])

    Country  Country_count
0  Pakistan              4
2  Pakistan              4
4  Pakistan              4
7  Pakistan              4
1     India              3
5     India              3
9     India              3
3       UAE              2
8       UAE              2
6        UK              1

Most common: Pakistan

## Solution 15 — Manual target encoding

In [65]:
buy = pd.DataFrame({
    'Department': ['IT', 'IT', 'HR', 'HR', 'HR', 'Finance', 'Finance', 'IT'],
    'Purchased':  [1,    0,    0,    0,    1,    1,         1,         1]
})
rate = buy.groupby('Department')['Purchased'].mean()
print(rate)
buy['Department_target_enc'] = buy['Department'].map(rate)
buy

Department
Finance    1.000000
HR         0.333333
IT         0.666667
Name: Purchased, dtype: float64

  Department  Purchased  Department_target_enc
0         IT          1               0.666667
1         IT          0               0.666667
2         HR          0               0.333333
3         HR          0               0.333333
4         HR          1               0.333333
5    Finance          1               1.000000
6    Finance          1               1.000000
7         IT          1               0.666667

## Solution 16 — Leakage detection

1. **No, it is not safe.**
2. The encoding for each category was computed using the targets of the *test* rows too. The training features
   now contain information about the test answers, so the test score is optimistic — the model has "seen" part of the test.
   The effect is largest for rare categories (a category with 1 row gets exactly its own target!).
3. **Split first.** Compute the category means on the training set only, map them onto both train and test,
   fill unseen categories with the global training mean, and ideally use out-of-fold (cross-validated) means for the
   training rows themselves (this is what `sklearn.preprocessing.TargetEncoder` does).

## Solution 17 — Multi-hot encoding of `Languages`

In [66]:
lang = pd.DataFrame({
    'Name': ['Ali', 'Sara', 'Ahmed', 'Ayesha'],
    'Languages': ['Urdu,English', 'English', 'Urdu,Punjabi,English', 'Urdu']
})
multi = lang['Languages'].str.get_dummies(sep=',')
result = pd.concat([lang[['Name']], multi], axis=1)
result['n_languages'] = multi.sum(axis=1)
result

     Name  English  Punjabi  Urdu  n_languages
0     Ali        1        0     1            2
1    Sara        1        0     0            1
2   Ahmed        1        1     1            3
3  Ayesha        0        0     1            1

## Solution 18 — Group rare categories into `Other`

In [67]:
cities = pd.DataFrame({'City': ['Lahore'] * 4 + ['Karachi'] * 3 + ['Islamabad'] * 3 +
                                 ['Multan', 'Quetta', 'Peshawar', 'Multan']})
counts = cities['City'].value_counts()
rare = counts[counts < 3].index
cities['City_grouped'] = cities['City'].where(~cities['City'].isin(rare), 'Other')
print(counts, '\n')
print(cities['City_grouped'].value_counts())

City
Lahore       4
Karachi      3
Islamabad    3
Multan       2
Quetta       1
Peshawar     1
Name: count, dtype: int64

City_grouped
Lahore       4
Other        4
Karachi      3
Islamabad    3
Name: count, dtype: int64

## Solution 19 — Unknown categories

The encoder only knows the categories it saw during `fit` (Lahore, Karachi, Islamabad). When `Multan` appears at
prediction time there is no column for it. With the default `handle_unknown='error'`, `transform` raises an error and the
production system crashes.

`handle_unknown='ignore'` makes the encoder output **all zeros** for that row's City columns, so the row is still
processed — the model simply gets "none of the known cities".

## Solution 20 — Binary encoding arithmetic

1. One-hot: **16 columns** (15 with `drop_first`).
2. Binary: 2⁴ = 16, so **4 bits** (in practice libraries often need 5 because code 0 is reserved — still tiny).
3. Binary encoding needs about log₂(k) columns instead of k, so dimensionality grows very slowly as categories increase.

## Solution 21 — Hash encoding

1. A hash function turns each category string into a number, and that number (modulo *n*) chooses one of *n* fixed output columns.
2. The number of columns is fixed in advance, no matter how many categories exist (even ones never seen before), and no
   category dictionary has to be stored.
3. A **collision** is when two different categories land in the same column, so the model cannot tell them apart.
   More columns → fewer collisions.

## Solution 22 — `OneHotEncoder(handle_unknown="ignore")`

In [68]:
from sklearn.preprocessing import OneHotEncoder

train = pd.DataFrame({'Color': ['Red', 'Blue', 'Green', 'Red']})
test = pd.DataFrame({'Color': ['Blue', 'Purple']})       # Purple is unseen

enc = OneHotEncoder(handle_unknown='ignore', sparse_output=False)
enc.fit(train[['Color']])
print(enc.get_feature_names_out())
print(enc.transform(test[['Color']]))                      # Purple -> all zeros, no error

['Color_Blue' 'Color_Green' 'Color_Red']
[[1. 0. 0.]
 [0. 0. 0.]]

## Solution 23 & 24 — `ColumnTransformer` + `Pipeline`

In [69]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LogisticRegression

X = pd.DataFrame({
    'Age':        [25, 32, 47, 51, 23, 36, 29, 60, 41, 38],
    'Income':     [30, 52, 80, 95, 28, 61, 40, 110, 70, 58],
    'Gender':     ['Male', 'Female', 'Male', 'Female', 'Male', 'Female', 'Male', 'Male', 'Female', 'Female'],
    'City':       ['Lahore', 'Karachi', 'Lahore', 'Islamabad', 'Karachi', 'Lahore', 'Islamabad', 'Karachi', 'Lahore', 'Karachi'],
    'Department': ['IT', 'HR', 'IT', 'Finance', 'HR', 'IT', 'Finance', 'IT', 'HR', 'Finance']
})
y = [0, 0, 1, 1, 0, 1, 0, 1, 1, 0]

pre = ColumnTransformer([
    ('num', StandardScaler(), ['Age', 'Income']),
    ('cat', OneHotEncoder(handle_unknown='ignore'), ['Gender', 'City', 'Department'])
])
print('P23 transformed shape:', pre.fit_transform(X).shape)

pipe = Pipeline([('preprocessor', pre), ('model', LogisticRegression())])
pipe.fit(X, y)
print('P24 training accuracy:', pipe.score(X, y))   # 10 rows scored on themselves -> not a real evaluation (see Solution 30)

P23 transformed shape: (10, 10)
P24 training accuracy: 1.0

## Solution 25 — Numbers that are really categories

| Column | Type | Why |
|---|---|---|
| `Age` | numeric measurement | differences are meaningful (30 is 10 more than 20) |
| `Salary` | numeric measurement | amounts can be compared and averaged |
| `NumberOfChildren` | numeric (count) | 2 children really is more than 1 |
| `PostalCode` | **category** | 75000 is not "bigger" than 54000; it's a location label |
| `ProductID` | **identifier** | just a name for a product; usually dropped, or frequency/target encoded |

Rule: *if averaging the column makes no sense, it is not a quantity.*

## Solution 26 — Choose the encoding

| Feature | Encoding | Why |
|---|---|---|
| Gender (2 values) | binary 0/1 | only two categories |
| City (3 values) | one-hot | nominal, few categories |
| Education | ordinal | clear order School < Bachelor < Master < PhD |
| Satisfaction | ordinal | clear order Bad < Okay < Good < Excellent |
| Browser | one-hot | nominal, few categories |
| Skills (many per row) | multi-hot (`str.get_dummies`) | a row can have several skills |
| Country (150+) | group rare → Other + one-hot, or frequency / target encoding | too many columns for plain one-hot |
| ProductID (100k) | frequency, target (leak-safe), or hash encoding — or drop | one-hot would create 100k columns |

## Solution 27 — Full manual encoding (15 rows)

In [70]:
rng = np.random.default_rng(42)
n = 15
d27 = pd.DataFrame({
    'Age': rng.integers(20, 55, n),
    'Gender': rng.choice(['Male', 'Female'], n),
    'Education': rng.choice(['School', 'Bachelor', 'Master', 'PhD'], n),
    'City': rng.choice(['Lahore', 'Karachi', 'Islamabad'], n),
    'Department': rng.choice(['IT', 'HR', 'Finance'], n),
    'Purchased': rng.integers(0, 2, n)
})

d27['Gender'] = d27['Gender'].map({'Female': 0, 'Male': 1})                               # 1. binary
d27['Education'] = d27['Education'].map({'School': 0, 'Bachelor': 1, 'Master': 2, 'PhD': 3})  # 2. ordinal
d27 = pd.get_dummies(d27, columns=['City', 'Department'], dtype=int)                        # 3-4. one-hot

# 5-6: Age untouched, Purchased moved to the end as the target
d27 = d27[[c for c in d27.columns if c != 'Purchased'] + ['Purchased']]
d27                                                                                          # 7. display

,Age,Gender,Education,City_Islamabad,City_Karachi,City_Lahore,Department_Finance,Department_HR,Department_IT,Purchased
0,23,0,1,1,0,0,1,0,0,0
1,47,0,0,0,1,0,1,0,0,0
2,42,1,0,1,0,0,0,1,0,0
3,35,0,2,1,0,0,1,0,0,1
4,35,1,3,1,0,0,0,1,0,1
5,50,0,0,1,0,0,0,0,1,1
6,23,1,3,0,0,1,1,0,0,0
7,44,1,3,0,1,0,0,1,0,0
8,27,0,1,0,1,0,0,0,1,1
9,23,0,2,0,1,0,0,1,0,1
10,38,0,0,0,0,1,1,0,0,1
11,54,1,3,0,1,0,0,0,1,0
12,45,0,2,0,0,1,0,1,0,0
13,46,0,1,1,0,0,0,0,1,1
14,45,1,0,1,0,0,1,0,0,1

## Solution 30 — Train/test encoding with a full pipeline

In [71]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report

rng = np.random.default_rng(0)
n = 60
d30 = pd.DataFrame({
    'Age': rng.integers(20, 60, n),
    'Income': rng.normal(60, 20, n).round(1),
    'Gender': rng.choice(['Male', 'Female'], n),
    'City': rng.choice(['Lahore', 'Karachi', 'Islamabad', 'Multan'], n),
})
# target depends on Income and City so the model has something to learn
score = 0.05 * (d30['Income'] - 60) + (d30['City'] == 'Lahore') * 1.0
d30['Purchased'] = (score + rng.normal(0, 0.5, n) > 0).astype(int)

X = d30.drop(columns='Purchased')
y = d30['Purchased']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=42, stratify=y)

num_cols = X.select_dtypes(include='number').columns.tolist()
cat_cols = X.select_dtypes(include=['object', 'string', 'category']).columns.tolist()
print('numeric:', num_cols, '| categorical:', cat_cols)

pipe30 = Pipeline([
    ('pre', ColumnTransformer([
        ('num', StandardScaler(), num_cols),
        ('cat', OneHotEncoder(handle_unknown='ignore'), cat_cols)
    ])),
    ('model', LogisticRegression())
])
pipe30.fit(X_train, y_train)                 # everything is learned from TRAIN only
pred = pipe30.predict(X_test)
print('Test accuracy:', round(accuracy_score(y_test, pred), 3))
print(classification_report(y_test, pred, zero_division=0))

numeric: ['Age', 'Income'] | categorical: ['Gender', 'City']
Test accuracy: 0.733
              precision    recall  f1-score   support

           0       0.67      0.67      0.67         6
           1       0.78      0.78      0.78         9

    accuracy                           0.73        15
   macro avg       0.72      0.72      0.72        15
weighted avg       0.73      0.73      0.73        15

## Solution 31 — Leak-free target encoding

In [72]:
rng = np.random.default_rng(1)
d31 = pd.DataFrame({
    'City': rng.choice(['Lahore', 'Karachi', 'Islamabad'], 40),
    'Age': rng.integers(20, 60, 40),
    'Income': rng.normal(60, 15, 40).round(1),
    'Purchased': rng.integers(0, 2, 40)
})
train31, test31 = train_test_split(d31, test_size=0.25, random_state=42)
test31 = test31.copy()
test31.iloc[0, test31.columns.get_loc('City')] = 'Quetta'      # a city never seen in training

city_rate = train31.groupby('City')['Purchased'].mean()        # 2. training data only
global_rate = train31['Purchased'].mean()

train31 = train31.assign(City_te=train31['City'].map(city_rate))                    # 3
test31['City_te'] = test31['City'].map(city_rate).fillna(global_rate)               # 4 + 5
print(city_rate, '\nglobal:', round(global_rate, 3))
test31.head()

City
Islamabad    0.545455
Karachi      0.222222
Lahore       0.600000
Name: Purchased, dtype: float64
global: 0.467

       City  Age  Income  Purchased   City_te
19   Quetta   58    41.3          0  0.466667
16  Karachi   49    43.9          0  0.222222
15  Karachi   31    73.2          0  0.222222
26  Karachi   38    53.0          1  0.222222
4    Lahore   39    45.8          1  0.600000

**6. What goes wrong if you compute the mean before splitting?** The test rows' targets leak into the feature.
The model looks better on the test set than it will be on truly new data. Unseen categories like `Quetta` are
filled with the global training rate instead of crashing or getting `NaN`.

## Solution 32 — High cardinality (50,000 ProductIDs)

1. **Yes** — about 50,000 new columns.
2. Huge, very sparse matrices: lots of memory, slow training, and most columns have only a few `1`s, so the model overfits them.
3. Alternatives: group rare products into `Other`, frequency/count encoding, target encoding, hash encoding,
   binary encoding, product-level aggregates (price, category), or learned embeddings.
4. **Yes** — popularity is often predictive, and it's only one column. (Different products with the same count become identical.)
5. **Yes** — often strong, because it directly captures each product's typical outcome.
6. Fit on the training split only, use out-of-fold means for training rows, apply smoothing toward the global mean
   for rare products, and use the global mean for unseen products.

## Solution 33 — Final Project: Customer Purchase Prediction

In [73]:
from sklearn.preprocessing import OrdinalEncoder
from sklearn.metrics import confusion_matrix

rng = np.random.default_rng(7)
n = 200
proj = pd.DataFrame({
    'Age': rng.integers(18, 65, n),
    'Income': rng.normal(70, 25, n).clip(15).round(1),
    'Gender': rng.choice(['Male', 'Female'], n),
    'Education': rng.choice(['School', 'Bachelor', 'Master', 'PhD'], n, p=[0.2, 0.4, 0.3, 0.1]),
    'City': rng.choice(['Lahore', 'Karachi', 'Islamabad', 'Multan'], n),
    'Browser': rng.choice(['Chrome', 'Safari', 'Firefox'], n, p=[0.6, 0.25, 0.15]),
    'Device': rng.choice(['Mobile', 'Desktop', 'Tablet'], n, p=[0.55, 0.35, 0.10]),
})
edu_rank = proj['Education'].map({'School': 0, 'Bachelor': 1, 'Master': 2, 'PhD': 3})
logit = 0.04 * (proj['Income'] - 70) + 0.5 * edu_rank + 0.8 * (proj['Device'] == 'Desktop') - 0.8
proj['Purchased'] = (rng.random(n) < 1 / (1 + np.exp(-logit))).astype(int)

# Part 1 — inspection
print(proj.head(), '\n')
print('shape:', proj.shape)
print(proj.dtypes, '\n')
X = proj.drop(columns='Purchased')
y = proj['Purchased']
cat_cols = X.select_dtypes(include=['object', 'string', 'category']).columns.tolist()
num_cols = X.select_dtypes(include='number').columns.tolist()
print('categorical:', cat_cols)
print('numerical  :', num_cols)

   Age  Income  Gender Education       City Browser   Device  Purchased
0   62    19.1  Female  Bachelor  Islamabad  Safari  Desktop          0
1   47    62.4  Female    School     Lahore  Chrome  Desktop          1
2   50    47.5    Male       PhD    Karachi  Chrome   Mobile          0
3   60    74.1  Female  Bachelor     Lahore  Chrome   Mobile          1
4   45   126.1    Male    Master  Islamabad  Chrome  Desktop          1

shape: (200, 8)
Age            int64
Income       float64
Gender           str
Education        str
City             str
Browser          str
Device           str
Purchased      int64
dtype: object

categorical: ['Gender', 'Education', 'City', 'Browser', 'Device']
numerical  : ['Age', 'Income']

In [79]:
# Part 5 — split BEFORE fitting anything
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=42, stratify=y)

# Parts 2-4 + 6 — one ColumnTransformer does binary, ordinal and one-hot encoding
pre33 = ColumnTransformer([
    ('num', StandardScaler(), ['Age', 'Income']),
    ('gender', OneHotEncoder(drop='if_binary'), ['Gender']),                                       # binary 0/1
    ('edu', OrdinalEncoder(categories=[['School', 'Bachelor', 'Master', 'PhD']]), ['Education']),  # ordered
    ('nominal', OneHotEncoder(handle_unknown='ignore'), ['City', 'Browser', 'Device'])              # one-hot
])

# Parts 7-8 — pipeline + model
model33 = Pipeline([('pre', pre33), ('model', LogisticRegression(max_iter=1000))])
model33.fit(X_train, y_train)

# Part 9 — evaluation
pred = model33.predict(X_test)
print('Accuracy:', round(accuracy_score(y_test, pred), 3))
print('Confusion matrix:\n', confusion_matrix(y_test, pred))
print(classification_report(y_test, pred, zero_division=0))
print('Features after encoding:', len(model33.named_steps['pre'].get_feature_names_out()))

Accuracy: 0.64
Confusion matrix:
 [[21  7]
 [11 11]]
              precision    recall  f1-score   support

           0       0.66      0.75      0.70        28
           1       0.61      0.50      0.55        22

    accuracy                           0.64        50
   macro avg       0.63      0.62      0.62        50
weighted avg       0.64      0.64      0.63        50

Features after encoding: 14

**Part 10 — explanation**

- **Gender** has two values, so one 0/1 column is enough (`drop='if_binary'`).
- **Education** has a real order, so `OrdinalEncoder` with an explicit category order keeps School < Bachelor < Master < PhD.
- **City** has no order — label encoding (0,1,2,3) would invent one, so it is one-hot encoded.
- **Leakage:** the scaler and encoders are fitted inside the pipeline on the training split only; the test set is only transformed.
- **Unknown categories:** `handle_unknown='ignore'` means a new city/browser/device in production produces zeros instead of an error.

## Interview answers (short)

1. Converting categories into numbers a model can use. 2. Most models do arithmetic, so they need numbers.
3. Values that name groups. 4. Nominal = no order (City); ordinal = order (Education). 5. Two categories → 0/1.
6. One 0/1 column per category. 7. It invents an order/distance between categories that don't have one.
8. Creates one-hot columns. 9. Drops the first dummy column of each feature. 10. Category → its share of rows.
11. Category → its number of rows. 12. Ordered categories → ordered integers.
13. Category → mean target for that category. 14. The target values themselves get into the feature (worse if computed before the split).
15. `fit` learns (categories, means…), `transform` applies what was learned. 16. So no test information leaks in.
17. Unseen categories become all-zero rows instead of raising an error. 18. Applies different preprocessing to different columns.
19. Bundles preprocessing + model so the same steps run in training, validation and production (no leakage).
20. When there are many categories and one-hot would explode the column count. 21. A column with very many unique values.
22. Category index written in binary digits, one column per digit. 23. Category → hash → one of *n* fixed columns.
24. Several 1s per row because a row can belong to several categories. 25. `df['Skills'].str.get_dummies(sep=',')`.