# Topic 10 — Combining DataFrames — ✍️ Practice & Solutions

This notebook has every **practice problem** for Topic 10, each followed by its **✅ solution**.

**How to use it**
1. Read the lesson first: [Topic_10_Lesson.ipynb](Topic_10_Lesson.ipynb).
2. Read a problem and write your answer in the code cell under it.
3. Only then scroll down to the ✅ solution and compare.
4. Stuck or confused? Go back to the matching lesson section — every solution uses only what the lesson teaches.

> 📚 **Course navigation** — you are in **Topic 10: Combining DataFrames**
> ⬅️ Previous: [Topic 09 — Pandas Data Manipulation](../Topic_09_Pandas_Data_Manipulation/Topic_09_Lesson.ipynb)  ·  ➡️ Next: [Topic 11 — Feature Engineering](../Topic_11_Feature_Engineering/Topic_11_Lesson.ipynb)  ·  🗂️ [All topics](../Topic_00_All_Topics_Index.ipynb)

<details><summary>Full course sequence (click to expand)</summary>

| # | Topic | Lesson | Practice & Solutions |
|---|---|---|---|
| 01 | Python Basics | [📖 Lesson](../Topic_01_Python_Basics/Topic_01_Lesson.ipynb) | [✍️ Practice](../Topic_01_Python_Basics/Topic_01_Practice_Solutions.ipynb) |
| 02 | Pandas DataFrame Basics | [📖 Lesson](../Topic_02_Pandas_DataFrame_Basics/Topic_02_Lesson.ipynb) | [✍️ Practice](../Topic_02_Pandas_DataFrame_Basics/Topic_02_Practice_Solutions.ipynb) |
| 03 | Handling Missing Values | [📖 Lesson](../Topic_03_Handling_Missing_Values/Topic_03_Lesson.ipynb) | [✍️ Practice](../Topic_03_Handling_Missing_Values/Topic_03_Practice_Solutions.ipynb) |
| 04 | Normalization & Standardization | [📖 Lesson](../Topic_04_Normalization_Standardization/Topic_04_Lesson.ipynb) | [✍️ Practice](../Topic_04_Normalization_Standardization/Topic_04_Practice_Solutions.ipynb) |
| 05 | Detecting & Treating Outliers | [📖 Lesson](../Topic_05_Outliers/Topic_05_Lesson.ipynb) | [✍️ Practice](../Topic_05_Outliers/Topic_05_Practice_Solutions.ipynb) |
| 🎯 | *🎯 Quiz 1 — Topics 01–05* | [🎯 Quiz 1](../Quiz_1_Topics_01-05/Quiz_1.ipynb) | |
| 06 | Encoding Techniques | [📖 Lesson](../Topic_06_Encoding_Techniques/Topic_06_Lesson.ipynb) | [✍️ Practice](../Topic_06_Encoding_Techniques/Topic_06_Practice_Solutions.ipynb) |
| 07 | Exploratory Data Analysis (EDA) | [📖 Lesson](../Topic_07_Exploratory_Data_Analysis/Topic_07_Lesson.ipynb) | [✍️ Practice](../Topic_07_Exploratory_Data_Analysis/Topic_07_Practice_Solutions.ipynb) |
| 08 | Data Visualization | [📖 Lesson](../Topic_08_Data_Visualization/Topic_08_Lesson.ipynb) | [✍️ Practice](../Topic_08_Data_Visualization/Topic_08_Practice_Solutions.ipynb) |
| 09 | Pandas Data Manipulation | [📖 Lesson](../Topic_09_Pandas_Data_Manipulation/Topic_09_Lesson.ipynb) | [✍️ Practice](../Topic_09_Pandas_Data_Manipulation/Topic_09_Practice_Solutions.ipynb) |
| **▶ 10 ◀** | **Combining DataFrames** | [📖 Lesson](../Topic_10_Combining_DataFrames/Topic_10_Lesson.ipynb) | [✍️ Practice](../Topic_10_Combining_DataFrames/Topic_10_Practice_Solutions.ipynb) |
| 🎯 | *🎯 Quiz 2 — Topics 06–10* | [🎯 Quiz 2](../Quiz_2_Topics_06-10/Quiz_2.ipynb) | |
| 11 | Feature Engineering | [📖 Lesson](../Topic_11_Feature_Engineering/Topic_11_Lesson.ipynb) | [✍️ Practice](../Topic_11_Feature_Engineering/Topic_11_Practice_Solutions.ipynb) |
| 11b | KBinsDiscretizer (Discretization) | [📖 Lesson](../Topic_11b_KBinsDiscretizer/Topic_11b_Lesson.ipynb) | [✍️ Practice](../Topic_11b_KBinsDiscretizer/Topic_11b_Practice_Solutions.ipynb) |
| 12 | Correlation & Multicollinearity | [📖 Lesson](../Topic_12_Correlation_Multicollinearity/Topic_12_Lesson.ipynb) | [✍️ Practice](../Topic_12_Correlation_Multicollinearity/Topic_12_Practice_Solutions.ipynb) |
| 13 | Data Transformation & Skewness | [📖 Lesson](../Topic_13_Data_Transformation_Skewness/Topic_13_Lesson.ipynb) | [✍️ Practice](../Topic_13_Data_Transformation_Skewness/Topic_13_Practice_Solutions.ipynb) |
| 14 | Statistics for Data Science | [📖 Lesson](../Topic_14_Statistics_for_Data_Science/Topic_14_Lesson.ipynb) | [✍️ Practice](../Topic_14_Statistics_for_Data_Science/Topic_14_Practice_Solutions.ipynb) |
| 🎯 | *🎯 Quiz 3 — Topics 11–14* | [🎯 Quiz 3](../Quiz_3_Topics_11-14/Quiz_3.ipynb) | |
| 15 | Probability for Data Science & ML | [📖 Lesson](../Topic_15_Probability_for_Data_Science_ML/Topic_15_Lesson.ipynb) | [✍️ Practice](../Topic_15_Probability_for_Data_Science_ML/Topic_15_Practice_Solutions.ipynb) |
| 16 | Feature Selection | [📖 Lesson](../Topic_16_Feature_Selection/Topic_16_Lesson.ipynb) | [✍️ Practice](../Topic_16_Feature_Selection/Topic_16_Practice_Solutions.ipynb) |
| 17 | Machine Learning | [📖 Lesson](../Topic_17_Machine_Learning/Topic_17_Lesson.ipynb) | [✍️ Practice](../Topic_17_Machine_Learning/Topic_17_Practice_Solutions.ipynb) |
| 🎯 | *🏁 Final Quiz — Topics 15–17* | [🏁 Final Quiz](../Quiz_4_Topics_15-17/Quiz_4.ipynb) | |

</details>

## 📋 Practice Index

**21 problems** — each one is followed by your answer cell and then its ✅ solution. Click a problem to jump to it.

- [✍️ Practice Problem 1](#p-1)
- [✍️ Practice Problem 2](#p-2)
- [✍️ Practice Problem 3](#p-3)
- [✍️ Practice Problem 4](#p-4)
- [✍️ Practice Problem 5](#p-5)
- [✍️ Practice Problem 6](#p-6)
- [✍️ Practice Problem 7](#p-7)
- [✍️ Practice Problem 8](#p-8)
- [✍️ Practice Problem 9](#p-9)
- [✍️ Practice Problem 10](#p-10)
- [✍️ Practice Problem 11](#p-11)
- [✍️ Practice Problem 12](#p-12)
- [✍️ Practice Problem 13](#p-13)
- [✍️ Practice Problem 14](#p-14)
- [✍️ Practice Problem 15](#p-15)
- [✍️ Practice Problem 16](#p-16)
- [✍️ Practice Problem 17](#p-17)
- [✍️ Practice Problem 18](#p-18)
- [✍️ Practice Problem 19](#p-19)
- [✍️ Practice Problem 20](#p-20)
- [Final Project — E-Commerce Database Integration](#p-21)

> 📖 Lesson for this topic: [Topic_10_Lesson.ipynb](Topic_10_Lesson.ipynb)

### ⚙️ Setup — run this cell first

Some problems use data, variables and functions created in the lesson. This cell quietly runs the whole lesson notebook so they all exist here.

In [1]:
%%capture
# Runs the lesson notebook (output hidden) so its variables exist here
%run ./Topic_10_Lesson.ipynb

---
# Practice Problems (20, increasing difficulty)

Run the next cell to create the practice datasets. Each problem has an empty code cell; solutions are in the **Solutions** section.

In [2]:
# ---------- Practice datasets ----------
q_jan = pd.DataFrame({'Sale_ID': [1, 2, 3], 'Store': ['A', 'B', 'A'], 'Amount': [500, 700, 300]})
q_feb = pd.DataFrame({'Sale_ID': [4, 5], 'Store': ['B', 'C'], 'Amount': [650, 900]})
q_mar = pd.DataFrame({'Sale_ID': [6, 7], 'Store': ['A', 'C'], 'Amount': [400, 1000], 'Promo': ['Yes', 'No']})

students_p = pd.DataFrame({'Student_ID': [1, 2, 3, 4, 5], 'Name': ['Ali', 'Sara', 'Omar', 'Hina', 'Bilal'],
                           'Class': ['A', 'A', 'B', 'B', 'C']})
marks_p = pd.DataFrame({'Student_ID': [1, 2, 2, 3, 6], 'Subject': ['Math', 'Math', 'English', 'Math', 'Math'],
                        'Marks': [88, 92, 75, 64, 71]})
classes_p = pd.DataFrame({'class_code': ['A', 'B', 'D'], 'Teacher': ['Mr. Khan', 'Ms. Noor', 'Mr. Ali']})

emp_p = pd.DataFrame({'Emp_ID': [10, 11, 12, 13], 'Name': ['Usman', 'Zara', 'Imran', 'Ayesha'], 'Dept_ID': [1, 2, 1, 3]})
dept_p = pd.DataFrame({'Dept_ID': [1, 2, 3, 3], 'Dept': ['IT', 'HR', 'Sales', 'Sales & Marketing']})    # Dept 3 twice!

stock_p = pd.DataFrame({'Store': ['A', 'A', 'B', 'B'], 'Product': ['Pen', 'Book', 'Pen', 'Bag'], 'Stock': [50, 20, 35, 10]})
price_p = pd.DataFrame({'Store': ['A', 'A', 'B', 'B'], 'Product': ['Pen', 'Book', 'Pen', 'Lamp'], 'Price': [20, 300, 22, 900]})

orders_p = pd.DataFrame({'order_id': range(1, 9), 'cust': ['C1', 'C2', 'c3', 'C1', 'C4 ', 'C2', 'C9', 'C3'],
                         'prod': [101, 102, 101, 103, 102, 104, 101, 103], 'qty': [1, 2, 1, 3, 1, 2, 1, 1]})
customers_p = pd.DataFrame({'id': ['C1', 'C2', 'C3', 'C4', 'C5'], 'name': ['Ali', 'Sara', 'Omar', 'Hina', 'Bilal'],
                            'city': ['Lahore', 'Karachi', 'Lahore', 'Multan', 'Karachi']})
products_p = pd.DataFrame({'prod_id': ['101', '102', '103', '104'], 'product': ['Pen', 'Book', 'Bag', 'Lamp'],
                           'price': [20, 300, 1200, 900]})
rates_p = pd.DataFrame({'Date': pd.to_datetime(['2025-01-01', '2025-01-10', '2025-01-20']), 'Rate': [279.0, 280.2, 281.0]})
payments_p = pd.DataFrame({'Date': pd.to_datetime(['2025-01-05', '2025-01-12', '2025-01-25', '2025-01-10']), 'USD': [100, 50, 200, 80]})
print('Practice datasets ready ✔')

Practice datasets ready ✔

<a id="p-1"></a>
### ✍️ Practice Problem 1

**(Easy) Row-wise concat:** Stack `q_jan` and `q_feb` into one DataFrame with a clean 0..n−1 index.

*(Solution in the **Practice Solutions** section at the end.)*

In [3]:
# ✍️ Practice Problem 1 — write your solution here

---
---
# Solutions

⚠️ Try the problems first!

### Solution 1

In [4]:
pd.concat([q_jan, q_feb], ignore_index=True)

   Sale_ID Store  Amount
0        1     A     500
1        2     B     700
2        3     A     300
3        4     B     650
4        5     C     900

**Explanation:** `ignore_index=True` replaces the repeated 0, 1, 2 / 0, 1 labels with 0..4.

<a id="p-2"></a>
### ✍️ Practice Problem 2

**(Easy) keys:** Stack `q_jan`, `q_feb`, `q_mar` with `keys=['Jan', 'Feb', 'Mar']`, then turn the key level into a `Month` column. What happens to the `Promo` column for January and February?

*(Solution in the **Practice Solutions** section at the end.)*

In [5]:
# ✍️ Practice Problem 2 — write your solution here

### Solution 2

In [6]:
months = (pd.concat([q_jan, q_feb, q_mar], keys=['Jan', 'Feb', 'Mar'], names=['Month', 'Row'])
          .reset_index(level='Month').reset_index(drop=True))
months

  Month  Sale_ID Store  Amount Promo
0   Jan        1     A     500   NaN
1   Jan        2     B     700   NaN
2   Jan        3     A     300   NaN
3   Feb        4     B     650   NaN
4   Feb        5     C     900   NaN
5   Mar        6     A     400   Yes
6   Mar        7     C    1000    No

**Explanation:** `Promo` only exists in March, so it is NaN for the January and February rows (outer join of columns).

<a id="p-3"></a>
### ✍️ Practice Problem 3

**(Easy) join='inner':** Stack the three months keeping **only** the columns shared by all of them.

*(Solution in the **Practice Solutions** section at the end.)*

In [7]:
# ✍️ Practice Problem 3 — write your solution here

### Solution 3

In [8]:
pd.concat([q_jan, q_feb, q_mar], join='inner', ignore_index=True)

   Sale_ID Store  Amount
0        1     A     500
1        2     B     700
2        3     A     300
3        4     B     650
4        5     C     900
5        6     A     400
6        7     C    1000

**Explanation:** `join='inner'` drops `Promo` because it is not present in every piece.

<a id="p-4"></a>
### ✍️ Practice Problem 4

**(Easy) Column-wise concat:** Create `a = pd.DataFrame({'x': [1, 2, 3]})` and `b = pd.DataFrame({'y': [10, 20, 30]}, index=[1, 2, 3])`. Concatenate them with `axis=1` and explain the result. Fix it so rows are paired by position.

*(Solution in the **Practice Solutions** section at the end.)*

In [9]:
# ✍️ Practice Problem 4 — write your solution here

### Solution 4

In [10]:
a = pd.DataFrame({'x': [1, 2, 3]})
b = pd.DataFrame({'y': [10, 20, 30]}, index=[1, 2, 3])
print(pd.concat([a, b], axis=1))                                     # aligned by index labels 0..3 → NaNs
print(pd.concat([a, b.reset_index(drop=True)], axis=1))             # paired by position

     x     y
0  1.0   NaN
1  2.0  10.0
2  3.0  20.0
3  NaN  30.0
   x   y
0  1  10
1  2  20
2  3  30

**Explanation:** `axis=1` aligns on index labels: label 0 exists only in `a`, label 3 only in `b` → 4 rows with NaNs. Resetting `b`'s index pairs rows by position.

<a id="p-5"></a>
### ✍️ Practice Problem 5

**(Easy) Inner merge:** Merge `students_p` with `marks_p` on `Student_ID` (inner). Which students/marks are missing and why?

*(Solution in the **Practice Solutions** section at the end.)*

In [11]:
# ✍️ Practice Problem 5 — write your solution here

### Solution 5

In [12]:
inner5 = pd.merge(students_p, marks_p, on='Student_ID', how='inner')
inner5

   Student_ID  Name Class  Subject  Marks
0           1   Ali     A     Math     88
1           2  Sara     A     Math     92
2           2  Sara     A  English     75
3           3  Omar     B     Math     64

**Explanation:** Hina (4) and Bilal (5) have no marks → dropped. The mark for Student_ID 6 has no student → dropped. Sara appears twice (two subjects).

<a id="p-6"></a>
### ✍️ Practice Problem 6

**(Easy) Left merge:** Keep **all** students, attaching their marks. Which students have no marks?

*(Solution in the **Practice Solutions** section at the end.)*

In [13]:
# ✍️ Practice Problem 6 — write your solution here

### Solution 6

In [14]:
left6 = pd.merge(students_p, marks_p, on='Student_ID', how='left')
print(left6)
print('No marks:', left6.loc[left6['Marks'].isna(), 'Name'].tolist())

   Student_ID   Name Class  Subject  Marks
0           1    Ali     A     Math   88.0
1           2   Sara     A     Math   92.0
2           2   Sara     A  English   75.0
3           3   Omar     B     Math   64.0
4           4   Hina     B      NaN    NaN
5           5  Bilal     C      NaN    NaN
No marks: ['Hina', 'Bilal']

**Explanation:** All five students are kept; Hina and Bilal get NaN for Subject/Marks.

<a id="p-7"></a>
### ✍️ Practice Problem 7

**(Medium) Right & outer:** Do a right and an outer merge of `students_p` and `marks_p`. Report the row count of inner, left, right and outer joins in a small table.

*(Solution in the **Practice Solutions** section at the end.)*

In [15]:
# ✍️ Practice Problem 7 — write your solution here

### Solution 7

In [16]:
counts7 = {how: len(pd.merge(students_p, marks_p, on='Student_ID', how=how)) for how in ['inner', 'left', 'right', 'outer']}
print(pd.Series(counts7, name='rows'))
print(pd.merge(students_p, marks_p, on='Student_ID', how='outer'))

inner    4
left     6
right    5
outer    7
Name: rows, dtype: int64
   Student_ID   Name Class  Subject  Marks
0           1    Ali     A     Math   88.0
1           2   Sara     A     Math   92.0
2           2   Sara     A  English   75.0
3           3   Omar     B     Math   64.0
4           4   Hina     B      NaN    NaN
5           5  Bilal     C      NaN    NaN
6           6    NaN   NaN     Math   71.0

**Explanation:** inner 4 · left 6 (4 matches + Hina + Bilal) · right 5 (every mark, including ID 6) · outer 7 (everything).

<a id="p-8"></a>
### ✍️ Practice Problem 8

**(Medium) Indicator:** Use an outer merge with `indicator=True` to list (a) students without marks and (b) marks for unknown students.

*(Solution in the **Practice Solutions** section at the end.)*

In [17]:
# ✍️ Practice Problem 8 — write your solution here

### Solution 8

In [18]:
chk8 = pd.merge(students_p, marks_p, on='Student_ID', how='outer', indicator=True)
print('Students without marks:', chk8.loc[chk8['_merge'] == 'left_only', 'Name'].tolist())
print('Marks for unknown students:'); print(chk8.loc[chk8['_merge'] == 'right_only', ['Student_ID', 'Subject', 'Marks']])

Students without marks: ['Hina', 'Bilal']
Marks for unknown students:
   Student_ID Subject  Marks
6           6    Math   71.0

**Explanation:** `left_only` = only in students; `right_only` = only in marks (Student_ID 6 → a data-quality issue).

<a id="p-9"></a>
### ✍️ Practice Problem 9

**(Medium) Different key names:** Attach each student's teacher: `students_p.Class` ↔ `classes_p.class_code`. Keep all students and drop the redundant key column.

*(Solution in the **Practice Solutions** section at the end.)*

In [19]:
# ✍️ Practice Problem 9 — write your solution here

### Solution 9

In [20]:
pd.merge(students_p, classes_p, left_on='Class', right_on='class_code', how='left').drop(columns='class_code')

   Student_ID   Name Class   Teacher
0           1    Ali     A  Mr. Khan
1           2   Sara     A  Mr. Khan
2           3   Omar     B  Ms. Noor
3           4   Hina     B  Ms. Noor
4           5  Bilal     C       NaN

**Explanation:** Bilal's class C has no teacher (NaN); class D in `classes_p` has no students and is ignored by the left join.

<a id="p-10"></a>
### ✍️ Practice Problem 10

**(Medium) Composite key:** Merge `stock_p` and `price_p` on both `Store` and `Product` (outer). Then show what goes wrong if you merge on `Product` only.

*(Solution in the **Practice Solutions** section at the end.)*

In [21]:
# ✍️ Practice Problem 10 — write your solution here

### Solution 10

In [22]:
print(pd.merge(stock_p, price_p, on=['Store', 'Product'], how='outer'))
print('\n❌ Product only:')
print(pd.merge(stock_p, price_p, on='Product', how='outer'))

  Store Product  Stock  Price
0     A    Book   20.0  300.0
1     A     Pen   50.0   20.0
2     B     Bag   10.0    NaN
3     B    Lamp    NaN  900.0
4     B     Pen   35.0   22.0

❌ Product only:
  Store_x Product  Stock Store_y  Price
0       B     Bag   10.0     NaN    NaN
1       A    Book   20.0       A  300.0
2     NaN    Lamp    NaN       B  900.0
3       A     Pen   50.0       A   20.0
4       A     Pen   50.0       B   22.0
5       B     Pen   35.0       A   20.0
6       B     Pen   35.0       B   22.0

**Explanation:** The composite key pairs each store's product with that store's price. On `Product` alone, the Pen rows of store A and B cross-match (2 × 2 = 4 rows) and `Store_x`/`Store_y` show the mix-up.

<a id="p-11"></a>
### ✍️ Practice Problem 11

**(Medium) Suffixes:** Create `x = pd.DataFrame({'ID': [1, 2], 'Score': [80, 90]})` and `y = pd.DataFrame({'ID': [1, 2], 'Score': [85, 70]})` (midterm vs final). Merge them with meaningful suffixes and add an `Improvement` column.

*(Solution in the **Practice Solutions** section at the end.)*

In [23]:
# ✍️ Practice Problem 11 — write your solution here

### Solution 11

In [24]:
x = pd.DataFrame({'ID': [1, 2], 'Score': [80, 90]})
y = pd.DataFrame({'ID': [1, 2], 'Score': [85, 70]})
m11 = pd.merge(x, y, on='ID', suffixes=('_midterm', '_final'), validate='one_to_one')
m11['Improvement'] = m11['Score_final'] - m11['Score_midterm']
m11

   ID  Score_midterm  Score_final  Improvement
0   1             80           85            5
1   2             90           70          -20

**Explanation:** Meaningful suffixes make the merged columns self-explanatory.

<a id="p-12"></a>
### ✍️ Practice Problem 12

**(Medium) Relationship & validation:** Merge `emp_p` with `dept_p` on `Dept_ID`. How many rows do you get and why? Re-run with `validate='many_to_one'`, catch the error, then fix `dept_p` (keep the first name) and merge again.

*(Solution in the **Practice Solutions** section at the end.)*

In [25]:
# ✍️ Practice Problem 12 — write your solution here

### Solution 12

In [26]:
print('Rows:', len(pd.merge(emp_p, dept_p, on='Dept_ID')), '(4 employees, but Ayesha appears twice)')
try:
    pd.merge(emp_p, dept_p, on='Dept_ID', validate='many_to_one')
except pd.errors.MergeError as e:
    print('MergeError:', str(e).split('\n')[0])
dept_fixed = dept_p.drop_duplicates(subset='Dept_ID', keep='first')
pd.merge(emp_p, dept_fixed, on='Dept_ID', validate='many_to_one')

Rows: 5 (4 employees, but Ayesha appears twice)
MergeError: Merge keys are not unique in right dataset; not a many-to-one merge

   Emp_ID    Name  Dept_ID   Dept
0      10   Usman        1     IT
1      11    Zara        2     HR
2      12   Imran        1     IT
3      13  Ayesha        3  Sales

**Explanation:** Dept_ID 3 appears twice, so Ayesha matches both rows (5 rows). Validation catches it; deduplicating the lookup table fixes it.

<a id="p-13"></a>
### ✍️ Practice Problem 13

**(Medium) join():** Set `Student_ID` as the index of `students_p`. Compute each student's average mark from `marks_p` with `groupby` and attach it with `join()` (keep all students). Then use `marks_p.join(..., on='Student_ID')` to add student names to every mark.

*(Solution in the **Practice Solutions** section at the end.)*

In [27]:
# ✍️ Practice Problem 13 — write your solution here

### Solution 13

In [28]:
st_idx = students_p.set_index('Student_ID')
avg_marks = marks_p.groupby('Student_ID')['Marks'].mean().rename('Avg_Mark')
print(st_idx.join(avg_marks))                                    # left join on the index
print(marks_p.join(st_idx[['Name']], on='Student_ID'))           # column (left) ↔ index (right)

             Name Class  Avg_Mark
Student_ID
1             Ali     A      88.0
2            Sara     A      83.5
3            Omar     B      64.0
4            Hina     B       NaN
5           Bilal     C       NaN
   Student_ID  Subject  Marks  Name
0           1     Math     88   Ali
1           2     Math     92  Sara
2           2  English     75  Sara
3           3     Math     64  Omar
4           6     Math     71   NaN

**Explanation:** `join` matches on the index; `on=` lets the **left** side use a column while the right side uses its index.

<a id="p-14"></a>
### ✍️ Practice Problem 14

**(Medium) merge vs concat:** Using `students_p` and `marks_p`, show why `pd.concat([students_p, marks_p], axis=1)` is the wrong way to combine them.

*(Solution in the **Practice Solutions** section at the end.)*

In [29]:
# ✍️ Practice Problem 14 — write your solution here

### Solution 14

In [30]:
print(pd.concat([students_p, marks_p], axis=1))
# Row 0 of students is glued to row 0 of marks by POSITION, not by Student_ID:
# e.g. Omar (ID 3) is paired with Sara's English mark (ID 2), and Bilal (ID 5) gets the mark of unknown student 6.

   Student_ID   Name Class  Student_ID  Subject  Marks
0           1    Ali     A           1     Math     88
1           2   Sara     A           2     Math     92
2           3   Omar     B           2  English     75
3           4   Hina     B           3     Math     64
4           5  Bilal     C           6     Math     71

**Explanation:** `concat(axis=1)` never looks at `Student_ID`; only `merge` pairs rows by the key.

<a id="p-15"></a>
### ✍️ Practice Problem 15

**(Hard) Duplicate-key detection:** For `dept_p`, `marks_p` and `orders_p`, report which key columns are unique (`is_unique`) and list duplicated keys with `value_counts()`. Which ones are problems for a lookup merge?

*(Solution in the **Practice Solutions** section at the end.)*

In [31]:
# ✍️ Practice Problem 15 — write your solution here

### Solution 15

In [32]:
for name, frame, key in [('dept_p', dept_p, 'Dept_ID'), ('marks_p', marks_p, 'Student_ID'), ('orders_p', orders_p, 'cust')]:
    vc = frame[key].value_counts()
    print(f'{name}.{key}: unique={frame[key].is_unique} | duplicated keys: {vc[vc > 1].to_dict()}')

dept_p.Dept_ID: unique=False | duplicated keys: {3: 2}
marks_p.Student_ID: unique=False | duplicated keys: {2: 2}
orders_p.cust: unique=False | duplicated keys: {'C1': 2, 'C2': 2}

**Explanation:** `dept_p` is meant to be a lookup table (one row per department) → its duplicate is a **problem**. `marks_p` and `orders_p` are fact tables where repeated keys are **expected** (many marks per student, many orders per customer).

<a id="p-16"></a>
### ✍️ Practice Problem 16

**(Hard) Cleaning keys:** Merge `orders_p` with `customers_p` (`cust` ↔ `id`). First show how many orders fail to match; then clean the keys (strip + upper) and merge again with `validate='many_to_one'` and `indicator=True`.

*(Solution in the **Practice Solutions** section at the end.)*

In [33]:
# ✍️ Practice Problem 16 — write your solution here

### Solution 16

In [34]:
before = pd.merge(orders_p, customers_p, left_on='cust', right_on='id', how='left', indicator=True)
print('Unmatched before cleaning:', (before['_merge'] == 'left_only').sum(), before.loc[before['_merge'] == 'left_only', 'cust'].tolist())
orders_clean = orders_p.assign(cust=orders_p['cust'].str.strip().str.upper())
after = pd.merge(orders_clean, customers_p, left_on='cust', right_on='id', how='left', validate='many_to_one', indicator=True)
print('Unmatched after cleaning:', (after['_merge'] == 'left_only').sum(), after.loc[after['_merge'] == 'left_only', 'cust'].tolist())
after

Unmatched before cleaning: 3 ['c3', 'C4 ', 'C9']
Unmatched after cleaning: 1 ['C9']

   order_id cust  prod  qty   id  name     city     _merge
0         1   C1   101    1   C1   Ali   Lahore       both
1         2   C2   102    2   C2  Sara  Karachi       both
2         3   C3   101    1   C3  Omar   Lahore       both
3         4   C1   103    3   C1   Ali   Lahore       both
4         5   C4   102    1   C4  Hina   Multan       both
5         6   C2   104    2   C2  Sara  Karachi       both
6         7   C9   101    1  NaN   NaN      NaN  left_only
7         8   C3   103    1   C3  Omar   Lahore       both

**Explanation:** 'c3' and 'C4 ' failed only because of case/spaces. After cleaning, only C9 is unmatched — a customer that truly doesn't exist.

<a id="p-17"></a>
### ✍️ Practice Problem 17

**(Hard) Data-type mismatch:** Merge the cleaned orders with `products_p` (`prod` ↔ `prod_id`). Fix the type mismatch and compute `revenue = qty × price`.

*(Solution in the **Practice Solutions** section at the end.)*

In [35]:
# ✍️ Practice Problem 17 — write your solution here

### Solution 17

In [36]:
print(orders_clean['prod'].dtype, 'vs', products_p['prod_id'].dtype)
products_fixed = products_p.assign(prod_id=products_p['prod_id'].astype(int))
full17 = orders_clean.merge(products_fixed, left_on='prod', right_on='prod_id', how='left', validate='many_to_one')
full17['revenue'] = full17['qty'] * full17['price']
full17[['order_id', 'cust', 'product', 'qty', 'price', 'revenue']]

int64 vs str

   order_id cust product  qty  price  revenue
0         1   C1     Pen    1     20       20
1         2   C2    Book    2    300      600
2         3   C3     Pen    1     20       20
3         4   C1     Bag    3   1200     3600
4         5   C4    Book    1    300      300
5         6   C2    Lamp    2    900     1800
6         7   C9     Pen    1     20       20
7         8   C3     Bag    1   1200     1200

**Explanation:** int64 vs text keys raise a ValueError; converting `prod_id` to int makes them compatible.

<a id="p-18"></a>
### ✍️ Practice Problem 18

**(Hard) Merge after aggregation:** Build a customer summary (orders, total quantity, total revenue) by aggregating first and then merging onto `customers_p` (all customers, zeros for those without orders).

*(Solution in the **Practice Solutions** section at the end.)*

In [37]:
# ✍️ Practice Problem 18 — write your solution here

### Solution 18

In [38]:
summary18 = full17.groupby('cust').agg(orders=('order_id', 'count'), total_qty=('qty', 'sum'), revenue=('revenue', 'sum')).reset_index()
cust_summary = customers_p.merge(summary18, left_on='id', right_on='cust', how='left').drop(columns='cust')
cust_summary[['orders', 'total_qty', 'revenue']] = cust_summary[['orders', 'total_qty', 'revenue']].fillna(0).astype(int)
cust_summary

   id   name     city  orders  total_qty  revenue
0  C1    Ali   Lahore       2          4     3620
1  C2   Sara  Karachi       2          4     2400
2  C3   Omar   Lahore       2          2     1220
3  C4   Hina   Multan       1          1      300
4  C5  Bilal  Karachi       0          0        0

**Explanation:** Aggregating first gives exactly one row per customer, so the merge is one-to-one and cannot multiply rows. Bilal (C5) gets zeros.

<a id="p-19"></a>
### ✍️ Practice Problem 19

**(Hard) merge_asof:** For each payment in `payments_p`, attach the latest exchange rate valid **on or before** the payment date from `rates_p`, and compute the PKR amount.

*(Solution in the **Practice Solutions** section at the end.)*

In [39]:
# ✍️ Practice Problem 19 — write your solution here

### Solution 19

In [40]:
asof19 = pd.merge_asof(payments_p.sort_values('Date'), rates_p.sort_values('Date'), on='Date', direction='backward')
asof19['PKR'] = asof19['USD'] * asof19['Rate']
asof19

        Date  USD   Rate      PKR
0 2025-01-05  100  279.0  27900.0
1 2025-01-10   80  280.2  22416.0
2 2025-01-12   50  280.2  14010.0
3 2025-01-25  200  281.0  56200.0

**Explanation:** `merge_asof` needs both tables sorted by `Date`; `direction='backward'` picks the most recent rate on or before each payment (Jan 10 uses the Jan 10 rate).

<a id="p-20"></a>
### ✍️ Practice Problem 20

**(Hard) Full pipeline with checks:** Write a function `safe_lookup(left, right, left_key, right_key)` that prints row counts, checks key dtypes and uniqueness on the right, merges with `how='left'`, `validate='many_to_one'`, `indicator=True`, and warns about unmatched rows. Use it to build the full orders + customers + products table.

*(Solution in the **Practice Solutions** section at the end.)*

In [41]:
# ✍️ Practice Problem 20 — write your solution here

### Solution 20

In [42]:
def safe_lookup(left, right, left_key, right_key):
    print(f'→ {left_key} ↔ {right_key}: left rows={len(left)}, right rows={len(right)}')
    if left[left_key].dtype != right[right_key].dtype:
        print(f'  ⚠ dtype mismatch {left[left_key].dtype} vs {right[right_key].dtype} → converting right key')
        right = right.assign(**{right_key: right[right_key].astype(left[left_key].dtype)})
    if not right[right_key].is_unique:
        raise ValueError(f'right key {right_key} is not unique — fix the lookup table first')
    out = pd.merge(left, right, left_on=left_key, right_on=right_key, how='left', validate='many_to_one', indicator=True)
    unmatched = (out['_merge'] == 'left_only').sum()
    if unmatched:
        print(f'  ⚠ {unmatched} unmatched row(s): {out.loc[out["_merge"] == "left_only", left_key].tolist()}')
    assert len(out) == len(left), 'row count changed!'
    return out.drop(columns='_merge')

full20 = (orders_p.assign(cust=orders_p['cust'].str.strip().str.upper())
          .pipe(safe_lookup, customers_p, 'cust', 'id')
          .pipe(safe_lookup, products_p, 'prod', 'prod_id'))
full20['revenue'] = full20['qty'] * full20['price']
full20

→ cust ↔ id: left rows=8, right rows=5

  ⚠ 1 unmatched row(s): ['C9']
→ prod ↔ prod_id: left rows=8, right rows=4
  ⚠ dtype mismatch int64 vs str → converting right key

   order_id cust  prod  qty   id  name     city  prod_id product  price  revenue
0         1   C1   101    1   C1   Ali   Lahore      101     Pen     20       20
1         2   C2   102    2   C2  Sara  Karachi      102    Book    300      600
2         3   C3   101    1   C3  Omar   Lahore      101     Pen     20       20
3         4   C1   103    3   C1   Ali   Lahore      103     Bag   1200     3600
4         5   C4   102    1   C4  Hina   Multan      102    Book    300      300
5         6   C2   104    2   C2  Sara  Karachi      104    Lamp    900     1800
6         7   C9   101    1  NaN   NaN      NaN      101     Pen     20       20
7         8   C3   103    1   C3  Omar   Lahore      103     Bag   1200     1200

**Explanation:** The helper bundles the checklist from Section 18. `.pipe` lets us chain it like a normal method.

<a id="p-21"></a>
---
# Final Project — E-Commerce Database Integration

**Scenario:** an online store exports four tables from different systems. They contain realistic problems (duplicate keys, unknown IDs, different key names, mismatched data types, missing payments). Build one clean analytical DataFrame and analyse it.

## Create the four tables

In [43]:
rng = np.random.default_rng(10)

# ---------- Customers (60 rows + 1 duplicate) ----------
first = ['Ali', 'Sara', 'Omar', 'Hina', 'Bilal', 'Zara', 'Usman', 'Ayesha', 'Hamza', 'Fatima', 'Imran', 'Mariam']
last = ['Khan', 'Ahmed', 'Farooq', 'Malik', 'Raza', 'Iqbal', 'Noor', 'Butt']
customers = pd.DataFrame({
    'Customer_ID': [f'C{100 + i}' for i in range(60)],
    'Name': [f'{rng.choice(first)} {rng.choice(last)}' for _ in range(60)],
    'Gender': rng.choice(['Male', 'Female'], 60),
    'Age': rng.integers(18, 65, 60),
    'City': rng.choice(['Lahore', 'Karachi', 'Islamabad', 'Multan', 'Peshawar'], 60, p=[0.3, 0.3, 0.2, 0.1, 0.1]),
})
customers = pd.concat([customers, customers.iloc[[7]].assign(City='Karachi')], ignore_index=True)   # C107 twice (moved city)

# ---------- Products (32 rows) ----------
cat_price = {'Electronics': (5000, 150000), 'Fashion': (800, 9000), 'Home': (1500, 40000), 'Books': (500, 3000)}
categories = rng.choice(list(cat_price), 32, p=[0.3, 0.3, 0.2, 0.2])
products = pd.DataFrame({
    'Product_ID': [f'P{200 + i}' for i in range(32)],
    'Product': [f'{c[:4]}-Item-{i}' for i, c in enumerate(categories)],
    'Category': categories,
    'Price': [int(rng.integers(*cat_price[c]) // 10 * 10) for c in categories],
})

# ---------- Orders (160 rows, 2024-10 .. 2025-03) ----------
n_orders = 160
orders = pd.DataFrame({
    'Order_ID': np.arange(5000, 5000 + n_orders),
    'Customer_ID': rng.choice(customers['Customer_ID'].unique(), n_orders),
    'Product_ID': rng.choice(products['Product_ID'], n_orders),
    'Order_Date': pd.to_datetime('2024-10-01') + pd.to_timedelta(rng.integers(0, 182, n_orders), unit='D'),
    'Quantity': rng.integers(1, 5, n_orders),
})
orders.loc[[5, 40], 'Customer_ID'] = ['C999', 'C998']          # unknown customers
orders.loc[[12], 'Product_ID'] = ['P999']                        # unknown product
orders = orders.sort_values('Order_Date').reset_index(drop=True)

# ---------- Payments (from another system: key has a DIFFERENT NAME and TYPE) ----------
paid = orders.sample(150, random_state=3)
payments = pd.DataFrame({
    'order_ref': paid['Order_ID'].astype(str).values,          # text instead of int!
    'Payment_Method': rng.choice(['Card', 'Cash on Delivery', 'Wallet', 'Bank Transfer'], 150, p=[0.4, 0.35, 0.15, 0.1]),
    'Payment_Status': rng.choice(['Paid', 'Pending', 'Failed'], 150, p=[0.85, 0.1, 0.05]),
})
payments = pd.concat([payments,
                      pd.DataFrame({'order_ref': ['9001', '9002'], 'Payment_Method': ['Card', 'Wallet'], 'Payment_Status': ['Paid', 'Paid']}),
                      payments.iloc[[0]]], ignore_index=True)   # 2 payments for unknown orders + 1 duplicate payment

for name, t in [('customers', customers), ('products', products), ('orders', orders), ('payments', payments)]:
    print(f'{name:<10} {t.shape}')

customers  (61, 5)
products   (32, 4)
orders     (160, 5)
payments   (153, 3)

## Step 1 — Data validation (types, missing values, key formats)

In [44]:
def profile(name, df, key):
    print(f'{name:<10} rows={len(df):>3} | key={key} dtype={df[key].dtype} | key unique={df[key].is_unique} | '
          f'missing keys={df[key].isna().sum()} | missing cells={df.isna().sum().sum()}')

profile('customers', customers, 'Customer_ID')
profile('products', products, 'Product_ID')
profile('orders', orders, 'Order_ID')
profile('payments', payments, 'order_ref')
print('\norders.Order_ID dtype:', orders['Order_ID'].dtype, '| payments.order_ref dtype:', payments['order_ref'].dtype, '→ mismatch!')

customers  rows= 61 | key=Customer_ID dtype=str | key unique=False | missing keys=0 | missing cells=0
products   rows= 32 | key=Product_ID dtype=str | key unique=True | missing keys=0 | missing cells=0
orders     rows=160 | key=Order_ID dtype=int64 | key unique=True | missing keys=0 | missing cells=0
payments   rows=153 | key=order_ref dtype=str | key unique=False | missing keys=0 | missing cells=0

orders.Order_ID dtype: int64 | payments.order_ref dtype: str → mismatch!

## Step 2 — Duplicate-key checks

In [45]:
dup_cust = customers[customers['Customer_ID'].duplicated(keep=False)]
print('Duplicated customers:'); print(dup_cust, '\n')
vc = payments['order_ref'].value_counts()
print('Orders with more than one payment record:', vc[vc > 1].to_dict())

# Fix: keep the LAST customer record (most recent info) and one payment per order
customers = customers.drop_duplicates(subset='Customer_ID', keep='last').reset_index(drop=True)
payments = payments.drop_duplicates().reset_index(drop=True)
payments['Order_ID'] = payments['order_ref'].astype(int)          # fix the dtype for merging
print('\nAfter fixing → customers unique:', customers['Customer_ID'].is_unique, '| payments unique:', payments['Order_ID'].is_unique)

Duplicated customers:
   Customer_ID        Name  Gender  Age     City
7         C107  Bilal Noor  Female   47   Multan
60        C107  Bilal Noor  Female   47  Karachi

Orders with more than one payment record: {'5004': 2}

After fixing → customers unique: True | payments unique: True

## Step 3 — Inner join: orders that have both a known customer and a known product

In [46]:
inner = (orders.merge(customers, on='Customer_ID', how='inner', validate='many_to_one')
               .merge(products, on='Product_ID', how='inner', validate='many_to_one'))
print(f'orders: {len(orders)} → inner join: {len(inner)} rows (orders with unknown customer/product dropped)')

orders: 160 → inner join: 157 rows (orders with unknown customer/product dropped)

## Step 4 — Left join: keep every order (main fact table), enrich with customers and products

In [47]:
left = (orders.merge(customers, on='Customer_ID', how='left', validate='many_to_one')
              .merge(products, on='Product_ID', how='left', validate='many_to_one'))
print(f'Rows: {len(left)} (= orders) | orders missing customer info: {left["Name"].isna().sum()} | missing product info: {left["Product"].isna().sum()}')

Rows: 160 (= orders) | orders missing customer info: 2 | missing product info: 1

## Step 5 — Outer join: reconcile customers and orders

In [48]:
recon = pd.merge(customers[['Customer_ID', 'Name']], orders[['Order_ID', 'Customer_ID']], on='Customer_ID', how='outer', indicator=True)
print(recon['_merge'].value_counts())
print('Customers who never ordered:', recon.loc[recon['_merge'] == 'left_only', 'Customer_ID'].nunique())
print('Orders from unknown customers:', recon.loc[recon['_merge'] == 'right_only', 'Order_ID'].astype(int).tolist())

_merge
both          158
left_only       3
right_only      2
Name: count, dtype: int64
Customers who never ordered: 3
Orders from unknown customers: [5040, 5005]

## Step 6 — Multiple-key join: city × category promotions

In [49]:
promotions = pd.DataFrame({'City': ['Lahore', 'Lahore', 'Karachi', 'Islamabad', 'Multan'],
                           'Category': ['Electronics', 'Fashion', 'Electronics', 'Home', 'Books'],
                           'Promo_Discount': [0.10, 0.15, 0.05, 0.20, 0.25]})
left = left.merge(promotions, on=['City', 'Category'], how='left', validate='many_to_one')
left['Promo_Discount'] = left['Promo_Discount'].fillna(0)
print('Orders receiving a promotion:', (left['Promo_Discount'] > 0).sum())
print(left.loc[left['Promo_Discount'] > 0, ['Order_ID', 'City', 'Category', 'Promo_Discount']].head())

Orders receiving a promotion: 52
   Order_ID       City     Category  Promo_Discount
1      5055     Lahore      Fashion            0.15
3      5023     Lahore      Fashion            0.15
4      5070    Karachi  Electronics            0.05
5      5064  Islamabad         Home            0.20
6      5107     Multan        Books            0.25

## Step 7 — Merge with different column names: payments (`order_ref`) — Step 8 — merge indicator — Step 9 — merge validation

In [50]:
pay_check = pd.merge(orders[['Order_ID']], payments[['order_ref', 'Payment_Method', 'Payment_Status']].assign(order_ref=lambda d: d['order_ref'].astype(int)),
                     left_on='Order_ID', right_on='order_ref', how='outer', indicator=True, validate='one_to_one')
print(pay_check['_merge'].value_counts())
print('Orders without a payment record:', pay_check.loc[pay_check['_merge'] == 'left_only', 'Order_ID'].astype(int).tolist())
print('Payments for unknown orders    :', pay_check.loc[pay_check['_merge'] == 'right_only', 'order_ref'].astype(int).tolist())

left = left.merge(payments[['Order_ID', 'Payment_Method', 'Payment_Status']], on='Order_ID', how='left', validate='one_to_one')
left['Payment_Status'] = left['Payment_Status'].fillna('No Record')
print('\nRows still equal to orders:', len(left) == len(orders))

_merge
both          150
left_only      10
right_only      2
Name: count, dtype: int64
Orders without a payment record: [5017, 5024, 5033, 5092, 5109, 5119, 5124, 5125, 5128, 5147]
Payments for unknown orders    : [9001, 9002]

Rows still equal to orders: True

## Step 10 — Join using indexes: attach per-product sales totals

In [51]:
prod_idx = products.set_index('Product_ID')
units_per_product = orders.groupby('Product_ID')['Quantity'].sum().rename('Units_Sold')
product_stats = prod_idx.join(units_per_product, how='left').fillna({'Units_Sold': 0})
product_stats['Units_Sold'] = product_stats['Units_Sold'].astype(int)
product_stats.sort_values('Units_Sold', ascending=False).head()

                 Product Category  Price  Units_Sold
Product_ID
P204         Fash-Item-4  Fashion   2600          26
P225        Fash-Item-25  Fashion   1650          22
P226        Book-Item-26    Books   2810          21
P229        Fash-Item-29  Fashion   2020          19
P230        Fash-Item-30  Fashion   3780          18

## Step 11 — Concatenate monthly datasets

In [52]:
# Pretend each month arrived as a separate file
monthly_files = {str(p): g.drop(columns='Order_Month') for p, g in orders.assign(Order_Month=orders['Order_Date'].dt.to_period('M')).groupby('Order_Month')}
print({k: len(v) for k, v in monthly_files.items()})
recombined = pd.concat(monthly_files.values(), keys=monthly_files.keys(), names=['Month', 'Row']).reset_index(level='Month').reset_index(drop=True)
print('Recombined rows:', len(recombined), '| equals original:', len(recombined) == len(orders))
recombined.head()

{'2024-10': 27, '2024-11': 30, '2024-12': 27, '2025-01': 29, '2025-02': 27, '2025-03': 20}

Recombined rows: 160 | equals original: True

     Month  Order_ID Customer_ID Product_ID Order_Date  Quantity
0  2024-10      5033        C114       P220 2024-10-01         3
1  2024-10      5055        C143       P228 2024-10-02         1
2  2024-10      5027        C105       P229 2024-10-03         4
3  2024-10      5023        C155       P201 2024-10-04         1
4  2024-10      5070        C146       P210 2024-10-06         2

## Step 12 — Combine all tables into one analytical DataFrame · Step 13 — Revenue

In [53]:
analytics = left.copy()
analytics['Gross_Revenue'] = analytics['Quantity'] * analytics['Price']
analytics['Revenue'] = (analytics['Gross_Revenue'] * (1 - analytics['Promo_Discount'])).round(0)
analytics['Month'] = analytics['Order_Date'].dt.to_period('M')
cols = ['Order_ID', 'Order_Date', 'Month', 'Customer_ID', 'Name', 'Gender', 'Age', 'City', 'Product_ID', 'Product', 'Category',
        'Price', 'Quantity', 'Promo_Discount', 'Gross_Revenue', 'Revenue', 'Payment_Method', 'Payment_Status']
analytics = analytics[cols]
print(analytics.shape)
analytics.head()

(160, 18)

,Order_ID,Order_Date,Month,Customer_ID,Name,Gender,Age,City,Product_ID,Product,Category,Price,Quantity,Promo_Discount,Gross_Revenue,Revenue,Payment_Method,Payment_Status
0,5033,2024-10-01,2024-10,C114,Imran Noor,Male,46.0,Peshawar,P220,Elec-Item-20,Electronics,21710.0,3,0.00,65130.0,65130.0,NaN,No Record
1,5055,2024-10-02,2024-10,C143,Sara Ahmed,Male,20.0,Lahore,P228,Fash-Item-28,Fashion,5310.0,1,0.15,5310.0,4514.0,Cash on Delivery,Paid
2,5027,2024-10-03,2024-10,C105,Sara Ahmed,Male,20.0,Karachi,P229,Fash-Item-29,Fashion,2020.0,4,0.00,8080.0,8080.0,Cash on Delivery,Paid
3,5023,2024-10-04,2024-10,C155,Usman Noor,Male,63.0,Lahore,P201,Fash-Item-1,Fashion,1900.0,1,0.15,1900.0,1615.0,Bank Transfer,Paid
4,5070,2024-10-06,2024-10,C146,Zara Raza,Female,58.0,Karachi,P210,Elec-Item-10,Electronics,140690.0,2,0.05,281380.0,267311.0,Wallet,Failed

## Step 14 — Analyse customers

In [54]:
valid = analytics.dropna(subset=['Name', 'Product'])            # only fully matched orders for analysis
cust_stats = valid.groupby(['Customer_ID', 'Name']).agg(Orders=('Order_ID', 'count'), Revenue=('Revenue', 'sum')).reset_index()
all_customers = customers.merge(cust_stats[['Customer_ID', 'Orders', 'Revenue']], on='Customer_ID', how='left').fillna({'Orders': 0, 'Revenue': 0})
print('Customers without orders:', (all_customers['Orders'] == 0).sum())
print('Top 5 customers:'); print(all_customers.sort_values('Revenue', ascending=False).head()[['Customer_ID', 'Name', 'City', 'Orders', 'Revenue']])

Customers without orders: 3
Top 5 customers:
   Customer_ID          Name      City  Orders   Revenue
14        C115     Sara Butt  Peshawar     6.0  997180.0
12        C113   Mariam Noor    Multan     4.0  571582.0
25        C126  Usman Farooq   Karachi     4.0  511662.0
43        C144    Zara Malik    Multan     5.0  495150.0
20        C121     Zara Noor    Lahore     5.0  484923.0

## Step 15 — Analyse products · Step 16 — Analyse cities · Step 17 — Analyse payment methods

In [55]:
print('Revenue by category:'); print(valid.groupby('Category')['Revenue'].sum().sort_values(ascending=False), '\n')
print('Top 5 products:'); print(valid.groupby(['Product_ID', 'Product'])['Revenue'].sum().nlargest(5), '\n')
print('City summary:')
print(valid.groupby('City').agg(Orders=('Order_ID', 'count'), Customers=('Customer_ID', 'nunique'), Revenue=('Revenue', 'sum'))
      .sort_values('Revenue', ascending=False), '\n')
print('Payment methods:')
print(pd.crosstab(valid['Payment_Method'].fillna('No Record'), valid['Payment_Status'], margins=True))

Revenue by category:
Category
Electronics    7245108.0
Home            754992.0
Fashion         659898.0
Books            73150.0
Name: Revenue, dtype: float64

Top 5 products:

Product_ID  Product
P210        Elec-Item-10    1885246.0
P215        Elec-Item-15    1540452.0
P202        Elec-Item-2     1046247.0
P211        Elec-Item-11     932285.0
P223        Elec-Item-23     765297.0
Name: Revenue, dtype: float64

City summary:
           Orders  Customers    Revenue
City
Karachi        51         18  2712673.0
Peshawar       31         10  2040770.0
Lahore         41         15  1878863.0
Multan         17          7  1284040.0
Islamabad      17          7   816802.0

Payment methods:

Payment_Status    Failed  No Record  Paid  Pending  All
Payment_Method
Bank Transfer          0          0    17        0   17
Card                   5          0    45        7   57
Cash on Delivery       2          0    44        8   54
No Record              0         10     0        0   10
Wallet                 4          0    11        4   19
All                   11         10   117       19  157

## Step 18 — Identify unmatched records · Step 19 — Detect data-quality problems

In [56]:
quality = pd.Series({
    'Duplicate customer IDs found (fixed)': 1,
    'Duplicate payment rows found (fixed)': 1,
    'Orders with unknown customer': analytics['Name'].isna().sum(),
    'Orders with unknown product': analytics['Product'].isna().sum(),
    'Orders without payment record': (analytics['Payment_Status'] == 'No Record').sum(),
    'Payments for unknown orders': (pay_check['_merge'] == 'right_only').sum(),
    'Failed payments': (analytics['Payment_Status'] == 'Failed').sum(),
    'Customers who never ordered': (all_customers['Orders'] == 0).sum(),
    'Products never sold': (product_stats['Units_Sold'] == 0).sum(),
    'Key dtype mismatch (payments.order_ref text vs int)': 'fixed with astype(int)',
})
quality.to_frame('Count / status')

                                                            Count / status
Duplicate customer IDs found (fixed)                                     1
Duplicate payment rows found (fixed)                                     1
Orders with unknown customer                                             2
Orders with unknown product                                              1
Orders without payment record                                           10
Payments for unknown orders                                              2
Failed payments                                                         12
Customers who never ordered                                              3
Products never sold                                                      0
Key dtype mismatch (payments.order_ref text vs ...  fixed with astype(int)

## Step 20 — Final analytical DataFrame

In [57]:
final = analytics[analytics['Name'].notna() & analytics['Product'].notna()].reset_index(drop=True)
final['Paid'] = final['Payment_Status'] == 'Paid'
print(f'Final analytical table: {final.shape[0]} orders × {final.shape[1]} columns | no missing customer/product info')
print(f"Total revenue: {final['Revenue'].sum():,.0f} PKR | paid revenue: {final.loc[final['Paid'], 'Revenue'].sum():,.0f} PKR")
print('\nMonthly revenue:'); print(final.groupby('Month')['Revenue'].sum())
final.head()

Final analytical table: 157 orders × 19 columns | no missing customer/product info
Total revenue: 8,733,148 PKR | paid revenue: 6,770,066 PKR

Monthly revenue:
Month
2024-10    1301342.0
2024-11    2310183.0
2024-12    1927308.0
2025-01    1703058.0
2025-02     746165.0
2025-03     745092.0
Freq: M, Name: Revenue, dtype: float64

,Order_ID,Order_Date,Month,Customer_ID,Name,Gender,Age,City,Product_ID,Product,Category,Price,Quantity,Promo_Discount,Gross_Revenue,Revenue,Payment_Method,Payment_Status,Paid
0,5033,2024-10-01,2024-10,C114,Imran Noor,Male,46.0,Peshawar,P220,Elec-Item-20,Electronics,21710.0,3,0.00,65130.0,65130.0,NaN,No Record,False
1,5055,2024-10-02,2024-10,C143,Sara Ahmed,Male,20.0,Lahore,P228,Fash-Item-28,Fashion,5310.0,1,0.15,5310.0,4514.0,Cash on Delivery,Paid,True
2,5027,2024-10-03,2024-10,C105,Sara Ahmed,Male,20.0,Karachi,P229,Fash-Item-29,Fashion,2020.0,4,0.00,8080.0,8080.0,Cash on Delivery,Paid,True
3,5023,2024-10-04,2024-10,C155,Usman Noor,Male,63.0,Lahore,P201,Fash-Item-1,Fashion,1900.0,1,0.15,1900.0,1615.0,Bank Transfer,Paid,True
4,5070,2024-10-06,2024-10,C146,Zara Raza,Female,58.0,Karachi,P210,Elec-Item-10,Electronics,140690.0,2,0.05,281380.0,267311.0,Wallet,Failed,False

## Why each combining method was selected

| Step | Method | Why this method |
|---|---|---|
| Enrich orders with customers/products | `merge(how='left', validate='many_to_one')` | Orders are the **fact table** (one row per event) — keep every order and **look up** details by key; validation guarantees the lookup can't multiply rows |
| Only complete orders (Step 3) | `merge(how='inner')` | When analysis requires both sides to exist |
| Reconciliation (Steps 5, 7–8) | `merge(how='outer', indicator=True)` | Shows what exists on **both** sides and what is missing on each |
| Promotions (Step 6) | `merge(on=['City', 'Category'])` | A promotion is identified by the **pair** (composite key) |
| Payments (Step 7) | `merge(left_on=..., right_on=...)` after `astype(int)` | Different key **name** and **type** in the payment system |
| Product stats (Step 10) | `DataFrame.join()` | Both sides were already **indexed** by Product_ID (a groupby result) |
| Monthly files (Step 11) | `pd.concat(..., keys=...)` | Same columns, different rows → **stacking**, not matching |
| Customer summary (Step 14) | aggregate → `merge` | Aggregating first keeps the merge one-to-one and avoids duplication |

---
# Final Cheat Sheet

## `pd.concat()` — stack / glue
```python
pd.concat([df1, df2])                                   # stack rows (axis=0)
pd.concat([df1, df2], ignore_index=True)                # fresh 0..n-1 index
pd.concat([jan, feb], keys=['Jan', 'Feb'])              # remember the source (MultiIndex)
pd.concat([df1, df2], join='inner')                     # only shared columns
pd.concat([df1, df2], axis=1)                           # side by side, aligned on INDEX
pd.concat(list_of_dfs, ignore_index=True)               # many files: build a list, concat once
```

## `pd.merge()` — match on key columns
```python
pd.merge(left, right, on='key', how='inner')            # 'inner' | 'left' | 'right' | 'outer' | 'cross'
pd.merge(left, right, left_on='cust_id', right_on='id') # different key names
pd.merge(left, right, on=['k1', 'k2'])                  # composite key
pd.merge(left, right, on='key', suffixes=('_a', '_b'))  # overlapping column names
pd.merge(left, right, on='key', validate='many_to_one') # '1:1' | '1:m' | 'm:1' | 'm:m'
pd.merge(left, right, on='key', how='outer', indicator=True)   # _merge: both / left_only / right_only
pd.merge(left, right, left_on='key', right_index=True)  # column ↔ index
pd.merge_asof(a.sort_values('t'), b.sort_values('t'), on='t', direction='backward')   # nearest earlier match
pd.merge_ordered(a, b, on='date', fill_method='ffill')  # ordered merge with forward fill
```

| how | Keeps |
|---|---|
| `inner` | Keys in **both** |
| `left` | All **left** keys |
| `right` | All **right** keys |
| `outer` | **All** keys from both |

## `df.join()` — match on the index
```python
left.join(right)                          # index ↔ index, how='left'
left.join(right, how='inner'/'outer'/'right')
left.join(right, on='key')                # left column ↔ right index
left.join(right, lsuffix='_l', rsuffix='_r')
left.join([df2, df3])                     # several indexed tables
```

## Before every merge
```text
✔ key dtypes match          ✔ keys cleaned (strip/case/zeros)   ✔ lookup keys unique (is_unique)
✔ no missing keys           ✔ validate= the relationship         ✔ compare row counts before/after
✔ indicator=True to find unmatched rows                         ✔ check new NaNs after left joins
```

🎉 **You have completed Topic 10 — Combining DataFrames with Pandas!**

---
## 🎯 Quiz 2 time!

You have finished Topics 06–10. Test yourself: **[🎯 Quiz 2 — Topics 06–10](../Quiz_2_Topics_06-10/Quiz_2.ipynb)** — 20 multiple-choice questions + 5 coding tasks, checked automatically.