# Topic 09 — Pandas Data Manipulation — ✍️ Practice & Solutions

This notebook has every **practice problem** for Topic 09, each followed by its **✅ solution**.

**How to use it**
1. Read the lesson first: [Topic_09_Lesson.ipynb](Topic_09_Lesson.ipynb).
2. Read a problem and write your answer in the code cell under it.
3. Only then scroll down to the ✅ solution and compare.
4. Stuck or confused? Go back to the matching lesson section — every solution uses only what the lesson teaches.

> 📚 **Course navigation** — you are in **Topic 09: Pandas Data Manipulation**
> ⬅️ Previous: [Topic 08 — Data Visualization](../Topic_08_Data_Visualization/Topic_08_Lesson.ipynb)  ·  ➡️ Next: [Topic 10 — Combining DataFrames](../Topic_10_Combining_DataFrames/Topic_10_Lesson.ipynb)  ·  🗂️ [All topics](../Topic_00_All_Topics_Index.ipynb)

<details><summary>Full course sequence (click to expand)</summary>

| # | Topic | Lesson | Practice & Solutions |
|---|---|---|---|
| 01 | Python Basics | [📖 Lesson](../Topic_01_Python_Basics/Topic_01_Lesson.ipynb) | [✍️ Practice](../Topic_01_Python_Basics/Topic_01_Practice_Solutions.ipynb) |
| 02 | Pandas DataFrame Basics | [📖 Lesson](../Topic_02_Pandas_DataFrame_Basics/Topic_02_Lesson.ipynb) | [✍️ Practice](../Topic_02_Pandas_DataFrame_Basics/Topic_02_Practice_Solutions.ipynb) |
| 03 | Handling Missing Values | [📖 Lesson](../Topic_03_Handling_Missing_Values/Topic_03_Lesson.ipynb) | [✍️ Practice](../Topic_03_Handling_Missing_Values/Topic_03_Practice_Solutions.ipynb) |
| 04 | Normalization & Standardization | [📖 Lesson](../Topic_04_Normalization_Standardization/Topic_04_Lesson.ipynb) | [✍️ Practice](../Topic_04_Normalization_Standardization/Topic_04_Practice_Solutions.ipynb) |
| 05 | Detecting & Treating Outliers | [📖 Lesson](../Topic_05_Outliers/Topic_05_Lesson.ipynb) | [✍️ Practice](../Topic_05_Outliers/Topic_05_Practice_Solutions.ipynb) |
| 06 | Encoding Techniques | [📖 Lesson](../Topic_06_Encoding_Techniques/Topic_06_Lesson.ipynb) | [✍️ Practice](../Topic_06_Encoding_Techniques/Topic_06_Practice_Solutions.ipynb) |
| 07 | Exploratory Data Analysis (EDA) | [📖 Lesson](../Topic_07_Exploratory_Data_Analysis/Topic_07_Lesson.ipynb) | [✍️ Practice](../Topic_07_Exploratory_Data_Analysis/Topic_07_Practice_Solutions.ipynb) |
| 08 | Data Visualization | [📖 Lesson](../Topic_08_Data_Visualization/Topic_08_Lesson.ipynb) | [✍️ Practice](../Topic_08_Data_Visualization/Topic_08_Practice_Solutions.ipynb) |
| **▶ 09 ◀** | **Pandas Data Manipulation** | [📖 Lesson](../Topic_09_Pandas_Data_Manipulation/Topic_09_Lesson.ipynb) | [✍️ Practice](../Topic_09_Pandas_Data_Manipulation/Topic_09_Practice_Solutions.ipynb) |
| 10 | Combining DataFrames | [📖 Lesson](../Topic_10_Combining_DataFrames/Topic_10_Lesson.ipynb) | [✍️ Practice](../Topic_10_Combining_DataFrames/Topic_10_Practice_Solutions.ipynb) |
| 11 | Feature Engineering | [📖 Lesson](../Topic_11_Feature_Engineering/Topic_11_Lesson.ipynb) | [✍️ Practice](../Topic_11_Feature_Engineering/Topic_11_Practice_Solutions.ipynb) |
| 11b | KBinsDiscretizer (Discretization) | [📖 Lesson](../Topic_11b_KBinsDiscretizer/Topic_11b_Lesson.ipynb) | [✍️ Practice](../Topic_11b_KBinsDiscretizer/Topic_11b_Practice_Solutions.ipynb) |
| 12 | Correlation & Multicollinearity | [📖 Lesson](../Topic_12_Correlation_Multicollinearity/Topic_12_Lesson.ipynb) | [✍️ Practice](../Topic_12_Correlation_Multicollinearity/Topic_12_Practice_Solutions.ipynb) |
| 13 | Data Transformation & Skewness | [📖 Lesson](../Topic_13_Data_Transformation_Skewness/Topic_13_Lesson.ipynb) | [✍️ Practice](../Topic_13_Data_Transformation_Skewness/Topic_13_Practice_Solutions.ipynb) |
| 14 | Statistics for Data Science | [📖 Lesson](../Topic_14_Statistics_for_Data_Science/Topic_14_Lesson.ipynb) | [✍️ Practice](../Topic_14_Statistics_for_Data_Science/Topic_14_Practice_Solutions.ipynb) |
| 15 | Probability for Data Science & ML | [📖 Lesson](../Topic_15_Probability_for_Data_Science_ML/Topic_15_Lesson.ipynb) | [✍️ Practice](../Topic_15_Probability_for_Data_Science_ML/Topic_15_Practice_Solutions.ipynb) |
| 16 | Feature Selection | [📖 Lesson](../Topic_16_Feature_Selection/Topic_16_Lesson.ipynb) | [✍️ Practice](../Topic_16_Feature_Selection/Topic_16_Practice_Solutions.ipynb) |
| 17 | Machine Learning | [📖 Lesson](../Topic_17_Machine_Learning/Topic_17_Lesson.ipynb) | [✍️ Practice](../Topic_17_Machine_Learning/Topic_17_Practice_Solutions.ipynb) |

</details>

## 📋 Practice Index

**21 problems** — each one is followed by your answer cell and then its ✅ solution. Click a problem to jump to it.

- [✍️ Practice Problem 1](#p-1)
- [✍️ Practice Problem 2](#p-2)
- [✍️ Practice Problem 3](#p-3)
- [✍️ Practice Problem 4](#p-4)
- [✍️ Practice Problem 5](#p-5)
- [✍️ Practice Problem 6](#p-6)
- [✍️ Practice Problem 7](#p-7)
- [✍️ Practice Problem 8](#p-8)
- [✍️ Practice Problem 9](#p-9)
- [✍️ Practice Problem 10](#p-10)
- [✍️ Practice Problem 11](#p-11)
- [✍️ Practice Problem 12](#p-12)
- [✍️ Practice Problem 13](#p-13)
- [✍️ Practice Problem 14](#p-14)
- [✍️ Practice Problem 15](#p-15)
- [✍️ Practice Problem 16](#p-16)
- [✍️ Practice Problem 17](#p-17)
- [✍️ Practice Problem 18](#p-18)
- [✍️ Practice Problem 19](#p-19)
- [✍️ Practice Problem 20](#p-20)
- [Final Project — E-Commerce Data Manipulation](#p-21)

> 📖 Lesson for this topic: [Topic_09_Lesson.ipynb](Topic_09_Lesson.ipynb)

### ⚙️ Setup — run this cell first

Some problems use data, variables and functions created in the lesson. This cell quietly runs the whole lesson notebook so they all exist here.

In [1]:
%%capture
# Runs the lesson notebook (output hidden) so its variables exist here
%run ./Topic_09_Lesson.ipynb

---
# Practice Problems (20)

Run the next cell to create the datasets. Each problem has an **empty code cell**; solutions are in the separate **Solutions** section.

In [2]:
rp = np.random.default_rng(9)
n = 60
students = pd.DataFrame({
    'Student_ID': [f'S{100 + i}' for i in range(n)],
    'Name': rp.choice(['  ali', 'SARA ', 'Omar', 'hina', 'Bilal ', 'zara', 'Usman', 'AYESHA'], n),
    'Gender': rp.choice(['M', 'F', 'male', 'female'], n),
    'City': rp.choice(['Lahore', 'Karachi', 'Islamabad', 'Multan'], n),
    'Program': rp.choice(['CS', 'BBA', 'EE', 'Math'], n, p=[0.35, 0.3, 0.2, 0.15]),
    'Math': rp.integers(35, 100, n).astype(float),
    'English': rp.integers(40, 100, n).astype(float),
    'Fee': rp.choice([80000, 95000, 120000, 150000], n),
    'Enroll_Date': pd.to_datetime('2024-08-15') + pd.to_timedelta(rp.integers(0, 400, n), unit='D'),
    'Courses': rp.choice(['Python, Statistics', 'Accounting', 'Python, ML, SQL', 'Calculus, Physics', 'SQL'], n),
})
students.loc[rp.choice(n, 5, replace=False), 'Math'] = np.nan
students.loc[rp.choice(n, 4, replace=False), 'English'] = np.nan
students = pd.concat([students, students.iloc[[3, 7]]], ignore_index=True)       # 2 duplicate rows

daily_sales = pd.DataFrame({'Date': pd.date_range('2025-01-01', periods=30),
                            'Sales': rp.integers(100, 200, 30).astype(float)})
daily_sales.loc[[4, 5, 12, 20], 'Sales'] = np.nan
quarterly = pd.DataFrame({'Region': ['North', 'South', 'East'], 'Q1': [120, 90, 150], 'Q2': [135, 88, 160], 'Q3': [150, 95, 158], 'Q4': [170, 101, 165]})
students.head()

  Student_ID    Name Gender       City Program  Math  English     Fee Enroll_Date             Courses
0       S100    hina   male  Islamabad    Math  85.0     77.0  120000  2025-01-27     Python, ML, SQL
1       S101   Usman      F     Multan      CS  71.0     63.0  120000  2025-05-10     Python, ML, SQL
2       S102  AYESHA   male    Karachi      EE  45.0     93.0  120000  2024-08-21     Python, ML, SQL
3       S103    Omar   male  Islamabad      EE  43.0      NaN   95000  2024-10-05  Python, Statistics
4       S104     ali   male  Islamabad     BBA  84.0     74.0  120000  2025-04-18                 SQL

<a id="p-1"></a>
### ✍️ Practice Problem 1

**Selecting:** From `students`, select the `Name` column as a Series and `['Name', 'City', 'Math']` as a DataFrame. Then use `loc` to get rows with labels 5 to 10 and columns `Name` to `Program`, and `iloc` to get the first 5 rows and the last 3 columns.

*(Solution in the **Practice Solutions** section at the end.)*

In [3]:
# ✍️ Practice Problem 1 — write your solution here

---
---
# Solutions

⚠️ Try the problems first!

### Solution 1

In [4]:
print(type(students['Name']))
print(students[['Name', 'City', 'Math']].head(3))
print(students.loc[5:10, 'Name':'Program'])          # labels 5..10 INCLUDED, columns Name..Program
print(students.iloc[:5, -3:])                        # first 5 rows, last 3 columns

<class 'pandas.Series'>
     Name       City  Math
0    hina  Islamabad  85.0
1   Usman     Multan  71.0
2  AYESHA    Karachi  45.0
      Name  Gender       City Program
5   Bilal        F  Islamabad      CS
6     zara       M    Karachi      EE
7    Usman  female  Islamabad      EE
8     zara  female     Lahore      CS
9     zara       M  Islamabad      CS
10  AYESHA       F    Karachi      EE
      Fee Enroll_Date             Courses
0  120000  2025-01-27     Python, ML, SQL
1  120000  2025-05-10     Python, ML, SQL
2  120000  2024-08-21     Python, ML, SQL
3   95000  2024-10-05  Python, Statistics
4  120000  2025-04-18                 SQL

**Explanation:** `loc` slices by label (inclusive); `iloc` by position (end excluded). Negative positions count from the end.

<a id="p-2"></a>
### ✍️ Practice Problem 2

**`loc` vs `iloc`:** Sort `students` by `Math` (descending). Show the difference between `.loc[0]` and `.iloc[0]` on the sorted DataFrame and explain it in a comment.

*(Solution in the **Practice Solutions** section at the end.)*

In [5]:
# ✍️ Practice Problem 2 — write your solution here

### Solution 2

In [6]:
sorted_s = students.sort_values('Math', ascending=False)
print('loc[0]  →', sorted_s.loc[0, 'Name'], '(the row whose LABEL is 0)')
print('iloc[0] →', sorted_s.iloc[0]['Name'], '(the FIRST row after sorting = best Math score)')
# loc uses the original labels that travel with the rows; iloc uses the current position.

loc[0]  → hina (the row whose LABEL is 0)
iloc[0] → AYESHA (the FIRST row after sorting = best Math score)

**Explanation:** Sorting keeps the original index labels, so label 0 and position 0 are now different rows.

<a id="p-3"></a>
### ✍️ Practice Problem 3

**Filtering (multiple conditions):** Find students from Lahore **or** Karachi who study CS and have `Math` ≥ 80. Solve it once with `&`/`|`/`isin` and once with `query()`.

*(Solution in the **Practice Solutions** section at the end.)*

In [7]:
# ✍️ Practice Problem 3 — write your solution here

### Solution 3

In [8]:
cond = students['City'].isin(['Lahore', 'Karachi']) & (students['Program'] == 'CS') & (students['Math'] >= 80)
a = students[cond]
b = students.query('City in ["Lahore", "Karachi"] and Program == "CS" and Math >= 80')
print(len(a), 'students | same result:', a.equals(b))
a[['Name', 'City', 'Program', 'Math']]

3 students | same result: True

      Name     City Program  Math
40  AYESHA  Karachi      CS  92.0
42    hina   Lahore      CS  83.0
48     ali   Lahore      CS  80.0

**Explanation:** `isin` replaces `(City == 'Lahore') | (City == 'Karachi')`. Each condition is wrapped (or naturally separated by `&`) — parentheses are needed around comparisons.

<a id="p-4"></a>
### ✍️ Practice Problem 4

**`between` and `~`:** Find students whose `English` score is between 60 and 80 (inclusive) and who are **not** in the BBA program.

*(Solution in the **Practice Solutions** section at the end.)*

In [9]:
# ✍️ Practice Problem 4 — write your solution here

### Solution 4

In [10]:
res4 = students[students['English'].between(60, 80) & ~(students['Program'] == 'BBA')]
print(len(res4)); res4[['Name', 'Program', 'English']].head()

12

      Name Program  English
0     hina    Math     77.0
1    Usman      CS     63.0
7    Usman      EE     69.0
10  AYESHA      EE     65.0
12  AYESHA      CS     60.0

**Explanation:** `between` includes both ends; `~` negates the condition. Rows with missing English are excluded (NaN comparisons are False).

<a id="p-5"></a>
### ✍️ Practice Problem 5

**Adding columns:** Add `Average` (mean of Math and English), `Result` = 'Pass' if Average ≥ 50 else 'Fail' (with `np.where`), and `Grade` (A ≥ 85, B ≥ 70, C ≥ 50, else F) with `np.select`.

*(Solution in the **Practice Solutions** section at the end.)*

In [11]:
# ✍️ Practice Problem 5 — write your solution here

### Solution 5

In [12]:
s5 = students.copy()
s5['Average'] = s5[['Math', 'English']].mean(axis=1)                 # row mean (skips NaN)
s5['Result'] = np.where(s5['Average'] >= 50, 'Pass', 'Fail')
s5['Grade'] = np.select([s5['Average'] >= 85, s5['Average'] >= 70, s5['Average'] >= 50], ['A', 'B', 'C'], default='F')
s5[['Name', 'Math', 'English', 'Average', 'Result', 'Grade']].head(8)

     Name  Math  English  Average Result Grade
0    hina  85.0     77.0     81.0   Pass     B
1   Usman  71.0     63.0     67.0   Pass     C
2  AYESHA  45.0     93.0     69.0   Pass     C
3    Omar  43.0      NaN     43.0   Fail     F
4     ali  84.0     74.0     79.0   Pass     B
5  Bilal   62.0     91.0     76.5   Pass     B
6    zara  51.0     90.0     70.5   Pass     B
7   Usman  77.0     69.0     73.0   Pass     B

**Explanation:** `mean(axis=1)` averages across columns per row. `np.select` checks conditions in order, so the strictest (A) comes first.

<a id="p-6"></a>
### ✍️ Practice Problem 6

**`assign` chain:** In **one** chained expression, create `Fee_USD` (fee / 280, rounded) and `Discounted_Fee` (10% off for Math ≥ 90), then select `Name`, `Fee`, `Fee_USD`, `Discounted_Fee`.

*(Solution in the **Practice Solutions** section at the end.)*

In [13]:
# ✍️ Practice Problem 6 — write your solution here

### Solution 6

In [14]:
(students
 .assign(Fee_USD=lambda d: (d['Fee'] / 280).round(0),
         Discounted_Fee=lambda d: np.where(d['Math'] >= 90, d['Fee'] * 0.9, d['Fee']))
 .loc[:, ['Name', 'Fee', 'Fee_USD', 'Discounted_Fee']]
 .head())

     Name     Fee  Fee_USD  Discounted_Fee
0    hina  120000    429.0        120000.0
1   Usman  120000    429.0        120000.0
2  AYESHA  120000    429.0        120000.0
3    Omar   95000    339.0         95000.0
4     ali  120000    429.0        120000.0

**Explanation:** `assign` returns a new DataFrame, so it can be chained; lambdas receive the DataFrame at that point in the chain.

<a id="p-7"></a>
### ✍️ Practice Problem 7

**Sorting & renaming:** Sort by `Program` (A→Z) then `Math` (high→low) with missing Math values first. Rename `Math` → `Math_Score`, `English` → `English_Score`, and make all column names lowercase.

*(Solution in the **Practice Solutions** section at the end.)*

In [15]:
# ✍️ Practice Problem 7 — write your solution here

### Solution 7

In [16]:
s7 = (students.sort_values(['Program', 'Math'], ascending=[True, False], na_position='first')
      .rename(columns={'Math': 'Math_Score', 'English': 'English_Score'})
      .rename(columns=str.lower))
s7.head()

   student_id    name gender     city program  math_score  english_score     fee enroll_date             courses
17       S117     ali      M  Karachi     BBA         NaN           86.0   80000  2025-06-23   Calculus, Physics
19       S119    hina      M   Lahore     BBA         NaN           82.0  120000  2025-03-16  Python, Statistics
30       S130    Omar   male   Multan     BBA         NaN           40.0   80000  2025-09-13     Python, ML, SQL
11       S111  AYESHA      M  Karachi     BBA        96.0           53.0  120000  2024-12-08                 SQL
36       S136  AYESHA      M   Lahore     BBA        94.0           48.0   80000  2024-10-30     Python, ML, SQL

**Explanation:** `ascending` is a list matching the sort columns; `rename(columns=str.lower)` applies a function to every name.

<a id="p-8"></a>
### ✍️ Practice Problem 8

**Dropping:** Drop the `Courses` column, drop rows where **both** Math and English are missing, and show how many rows `dropna()` (any column) would remove.

*(Solution in the **Practice Solutions** section at the end.)*

In [17]:
# ✍️ Practice Problem 8 — write your solution here

### Solution 8

In [18]:
s8 = students.drop(columns='Courses')
s8 = s8.dropna(subset=['Math', 'English'], how='all')              # drop only if BOTH are missing
print('Rows after dropping both-missing:', len(s8), 'of', len(students))
print('dropna() on any column would remove:', len(students) - len(students.dropna()), 'rows')

Rows after dropping both-missing: 62 of 62
dropna() on any column would remove: 10 rows

**Explanation:** `how='all'` drops a row only when all listed columns are missing; the default `how='any'` is much stricter.

<a id="p-9"></a>
### ✍️ Practice Problem 9

**Index:** Set `Student_ID` as the index, look up student `S110`, then reset the index. Why is `reset_index(drop=True)` sometimes needed after filtering?

*(Solution in the **Practice Solutions** section at the end.)*

In [19]:
# ✍️ Practice Problem 9 — write your solution here

### Solution 9

In [20]:
s9 = students.drop_duplicates().set_index('Student_ID')
print(s9.loc['S110', ['Name', 'Program', 'Math']])
back = s9.reset_index()
filtered9 = students[students['Math'] > 90]
print('Index after filtering:', filtered9.index.tolist()[:5], '→ after reset:', filtered9.reset_index(drop=True).index.tolist()[:5])

Name       AYESHA
Program        EE
Math         48.0
Name: S110, dtype: object
Index after filtering: [11, 15, 25, 27, 34] → after reset: [0, 1, 2, 3, 4]

**Explanation:** We drop duplicates first so `S110` is unique. After filtering, the index has gaps; `reset_index(drop=True)` gives 0..n−1 (needed before position-based logic or when concatenating).

<a id="p-10"></a>
### ✍️ Practice Problem 10

**apply / map / DataFrame.map:** Map program codes to full names (`CS` → 'Computer Science', …), use `apply` on rows to build `"Name - City"`, and use `DataFrame.map` to format `Math` and `English` with one decimal. Then replace the row-wise `apply` with a vectorized version.

*(Solution in the **Practice Solutions** section at the end.)*

In [21]:
# ✍️ Practice Problem 10 — write your solution here

### Solution 10

In [22]:
s10 = students.copy()
s10['Program_Name'] = s10['Program'].map({'CS': 'Computer Science', 'BBA': 'Business Admin', 'EE': 'Electrical Eng.', 'Math': 'Mathematics'})
s10['Label_apply'] = s10.apply(lambda r: f"{r['Name'].strip().title()} - {r['City']}", axis=1)
s10['Label_vector'] = s10['Name'].str.strip().str.title() + ' - ' + s10['City']        # vectorized, much faster
print('Same labels:', s10['Label_apply'].equals(s10['Label_vector']))
print(s10[['Math', 'English']].head(3).map(lambda v: f'{v:.1f}' if pd.notna(v) else '-'))

Same labels: True
   Math English
0  85.0    77.0
1  71.0    63.0
2  45.0    93.0

**Explanation:** The `.str` + `+` version does the same job as `apply(axis=1)` without a Python loop.

<a id="p-11"></a>
### ✍️ Practice Problem 11

**GroupBy with named aggregation:** Per `Program`, compute the number of students, average Math, maximum English, and the number of distinct cities.

*(Solution in the **Practice Solutions** section at the end.)*

In [23]:
# ✍️ Practice Problem 11 — write your solution here

### Solution 11

In [24]:
students.groupby('Program').agg(
    students=('Student_ID', 'count'),
    avg_math=('Math', 'mean'),
    max_english=('English', 'max'),
    cities=('City', 'nunique'),
).round(1).sort_values('students', ascending=False)

         students  avg_math  max_english  cities
Program
BBA            23      72.8         91.0       4
CS             20      66.9         98.0       4
EE             14      63.2         98.0       4
Math            5      74.2         91.0       3

**Explanation:** Named aggregation gives clean column names; `nunique` counts distinct values.

<a id="p-12"></a>
### ✍️ Practice Problem 12

**transform:** Add `Program_Avg_Math` to every row and `Math_vs_Program` = Math − program average. Who is most above their program average?

*(Solution in the **Practice Solutions** section at the end.)*

In [25]:
# ✍️ Practice Problem 12 — write your solution here

### Solution 12

In [26]:
s12 = students.copy()
s12['Program_Avg_Math'] = s12.groupby('Program')['Math'].transform('mean').round(1)
s12['Math_vs_Program'] = (s12['Math'] - s12['Program_Avg_Math']).round(1)
s12.sort_values('Math_vs_Program', ascending=False)[['Name', 'Program', 'Math', 'Program_Avg_Math', 'Math_vs_Program']].head(3)

      Name Program  Math  Program_Avg_Math  Math_vs_Program
34  AYESHA      EE  99.0              63.2             35.8
25     ali      EE  95.0              63.2             31.8
39    zara      EE  93.0              63.2             29.8

**Explanation:** `transform` returns one value per row, so it can be assigned directly as a column.

<a id="p-13"></a>
### ✍️ Practice Problem 13

**groupby().filter():** Keep only the programs with at least 12 students, and only cities whose average Math is above 65.

*(Solution in the **Practice Solutions** section at the end.)*

In [27]:
# ✍️ Practice Problem 13 — write your solution here

### Solution 13

In [28]:
big_programs = students.groupby('Program').filter(lambda g: len(g) >= 12)
print('Programs kept:', sorted(big_programs['Program'].unique()))
good_cities = students.groupby('City').filter(lambda g: g['Math'].mean() > 65)
print('Cities kept:', sorted(good_cities['City'].unique()))

Programs kept: ['BBA', 'CS', 'EE']
Cities kept: ['Islamabad', 'Lahore', 'Multan']

**Explanation:** `filter` keeps all rows of the groups that satisfy the condition; the output has the original columns.

<a id="p-14"></a>
### ✍️ Practice Problem 14

**Pivot table:** Build a pivot table of average `Math` with programs as rows and cities as columns, with row/column totals (`margins=True`), rounded to 1 decimal.

*(Solution in the **Practice Solutions** section at the end.)*

In [29]:
# ✍️ Practice Problem 14 — write your solution here

### Solution 14

In [30]:
pd.pivot_table(students, index='Program', columns='City', values='Math', aggfunc='mean', margins=True, margins_name='All').round(1)

City     Islamabad  Karachi  Lahore  Multan   All
Program
BBA           68.8     79.0    75.2    69.2  72.8
CS            58.7     75.0    75.8    68.0  66.9
EE            75.3     46.0    58.0    70.0  63.2
Math          77.3     47.0     NaN    92.0  74.2
All           68.8     61.9    73.8    70.8  68.7

**Explanation:** Each cell is the average Math score for a program in a city; `All` gives the totals computed from the raw rows.

<a id="p-15"></a>
### ✍️ Practice Problem 15

**Crosstab:** Count students by `City` × `Program`, then show row percentages. Which city has the highest share of CS students?

*(Solution in the **Practice Solutions** section at the end.)*

In [31]:
# ✍️ Practice Problem 15 — write your solution here

### Solution 15

In [32]:
ct = pd.crosstab(students['City'], students['Program'])
pct = (pd.crosstab(students['City'], students['Program'], normalize='index') * 100).round(1)
print(ct, '\n'); print(pct)
print('\nHighest CS share:', pct['CS'].idxmax(), f"({pct['CS'].max()}%)")

Program    BBA  CS  EE  Math
City
Islamabad    6   8   7     3
Karachi      5   2   5     1
Lahore       7   5   1     0
Multan       5   5   1     1

Program     BBA    CS    EE  Math
City
Islamabad  25.0  33.3  29.2  12.5
Karachi    38.5  15.4  38.5   7.7
Lahore     53.8  38.5   7.7   0.0
Multan     41.7  41.7   8.3   8.3

Highest CS share: Multan (41.7%)

**Explanation:** `normalize='index'` makes each row sum to 100%, so cities of different sizes can be compared.

<a id="p-16"></a>
### ✍️ Practice Problem 16

**Strings:** Clean `Name` (strip + title case) and standardise `Gender` to 'Male'/'Female'. Count students whose `Courses` contain 'Python', and extract the **first** course into a new column.

*(Solution in the **Practice Solutions** section at the end.)*

In [33]:
# ✍️ Practice Problem 16 — write your solution here

### Solution 16

In [34]:
s16 = students.copy()
s16['Name'] = s16['Name'].str.strip().str.title()
s16['Gender'] = s16['Gender'].str.lower().map({'m': 'Male', 'male': 'Male', 'f': 'Female', 'female': 'Female'})
print('Students taking Python:', s16['Courses'].str.contains('Python').sum())
s16['First_Course'] = s16['Courses'].str.split(',').str[0].str.strip()
s16[['Name', 'Gender', 'Courses', 'First_Course']].head()

Students taking Python: 35

     Name  Gender             Courses First_Course
0    Hina    Male     Python, ML, SQL       Python
1   Usman  Female     Python, ML, SQL       Python
2  Ayesha    Male     Python, ML, SQL       Python
3    Omar    Male  Python, Statistics       Python
4     Ali    Male                 SQL          SQL

**Explanation:** Lower-casing first reduces the mapping to four keys; `str.split(',').str[0]` takes the first element of each list.

<a id="p-17"></a>
### ✍️ Practice Problem 17

**Dates:** Extract year, month and weekday from `Enroll_Date`. Count enrolments per month (`to_period('M')`), and filter students who enrolled in 2025 on a weekend.

*(Solution in the **Practice Solutions** section at the end.)*

In [35]:
# ✍️ Practice Problem 17 — write your solution here

### Solution 17

In [36]:
s17 = students.copy()
ed = s17['Enroll_Date'].dt
s17 = s17.assign(Year=ed.year, Month=ed.month, Weekday=ed.day_name())
print(s17.groupby(ed.to_period('M')).size().head(6))
weekend_2025 = s17[(s17['Year'] == 2025) & (ed.dayofweek >= 5)]
print('\nEnrolled in 2025 on a weekend:', len(weekend_2025))

Enroll_Date
2024-08    5
2024-09    7
2024-10    6
2024-11    4
2024-12    5
2025-01    1
Freq: M, dtype: int64

Enrolled in 2025 on a weekend: 9

**Explanation:** `to_period('M')` groups by calendar month; `dayofweek >= 5` means Saturday or Sunday.

<a id="p-18"></a>
### ✍️ Practice Problem 18

**Duplicates & missing values:** Count and remove duplicate rows. Fill missing `Math` with the program's median (via `transform`). For `daily_sales`, compare `ffill`, `bfill` and `interpolate`.

*(Solution in the **Practice Solutions** section at the end.)*

In [37]:
# ✍️ Practice Problem 18 — write your solution here

### Solution 18

In [38]:
print('Duplicate rows:', students.duplicated().sum())
s18 = students.drop_duplicates().copy()
s18['Math'] = s18['Math'].fillna(s18.groupby('Program')['Math'].transform('median'))
print('Missing Math after group-median fill:', s18['Math'].isna().sum())

ds = daily_sales.copy()
ds['ffill'] = ds['Sales'].ffill(); ds['bfill'] = ds['Sales'].bfill(); ds['interpolate'] = ds['Sales'].interpolate()
ds.iloc[3:7]

Duplicate rows: 2
Missing Math after group-median fill: 0

        Date  Sales  ffill  bfill  interpolate
3 2025-01-04  162.0  162.0  162.0   162.000000
4 2025-01-05    NaN  162.0  199.0   174.333333
5 2025-01-06    NaN  162.0  199.0   186.666667
6 2025-01-07  199.0  199.0  199.0   199.000000

**Explanation:** Group-aware filling uses the median of the student's own program. For the time series, `interpolate` gives values between the neighbours, `ffill` repeats the last known value and `bfill` the next one.

<a id="p-19"></a>
### ✍️ Practice Problem 19

**Binning & explode:** Bin `Math` into 'Low' (<50), 'Medium' (50–75), 'High' (>75) with `pd.cut`, and into quartiles with `pd.qcut`. Explode `Courses` into one row per course and find the 3 most popular courses.

*(Solution in the **Practice Solutions** section at the end.)*

In [39]:
# ✍️ Practice Problem 19 — write your solution here

### Solution 19

In [40]:
s19 = students.copy()
s19['Math_Level'] = pd.cut(s19['Math'], bins=[0, 50, 75, 100], labels=['Low', 'Medium', 'High'], right=False)
s19['Math_Quartile'] = pd.qcut(s19['Math'], q=4, labels=['Q1', 'Q2', 'Q3', 'Q4'])
print(s19['Math_Level'].value_counts().sort_index().to_dict(), s19['Math_Quartile'].value_counts().sort_index().to_dict())
courses = s19.assign(Course=s19['Courses'].str.split(', ')).explode('Course')
print('\nTop 3 courses:'); print(courses['Course'].value_counts().head(3))

{'Low': 11, 'Medium': 20, 'High': 26} {'Q1': 16, 'Q2': 13, 'Q3': 16, 'Q4': 12}

Top 3 courses:
Course
Python    35
SQL       32
ML        22
Name: count, dtype: int64

**Explanation:** `right=False` makes the bins `[0, 50)`, `[50, 75)`, `[75, 100)` (with 100 excluded — use 101 as the top edge if 100 can occur). `explode` needs a list, so split first.

<a id="p-20"></a>
### ✍️ Practice Problem 20

**Reshaping & window functions:** `melt` the `quarterly` table to long format, `pivot` it back, and compute per region: quarter-over-quarter `diff`, `pct_change`, cumulative sum and 2-quarter rolling mean. Also add a 7-day rolling mean and `cumsum` to `daily_sales` (after interpolating).

*(Solution in the **Practice Solutions** section at the end.)*

In [41]:
# ✍️ Practice Problem 20 — write your solution here

### Solution 20

In [42]:
long_q = quarterly.melt(id_vars='Region', var_name='Quarter', value_name='Sales')
wide_q = long_q.pivot(index='Region', columns='Quarter', values='Sales')
print(wide_q, '\n')
long_q = long_q.sort_values(['Region', 'Quarter'])
g = long_q.groupby('Region')['Sales']
long_q = long_q.assign(Diff=g.diff(), Pct_Change=(g.pct_change() * 100).round(1), Cumulative=g.cumsum(),
                       Rolling_2=g.transform(lambda s: s.rolling(2).mean()))
print(long_q, '\n')
ds20 = daily_sales.assign(Sales=daily_sales['Sales'].interpolate())
ds20['Rolling_7'] = ds20['Sales'].rolling(7).mean().round(1); ds20['Cumulative'] = ds20['Sales'].cumsum()
print(ds20.tail(3))

Quarter   Q1   Q2   Q3   Q4
Region
East     150  160  158  165
North    120  135  150  170
South     90   88   95  101

   Region Quarter  Sales  Diff  Pct_Change  Cumulative  Rolling_2
2    East      Q1    150   NaN         NaN         150        NaN
5    East      Q2    160  10.0         6.7         310      155.0
8    East      Q3    158  -2.0        -1.2         468      159.0
11   East      Q4    165   7.0         4.4         633      161.5
0   North      Q1    120   NaN         NaN         120        NaN
3   North      Q2    135  15.0        12.5         255      127.5
6   North      Q3    150  15.0        11.1         405      142.5
9   North      Q4    170  20.0        13.3         575      160.0
1   South      Q1     90   NaN         NaN          90        NaN
4   South      Q2     88  -2.0        -2.2         178       89.0
7   South      Q3     95   7.0         8.0         273       91.5
10  South      Q4    101   6.0         6.3         374       98.0

         Date  Sales  Rolling_7  Cumulative
27 2025-01-28  138.0      143.1      4081.5
28 2025-01-29  181.0      151.1      4262.5
29 2025-01-30  120.0      149.6      4382.5

**Explanation:** All ordered calculations are done **per region** with `groupby`, after sorting by quarter; `transform` with a lambda applies the rolling mean within each region.

<a id="p-21"></a>
---
# Final Project — E-Commerce Data Manipulation

**Scenario:** you receive a raw export of 260 orders from an online store. It has messy column names, inconsistent text, dates stored as text, missing values and duplicate rows. Your job: clean it and produce a business summary using the techniques from this notebook.

## Step 0 — Create the raw dataset

In [43]:
rr = np.random.default_rng(2025)
n = 250
products = {'Laptop': ('Electronics', 145000), 'Smartphone': ('Electronics', 85000), 'Earbuds': ('Electronics', 6500),
            'T-Shirt': ('Fashion', 1800), 'Jeans': ('Fashion', 4200), 'Sneakers': ('Fashion', 9500),
            'Novel': ('Books', 1200), 'Cookbook': ('Books', 2500), 'Face Wash': ('Beauty', 950), 'Perfume': ('Beauty', 7500)}
first = ['Ali', 'Sara', 'Omar', 'Hina', 'Bilal', 'Zara', 'Usman', 'Ayesha', 'Hamza', 'Fatima', 'Imran', 'Mariam']
last = ['Khan', 'Ahmed', 'Farooq', 'Malik', 'Raza', 'Iqbal', 'Tariq', 'Noor', 'Butt', 'Sheikh']
all_names = [f'{f} {l}' for f in first for l in last]
names = list(rr.choice(all_names, 40, replace=False))                     # 40 distinct customers
cust_ids = [f'C{200 + i}' for i in range(len(names))]
prod_names = rr.choice(list(products), n, p=[0.06, 0.09, 0.12, 0.14, 0.12, 0.08, 0.11, 0.07, 0.12, 0.09])
cust_idx = rr.integers(0, len(names), n)
raw = pd.DataFrame({
    'Order ID': [f'ORD-{5000 + i}' for i in range(n)],
    ' customer_id': np.array(cust_ids)[cust_idx],
    'Customer Name': [rr.choice([nm, nm.upper(), '  ' + nm.lower() + ' ']) for nm in np.array(names)[cust_idx]],
    'AGE': rr.integers(18, 60, len(names))[cust_idx].astype(float),
    'gender': rr.choice(['M', 'F'], len(names))[cust_idx],
    'City ': rr.choice(['lahore', 'Lahore ', 'KARACHI', 'Karachi', 'Islamabad', 'islamabad', 'Multan'], n),
    'Product': prod_names,
    'Category': [products[p][0] for p in prod_names],
    'Price': [round(products[p][1] * rr.uniform(0.95, 1.05), -1) for p in prod_names],
    'Quantity': np.where(np.isin(prod_names, ['Laptop', 'Smartphone']), 1, rr.integers(1, 5, n)),
    'Discount': rr.choice([0, 0.05, 0.10, 0.15, 0.20], n, p=[0.35, 0.2, 0.25, 0.12, 0.08]),
    'Order Date': (pd.to_datetime('2024-07-01') + pd.to_timedelta(rr.integers(0, 365, n), unit='D')).strftime('%d-%m-%Y'),
    'Payment Method': rr.choice(['Card', 'cash on delivery', 'COD', 'Wallet', 'card'], n),
    'Rating': rr.choice([1, 2, 3, 4, 5], n, p=[0.04, 0.06, 0.2, 0.4, 0.3]).astype(float),
})
# Inject realistic problems
raw.loc[rr.choice(n, 12, replace=False), 'AGE'] = np.nan
raw.loc[rr.choice(n, 20, replace=False), 'Rating'] = np.nan
raw.loc[rr.choice(n, 6, replace=False), 'Payment Method'] = np.nan
raw.loc[rr.choice(n, 3, replace=False), 'Order Date'] = 'unknown'
raw = pd.concat([raw, raw.sample(10, random_state=1)], ignore_index=True)       # duplicate rows
print(raw.shape)
raw.head()

(260, 14)

,Order ID,customer_id,Customer Name,AGE,gender,City,Product,Category,Price,Quantity,Discount,Order Date,Payment Method,Rating
0,ORD-5000,C214,Zara Noor,55.0,M,Lahore,Jeans,Fashion,4380.0,2,0.05,03-10-2024,Wallet,3.0
1,ORD-5001,C210,SARA TARIQ,33.0,M,Multan,T-Shirt,Fashion,1800.0,4,0.10,15-12-2024,Card,5.0
2,ORD-5002,C239,Ayesha Ahmed,55.0,M,Islamabad,Face Wash,Beauty,970.0,4,0.00,27-11-2024,COD,4.0
3,ORD-5003,C209,HINA TARIQ,22.0,F,KARACHI,Jeans,Fashion,4090.0,1,0.00,24-05-2025,Card,4.0
4,ORD-5004,C222,OMAR MALIK,44.0,M,lahore,Sneakers,Fashion,9030.0,2,0.00,17-04-2025,Card,3.0

## Step 1 — Clean column names

In [44]:
df = raw.copy()
df.columns = df.columns.str.strip().str.replace(' ', '_').str.title().str.replace('Id', 'ID')
print(df.columns.tolist())

['Order_ID', 'Customer_ID', 'Customer_Name', 'Age', 'Gender', 'City', 'Product', 'Category', 'Price', 'Quantity', 'Discount', 'Order_Date', 'Payment_Method', 'Rating']

**Why:** consistent `Title_Case` names without spaces are easy to type and avoid `KeyError`s caused by hidden spaces (`' customer_id'`, `'City '`).

## Step 2 — Convert dates

In [45]:
df['Order_Date'] = pd.to_datetime(df['Order_Date'], format='%d-%m-%Y', errors='coerce')
print('Unparseable dates:', df['Order_Date'].isna().sum(), '| range:', df['Order_Date'].min().date(), '→', df['Order_Date'].max().date())

Unparseable dates: 3 | range: 2024-07-01 → 2025-06-29

`errors='coerce'` turns the three 'unknown' values into `NaT` instead of crashing; `format=` avoids day/month confusion.

## Step 3 — Handle missing values

In [46]:
print('Missing before:\n', df.isna().sum()[df.isna().sum() > 0], '\n')
df['Age'] = df['Age'].fillna(df.groupby('Customer_ID')['Age'].transform('first'))       # same customer → same age
df['Age'] = df['Age'].fillna(df['Age'].median())
df['Rating_Missing'] = df['Rating'].isna().astype(int)                                   # keep the information
df['Rating'] = df['Rating'].fillna(df.groupby('Product')['Rating'].transform('median'))  # typical rating of that product
df['Payment_Method'] = df['Payment_Method'].fillna('Unknown')
df = df.dropna(subset=['Order_Date'])                                                    # can't analyse orders without a date
print('Missing after:\n', df.isna().sum()[df.isna().sum() > 0].to_dict() or 'none')

Missing before:
 Age               12
Order_Date         3
Payment_Method     6
Rating            20
dtype: int64

Missing after:
 none

**Decisions:** age is a customer attribute → borrow it from the same customer's other orders; ratings → product median + a flag; payment → an explicit 'Unknown' category; the 3 undated orders are dropped (tiny share).

## Step 4 — Remove duplicates

In [47]:
print('Duplicate rows:', df.duplicated().sum(), '| duplicate Order_IDs:', df['Order_ID'].duplicated().sum())
df = df.drop_duplicates(subset='Order_ID', keep='first').reset_index(drop=True)
print('Rows now:', len(df))

Duplicate rows: 10 | duplicate Order_IDs: 10
Rows now: 247

`Order_ID` defines a unique order, so we deduplicate on it.

## Step 5–7 — Revenue, Discount_Amount, Net_Revenue

In [48]:
df['Revenue'] = df['Price'] * df['Quantity']
df['Discount_Amount'] = (df['Revenue'] * df['Discount']).round(0)
df['Net_Revenue'] = df['Revenue'] - df['Discount_Amount']
df[['Order_ID', 'Product', 'Price', 'Quantity', 'Discount', 'Revenue', 'Discount_Amount', 'Net_Revenue']].head()

   Order_ID    Product   Price  Quantity  Discount  Revenue  Discount_Amount  Net_Revenue
0  ORD-5000      Jeans  4380.0         2      0.05   8760.0            438.0       8322.0
1  ORD-5001    T-Shirt  1800.0         4      0.10   7200.0            720.0       6480.0
2  ORD-5002  Face Wash   970.0         4      0.00   3880.0              0.0       3880.0
3  ORD-5003      Jeans  4090.0         1      0.00   4090.0              0.0       4090.0
4  ORD-5004   Sneakers  9030.0         2      0.00  18060.0              0.0      18060.0

## Step 8–9 — Age_Group and Price_Category

In [49]:
df['Age_Group'] = pd.cut(df['Age'], bins=[17, 25, 35, 45, 60], labels=['18–25', '26–35', '36–45', '46–60'])
df['Price_Category'] = pd.cut(df['Price'], bins=[0, 3000, 20000, np.inf], labels=['Budget', 'Mid-range', 'Premium'])
print(df['Age_Group'].value_counts().sort_index().to_dict())
print(df['Price_Category'].value_counts().to_dict())

{'18–25': 56, '26–35': 62, '36–45': 60, '46–60': 69}
{'Mid-range': 108, 'Budget': 98, 'Premium': 41}

## Step 15 (early) — String operations: clean names, cities, payment methods

In [50]:
df['Customer_Name'] = df['Customer_Name'].str.strip().str.replace(r'\s+', ' ', regex=True).str.title()
df['City'] = df['City'].str.strip().str.title()
df['Payment_Method'] = (df['Payment_Method'].str.strip().str.lower()
                        .replace({'cod': 'Cash on Delivery', 'cash on delivery': 'Cash on Delivery', 'card': 'Card',
                                  'wallet': 'Wallet', 'unknown': 'Unknown'}))
df['Gender'] = df['Gender'].map({'M': 'Male', 'F': 'Female'})
df['First_Name'] = df['Customer_Name'].str.split().str[0]
df['Order_Number'] = df['Order_ID'].str.extract(r'(\d+)').astype(int)
print(df['City'].value_counts().to_dict())
print(df['Payment_Method'].value_counts().to_dict())
print('Distinct customer name spellings now:', df['Customer_Name'].nunique(), '(was', raw['Customer Name'].nunique(), ')')

{'Karachi': 89, 'Lahore': 70, 'Islamabad': 67, 'Multan': 21}
{'Cash on Delivery': 99, 'Card': 91, 'Wallet': 51, 'Unknown': 6}
Distinct customer name spellings now: 40 (was 102 )

Text cleaning is done **before** grouping — otherwise 'lahore', 'Lahore ' and 'Lahore' would be three different cities. (It's step 15 in the task list but must logically come before steps 10–14.)

## Step 10 — Group by City

In [51]:
city_summary = df.groupby('City').agg(
    Orders=('Order_ID', 'count'), Customers=('Customer_ID', 'nunique'),
    Net_Revenue=('Net_Revenue', 'sum'), Avg_Order_Value=('Net_Revenue', 'mean'), Avg_Rating=('Rating', 'mean'),
).sort_values('Net_Revenue', ascending=False).round(1)
city_summary

           Orders  Customers  Net_Revenue  Avg_Order_Value  Avg_Rating
City
Karachi        89         36    2012060.0          22607.4         3.9
Lahore         70         34    1987018.0          28386.0         4.0
Islamabad      67         31    1599053.0          23866.5         4.1
Multan         21         17     494813.0          23562.5         4.1

## Step 11 — Group by Product

In [52]:
product_summary = df.groupby('Product').agg(
    Category=('Category', 'first'), Units=('Quantity', 'sum'), Net_Revenue=('Net_Revenue', 'sum'),
    Avg_Discount_pct=('Discount', lambda s: s.mean() * 100), Avg_Rating=('Rating', 'mean'),
).sort_values('Net_Revenue', ascending=False).round(1)
product_summary

               Category  Units  Net_Revenue  Avg_Discount_pct  Avg_Rating
Product
Smartphone  Electronics     27    2142421.0               6.9         4.0
Laptop      Electronics     14    1843555.0               9.6         4.0
Sneakers        Fashion     60     539236.0               5.9         4.0
Perfume          Beauty     70     478870.0               9.1         3.9
Earbuds     Electronics     77     470834.0               5.7         4.2
Jeans           Fashion     70     276807.0               6.1         4.1
T-Shirt         Fashion     79     129748.0               7.4         4.0
Cookbook          Books     37      88801.0               5.8         4.1
Novel             Books     76      84402.0               7.1         4.1
Face Wash        Beauty     43      38270.0               6.3         4.2

## Step 12 — Group by Category

In [53]:
cat_summary = df.groupby('Category').agg(Orders=('Order_ID', 'count'), Units=('Quantity', 'sum'),
                                         Net_Revenue=('Net_Revenue', 'sum'), Total_Discount=('Discount_Amount', 'sum'))
cat_summary['Revenue_Share_%'] = (cat_summary['Net_Revenue'] / cat_summary['Net_Revenue'].sum() * 100).round(1)
cat_summary.sort_values('Net_Revenue', ascending=False)

             Orders  Units  Net_Revenue  Total_Discount  Revenue_Share_%
Category
Electronics      68    118    4456810.0        381000.0             73.1
Fashion          90    209     945791.0         61959.0             15.5
Beauty           47    113     517140.0         47950.0              8.5
Books            42    113     173203.0         11277.0              2.8

## Step 13 — Pivot tables

In [54]:
print('Net revenue (thousand PKR) by city × category:')
print((pd.pivot_table(df, index='City', columns='Category', values='Net_Revenue', aggfunc='sum', fill_value=0,
                      margins=True, margins_name='Total') / 1000).round(0), '\n')
print('Average rating by age group × category:')
print(pd.pivot_table(df, index='Age_Group', columns='Category', values='Rating', aggfunc='mean', observed=True).round(2))

Net revenue (thousand PKR) by city × category:
Category   Beauty  Books  Electronics  Fashion   Total
City
Islamabad   119.0   34.0       1209.0    237.0  1599.0
Karachi     214.0   72.0       1354.0    372.0  2012.0
Lahore      151.0   50.0       1522.0    264.0  1987.0
Multan       32.0   18.0        372.0     73.0   495.0
Total       517.0  173.0       4457.0    946.0  6093.0

Average rating by age group × category:
Category   Beauty  Books  Electronics  Fashion
Age_Group
18–25        4.33   4.00         4.06     3.95
26–35        3.77   4.00         3.79     4.30
36–45        4.23   4.31         3.82     4.04
46–60        3.67   4.00         4.30     3.70

## Step 14 — Crosstabs

In [55]:
print('Payment method share by city (%):')
print((pd.crosstab(df['City'], df['Payment_Method'], normalize='index') * 100).round(0), '\n')
print('Orders by gender × price category:')
print(pd.crosstab(df['Gender'], df['Price_Category'], margins=True))

Payment method share by city (%):
Payment_Method  Card  Cash on Delivery  Unknown  Wallet
City
Islamabad       42.0              42.0      3.0    13.0
Karachi         37.0              36.0      3.0    24.0
Lahore          33.0              39.0      1.0    27.0
Multan          33.0              57.0      0.0    10.0

Orders by gender × price category:

Price_Category  Budget  Mid-range  Premium  All
Gender
Female              41         49       18  108
Male                57         59       23  139
All                 98        108       41  247

## Step 16 — Date analysis

In [56]:
df = df.sort_values('Order_Date').reset_index(drop=True)
od = df['Order_Date'].dt
df['Month'] = od.to_period('M')
df['Weekday'] = od.day_name()
df['Is_Weekend'] = od.dayofweek >= 5

monthly = df.groupby('Month').agg(Orders=('Order_ID', 'count'), Net_Revenue=('Net_Revenue', 'sum'))
print(monthly.assign(Net_Revenue_k=(monthly['Net_Revenue'] / 1000).round(0)).drop(columns='Net_Revenue'), '\n')
print('Orders by weekday:'); print(df['Weekday'].value_counts().reindex(['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday']))
print('\nWeekend share of net revenue: {:.1%}'.format(df.loc[df['Is_Weekend'], 'Net_Revenue'].sum() / df['Net_Revenue'].sum()))

         Orders  Net_Revenue_k
Month
2024-07      22          482.0
2024-08      25          711.0
2024-09      14          554.0
2024-10      13          260.0
2024-11      23          390.0
2024-12      30          841.0
2025-01      16          498.0
2025-02      16          360.0
2025-03      18          382.0
2025-04      27          627.0
2025-05      23          434.0
2025-06      20          555.0

Orders by weekday:
Weekday
Monday       43
Tuesday      32
Wednesday    34
Thursday     41
Friday       32
Saturday     27
Sunday       38
Name: count, dtype: int64

Weekend share of net revenue: 22.1%

## Step 17–18 — Cumulative and rolling revenue

In [57]:
daily_rev = df.groupby('Order_Date')['Net_Revenue'].sum().asfreq('D', fill_value=0)      # include days without orders
trend = pd.DataFrame({'Daily': daily_rev,
                      'Cumulative': daily_rev.cumsum(),
                      'Rolling_7d': daily_rev.rolling(7).sum(),
                      'Rolling_30d_Avg': daily_rev.rolling(30).mean().round(0)})
monthly['Cumulative_Net_Revenue'] = monthly['Net_Revenue'].cumsum()
monthly['MoM_Change_%'] = (monthly['Net_Revenue'].pct_change() * 100).round(1)
print(trend.tail(5), '\n')
monthly

              Daily  Cumulative  Rolling_7d  Rolling_30d_Avg
Order_Date
2025-06-25      0.0   5979492.0      2280.0          14901.0
2025-06-26      0.0   5979492.0      2280.0          14901.0
2025-06-27      0.0   5979492.0         0.0          14901.0
2025-06-28  86920.0   6066412.0     86920.0          17599.0
2025-06-29  26532.0   6092944.0    113452.0          18484.0

         Orders  Net_Revenue  Cumulative_Net_Revenue  MoM_Change_%
Month
2024-07      22     482257.0                482257.0           NaN
2024-08      25     711081.0               1193338.0          47.4
2024-09      14     554207.0               1747545.0         -22.1
2024-10      13     259788.0               2007333.0         -53.1
2024-11      23     389905.0               2397238.0          50.1
2024-12      30     840708.0               3237946.0         115.6
2025-01      16     497663.0               3735609.0         -40.8
2025-02      16     359849.0               4095458.0         -27.7
2025-03      18     381872.0               4477330.0           6.1
2025-04      27     627266.0               5104596.0          64.3
2025-05      23     433836.0               5538432.0         -30.8
2025-06      20     554512.0               6092944.0          27.8

## Step 19 — Rank products

In [58]:
ranked = product_summary.copy()
ranked['Revenue_Rank'] = ranked['Net_Revenue'].rank(ascending=False, method='min').astype(int)
ranked['Units_Rank'] = ranked['Units'].rank(ascending=False, method='min').astype(int)
ranked['Rank_in_Category'] = ranked.groupby('Category')['Net_Revenue'].rank(ascending=False, method='min').astype(int)
ranked.sort_values('Revenue_Rank')[['Category', 'Net_Revenue', 'Revenue_Rank', 'Units', 'Units_Rank', 'Rank_in_Category']]

               Category  Net_Revenue  Revenue_Rank  Units  Units_Rank  Rank_in_Category
Product
Smartphone  Electronics    2142421.0             1     27           9                 1
Laptop      Electronics    1843555.0             2     14          10                 2
Sneakers        Fashion     539236.0             3     60           6                 1
Perfume          Beauty     478870.0             4     70           4                 1
Earbuds     Electronics     470834.0             5     77           2                 3
Jeans           Fashion     276807.0             6     70           4                 2
T-Shirt         Fashion     129748.0             7     79           1                 3
Cookbook          Books      88801.0             8     37           8                 1
Novel             Books      84402.0             9     76           3                 2
Face Wash        Beauty      38270.0            10     43           7                 2

## Step 20 — Final business summary

In [59]:
customer_summary = df.groupby(['Customer_ID', 'Customer_Name']).agg(
    Orders=('Order_ID', 'count'), Net_Revenue=('Net_Revenue', 'sum'), Avg_Rating=('Rating', 'mean')
).sort_values('Net_Revenue', ascending=False)

best_month = monthly['Net_Revenue'].idxmax()
summary = pd.Series({
    'Clean orders analysed': len(df),
    'Unique customers': df['Customer_ID'].nunique(),
    'Gross revenue (PKR)': f"{df['Revenue'].sum():,.0f}",
    'Discounts given (PKR)': f"{df['Discount_Amount'].sum():,.0f}",
    'Net revenue (PKR)': f"{df['Net_Revenue'].sum():,.0f}",
    'Average order value (PKR)': f"{df['Net_Revenue'].mean():,.0f}",
    'Top city': city_summary.index[0],
    'Top category (share)': f"{cat_summary['Net_Revenue'].idxmax()} ({cat_summary['Revenue_Share_%'].max()}%)",
    'Top product': product_summary.index[0],
    'Most units sold': product_summary['Units'].idxmax(),
    'Best month': str(best_month),
    'Top customer': customer_summary.index[0][1],
    'Average rating': round(df['Rating'].mean(), 2),
    'Most common payment': df['Payment_Method'].value_counts().idxmax(),
})
print(summary.to_string())
print('\nTop 5 customers:'); print(customer_summary.head().round(1))

Clean orders analysed                        247
Unique customers                              40
Gross revenue (PKR)                    6,595,130
Discounts given (PKR)                    502,186
Net revenue (PKR)                      6,092,944
Average order value (PKR)                 24,668
Top city                                 Karachi
Top category (share)         Electronics (73.1%)
Top product                           Smartphone
Most units sold                          T-Shirt
Best month                               2024-12
Top customer                         Hamza Malik
Average rating                              4.03
Most common payment             Cash on Delivery

Top 5 customers:
                           Orders  Net_Revenue  Avg_Rating
Customer_ID Customer_Name
C208        Hamza Malik         7     496022.0         3.6
C227        Ali Tariq           8     360492.0         4.1
C214        Zara Noor           6     334806.0         3.8
C216        Omar Sheikh        12     289807.0         4.1
C218        Hina Noor           6     285520.0         4.5

### Project conclusions
- **Cleaning mattered:** hidden spaces, mixed case and duplicate spellings would otherwise have split cities, customers and payment methods into several fake groups; 10 duplicate orders and 3 undated orders were removed.
- **Revenue is concentrated** in the Electronics category (laptops and smartphones), while cheaper items (T-shirts, novels, face wash) drive the **number of units**.
- The **city**, **monthly trend**, **top customers** and **payment mix** tables above are the inputs for the marketing and inventory teams; read the exact numbers from your output.
- Every step used a vectorized pandas operation (no Python loops), so the same code scales to millions of rows.

---
# Pandas Data Manipulation Cheat Sheet

| Task | Code |
|---|---|
| Select column / columns | `df['c']` · `df[['a', 'b']]` |
| Select by label / position | `df.loc[rows, cols]` (end **included**) · `df.iloc[rows, cols]` (end **excluded**) |
| Filter | `df[(df.a > 1) & (df.b == 'x')]` · `\|` or · `~` not · `.isin([...])` · `.between(a, b)` · `df.query('a > 1 and b == "x"')` |
| New column | `df['c'] = df.a * df.b` · `np.where(cond, x, y)` · `np.select(conds, choices, default)` · `df.assign(c=lambda d: ...)` |
| Modify some rows | `df.loc[cond, 'c'] = value` (never chained assignment) |
| Sort | `df.sort_values(['a', 'b'], ascending=[True, False], na_position='first')` · `df.sort_index()` · `nlargest(n, 'c')` |
| Rename | `df.rename(columns={'old': 'new'})` · `df.columns.str.strip().str.lower()` |
| Drop | `df.drop(columns=[...])` · `df.drop(index=[...])` · `df.dropna(subset=[...], how='any'/'all', thresh=)` |
| Index | `df.set_index('c')` · `df.reset_index(drop=True)` |
| Functions | `s.map(dict/func)` · `s.apply(func)` · `df.apply(func, axis=0/1)` · `df.map(func)` (was `applymap`) — prefer vectorized ops |
| Group & summarise | `df.groupby('k').agg(new=('col', 'mean'), n=('col', 'count'))` |
| Group value on each row | `df.groupby('k')['c'].transform('mean')` |
| Keep whole groups | `df.groupby('k').filter(lambda g: len(g) >= 5)` |
| Pivot table | `pd.pivot_table(df, index=, columns=, values=, aggfunc=, fill_value=, margins=True)` |
| Frequency table | `pd.crosstab(df.a, df.b, normalize='index', margins=True)` |
| Strings | `.str.lower/upper/title/strip/contains/startswith/endswith/replace/split/len/extract` |
| Dates | `pd.to_datetime(s, format=, errors='coerce')` · `.dt.year/month/day/day_name()/hour/dayofweek` · `.dt.to_period('M')` · `resample('W')` |
| Duplicates | `df.duplicated(subset=, keep=)` · `df.drop_duplicates(subset=, keep='last')` |
| Missing values | `fillna(v)` · `ffill()` · `bfill()` · `interpolate()` · `groupby().ffill()` · `fillna(groupby().transform('median'))` |
| Recode | `replace({...})` (keeps unmatched) · `map({...})` (unmatched → NaN) |
| Bin | `pd.cut(s, bins=[...], labels=[...])` · `pd.qcut(s, q=4)` |
| Lists to rows | `df.assign(c=df.c.str.split(', ')).explode('c')` |
| Reshape | `melt(id_vars=)` · `pivot(index=, columns=, values=)` · `pivot_table` · `stack()` · `unstack()` · `pd.wide_to_long` |
| Conditional values | `s.where(cond, other)` · `s.mask(cond, other)` · `s.clip(lo, hi)` |
| Ordered calcs | `rank()` · `shift()` · `diff()` · `pct_change()` · `cumsum/cumprod/cummax/cummin()` |
| Windows | `rolling(7).mean()` · `rolling(7, min_periods=1)` · `expanding().mean()` |
| Performance | vectorize · avoid `iterrows`/`apply(axis=1)` · `astype('category')` · downcast · `memory_usage(deep=True)` |

### Golden rules
1. **Clean text before grouping** (strip, lower/title case).
2. **Convert dates** with an explicit `format=` and `errors='coerce'`.
3. Use **one `.loc[...] = ...`** for assignments (Copy-on-Write).
4. Prefer **`df = df.method(...)`** over `inplace=True`.
5. **agg** for summaries, **transform** for per-row group values, **filter** for whole groups.
6. **Sort** before `shift`/`diff`/`rolling`/`cumsum`, and use `groupby` for multiple entities.
7. Prefer **vectorized** operations over `apply` and loops.

🎉 **You have completed Topic 9 — Pandas Data Manipulation!**