# Topic 6 — Encoding Techniques in Python Pandas — 📖 Lesson

## Zero to Advanced

This notebook teaches categorical data encoding from beginner to advanced level.

### What you will learn

- What encoding is and why it is needed
- Categorical data
- Nominal vs ordinal categorical data
- Binary encoding using Pandas
- Label encoding
- `map()` and `replace()`
- Pandas categorical dtype
- `cat.codes`
- Ordinal encoding
- One-Hot Encoding
- `pd.get_dummies()`
- `drop_first`
- Encoding multiple columns
- Frequency encoding
- Count encoding
- Target encoding
- Data leakage
- Multi-hot encoding
- Rare-category encoding
- Unknown categories
- Binary encoding
- Hash encoding
- Scikit-learn `OneHotEncoder`
- `fit()` vs `transform()`
- `ColumnTransformer`
- Machine-learning pipelines
- Complete encoding project

---

## Important idea

Machine-learning algorithms generally work with numerical values. Encoding converts categorical values such as `Male`, `Female`, `Lahore`, and `Karachi` into numerical representations that a model can use.

> 📚 **Course navigation** — you are in **Topic 06: Encoding Techniques**
> ⬅️ Previous: [Topic 05 — Detecting & Treating Outliers](../Topic_05_Outliers/Topic_05_Lesson.ipynb)  ·  ➡️ Next: [Topic 07 — Exploratory Data Analysis (EDA)](../Topic_07_Exploratory_Data_Analysis/Topic_07_Lesson.ipynb)  ·  🗂️ [All topics](../Topic_00_All_Topics_Index.ipynb)

<details><summary>Full course sequence (click to expand)</summary>

| # | Topic | Lesson | Practice & Solutions |
|---|---|---|---|
| 01 | Python Basics | [📖 Lesson](../Topic_01_Python_Basics/Topic_01_Lesson.ipynb) | [✍️ Practice](../Topic_01_Python_Basics/Topic_01_Practice_Solutions.ipynb) |
| 02 | Pandas DataFrame Basics | [📖 Lesson](../Topic_02_Pandas_DataFrame_Basics/Topic_02_Lesson.ipynb) | [✍️ Practice](../Topic_02_Pandas_DataFrame_Basics/Topic_02_Practice_Solutions.ipynb) |
| 03 | Handling Missing Values | [📖 Lesson](../Topic_03_Handling_Missing_Values/Topic_03_Lesson.ipynb) | [✍️ Practice](../Topic_03_Handling_Missing_Values/Topic_03_Practice_Solutions.ipynb) |
| 04 | Normalization & Standardization | [📖 Lesson](../Topic_04_Normalization_Standardization/Topic_04_Lesson.ipynb) | [✍️ Practice](../Topic_04_Normalization_Standardization/Topic_04_Practice_Solutions.ipynb) |
| 05 | Detecting & Treating Outliers | [📖 Lesson](../Topic_05_Outliers/Topic_05_Lesson.ipynb) | [✍️ Practice](../Topic_05_Outliers/Topic_05_Practice_Solutions.ipynb) |
| 🎯 | *🎯 Quiz 1 — Topics 01–05* | [🎯 Quiz 1](../Quiz_1_Topics_01-05/Quiz_1.ipynb) | |
| **▶ 06 ◀** | **Encoding Techniques** | [📖 Lesson](../Topic_06_Encoding_Techniques/Topic_06_Lesson.ipynb) | [✍️ Practice](../Topic_06_Encoding_Techniques/Topic_06_Practice_Solutions.ipynb) |
| 07 | Exploratory Data Analysis (EDA) | [📖 Lesson](../Topic_07_Exploratory_Data_Analysis/Topic_07_Lesson.ipynb) | [✍️ Practice](../Topic_07_Exploratory_Data_Analysis/Topic_07_Practice_Solutions.ipynb) |
| 08 | Data Visualization | [📖 Lesson](../Topic_08_Data_Visualization/Topic_08_Lesson.ipynb) | [✍️ Practice](../Topic_08_Data_Visualization/Topic_08_Practice_Solutions.ipynb) |
| 09 | Pandas Data Manipulation | [📖 Lesson](../Topic_09_Pandas_Data_Manipulation/Topic_09_Lesson.ipynb) | [✍️ Practice](../Topic_09_Pandas_Data_Manipulation/Topic_09_Practice_Solutions.ipynb) |
| 10 | Combining DataFrames | [📖 Lesson](../Topic_10_Combining_DataFrames/Topic_10_Lesson.ipynb) | [✍️ Practice](../Topic_10_Combining_DataFrames/Topic_10_Practice_Solutions.ipynb) |
| 🎯 | *🎯 Quiz 2 — Topics 06–10* | [🎯 Quiz 2](../Quiz_2_Topics_06-10/Quiz_2.ipynb) | |
| 11 | Feature Engineering | [📖 Lesson](../Topic_11_Feature_Engineering/Topic_11_Lesson.ipynb) | [✍️ Practice](../Topic_11_Feature_Engineering/Topic_11_Practice_Solutions.ipynb) |
| 11b | KBinsDiscretizer (Discretization) | [📖 Lesson](../Topic_11b_KBinsDiscretizer/Topic_11b_Lesson.ipynb) | [✍️ Practice](../Topic_11b_KBinsDiscretizer/Topic_11b_Practice_Solutions.ipynb) |
| 12 | Correlation & Multicollinearity | [📖 Lesson](../Topic_12_Correlation_Multicollinearity/Topic_12_Lesson.ipynb) | [✍️ Practice](../Topic_12_Correlation_Multicollinearity/Topic_12_Practice_Solutions.ipynb) |
| 13 | Data Transformation & Skewness | [📖 Lesson](../Topic_13_Data_Transformation_Skewness/Topic_13_Lesson.ipynb) | [✍️ Practice](../Topic_13_Data_Transformation_Skewness/Topic_13_Practice_Solutions.ipynb) |
| 14 | Statistics for Data Science | [📖 Lesson](../Topic_14_Statistics_for_Data_Science/Topic_14_Lesson.ipynb) | [✍️ Practice](../Topic_14_Statistics_for_Data_Science/Topic_14_Practice_Solutions.ipynb) |
| 🎯 | *🎯 Quiz 3 — Topics 11–14* | [🎯 Quiz 3](../Quiz_3_Topics_11-14/Quiz_3.ipynb) | |
| 15 | Probability for Data Science & ML | [📖 Lesson](../Topic_15_Probability_for_Data_Science_ML/Topic_15_Lesson.ipynb) | [✍️ Practice](../Topic_15_Probability_for_Data_Science_ML/Topic_15_Practice_Solutions.ipynb) |
| 16 | Feature Selection | [📖 Lesson](../Topic_16_Feature_Selection/Topic_16_Lesson.ipynb) | [✍️ Practice](../Topic_16_Feature_Selection/Topic_16_Practice_Solutions.ipynb) |
| 17 | Machine Learning | [📖 Lesson](../Topic_17_Machine_Learning/Topic_17_Lesson.ipynb) | [✍️ Practice](../Topic_17_Machine_Learning/Topic_17_Practice_Solutions.ipynb) |
| 🎯 | *🏁 Final Quiz — Topics 15–17* | [🏁 Final Quiz](../Quiz_4_Topics_15-17/Quiz_4.ipynb) | |

</details>

## 📋 Lesson Index — What This Lesson Covers

This lesson has **30 sections**. Click any one to jump to it.

- [1. What Is Encoding?](#sec-1)
- [2. What Is Categorical Data?](#sec-2)
- [3. Binary Categories](#sec-3)
- [4. Encoding with `map()`](#sec-4)
- [5. Encoding with `replace()`](#sec-5)
- [6. Pandas `category` Data Type](#sec-6)
- [7. `cat.codes`](#sec-7)
- [8. Ordinal Encoding](#sec-8)
- [9. One-Hot Encoding](#sec-9)
- [10. `drop_first=True`](#sec-10)
- [11. Encoding Multiple Columns](#sec-11)
- [12. Automatically Finding Categorical Columns](#sec-12)
- [13. Frequency Encoding](#sec-13)
- [14. Frequency as a Percentage](#sec-14)
- [15. Count Encoding](#sec-15)
- [16. Target Encoding](#sec-16)
- [17. Data Leakage in Target Encoding](#sec-17)
- [18. Multi-Hot Encoding](#sec-18)
- [19. Rare Categories](#sec-19)
- [20. Unknown Categories](#sec-20)
- [21. Binary Encoding](#sec-21)
- [22. Hash Encoding](#sec-22)
- [23. Scikit-learn `OneHotEncoder`](#sec-23)
- [24. `fit()` vs `transform()`](#sec-24)
- [25. Encoding With `ColumnTransformer`](#sec-25)
- [26. Pipeline](#sec-26)
- [27. Encoding Numerical-Looking Categories](#sec-27)
- [28. Choosing the Correct Encoding Technique](#sec-28)
- [29. Complete Encoding Example](#sec-29)
- [35. Final Revision Cheat Sheet](#sec-30)

> ✍️ Practice problems with solutions: [Topic_06_Practice_Solutions.ipynb](Topic_06_Practice_Solutions.ipynb)  ·  🗂️ [All topics](../Topic_00_All_Topics_Index.ipynb)

<a id="sec-1"></a>
# 1. What Is Encoding?

Suppose we have:

| Name | Gender | City |
|---|---|---|
| Ali | Male | Lahore |
| Sara | Female | Karachi |
| Ahmed | Male | Islamabad |

The values `Male`, `Female`, `Lahore`, `Karachi`, and `Islamabad` are categorical values.

A machine-learning model usually needs numerical input.

Encoding converts categorical information into numerical representation.

Conceptually:

```text
Categorical data
       ↓
    Encoding
       ↓
Numerical representation
       ↓
Machine-learning model
```

Encoding does NOT mean that the original category itself becomes mathematically ordered. The correct encoding technique depends on the type of categorical variable.

In [1]:
import pandas as pd
import numpy as np

df = pd.DataFrame({
    'Name': ['Ali', 'Sara', 'Ahmed', 'John'],
    'Gender': ['Male', 'Female', 'Male', 'Male'],
    'City': ['Lahore', 'Karachi', 'Islamabad', 'Lahore']
})

df

    Name  Gender       City
0    Ali    Male     Lahore
1   Sara  Female    Karachi
2  Ahmed    Male  Islamabad
3   John    Male     Lahore

> ✍️ **Practice time:** Practice Problem 1 — open [Topic_06_Practice_Solutions.ipynb](Topic_06_Practice_Solutions.ipynb) to solve it and see the solution.

<a id="sec-2"></a>
# 2. What Is Categorical Data?

A categorical column contains values that represent groups or categories.

Examples:

```text
Gender: Male, Female
City: Lahore, Karachi, Islamabad
Color: Red, Blue, Green
Browser: Chrome, Safari, Firefox
```

There are two important types:

## Nominal categorical data

There is no meaningful order.

Example:

```text
Lahore
Karachi
Islamabad
```

There is no mathematical meaning to saying one city is greater than another.

## Ordinal categorical data

There is a meaningful order.

Example:

```text
School < Bachelor < Master < PhD
```

Another example:

```text
Low < Medium < High
```

This distinction is one of the most important ideas when choosing an encoding method.

<a id="sec-3"></a>
# 3. Binary Categories

A binary categorical variable has only two possible categories.

Examples:

```text
Male / Female
Yes / No
True / False
Pass / Fail
```

A simple representation is:

```text
No  → 0
Yes → 1
```

For binary variables, mapping to 0 and 1 is often straightforward.

In [2]:
df = pd.DataFrame({
    'Gender': ['Male', 'Female', 'Male', 'Female', 'Male']
})

df['Gender_encoded'] = df['Gender'].map({
    'Female': 0,
    'Male': 1
})

df

   Gender  Gender_encoded
0    Male               1
1  Female               0
2    Male               1
3  Female               0
4    Male               1

> ✍️ **Practice time:** Practice Problem 2 — open [Topic_06_Practice_Solutions.ipynb](Topic_06_Practice_Solutions.ipynb) to solve it and see the solution.

<a id="sec-4"></a>
# 4. Encoding with `map()`

`map()` is very useful when you explicitly know the mapping you want.

Example:

```python
df['Gender'].map({'Female': 0, 'Male': 1})
```

Advantages:

- Easy to understand
- Explicit mapping
- Good for binary categories
- Good for ordinal categories when you define the correct order

Be careful: if a value does not exist in the mapping dictionary, `map()` can produce `NaN`.

In [3]:
df = pd.DataFrame({
    'Status': ['Active', 'Inactive', 'Active', 'Active']
})

df['Status_encoded'] = df['Status'].map({
    'Inactive': 0,
    'Active': 1
})

df

     Status  Status_encoded
0    Active               1
1  Inactive               0
2    Active               1
3    Active               1

> ✍️ **Practice time:** Practice Problem 3 — open [Topic_06_Practice_Solutions.ipynb](Topic_06_Practice_Solutions.ipynb) to solve it and see the solution.

<a id="sec-5"></a>
# 5. Encoding with `replace()`

`replace()` can also replace category names with numerical values.

Example:

```python
df['Gender'] = df['Gender'].replace({
    'Male': 1,
    'Female': 0
})
```

Difference in idea:

- `map()` is commonly used to create a transformed Series from a mapping.
- `replace()` is a more general replacement operation and can work across DataFrame values.

In [4]:
df = pd.DataFrame({
    'Gender': ['Male', 'Female', 'Male', 'Female']
})

df['Gender_encoded'] = df['Gender'].replace({
    'Male': 1,
    'Female': 0
})

df

   Gender Gender_encoded
0    Male              1
1  Female              0
2    Male              1
3  Female              0

> ✍️ **Practice time:** Practice Problem 4 — open [Topic_06_Practice_Solutions.ipynb](Topic_06_Practice_Solutions.ipynb) to solve it and see the solution.

<a id="sec-6"></a>
# 6. Pandas `category` Data Type

Pandas provides a special categorical data type.

You can convert a column using:

```python
df['City'] = df['City'].astype('category')
```

This is useful when a column contains repeated categorical values.

Categorical dtype can also provide a structured list of categories and can save memory in appropriate datasets.

In [5]:
df = pd.DataFrame({
    'City': ['Lahore', 'Karachi', 'Lahore', 'Islamabad', 'Karachi']
})

df['City'] = df['City'].astype('category')

print(df)
print(df['City'].cat.categories)

        City
0     Lahore
1    Karachi
2     Lahore
3  Islamabad
4    Karachi
Index(['Islamabad', 'Karachi', 'Lahore'], dtype='str')

> ✍️ **Practice time:** Practice Problem 5 — open [Topic_06_Practice_Solutions.ipynb](Topic_06_Practice_Solutions.ipynb) to solve it and see the solution.

<a id="sec-7"></a>
# 7. `cat.codes`

After converting a Series to categorical dtype, Pandas provides category codes.

Example:

```python
df['City'].astype('category').cat.codes
```

Important warning:

`cat.codes` assigns integer codes to categories, but those codes should not automatically be interpreted as meaningful numerical order.

For example:

```text
Lahore     → 1
Karachi    → 0
Islamabad  → 2
```

does NOT mean:

```text
Islamabad > Lahore > Karachi
```

For nominal categories, one-hot encoding is often safer.

In [6]:
df = pd.DataFrame({
    'City': ['Lahore', 'Karachi', 'Islamabad', 'Lahore']
})

df['City_category'] = df['City'].astype('category')
df['City_code'] = df['City_category'].cat.codes

df

        City City_category  City_code
0     Lahore        Lahore          2
1    Karachi       Karachi          1
2  Islamabad     Islamabad          0
3     Lahore        Lahore          2

> ✍️ **Practice time:** Practice Problem 6 — open [Topic_06_Practice_Solutions.ipynb](Topic_06_Practice_Solutions.ipynb) to solve it and see the solution.

<a id="sec-8"></a>
# 8. Ordinal Encoding

Ordinal encoding is appropriate when categories have a meaningful order.

Example:

```text
School
Bachelor
Master
PhD
```

We can encode:

```text
School   → 0
Bachelor → 1
Master   → 2
PhD      → 3
```

The numerical order represents the real-world order.

In [7]:
df = pd.DataFrame({
    'Education': [
        'Bachelor',
        'Master',
        'School',
        'PhD',
        'Master'
    ]
})

education_map = {
    'School': 0,
    'Bachelor': 1,
    'Master': 2,
    'PhD': 3
}

df['Education_encoded'] = df['Education'].map(education_map)

df

  Education  Education_encoded
0  Bachelor                  1
1    Master                  2
2    School                  0
3       PhD                  3
4    Master                  2

> ✍️ **Practice time:** Practice Problem 7 — open [Topic_06_Practice_Solutions.ipynb](Topic_06_Practice_Solutions.ipynb) to solve it and see the solution.

<a id="sec-9"></a>
# 9. One-Hot Encoding

One-Hot Encoding creates a separate binary column for each category.

Suppose:

```text
City
Lahore
Karachi
Islamabad
```

One-hot representation:

```text
City        Lahore  Karachi  Islamabad
Lahore         1       0         0
Karachi        0       1         0
Islamabad      0       0         1
```

This avoids creating an artificial numerical order between nominal categories.

In [8]:
df = pd.DataFrame({
    'City': ['Lahore', 'Karachi', 'Islamabad', 'Lahore']
})

encoded = pd.get_dummies(
    df,
    columns=['City'],
    dtype=int
)

encoded

   City_Islamabad  City_Karachi  City_Lahore
0               0             0            1
1               0             1            0
2               1             0            0
3               0             0            1

> ✍️ **Practice time:** Practice Problem 8 — open [Topic_06_Practice_Solutions.ipynb](Topic_06_Practice_Solutions.ipynb) to solve it and see the solution.

<a id="sec-10"></a>
# 10. `drop_first=True`

Pandas allows you to remove one dummy column:

```python
pd.get_dummies(
    df,
    columns=['City'],
    drop_first=True,
    dtype=int
)
```

If there are three categories, two dummy columns can be enough for many linear-model setups because the omitted category can be represented by all zeros.

However, `drop_first=True` should not be treated as a universal rule. The appropriate representation depends on the model and preprocessing design.

In [9]:
df = pd.DataFrame({
    'City': ['Lahore', 'Karachi', 'Islamabad', 'Lahore']
})

encoded = pd.get_dummies(
    df,
    columns=['City'],
    drop_first=True,
    dtype=int
)

encoded

   City_Karachi  City_Lahore
0             0            1
1             1            0
2             0            0
3             0            1

> ✍️ **Practice time:** Practice Problem 9 — open [Topic_06_Practice_Solutions.ipynb](Topic_06_Practice_Solutions.ipynb) to solve it and see the solution.

<a id="sec-11"></a>
# 11. Encoding Multiple Columns

A DataFrame can contain several categorical columns.

Example:

```text
Gender
City
Department
```

We can encode several columns at once with `get_dummies()`.

In [10]:
df = pd.DataFrame({
    'Age': [25, 30, 28, 35],
    'Gender': ['Male', 'Female', 'Male', 'Female'],
    'City': ['Lahore', 'Karachi', 'Islamabad', 'Lahore']
})

encoded = pd.get_dummies(
    df,
    columns=['Gender', 'City'],
    dtype=int
)

encoded

   Age  Gender_Female  Gender_Male  City_Islamabad  City_Karachi  City_Lahore
0   25              0            1               0             0            1
1   30              1            0               0             1            0
2   28              0            1               1             0            0
3   35              1            0               0             0            1

> ✍️ **Practice time:** Practice Problem 10 — open [Topic_06_Practice_Solutions.ipynb](Topic_06_Practice_Solutions.ipynb) to solve it and see the solution.

<a id="sec-12"></a>
# 12. Automatically Finding Categorical Columns

In a real dataset, you may have many columns.

You can find text/categorical columns using:

```python
df.select_dtypes(include=['object', 'string', 'category']).columns
```

> **pandas 3 note:** since pandas 3.0, text columns get the new `str` dtype by default instead of `object`.
> `select_dtypes(include='object')` still finds them, but prints a `Pandas4Warning` saying this will stop
> working in pandas 4. Listing `'string'` (and `'category'` for categorical columns) is the future-proof way.

This is useful when preprocessing large datasets.

In [11]:
df = pd.DataFrame({
    'Age': [25, 30, 28],
    'Gender': ['Male', 'Female', 'Male'],
    'City': ['Lahore', 'Karachi', 'Lahore'],
    'Salary': [50000, 70000, 60000]
})

categorical_columns = df.select_dtypes(
    include=['object', 'string', 'category']
).columns

print(categorical_columns)

Index(['Gender', 'City'], dtype='str')

> ✍️ **Practice time:** Practice Problem 11 — open [Topic_06_Practice_Solutions.ipynb](Topic_06_Practice_Solutions.ipynb) to solve it and see the solution.

<a id="sec-13"></a>
# 13. Frequency Encoding

Frequency encoding replaces each category with how frequently it appears.

Example:

```text
Lahore      appears 3 times
Karachi     appears 2 times
Islamabad   appears 1 time
```

Frequency encoding:

```text
Lahore     → 3
Karachi    → 2
Islamabad  → 1
```

This can be useful for high-cardinality categorical variables.

In [12]:
df = pd.DataFrame({
    'City': [
        'Lahore',
        'Lahore',
        'Lahore',
        'Karachi',
        'Karachi',
        'Islamabad'
    ]
})

frequency = df['City'].value_counts()

df['City_frequency'] = df['City'].map(frequency)

df

        City  City_frequency
0     Lahore               3
1     Lahore               3
2     Lahore               3
3    Karachi               2
4    Karachi               2
5  Islamabad               1

> ✍️ **Practice time:** Practice Problem 12 — open [Topic_06_Practice_Solutions.ipynb](Topic_06_Practice_Solutions.ipynb) to solve it and see the solution.

> 🧩 **Data used by the next sections** — this code comes from *Practice Problem 12* (in the practice notebook). Run it so the examples below work.

In [13]:


data = {
    "Name": ["Ali", "Sara", "Ahmed", "Ayesha", "Usman", "Fatima"],
    "Gender": ["Male", "Female", "Male", "Female", "Male", "Female"],
    "City": ["Lahore", "Karachi", "Islamabad", "Lahore", "Karachi", "Islamabad"],
    "Education": ["Bachelor", "Master", "Bachelor", "PhD", "Master", "Bachelor"],
    "Age": [22, 28, 25, 35, 30, 24],
    "Purchased": ["Yes", "No", "Yes", "Yes", "No", "Yes"],
    "Product": ["Laptop", "Phone", "Laptop", "Tablet", "Phone", "Laptop"]
}

df = pd.DataFrame(data)
freq= df["Product"].value_counts();


df["Product-Feq"] = df["Product"].map(freq)
df

     Name  Gender       City Education  Age Purchased Product  Product-Feq
0     Ali    Male     Lahore  Bachelor   22       Yes  Laptop            3
1    Sara  Female    Karachi    Master   28        No   Phone            2
2   Ahmed    Male  Islamabad  Bachelor   25       Yes  Laptop            3
3  Ayesha  Female     Lahore       PhD   35       Yes  Tablet            1
4   Usman    Male    Karachi    Master   30        No   Phone            2
5  Fatima  Female  Islamabad  Bachelor   24       Yes  Laptop            3

<a id="sec-14"></a>
# 14. Frequency as a Percentage

You can calculate relative frequency with:

```python
value_counts(normalize=True)
```

For example, if a category appears in 50% of the rows, its frequency encoding becomes `0.50`.

In [14]:
frequency_percentage = df['City'].value_counts(normalize=True)

print(frequency_percentage)
df['City_frequency_percentage'] = df['City'].map(
    frequency_percentage
)

df

City
Lahore       0.333333
Karachi      0.333333
Islamabad    0.333333
Name: proportion, dtype: float64

,Name,Gender,City,Education,Age,Purchased,Product,Product-Feq,City_frequency_percentage
0,Ali,Male,Lahore,Bachelor,22,Yes,Laptop,3,0.333333
1,Sara,Female,Karachi,Master,28,No,Phone,2,0.333333
2,Ahmed,Male,Islamabad,Bachelor,25,Yes,Laptop,3,0.333333
3,Ayesha,Female,Lahore,PhD,35,Yes,Tablet,1,0.333333
4,Usman,Male,Karachi,Master,30,No,Phone,2,0.333333
5,Fatima,Female,Islamabad,Bachelor,24,Yes,Laptop,3,0.333333

> ✍️ **Practice time:** Practice Problem 13 — open [Topic_06_Practice_Solutions.ipynb](Topic_06_Practice_Solutions.ipynb) to solve it and see the solution.

<a id="sec-15"></a>
# 15. Count Encoding

Count encoding is closely related to frequency encoding.

Instead of representing the category itself, we represent how many times that category appears.

Example:

```text
Chrome → 500
Safari → 300
Firefox → 200
```

The key idea is:

```python
counts = df['Browser'].value_counts()
df['Browser_count'] = df['Browser'].map(counts)
```

In [15]:
df = pd.DataFrame({
    'Browser': [
        'Chrome', 'Chrome', 'Safari',
        'Firefox', 'Chrome', 'Safari'
    ]
})

counts = df['Browser'].value_counts()

df['Browser_count'] = df['Browser'].map(counts)

df

   Browser  Browser_count
0   Chrome              3
1   Chrome              3
2   Safari              2
3  Firefox              1
4   Chrome              3
5   Safari              2

> ✍️ **Practice time:** Practice Problem 14 — open [Topic_06_Practice_Solutions.ipynb](Topic_06_Practice_Solutions.ipynb) to solve it and see the solution.

<a id="sec-16"></a>
# 16. Target Encoding

Target encoding replaces each category with a statistic calculated from the target variable, commonly the mean target value for that category.

Example:

| City | Purchased |
|---|---:|
| Lahore | 1 |
| Lahore | 1 |
| Lahore | 0 |
| Karachi | 0 |
| Karachi | 0 |
| Islamabad | 1 |

Mean purchase rate:

```text
Lahore     → (1 + 1 + 0) / 3 = 0.67
Karachi    → (0 + 0) / 2 = 0.00
Islamabad  → 1 / 1 = 1.00
```

The category is therefore represented using information about the target.

In [16]:
df = pd.DataFrame({
    'City': [
        'Lahore', 'Lahore', 'Lahore',
        'Karachi', 'Karachi', 'Islamabad'
    ],
    'Purchased': [1, 1, 0, 0, 0, 1]
})

target_mean = df.groupby('City')['Purchased'].mean()

df['City_target_encoded'] = df['City'].map(target_mean)

df

        City  Purchased  City_target_encoded
0     Lahore          1             0.666667
1     Lahore          1             0.666667
2     Lahore          0             0.666667
3    Karachi          0             0.000000
4    Karachi          0             0.000000
5  Islamabad          1             1.000000

> ✍️ **Practice time:** Practice Problem 15 — open [Topic_06_Practice_Solutions.ipynb](Topic_06_Practice_Solutions.ipynb) to solve it and see the solution.

<a id="sec-17"></a>
# 17. Data Leakage in Target Encoding

Target encoding has an important risk: **data leakage**.

If you calculate target statistics using the entire dataset before splitting into training and test data, information from the test set can influence the features.

This is especially dangerous when the category has few observations.

Correct high-level workflow:

```text
Raw data
   ↓
Train/Test split
   ↓
Learn encoding from training data
   ↓
Transform training data
   ↓
Transform test data using training mapping
```

Never allow test-target information to influence training preprocessing.

> ✍️ **Practice time:** Practice Problem 16 — Leakage Detection — open [Topic_06_Practice_Solutions.ipynb](Topic_06_Practice_Solutions.ipynb) to solve it and see the solution.

<a id="sec-18"></a>
# 18. Multi-Hot Encoding

Sometimes one row can contain multiple categories.

Example:

| User | Skills |
|---|---|
| Ali | Python,SQL |
| Sara | Python,Java |
| John | Java,React |

A user can have multiple skills, so each row can contain multiple `1` values.

Result:

```text
User   Python  SQL  Java  React
Ali       1      1     0      0
Sara      1      0     1      0
John      0      0     1      1
```

This is commonly called multi-hot encoding.

In [17]:
df = pd.DataFrame({
    'User': ['Ali', 'Sara', 'John'],
    'Skills': [
        'Python,SQL',
        'Python,Java',
        'Java,React'
    ]
})

skills_encoded = df['Skills'].str.get_dummies(sep=',')

skills_encoded

   Java  Python  React  SQL
0     0       1      0    1
1     1       1      0    0
2     1       0      1    0

> ✍️ **Practice time:** Practice Problem 17 — open [Topic_06_Practice_Solutions.ipynb](Topic_06_Practice_Solutions.ipynb) to solve it and see the solution.

<a id="sec-19"></a>
# 19. Rare Categories

Imagine a dataset contains:

```text
Lahore      5000
Karachi     4000
Islamabad   3000
Multan        20
Quetta        10
Peshawar       5
```

If there are hundreds or thousands of rare categories, one-hot encoding may create many columns.

A common strategy is to group rare categories into `Other`.

For example:

```text
Multan   → Other
Quetta   → Other
Peshawar → Other
```

In [18]:
df = pd.DataFrame({
    'City': [
        'Lahore', 'Lahore', 'Lahore', 'Lahore',
        'Karachi', 'Karachi',
        'Islamabad',
        'Multan',
        'Quetta'
    ]
})

counts = df['City'].value_counts()

threshold = 2

rare_categories = counts[counts < threshold].index

# Create a copy so the original category column is preserved.
df['City_grouped'] = df['City'].where(
    ~df['City'].isin(rare_categories),
    'Other'
)

print(df)

        City City_grouped
0     Lahore       Lahore
1     Lahore       Lahore
2     Lahore       Lahore
3     Lahore       Lahore
4    Karachi      Karachi
5    Karachi      Karachi
6  Islamabad        Other
7     Multan        Other
8     Quetta        Other

> ✍️ **Practice time:** Practice Problem 18 — open [Topic_06_Practice_Solutions.ipynb](Topic_06_Practice_Solutions.ipynb) to solve it and see the solution.

<a id="sec-20"></a>
# 20. Unknown Categories

A common real-world problem occurs when training data contains:

```text
Lahore
Karachi
Islamabad
```

but future data contains:

```text
Multan
```

The encoder needs a strategy for unseen categories.

In machine-learning workflows, Scikit-learn's `OneHotEncoder` supports:

```python
handle_unknown='ignore'
```

This prevents an unseen category from causing an error during transformation.

> ✍️ **Practice time:** Practice Problem 19 — open [Topic_06_Practice_Solutions.ipynb](Topic_06_Practice_Solutions.ipynb) to solve it and see the solution.

<a id="sec-21"></a>
# 21. Binary Encoding

Binary encoding represents categories using binary digits.

Suppose there are eight categories:

```text
A → 000
B → 001
C → 010
D → 011
E → 100
F → 101
G → 110
H → 111
```

One-hot encoding would need eight columns.

Binary encoding needs only three binary columns for eight categories.

Binary encoding is especially useful when categorical cardinality is large.

For practical implementation, libraries such as `category_encoders` can be used.

> ✍️ **Practice time:** Practice Problem 20 — open [Topic_06_Practice_Solutions.ipynb](Topic_06_Practice_Solutions.ipynb) to solve it and see the solution.

<a id="sec-22"></a>
# 22. Hash Encoding

Hash encoding maps categories to a fixed number of columns using a hashing function.

Conceptually:

```text
100,000 unique categories
          ↓
     Hash encoding
          ↓
      100 columns
```

The main advantage is controlling the number of output features.

The trade-off is that different categories can sometimes map to the same location. This is called a hash collision.

> ✍️ **Practice time:** Practice Problem 21 — open [Topic_06_Practice_Solutions.ipynb](Topic_06_Practice_Solutions.ipynb) to solve it and see the solution.

<a id="sec-23"></a>
# 23. Scikit-learn `OneHotEncoder`

For production machine-learning pipelines, Scikit-learn's `OneHotEncoder` is often more suitable than manually encoding train and test data independently.

Important parameters include:

- `handle_unknown='ignore'`
- `sparse_output=False`

The encoder learns categories from the training data and then transforms new data using the learned representation.

In [19]:
from sklearn.preprocessing import OneHotEncoder

train = pd.DataFrame({
    'City': ['Lahore', 'Karachi', 'Islamabad', 'Lahore']
})

encoder = OneHotEncoder(
    handle_unknown='ignore',
    sparse_output=False
)

train_encoded = encoder.fit_transform(train[['City']])

train_encoded

array([[0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.]])

<a id="sec-24"></a>
# 24. `fit()` vs `transform()`

This distinction is critical in machine learning.

### `fit()`

The encoder learns information from data.

For one-hot encoding, it learns the available categories.

### `transform()`

The encoder applies what it already learned to new data.

Correct workflow:

```python
encoder.fit(X_train)
X_train_encoded = encoder.transform(X_train)
X_test_encoded = encoder.transform(X_test)
```

Shortcut for training data:

```python
X_train_encoded = encoder.fit_transform(X_train)
```

Do NOT fit a separate encoder on the test data.

In [20]:
train = pd.DataFrame({
    'City': ['Lahore', 'Karachi', 'Islamabad', 'Lahore']
})

test = pd.DataFrame({
    'City': ['Lahore', 'Multan']
})

encoder = OneHotEncoder(
    handle_unknown='ignore',
    sparse_output=False
)

X_train = encoder.fit_transform(train[['City']])
X_test = encoder.transform(test[['City']])

print('Train:')
print(X_train)

print('\nTest:')
print(X_test)

Train:
[[0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]]

Test:
[[0. 0. 1.]
 [0. 0. 0.]]

> ✍️ **Practice time:** Practice Problem 22 — open [Topic_06_Practice_Solutions.ipynb](Topic_06_Practice_Solutions.ipynb) to solve it and see the solution.

<a id="sec-25"></a>
# 25. Encoding With `ColumnTransformer`

Real datasets contain both numerical and categorical columns.

Example:

```text
Age       → numerical
Salary    → numerical
Gender    → categorical
City      → categorical
```

We can apply different preprocessing to different columns using `ColumnTransformer`.

In [21]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler, OneHotEncoder

X = pd.DataFrame({
    'Age': [25, 30, 28, 35],
    'Salary': [50000, 70000, 60000, 90000],
    'Gender': ['Male', 'Female', 'Male', 'Female'],
    'City': ['Lahore', 'Karachi', 'Islamabad', 'Lahore']
})

numeric_features = ['Age', 'Salary']
categorical_features = ['Gender', 'City']

preprocessor = ColumnTransformer(
    transformers=[
        (
            'num',
            StandardScaler(),
            numeric_features
        ),
        (
            'cat',
            OneHotEncoder(handle_unknown='ignore'),
            categorical_features
        )
    ]
)

X_transformed = preprocessor.fit_transform(X)

print(X_transformed)

[[-1.23624508 -1.18321596  0.          1.          0.          0.
   1.        ]
 [ 0.13736056  0.16903085  1.          0.          0.          1.
   0.        ]
 [-0.41208169 -0.50709255  0.          1.          1.          0.
   0.        ]
 [ 1.5109662   1.52127766  1.          0.          0.          0.
   1.        ]]

> ✍️ **Practice time:** Practice Problem 23 — open [Topic_06_Practice_Solutions.ipynb](Topic_06_Practice_Solutions.ipynb) to solve it and see the solution.

<a id="sec-26"></a>
# 26. Pipeline

A Pipeline allows preprocessing and model training to be connected into one workflow.

Conceptually:

```text
Raw data
   ↓
Preprocessing
   ↓
Encoding
   ↓
Scaling
   ↓
Machine-learning model
```

This reduces the chance of accidentally applying inconsistent preprocessing.

In [22]:
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LogisticRegression

pipeline = Pipeline([
    ('preprocessor', preprocessor),
    ('model', LogisticRegression())
])

print(pipeline)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('num', StandardScaler(),
                                                  ['Age', 'Salary']),
                                                 ('cat',
                                                  OneHotEncoder(handle_unknown='ignore'),
                                                  ['Gender', 'City'])])),
                ('model', LogisticRegression())])

> ✍️ **Practice time:** Practice Problem 24 — open [Topic_06_Practice_Solutions.ipynb](Topic_06_Practice_Solutions.ipynb) to solve it and see the solution.

<a id="sec-27"></a>
# 27. Encoding Numerical-Looking Categories

Be careful with columns that look numerical but are actually categories.

For example:

```text
PostalCode
54000
44000
75000
```

If postal code is an identifier rather than a quantity, treating it as a continuous numerical feature may be inappropriate.

Always ask:

> Does this number represent a measurable quantity, or is it just a category/identifier?

> ✍️ **Practice time:** Practice Problem 25 — open [Topic_06_Practice_Solutions.ipynb](Topic_06_Practice_Solutions.ipynb) to solve it and see the solution.

<a id="sec-28"></a>
# 28. Choosing the Correct Encoding Technique

Use this mental decision process.

```text
Categorical variable
        |
        v
Does it have a meaningful order?
        |
   +----+----+
   |         |
  Yes        No
   |         |
Ordinal    How many categories?
Encoding       |
          +----+----+
          |         |
         Few       Many
          |         |
       One-Hot   Consider frequency,
                 target, binary, or hash
```

Examples:

| Feature | Possible technique |
|---|---|
| Yes/No | Binary |
| Gender | Binary or one-hot |
| City | One-hot |
| Education level | Ordinal |
| Satisfaction level | Ordinal |
| Browser | One-hot |
| Very high-cardinality ID-like feature | Frequency/hash/other domain-specific strategy |
| Multiple skills per user | Multi-hot |
| Category with target relationship | Target encoding with leakage controls |

> ✍️ **Practice time:** Practice Problem 26 — Choose the Encoding — open [Topic_06_Practice_Solutions.ipynb](Topic_06_Practice_Solutions.ipynb) to solve it and see the solution.

<a id="sec-29"></a>
# 29. Complete Encoding Example

Now we will combine several encoding concepts in one dataset.

In [23]:
df = pd.DataFrame({
    'Age': [22, 25, 30, 35, 28, 40, 26, 31],
    'Gender': [
        'Male', 'Female', 'Male', 'Female',
        'Male', 'Male', 'Female', 'Female'
    ],
    'Education': [
        'Bachelor', 'Master', 'PhD', 'School',
        'Master', 'PhD', 'Bachelor', 'Master'
    ],
    'City': [
        'Lahore', 'Karachi', 'Lahore', 'Islamabad',
        'Karachi', 'Lahore', 'Multan', 'Karachi'
    ],
    'Purchased': [1, 1, 0, 0, 1, 1, 0, 1]
})

print(df)

   Age  Gender Education       City  Purchased
0   22    Male  Bachelor     Lahore          1
1   25  Female    Master    Karachi          1
2   30    Male       PhD     Lahore          0
3   35  Female    School  Islamabad          0
4   28    Male    Master    Karachi          1
5   40    Male       PhD     Lahore          1
6   26  Female  Bachelor     Multan          0
7   31  Female    Master    Karachi          1

## Step 1 — Identify column types

Numerical:

```text
Age
Purchased
```

Categorical:

```text
Gender
Education
City
```

`Education` is ordinal because it has a meaningful educational progression.

`City` is nominal because cities do not have a natural numerical order.

In [24]:
df['Gender_encoded'] = df['Gender'].map({
    'Female': 0,
    'Male': 1
})

education_map = {
    'School': 0,
    'Bachelor': 1,
    'Master': 2,
    'PhD': 3
}

df['Education_encoded'] = df['Education'].map(education_map)

df

,Age,Gender,Education,City,Purchased,Gender_encoded,Education_encoded
0,22,Male,Bachelor,Lahore,1,1,1
1,25,Female,Master,Karachi,1,0,2
2,30,Male,PhD,Lahore,0,1,3
3,35,Female,School,Islamabad,0,0,0
4,28,Male,Master,Karachi,1,1,2
5,40,Male,PhD,Lahore,1,1,3
6,26,Female,Bachelor,Multan,0,0,1
7,31,Female,Master,Karachi,1,0,2

## Step 2 — One-hot encode City

City is nominal, so we avoid imposing an artificial order.

In [25]:
df_encoded = pd.get_dummies(
    df,
    columns=['City'],
    dtype=int
)

print(df_encoded)

   Age  Gender Education  Purchased  Gender_encoded  Education_encoded  \
0   22    Male  Bachelor          1               1                  1
1   25  Female    Master          1               0                  2
2   30    Male       PhD          0               1                  3
3   35  Female    School          0               0                  0
4   28    Male    Master          1               1                  2
5   40    Male       PhD          1               1                  3
6   26  Female  Bachelor          0               0                  1
7   31  Female    Master          1               0                  2

   City_Islamabad  City_Karachi  City_Lahore  City_Multan
0               0             0            1            0
1               0             1            0            0
2               0             0            1            0
3               1             0            0            0
4               0             1            0            0
5               0             0            1            0
6               0             0            0            1
7               0             1            0            0

> ✍️ **Practice time:** Practice Problem 27 — Full Manual Encoding, 30. Advanced Exercise — Train/Test Encoding, 31. Advanced Exercise — Target Encoding, 32. Advanced Exercise — High Cardinality, 33. Final Project — Customer Purchase Prediction, 34. Interview Questions — open [Topic_06_Practice_Solutions.ipynb](Topic_06_Practice_Solutions.ipynb) to solve it and see the solution.

<a id="sec-30"></a>
# 35. Final Revision Cheat Sheet

## Binary

```text
Yes → 1
No  → 0
```

Use for two-category variables when a binary representation makes sense.

## Ordinal

```text
Low → 0
Medium → 1
High → 2
```

Use when there is a meaningful order.

## One-Hot

```text
Lahore → [1,0,0]
Karachi → [0,1,0]
Islamabad → [0,0,1]
```

Use commonly for nominal categories with manageable cardinality.

## Frequency

```text
Lahore → 500
Karachi → 300
```

Represent categories using their occurrence frequency.

## Target

```text
Category → target statistic
```

Powerful but requires careful leakage prevention.

## Multi-Hot

One row can contain multiple active categories.

## Binary / Hash Encoding

Useful techniques to investigate when cardinality becomes very large.

---

### Most important rule

```text
Train data
    ↓
fit preprocessing
    ↓
transform train
    ↓
transform test using the SAME learned preprocessing
```

Never independently learn preprocessing from the test set.