# Topic 03 — Handling Missing Values — ✍️ Practice & Solutions

This notebook has every **practice problem** for Topic 03, each followed by its **✅ solution**.

**How to use it**
1. Read the lesson first: [Topic_03_Lesson.ipynb](Topic_03_Lesson.ipynb).
2. Read a problem and write your answer in the code cell under it.
3. Only then scroll down to the ✅ solution and compare.
4. Stuck or confused? Go back to the matching lesson section — every solution uses only what the lesson teaches.

> 📚 **Course navigation** — you are in **Topic 03: Handling Missing Values**
> ⬅️ Previous: [Topic 02 — Pandas DataFrame Basics](../Topic_02_Pandas_DataFrame_Basics/Topic_02_Lesson.ipynb)  ·  ➡️ Next: [Topic 04 — Normalization & Standardization](../Topic_04_Normalization_Standardization/Topic_04_Lesson.ipynb)  ·  🗂️ [All topics](../Topic_00_All_Topics_Index.ipynb)

<details><summary>Full course sequence (click to expand)</summary>

| # | Topic | Lesson | Practice & Solutions |
|---|---|---|---|
| 01 | Python Basics | [📖 Lesson](../Topic_01_Python_Basics/Topic_01_Lesson.ipynb) | [✍️ Practice](../Topic_01_Python_Basics/Topic_01_Practice_Solutions.ipynb) |
| 02 | Pandas DataFrame Basics | [📖 Lesson](../Topic_02_Pandas_DataFrame_Basics/Topic_02_Lesson.ipynb) | [✍️ Practice](../Topic_02_Pandas_DataFrame_Basics/Topic_02_Practice_Solutions.ipynb) |
| **▶ 03 ◀** | **Handling Missing Values** | [📖 Lesson](../Topic_03_Handling_Missing_Values/Topic_03_Lesson.ipynb) | [✍️ Practice](../Topic_03_Handling_Missing_Values/Topic_03_Practice_Solutions.ipynb) |
| 04 | Normalization & Standardization | [📖 Lesson](../Topic_04_Normalization_Standardization/Topic_04_Lesson.ipynb) | [✍️ Practice](../Topic_04_Normalization_Standardization/Topic_04_Practice_Solutions.ipynb) |
| 05 | Detecting & Treating Outliers | [📖 Lesson](../Topic_05_Outliers/Topic_05_Lesson.ipynb) | [✍️ Practice](../Topic_05_Outliers/Topic_05_Practice_Solutions.ipynb) |
| 🎯 | *🎯 Quiz 1 — Topics 01–05* | [🎯 Quiz 1](../Quiz_1_Topics_01-05/Quiz_1.ipynb) | |
| 06 | Encoding Techniques | [📖 Lesson](../Topic_06_Encoding_Techniques/Topic_06_Lesson.ipynb) | [✍️ Practice](../Topic_06_Encoding_Techniques/Topic_06_Practice_Solutions.ipynb) |
| 07 | Exploratory Data Analysis (EDA) | [📖 Lesson](../Topic_07_Exploratory_Data_Analysis/Topic_07_Lesson.ipynb) | [✍️ Practice](../Topic_07_Exploratory_Data_Analysis/Topic_07_Practice_Solutions.ipynb) |
| 08 | Data Visualization | [📖 Lesson](../Topic_08_Data_Visualization/Topic_08_Lesson.ipynb) | [✍️ Practice](../Topic_08_Data_Visualization/Topic_08_Practice_Solutions.ipynb) |
| 09 | Pandas Data Manipulation | [📖 Lesson](../Topic_09_Pandas_Data_Manipulation/Topic_09_Lesson.ipynb) | [✍️ Practice](../Topic_09_Pandas_Data_Manipulation/Topic_09_Practice_Solutions.ipynb) |
| 10 | Combining DataFrames | [📖 Lesson](../Topic_10_Combining_DataFrames/Topic_10_Lesson.ipynb) | [✍️ Practice](../Topic_10_Combining_DataFrames/Topic_10_Practice_Solutions.ipynb) |
| 🎯 | *🎯 Quiz 2 — Topics 06–10* | [🎯 Quiz 2](../Quiz_2_Topics_06-10/Quiz_2.ipynb) | |
| 11 | Feature Engineering | [📖 Lesson](../Topic_11_Feature_Engineering/Topic_11_Lesson.ipynb) | [✍️ Practice](../Topic_11_Feature_Engineering/Topic_11_Practice_Solutions.ipynb) |
| 11b | KBinsDiscretizer (Discretization) | [📖 Lesson](../Topic_11b_KBinsDiscretizer/Topic_11b_Lesson.ipynb) | [✍️ Practice](../Topic_11b_KBinsDiscretizer/Topic_11b_Practice_Solutions.ipynb) |
| 12 | Correlation & Multicollinearity | [📖 Lesson](../Topic_12_Correlation_Multicollinearity/Topic_12_Lesson.ipynb) | [✍️ Practice](../Topic_12_Correlation_Multicollinearity/Topic_12_Practice_Solutions.ipynb) |
| 13 | Data Transformation & Skewness | [📖 Lesson](../Topic_13_Data_Transformation_Skewness/Topic_13_Lesson.ipynb) | [✍️ Practice](../Topic_13_Data_Transformation_Skewness/Topic_13_Practice_Solutions.ipynb) |
| 14 | Statistics for Data Science | [📖 Lesson](../Topic_14_Statistics_for_Data_Science/Topic_14_Lesson.ipynb) | [✍️ Practice](../Topic_14_Statistics_for_Data_Science/Topic_14_Practice_Solutions.ipynb) |
| 🎯 | *🎯 Quiz 3 — Topics 11–14* | [🎯 Quiz 3](../Quiz_3_Topics_11-14/Quiz_3.ipynb) | |
| 15 | Probability for Data Science & ML | [📖 Lesson](../Topic_15_Probability_for_Data_Science_ML/Topic_15_Lesson.ipynb) | [✍️ Practice](../Topic_15_Probability_for_Data_Science_ML/Topic_15_Practice_Solutions.ipynb) |
| 16 | Feature Selection | [📖 Lesson](../Topic_16_Feature_Selection/Topic_16_Lesson.ipynb) | [✍️ Practice](../Topic_16_Feature_Selection/Topic_16_Practice_Solutions.ipynb) |
| 17 | Machine Learning | [📖 Lesson](../Topic_17_Machine_Learning/Topic_17_Lesson.ipynb) | [✍️ Practice](../Topic_17_Machine_Learning/Topic_17_Practice_Solutions.ipynb) |
| 🎯 | *🏁 Final Quiz — Topics 15–17* | [🏁 Final Quiz](../Quiz_4_Topics_15-17/Quiz_4.ipynb) | |

</details>

## 📋 Practice Index

**38 problems** — each one is followed by your answer cell and then its ✅ solution. Click a problem to jump to it.

- [Practice 1 — Create a DataFrame](#p-1)
- [Practice 2 — Basic inspection](#p-2)
- [Practice 3 — Detect missing values](#p-3)
- [Practice 4 — Missing counts](#p-4)
- [Practice 5 — Total missing values](#p-5)
- [Practice 6 — Missing percentage](#p-6)
- [Practice 7 — Build the report](#p-7)
- [Practice 8 — Incomplete rows](#p-8)
- [Practice 9 — Complete rows](#p-9)
- [Practice 10 — Drop incomplete rows](#p-10)
- [Practice 11 — Use `subset`](#p-11)
- [Practice 12 — Drop columns](#p-12)
- [Practice 13 — Compare `any` and `all`](#p-13)
- [Practice 14 — Use `thresh`](#p-14)
- [Practice 15 — Fixed-value filling](#p-15)
- [Practice 16 — Mean imputation](#p-16)
- [Practice 17 — Median imputation](#p-17)
- [Practice 18 — Compare mean and median](#p-18)
- [Practice 19 — Mode imputation](#p-19)
- [Practice 20 — Unknown category](#p-20)
- [Practice 21 — Forward fill](#p-21)
- [Practice 22 — Backward fill](#p-22)
- [Practice 23 — Interpolation](#p-23)
- [Practice 24 — Standardize markers](#p-24)
- [Practice 25 — CSV import](#p-25)
- [Practice 26 — Column-specific strategies](#p-26)
- [Practice 27 — Numeric mean filling](#p-27)
- [Practice 28 — Group-based filling](#p-28)
- [Practice 29 — Filter by missingness](#p-29)
- [Practice 30 — Assignment approach](#p-30)
- [Practice 31 — Complete workflow](#p-31)
- [32. Comprehensive Practice Dataset](#p-32)
- [Practice 32 — Full analysis challenge](#p-33)
- [Practice 32b-1 — Missingness type](#p-34)
- [Practice 32b-2 — SimpleImputer without leakage](#p-35)
- [Practice 32b-3 — KNN vs median](#p-36)
- [33. Advanced Decision-Making Challenge](#p-37)
- [34. Final Exam — No Hints](#p-38)

> 📖 Lesson for this topic: [Topic_03_Lesson.ipynb](Topic_03_Lesson.ipynb)

### ⚙️ Setup — run this cell first

Some problems use data, variables and functions created in the lesson. This cell quietly runs the whole lesson notebook so they all exist here.

In [1]:
%%capture
# Runs the lesson notebook (output hidden) so its variables exist here
%run ./Topic_03_Lesson.ipynb

<a id="p-1"></a>
### Practice 1 — Create a DataFrame

Create your own DataFrame with at least 4 columns and several missing values.

In [2]:
import pandas as pd
import numpy as np

df = pd.DataFrame({
    "Name": [
        "Ali", "Sara", "Ahmed", "Ayesha", "Usman",
        "Hassan", "Fatima", "Bilal", "Zainab", "Hamza",
        "Omar", "Mariam", "Saad", "Hira", "Talha",
        "Noor", "Danish", "Iqra", "Fahad", "Sana",
        "Kamran", "Laiba", "Raza", "Anum", "Waleed",
        "Mahnoor", "Salman", "Eman", "Arslan", "Areeba"
    ],

    "Age": [
        23, np.nan, 30, 27, np.nan,
        35, 24, np.nan, 29, 31,
        np.nan, 26, 40, np.nan, 28,
        33, 22, np.nan, 36, 25,
        29, np.nan, 34, 27, np.nan,
        31, 24, np.nan, 38, 26
    ],

    "Salary": [
        90000, 75000, np.nan, 85000, 65000,
        np.nan, 72000, 95000, np.nan, 88000,
        70000, np.nan, 120000, 68000, np.nan,
        105000, 60000, 78000, np.nan, 82000,
        91000, np.nan, 99000, 73000, 67000,
        np.nan, 86000, 71000, np.nan, 80000
    ],

    "Department": [
        "IT", "HR", np.nan, "IT", "Finance",
        "Marketing", "HR", np.nan, "IT", "Finance",
        "Sales", "HR", "IT", np.nan, "Marketing",
        "IT", "Finance", "Sales", np.nan, "HR",
        "IT", "Finance", np.nan, "HR", "Sales",
        "IT", np.nan, "Marketing", "Finance", "HR"
    ]
})

print(df)

       Name   Age    Salary Department
0       Ali  23.0   90000.0         IT
1      Sara   NaN   75000.0         HR
2     Ahmed  30.0       NaN        NaN
3    Ayesha  27.0   85000.0         IT
4     Usman   NaN   65000.0    Finance
5    Hassan  35.0       NaN  Marketing
6    Fatima  24.0   72000.0         HR
7     Bilal   NaN   95000.0        NaN
8    Zainab  29.0       NaN         IT
9     Hamza  31.0   88000.0    Finance
10     Omar   NaN   70000.0      Sales
11   Mariam  26.0       NaN         HR
12     Saad  40.0  120000.0         IT
13     Hira   NaN   68000.0        NaN
14    Talha  28.0       NaN  Marketing
15     Noor  33.0  105000.0         IT
16   Danish  22.0   60000.0    Finance
17     Iqra   NaN   78000.0      Sales
18    Fahad  36.0       NaN        NaN
19     Sana  25.0   82000.0         HR
20   Kamran  29.0   91000.0         IT
21    Laiba   NaN       NaN    Finance
22     Raza  34.0   99000.0        NaN
23     Anum  27.0   73000.0         HR
24   Waleed   NaN   67000.0      Sales
25  Mahnoor  31.0       NaN         IT
26   Salman  24.0   86000.0        NaN
27     Eman   NaN   71000.0  Marketing
28   Arslan  38.0       NaN    Finance
29   Areeba  26.0   80000.0         HR

<a id="p-2"></a>
### Practice 2 — Basic inspection

Display the first 3 rows, shape, column names, and data types.

In [3]:
print(df.head(3))
print(df.shape)
print(df.columns)
print(df.dtypes)

    Name   Age   Salary Department
0    Ali  23.0  90000.0         IT
1   Sara   NaN  75000.0         HR
2  Ahmed  30.0      NaN        NaN
(30, 4)
Index(['Name', 'Age', 'Salary', 'Department'], dtype='str')
Name              str
Age           float64
Salary        float64
Department        str
dtype: object

<a id="p-3"></a>
### Practice 3 — Detect missing values

Create a Boolean DataFrame showing missing values.

In [4]:
print(df.isna())

     Name    Age  Salary  Department
0   False  False   False       False
1   False   True   False       False
2   False  False    True        True
3   False  False   False       False
4   False   True   False       False
5   False  False    True       False
6   False  False   False       False
7   False   True   False        True
8   False  False    True       False
9   False  False   False       False
10  False   True   False       False
11  False  False    True       False
12  False  False   False       False
13  False   True   False        True
14  False  False    True       False
15  False  False   False       False
16  False  False   False       False
17  False   True   False       False
18  False  False    True        True
19  False  False   False       False
20  False  False   False       False
21  False   True    True       False
22  False  False   False        True
23  False  False   False       False
24  False   True   False       False
25  False  False    True       False
26  False  False   False        True
27  False   True   False       False
28  False  False    True       False
29  False  False   False       False

<a id="p-4"></a>
### Practice 4 — Missing counts

Find the number of missing values in every column.

In [5]:
missing_count = df.isna().sum()
print(missing_count)

Name          0
Age           9
Salary        9
Department    6
dtype: int64

<a id="p-5"></a>
### Practice 5 — Total missing values

Calculate the total number of missing values.

In [6]:
total_missing= df.isna().sum().sum()
print("Total missing values:", total_missing)

Total missing values: 24

<a id="p-6"></a>
### Practice 6 — Missing percentage

Calculate the missing percentage for every column.

In [7]:
missing_percentage = df.isna().mean() * 100
print(missing_percentage)

Name           0.0
Age           30.0
Salary        30.0
Department    20.0
dtype: float64

<a id="p-7"></a>
### Practice 7 — Build the report

Create a DataFrame with `Missing Count` and `Missing Percentage`.

In [8]:
missing_report = pd.DataFrame({
    "Missing Count": df.isna().sum(),
    "Missing Percentage": df.isna().mean() * 100
})

print(missing_report)

            Missing Count  Missing Percentage
Name                    0                 0.0
Age                     9                30.0
Salary                  9                30.0
Department              6                20.0

<a id="p-8"></a>
### Practice 8 — Incomplete rows

Return only rows containing at least one missing value.

In [9]:

rows = df[df.isna().any(axis=1)]
print(rows)

       Name   Age   Salary Department
1      Sara   NaN  75000.0         HR
2     Ahmed  30.0      NaN        NaN
4     Usman   NaN  65000.0    Finance
5    Hassan  35.0      NaN  Marketing
7     Bilal   NaN  95000.0        NaN
8    Zainab  29.0      NaN         IT
10     Omar   NaN  70000.0      Sales
11   Mariam  26.0      NaN         HR
13     Hira   NaN  68000.0        NaN
14    Talha  28.0      NaN  Marketing
17     Iqra   NaN  78000.0      Sales
18    Fahad  36.0      NaN        NaN
21    Laiba   NaN      NaN    Finance
22     Raza  34.0  99000.0        NaN
24   Waleed   NaN  67000.0      Sales
25  Mahnoor  31.0      NaN         IT
26   Salman  24.0  86000.0        NaN
27     Eman   NaN  71000.0  Marketing
28   Arslan  38.0      NaN    Finance

<a id="p-9"></a>
### Practice 9 — Complete rows

Return only rows with no missing values.

In [10]:
complete_rows = df[df.notna().all(axis=1)]
print(complete_rows)

      Name   Age    Salary Department
0      Ali  23.0   90000.0         IT
3   Ayesha  27.0   85000.0         IT
6   Fatima  24.0   72000.0         HR
9    Hamza  31.0   88000.0    Finance
12    Saad  40.0  120000.0         IT
15    Noor  33.0  105000.0         IT
16  Danish  22.0   60000.0    Finance
19    Sana  25.0   82000.0         HR
20  Kamran  29.0   91000.0         IT
23    Anum  27.0   73000.0         HR
29  Areeba  26.0   80000.0         HR

<a id="p-10"></a>
### Practice 10 — Drop incomplete rows

Create a new DataFrame containing only complete rows.

In [11]:
clean_df = df.dropna()
print(clean_df)

      Name   Age    Salary Department
0      Ali  23.0   90000.0         IT
3   Ayesha  27.0   85000.0         IT
6   Fatima  24.0   72000.0         HR
9    Hamza  31.0   88000.0    Finance
12    Saad  40.0  120000.0         IT
15    Noor  33.0  105000.0         IT
16  Danish  22.0   60000.0    Finance
19    Sana  25.0   82000.0         HR
20  Kamran  29.0   91000.0         IT
23    Anum  27.0   73000.0         HR
29  Areeba  26.0   80000.0         HR

<a id="p-11"></a>
### Practice 11 — Use `subset`

Remove rows only when `Age` is missing.

In [12]:
print(df.dropna(subset=["Age"]))

       Name   Age    Salary Department
0       Ali  23.0   90000.0         IT
2     Ahmed  30.0       NaN        NaN
3    Ayesha  27.0   85000.0         IT
5    Hassan  35.0       NaN  Marketing
6    Fatima  24.0   72000.0         HR
8    Zainab  29.0       NaN         IT
9     Hamza  31.0   88000.0    Finance
11   Mariam  26.0       NaN         HR
12     Saad  40.0  120000.0         IT
14    Talha  28.0       NaN  Marketing
15     Noor  33.0  105000.0         IT
16   Danish  22.0   60000.0    Finance
18    Fahad  36.0       NaN        NaN
19     Sana  25.0   82000.0         HR
20   Kamran  29.0   91000.0         IT
22     Raza  34.0   99000.0        NaN
23     Anum  27.0   73000.0         HR
25  Mahnoor  31.0       NaN         IT
26   Salman  24.0   86000.0        NaN
28   Arslan  38.0       NaN    Finance
29   Areeba  26.0   80000.0         HR

<a id="p-12"></a>
### Practice 12 — Drop columns

Create a DataFrame containing only columns with no missing values.

In [13]:
print(df.dropna(axis=1))

       Name
0       Ali
1      Sara
2     Ahmed
3    Ayesha
4     Usman
5    Hassan
6    Fatima
7     Bilal
8    Zainab
9     Hamza
10     Omar
11   Mariam
12     Saad
13     Hira
14    Talha
15     Noor
16   Danish
17     Iqra
18    Fahad
19     Sana
20   Kamran
21    Laiba
22     Raza
23     Anum
24   Waleed
25  Mahnoor
26   Salman
27     Eman
28   Arslan
29   Areeba

<a id="p-13"></a>
### Practice 13 — Compare `any` and `all`

Create a small DataFrame with one completely empty row and one partially empty row. Test both options.

In [14]:
print(df.dropna(how="all"))
print(df.dropna(how="any"))

       Name   Age    Salary Department
0       Ali  23.0   90000.0         IT
1      Sara   NaN   75000.0         HR
2     Ahmed  30.0       NaN        NaN
3    Ayesha  27.0   85000.0         IT
4     Usman   NaN   65000.0    Finance
5    Hassan  35.0       NaN  Marketing
6    Fatima  24.0   72000.0         HR
7     Bilal   NaN   95000.0        NaN
8    Zainab  29.0       NaN         IT
9     Hamza  31.0   88000.0    Finance
10     Omar   NaN   70000.0      Sales
11   Mariam  26.0       NaN         HR
12     Saad  40.0  120000.0         IT
13     Hira   NaN   68000.0        NaN
14    Talha  28.0       NaN  Marketing
15     Noor  33.0  105000.0         IT
16   Danish  22.0   60000.0    Finance
17     Iqra   NaN   78000.0      Sales
18    Fahad  36.0       NaN        NaN
19     Sana  25.0   82000.0         HR
20   Kamran  29.0   91000.0         IT
21    Laiba   NaN       NaN    Finance
22     Raza  34.0   99000.0        NaN
23     Anum  27.0   73000.0         HR
24   Waleed   NaN   67000.0      Sales
25  Mahnoor  31.0       NaN         IT
26   Salman  24.0   86000.0        NaN
27     Eman   NaN   71000.0  Marketing
28   Arslan  38.0       NaN    Finance
29   Areeba  26.0   80000.0         HR
      Name   Age    Salary Department
0      Ali  23.0   90000.0         IT
3   Ayesha  27.0   85000.0         IT
6   Fatima  24.0   72000.0         HR
9    Hamza  31.0   88000.0    Finance
12    Saad  40.0  120000.0         IT
15    Noor  33.0  105000.0         IT
16  Danish  22.0   60000.0    Finance
19    Sana  25.0   82000.0         HR
20  Kamran  29.0   91000.0         IT
23    Anum  27.0   73000.0         HR
29  Areeba  26.0   80000.0         HR

<a id="p-14"></a>
### Practice 14 — Use `thresh`

Keep rows containing at least 3 non-missing values.

In [15]:
print(df.dropna(thresh=3))

       Name   Age    Salary Department
0       Ali  23.0   90000.0         IT
1      Sara   NaN   75000.0         HR
3    Ayesha  27.0   85000.0         IT
4     Usman   NaN   65000.0    Finance
5    Hassan  35.0       NaN  Marketing
6    Fatima  24.0   72000.0         HR
8    Zainab  29.0       NaN         IT
9     Hamza  31.0   88000.0    Finance
10     Omar   NaN   70000.0      Sales
11   Mariam  26.0       NaN         HR
12     Saad  40.0  120000.0         IT
14    Talha  28.0       NaN  Marketing
15     Noor  33.0  105000.0         IT
16   Danish  22.0   60000.0    Finance
17     Iqra   NaN   78000.0      Sales
19     Sana  25.0   82000.0         HR
20   Kamran  29.0   91000.0         IT
22     Raza  34.0   99000.0        NaN
23     Anum  27.0   73000.0         HR
24   Waleed   NaN   67000.0      Sales
25  Mahnoor  31.0       NaN         IT
26   Salman  24.0   86000.0        NaN
27     Eman   NaN   71000.0  Marketing
28   Arslan  38.0       NaN    Finance
29   Areeba  26.0   80000.0         HR

# Practice Solutions (FIX-2026-09-27)

Try each practice first — your own answers above are kept exactly as written. Every solution below uses a **fresh copy**
of the sample data, so it works no matter which cells ran before.

In [16]:
import pandas as pd
import numpy as np

def fresh_df():
    return pd.DataFrame({
        "Name": ["Ali", "Ahmed", "Sara", "Usman", "Ayesha"],
        "Age": [25, np.nan, 30, 28, np.nan],
        "Salary": [50000, 60000, np.nan, 55000, 70000],
        "City": ["Lahore", "Karachi", None, "Islamabad", "Lahore"]
    })

df = fresh_df()
# Practice 1-7: detect, count, percentage, report
print(df.head(3), df.shape, df.columns.tolist(), df.dtypes, sep="\n\n")
print(df.isna())
print(df.isna().sum())
print("total missing:", df.isna().sum().sum())
report = pd.DataFrame({"Missing Count": df.isna().sum(),
                       "Missing Percentage": (df.isna().mean() * 100).round(1)})
report

    Name   Age   Salary     City
0    Ali  25.0  50000.0   Lahore
1  Ahmed   NaN  60000.0  Karachi
2   Sara  30.0      NaN      NaN

(5, 4)

['Name', 'Age', 'Salary', 'City']

Name          str
Age       float64
Salary    float64
City          str
dtype: object
    Name    Age  Salary   City
0  False  False   False  False
1  False   True   False  False
2  False  False    True   True
3  False  False   False  False
4  False   True   False  False
Name      0
Age       2
Salary    1
City      1
dtype: int64
total missing: 4

        Missing Count  Missing Percentage
Name                0                 0.0
Age                 2                40.0
Salary              1                20.0
City                1                20.0

## ✅ Solution — Practice 8–14 — Selecting and dropping

In [17]:
df = fresh_df()
print(df[df.isna().any(axis=1)], "\n")        # 8 incomplete rows
print(df[df.notna().all(axis=1)], "\n")       # 9 complete rows
complete = df.dropna()                          # 10
print(df.dropna(subset=["Age"]), "\n")        # 11
print(df.dropna(axis=1), "\n")                # 12 only complete columns (Name)

p13 = pd.DataFrame({"A": [1, np.nan, np.nan], "B": [2, np.nan, 5], "C": [3, np.nan, np.nan]})
print(p13.dropna(how="any"), "\n")   # drops rows 1 and 2
print(p13.dropna(how="all"), "\n")   # drops only the fully empty row 1

print(df.dropna(thresh=3))             # 14 keep rows with >= 3 non-missing values

     Name   Age   Salary     City
1   Ahmed   NaN  60000.0  Karachi
2    Sara  30.0      NaN      NaN
4  Ayesha   NaN  70000.0   Lahore

    Name   Age   Salary       City
0    Ali  25.0  50000.0     Lahore
3  Usman  28.0  55000.0  Islamabad

    Name   Age   Salary       City
0    Ali  25.0  50000.0     Lahore
2   Sara  30.0      NaN        NaN
3  Usman  28.0  55000.0  Islamabad

     Name
0     Ali
1   Ahmed
2    Sara
3   Usman
4  Ayesha

     A    B    C
0  1.0  2.0  3.0

     A    B    C
0  1.0  2.0  3.0
2  NaN  5.0  NaN

     Name   Age   Salary       City
0     Ali  25.0  50000.0     Lahore
1   Ahmed   NaN  60000.0    Karachi
3   Usman  28.0  55000.0  Islamabad
4  Ayesha   NaN  70000.0     Lahore

<a id="p-15"></a>
### Practice 15 — Fixed-value filling

Create a version of `Age` where missing values are replaced with `0`.

> 🧩 *Re-creates the data this problem uses (exactly as it was at this point of the lesson).*

In [18]:
import pandas as pd
import numpy as np

df = pd.DataFrame({
    "Name": [
        "Ali", "Sara", "Ahmed", "Ayesha", "Usman",
        "Hassan", "Fatima", "Bilal", "Zainab", "Hamza",
        "Omar", "Mariam", "Saad", "Hira", "Talha",
        "Noor", "Danish", "Iqra", "Fahad", "Sana",
        "Kamran", "Laiba", "Raza", "Anum", "Waleed",
        "Mahnoor", "Salman", "Eman", "Arslan", "Areeba"
    ],

    "Age": [
        23, np.nan, 30, 27, np.nan,
        35, 24, np.nan, 29, 31,
        np.nan, 26, 40, np.nan, 28,
        33, 22, np.nan, 36, 25,
        29, np.nan, 34, 27, np.nan,
        31, 24, np.nan, 38, 26
    ],

    "Salary": [
        90000, 75000, np.nan, 85000, 65000,
        np.nan, 72000, 95000, np.nan, 88000,
        70000, np.nan, 120000, 68000, np.nan,
        105000, 60000, 78000, np.nan, 82000,
        91000, np.nan, 99000, 73000, 67000,
        np.nan, 86000, 71000, np.nan, 80000
    ],

    "Department": [
        "IT", "HR", np.nan, "IT", "Finance",
        "Marketing", "HR", np.nan, "IT", "Finance",
        "Sales", "HR", "IT", np.nan, "Marketing",
        "IT", "Finance", "Sales", np.nan, "HR",
        "IT", "Finance", np.nan, "HR", "Sales",
        "IT", np.nan, "Marketing", "Finance", "HR"
    ]
})

print(df)

       Name   Age    Salary Department
0       Ali  23.0   90000.0         IT
1      Sara   NaN   75000.0         HR
2     Ahmed  30.0       NaN        NaN
3    Ayesha  27.0   85000.0         IT
4     Usman   NaN   65000.0    Finance
5    Hassan  35.0       NaN  Marketing
6    Fatima  24.0   72000.0         HR
7     Bilal   NaN   95000.0        NaN
8    Zainab  29.0       NaN         IT
9     Hamza  31.0   88000.0    Finance
10     Omar   NaN   70000.0      Sales
11   Mariam  26.0       NaN         HR
12     Saad  40.0  120000.0         IT
13     Hira   NaN   68000.0        NaN
14    Talha  28.0       NaN  Marketing
15     Noor  33.0  105000.0         IT
16   Danish  22.0   60000.0    Finance
17     Iqra   NaN   78000.0      Sales
18    Fahad  36.0       NaN        NaN
19     Sana  25.0   82000.0         HR
20   Kamran  29.0   91000.0         IT
21    Laiba   NaN       NaN    Finance
22     Raza  34.0   99000.0        NaN
23     Anum  27.0   73000.0         HR
24   Waleed   NaN   67000.0      Sales
25  Mahnoor  31.0       NaN         IT
26   Salman  24.0   86000.0        NaN
27     Eman   NaN   71000.0  Marketing
28   Arslan  38.0       NaN    Finance
29   Areeba  26.0   80000.0         HR

In [19]:
filled_age = df["Age"].fillna(0)
print(filled_age)

0     23.0
1      0.0
2     30.0
3     27.0
4      0.0
5     35.0
6     24.0
7      0.0
8     29.0
9     31.0
10     0.0
11    26.0
12    40.0
13     0.0
14    28.0
15    33.0
16    22.0
17     0.0
18    36.0
19    25.0
20    29.0
21     0.0
22    34.0
23    27.0
24     0.0
25    31.0
26    24.0
27     0.0
28    38.0
29    26.0
Name: Age, dtype: float64

<a id="p-16"></a>
### Practice 16 — Mean imputation

Fill missing `Salary` values using the mean salary.

In [20]:
salary_mean = df["Salary"].mean()
print("Mean age:", salary_mean)

df_salary_mean = df.copy()
df_salary_mean["Salary"] = df_age_mean["Salary"].fillna(salary_mean)
print(df_salary_mean)

Mean age: 81904.76190476191
       Name   Age         Salary Department
0       Ali  23.0   90000.000000         IT
1      Sara   NaN   75000.000000         HR
2     Ahmed  30.0   81904.761905        NaN
3    Ayesha  27.0   85000.000000         IT
4     Usman   NaN   65000.000000    Finance
5    Hassan  35.0   81904.761905  Marketing
6    Fatima  24.0   72000.000000         HR
7     Bilal   NaN   95000.000000        NaN
8    Zainab  29.0   81904.761905         IT
9     Hamza  31.0   88000.000000    Finance
10     Omar   NaN   70000.000000      Sales
11   Mariam  26.0   81904.761905         HR
12     Saad  40.0  120000.000000         IT
13     Hira   NaN   68000.000000        NaN
14    Talha  28.0   81904.761905  Marketing
15     Noor  33.0  105000.000000         IT
16   Danish  22.0   60000.000000    Finance
17     Iqra   NaN   78000.000000      Sales
18    Fahad  36.0   81904.761905        NaN
19     Sana  25.0   82000.000000         HR
20   Kamran  29.0   91000.000000         IT
21    Laiba   NaN   81904.761905    Finance
22     Raza  34.0   99000.000000        NaN
23     Anum  27.0   73000.000000         HR
24   Waleed   NaN   67000.000000      Sales
25  Mahnoor  31.0   81904.761905         IT
26   Salman  24.0   86000.000000        NaN
27     Eman   NaN   71000.000000  Marketing
28   Arslan  38.0   81904.761905    Finance
29   Areeba  26.0   80000.000000         HR

<a id="p-17"></a>
### Practice 17 — Median imputation

Fill missing `Age` values using the median.

In [21]:
age_median = df["Age"].median()
print("Median age:", age_median)

df_age_median = df.copy()
df_age_median["Age"] = df_age_median["Age"].fillna(age_median)
print(df_age_median)

Median age: 29.0
       Name   Age    Salary Department
0       Ali  23.0   90000.0         IT
1      Sara  29.0   75000.0         HR
2     Ahmed  30.0       NaN        NaN
3    Ayesha  27.0   85000.0         IT
4     Usman  29.0   65000.0    Finance
5    Hassan  35.0       NaN  Marketing
6    Fatima  24.0   72000.0         HR
7     Bilal  29.0   95000.0        NaN
8    Zainab  29.0       NaN         IT
9     Hamza  31.0   88000.0    Finance
10     Omar  29.0   70000.0      Sales
11   Mariam  26.0       NaN         HR
12     Saad  40.0  120000.0         IT
13     Hira  29.0   68000.0        NaN
14    Talha  28.0       NaN  Marketing
15     Noor  33.0  105000.0         IT
16   Danish  22.0   60000.0    Finance
17     Iqra  29.0   78000.0      Sales
18    Fahad  36.0       NaN        NaN
19     Sana  25.0   82000.0         HR
20   Kamran  29.0   91000.0         IT
21    Laiba  29.0       NaN    Finance
22     Raza  34.0   99000.0        NaN
23     Anum  27.0   73000.0         HR
24   Waleed  29.0   67000.0      Sales
25  Mahnoor  31.0       NaN         IT
26   Salman  24.0   86000.0        NaN
27     Eman  29.0   71000.0  Marketing
28   Arslan  38.0       NaN    Finance
29   Areeba  26.0   80000.0         HR

<a id="p-18"></a>
### Practice 18 — Compare mean and median

Create a Series with an obvious outlier, calculate both statistics, and explain your preferred imputation method in a comment.

In [22]:
df

       Name   Age    Salary Department
0       Ali  23.0   90000.0         IT
1      Sara   NaN   75000.0         HR
2     Ahmed  30.0       NaN        NaN
3    Ayesha  27.0   85000.0         IT
4     Usman   NaN   65000.0    Finance
5    Hassan  35.0       NaN  Marketing
6    Fatima  24.0   72000.0         HR
7     Bilal   NaN   95000.0        NaN
8    Zainab  29.0       NaN         IT
9     Hamza  31.0   88000.0    Finance
10     Omar   NaN   70000.0      Sales
11   Mariam  26.0       NaN         HR
12     Saad  40.0  120000.0         IT
13     Hira   NaN   68000.0        NaN
14    Talha  28.0       NaN  Marketing
15     Noor  33.0  105000.0         IT
16   Danish  22.0   60000.0    Finance
17     Iqra   NaN   78000.0      Sales
18    Fahad  36.0       NaN        NaN
19     Sana  25.0   82000.0         HR
20   Kamran  29.0   91000.0         IT
21    Laiba   NaN       NaN    Finance
22     Raza  34.0   99000.0        NaN
23     Anum  27.0   73000.0         HR
24   Waleed   NaN   67000.0      Sales
25  Mahnoor  31.0       NaN         IT
26   Salman  24.0   86000.0        NaN
27     Eman   NaN   71000.0  Marketing
28   Arslan  38.0       NaN    Finance
29   Areeba  26.0   80000.0         HR

<a id="p-19"></a>
### Practice 19 — Mode imputation

Fill missing `Department` values using the mode.

In [23]:
dep_mode = df["Department"].mode()[0]
print("dep mode:", dep_mode)

df_dep_mode = df.copy()
df_dep_mode["Department"] = df_dep_mode["Department"].fillna(dep_mode)
print(df_dep_mode)

dep mode: IT
       Name   Age    Salary Department
0       Ali  23.0   90000.0         IT
1      Sara   NaN   75000.0         HR
2     Ahmed  30.0       NaN         IT
3    Ayesha  27.0   85000.0         IT
4     Usman   NaN   65000.0    Finance
5    Hassan  35.0       NaN  Marketing
6    Fatima  24.0   72000.0         HR
7     Bilal   NaN   95000.0         IT
8    Zainab  29.0       NaN         IT
9     Hamza  31.0   88000.0    Finance
10     Omar   NaN   70000.0      Sales
11   Mariam  26.0       NaN         HR
12     Saad  40.0  120000.0         IT
13     Hira   NaN   68000.0         IT
14    Talha  28.0       NaN  Marketing
15     Noor  33.0  105000.0         IT
16   Danish  22.0   60000.0    Finance
17     Iqra   NaN   78000.0      Sales
18    Fahad  36.0       NaN         IT
19     Sana  25.0   82000.0         HR
20   Kamran  29.0   91000.0         IT
21    Laiba   NaN       NaN    Finance
22     Raza  34.0   99000.0         IT
23     Anum  27.0   73000.0         HR
24   Waleed   NaN   67000.0      Sales
25  Mahnoor  31.0       NaN         IT
26   Salman  24.0   86000.0         IT
27     Eman   NaN   71000.0  Marketing
28   Arslan  38.0       NaN    Finance
29   Areeba  26.0   80000.0         HR

<a id="p-20"></a>
### Practice 20 — Unknown category

Replace missing `Department` values with `Unknown`.

## ✅ Solution — Practice 15–20 — Filling with values and statistics

In [24]:
df = fresh_df()
print(df["Age"].fillna(0).tolist())                                   # 15
print(df["Salary"].fillna(df["Salary"].mean()).tolist())              # 16
print(df["Age"].fillna(df["Age"].median()).tolist())                  # 17

s = pd.Series([20, 22, 23, 25, 300])                                  # 18
print("mean:", s.mean(), "median:", s.median())
# Prefer the MEDIAN: the single outlier (300) drags the mean far away from typical values.

print(df["City"].fillna(df["City"].mode()[0]).tolist())               # 19
print(df["City"].fillna("Unknown").tolist())                          # 20

[25.0, 0.0, 30.0, 28.0, 0.0]
[50000.0, 60000.0, 58750.0, 55000.0, 70000.0]
[25.0, 28.0, 30.0, 28.0, 28.0]
mean: 78.0 median: 23.0
['Lahore', 'Karachi', 'Lahore', 'Islamabad', 'Lahore']
['Lahore', 'Karachi', 'Unknown', 'Islamabad', 'Lahore']

<a id="p-21"></a>
### Practice 21 — Forward fill

Use `ffill()` on `pd.Series([10, 12, np.nan, np.nan, 20])`.

<a id="p-22"></a>
### Practice 22 — Backward fill

Use `bfill()` on `pd.Series([10, np.nan, np.nan, 20])`.

<a id="p-23"></a>
### Practice 23 — Interpolation

Create a Series with at least two missing values between known numbers and use `interpolate()`.

In [25]:
measurements = pd.Series([30, 32, np.nan, 36])
print("Before:")
print(measurements)
print("\nAfter interpolation:")
print(measurements.interpolate())

Before:
0    30.0
1    32.0
2     NaN
3    36.0
dtype: float64

After interpolation:
0    30.0
1    32.0
2    34.0
3    36.0
dtype: float64

<a id="p-24"></a>
### Practice 24 — Standardize markers

Create a DataFrame containing at least three different missing-value markers and replace them all with `np.nan`.

In [26]:
messy = pd.DataFrame({
    "Name": ["Ali", "Sara", "Usman", "Ayesha"],
    "Age": [25, "NA", "?", 30],
    "City": ["Lahore", "null", "-", "Karachi"]
})

print("Before:")
print(messy)

messy_clean = messy.replace(
    ["?", "N/A", "NA", "null", "-"],
    np.nan
)

print("\nAfter:")
print(messy_clean)

Before:
     Name Age     City
0     Ali  25   Lahore
1    Sara  NA     null
2   Usman   ?        -
3  Ayesha  30  Karachi

After:
     Name  Age     City
0     Ali   25   Lahore
1    Sara  NaN      NaN
2   Usman  NaN      NaN
3  Ayesha   30  Karachi

<a id="p-25"></a>
### Practice 25 — CSV import

Write code that loads `data.csv` and treats `?`, `NA`, and `N/A` as missing.

## ✅ Solution — Practice 21–25 — ffill, bfill, interpolation, markers, CSV

In [27]:
print(pd.Series([10, 12, np.nan, np.nan, 20]).ffill().tolist())      # 21
print(pd.Series([10, np.nan, np.nan, 20]).bfill().tolist())           # 22
print(pd.Series([10, np.nan, np.nan, 40]).interpolate().tolist())     # 23 -> 20, 30 filled linearly

messy = pd.DataFrame({"Age": [25, "?", "N/A", 40, "missing"],
                      "City": ["Lahore", "-", "null", "Karachi", "?"]})
clean = messy.replace(["?", "N/A", "null", "-", "missing"], np.nan)  # 24
clean["Age"] = pd.to_numeric(clean["Age"])
print(clean, clean.isna().sum(), sep="\n")

# 25 (no file needed to read the syntax):
# data = pd.read_csv("data.csv", na_values=["?", "NA", "N/A"])

[10.0, 12.0, 12.0, 12.0, 20.0]
[10.0, 20.0, 20.0, 20.0]
[10.0, 20.0, 30.0, 40.0]
    Age     City
0  25.0   Lahore
1   NaN      NaN
2   NaN      NaN
3  40.0  Karachi
4   NaN      NaN
Age     3
City    3
dtype: int64

<a id="p-26"></a>
### Practice 26 — Column-specific strategies

Using the original `df`, fill `Age` with median, `Salary` with mean, and `Department` with mode. Store the result in a new DataFrame.

<a id="p-27"></a>
### Practice 27 — Numeric mean filling

Fill all numeric missing values using their respective column means without manually naming the columns.

<a id="p-28"></a>
### Practice 28 — Group-based filling

Create a DataFrame with `Department` and `Salary`. Fill missing salaries using the median salary within each department.

> 🧩 *Re-creates the data this problem uses (exactly as it was at this point of the lesson).*

In [28]:
import pandas as pd
import numpy as np

df = pd.DataFrame({
    "Name": [
        "Ali", "Sara", "Ahmed", "Ayesha", "Usman",
        "Hassan", "Fatima", "Bilal", "Zainab", "Hamza",
        "Omar", "Mariam", "Saad", "Hira", "Talha",
        "Noor", "Danish", "Iqra", "Fahad", "Sana",
        "Kamran", "Laiba", "Raza", "Anum", "Waleed",
        "Mahnoor", "Salman", "Eman", "Arslan", "Areeba"
    ],

    "Age": [
        23, np.nan, 30, 27, np.nan,
        35, 24, np.nan, 29, 31,
        np.nan, 26, 40, np.nan, 28,
        33, 22, np.nan, 36, 25,
        29, np.nan, 34, 27, np.nan,
        31, 24, np.nan, 38, 26
    ],

    "Salary": [
        90000, 75000, np.nan, 85000, 65000,
        np.nan, 72000, 95000, np.nan, 88000,
        70000, np.nan, 120000, 68000, np.nan,
        105000, 60000, 78000, np.nan, 82000,
        91000, np.nan, 99000, 73000, 67000,
        np.nan, 86000, 71000, np.nan, 80000
    ],

    "Department": [
        "IT", "HR", np.nan, "IT", "Finance",
        "Marketing", "HR", np.nan, "IT", "Finance",
        "Sales", "HR", "IT", np.nan, "Marketing",
        "IT", "Finance", "Sales", np.nan, "HR",
        "IT", "Finance", np.nan, "HR", "Sales",
        "IT", np.nan, "Marketing", "Finance", "HR"
    ]
})

print(df)

       Name   Age    Salary Department
0       Ali  23.0   90000.0         IT
1      Sara   NaN   75000.0         HR
2     Ahmed  30.0       NaN        NaN
3    Ayesha  27.0   85000.0         IT
4     Usman   NaN   65000.0    Finance
5    Hassan  35.0       NaN  Marketing
6    Fatima  24.0   72000.0         HR
7     Bilal   NaN   95000.0        NaN
8    Zainab  29.0       NaN         IT
9     Hamza  31.0   88000.0    Finance
10     Omar   NaN   70000.0      Sales
11   Mariam  26.0       NaN         HR
12     Saad  40.0  120000.0         IT
13     Hira   NaN   68000.0        NaN
14    Talha  28.0       NaN  Marketing
15     Noor  33.0  105000.0         IT
16   Danish  22.0   60000.0    Finance
17     Iqra   NaN   78000.0      Sales
18    Fahad  36.0       NaN        NaN
19     Sana  25.0   82000.0         HR
20   Kamran  29.0   91000.0         IT
21    Laiba   NaN       NaN    Finance
22     Raza  34.0   99000.0        NaN
23     Anum  27.0   73000.0         HR
24   Waleed   NaN   67000.0      Sales
25  Mahnoor  31.0       NaN         IT
26   Salman  24.0   86000.0        NaN
27     Eman   NaN   71000.0  Marketing
28   Arslan  38.0       NaN    Finance
29   Areeba  26.0   80000.0         HR

In [29]:
dep= df.copy()

# print("Before:")
# print(dep)

dep["Salary"] = df.groupby("Department")["Salary"].transform( lambda salaries :salaries.fillna(salaries.median()))
dep

       Name   Age    Salary Department
0       Ali  23.0   90000.0         IT
1      Sara   NaN   75000.0         HR
2     Ahmed  30.0       NaN        NaN
3    Ayesha  27.0   85000.0         IT
4     Usman   NaN   65000.0    Finance
5    Hassan  35.0   71000.0  Marketing
6    Fatima  24.0   72000.0         HR
7     Bilal   NaN       NaN        NaN
8    Zainab  29.0   91000.0         IT
9     Hamza  31.0   88000.0    Finance
10     Omar   NaN   70000.0      Sales
11   Mariam  26.0   75000.0         HR
12     Saad  40.0  120000.0         IT
13     Hira   NaN       NaN        NaN
14    Talha  28.0   71000.0  Marketing
15     Noor  33.0  105000.0         IT
16   Danish  22.0   60000.0    Finance
17     Iqra   NaN   78000.0      Sales
18    Fahad  36.0       NaN        NaN
19     Sana  25.0   82000.0         HR
20   Kamran  29.0   91000.0         IT
21    Laiba   NaN   65000.0    Finance
22     Raza  34.0       NaN        NaN
23     Anum  27.0   73000.0         HR
24   Waleed   NaN   67000.0      Sales
25  Mahnoor  31.0   91000.0         IT
26   Salman  24.0       NaN        NaN
27     Eman   NaN   71000.0  Marketing
28   Arslan  38.0   65000.0    Finance
29   Areeba  26.0   80000.0         HR

<a id="p-29"></a>
### Practice 29 — Filter by missingness

1. Return rows where `Salary` is missing.
2. Return rows where `Salary` is not missing.

In [30]:
print("Age missing:")
print(df[df["Salary"].isna()])

print("\nAge present:")
print(df[df["Salary"].notna()])

Age missing:
       Name   Age  Salary Department
2     Ahmed  30.0     NaN        NaN
5    Hassan  35.0     NaN  Marketing
8    Zainab  29.0     NaN         IT
11   Mariam  26.0     NaN         HR
14    Talha  28.0     NaN  Marketing
18    Fahad  36.0     NaN        NaN
21    Laiba   NaN     NaN    Finance
25  Mahnoor  31.0     NaN         IT
28   Arslan  38.0     NaN    Finance

Age present:
      Name   Age    Salary Department
0      Ali  23.0   90000.0         IT
1     Sara   NaN   75000.0         HR
3   Ayesha  27.0   85000.0         IT
4    Usman   NaN   65000.0    Finance
6   Fatima  24.0   72000.0         HR
7    Bilal   NaN   95000.0        NaN
9    Hamza  31.0   88000.0    Finance
10    Omar   NaN   70000.0      Sales
12    Saad  40.0  120000.0         IT
13    Hira   NaN   68000.0        NaN
15    Noor  33.0  105000.0         IT
16  Danish  22.0   60000.0    Finance
17    Iqra   NaN   78000.0      Sales
19    Sana  25.0   82000.0         HR
20  Kamran  29.0   91000.0         IT
22    Raza  34.0   99000.0        NaN
23    Anum  27.0   73000.0         HR
24  Waleed   NaN   67000.0      Sales
26  Salman  24.0   86000.0        NaN
27    Eman   NaN   71000.0  Marketing
29  Areeba  26.0   80000.0         HR

<a id="p-30"></a>
### Practice 30 — Assignment approach

Copy `df` and fill missing `Age` using assignment. Do not modify the original `df`.

## ✅ Solution — Practice 26–30 — Column strategies, groups, filtering, assignment

In [31]:
df = fresh_df()
p26 = df.copy()
p26["Age"] = p26["Age"].fillna(p26["Age"].median())
p26["Salary"] = p26["Salary"].fillna(p26["Salary"].mean())
p26["City"] = p26["City"].fillna(p26["City"].mode()[0])
print(p26, "\n")

num_cols = df.select_dtypes(include="number").columns                 # 27 no hard-coded names
p27 = df.copy()
p27[num_cols] = p27[num_cols].fillna(p27[num_cols].mean())
print(p27, "\n")

dept = pd.DataFrame({"Department": ["IT", "IT", "HR", "HR", "IT", "HR"],
                     "Salary": [90000, np.nan, 60000, np.nan, 110000, 64000]})
dept["Salary"] = dept.groupby("Department")["Salary"].transform(lambda s: s.fillna(s.median()))   # 28
print(dept, "\n")

print(df[df["Salary"].isna()], "\n")                                 # 29.1
print(df[df["Salary"].notna()], "\n")                                # 29.2

p30 = df.copy()                                                        # 30
p30["Age"] = p30["Age"].fillna(p30["Age"].median())
print("original still has", df["Age"].isna().sum(), "missing ages; copy has", p30["Age"].isna().sum())

     Name   Age   Salary       City
0     Ali  25.0  50000.0     Lahore
1   Ahmed  28.0  60000.0    Karachi
2    Sara  30.0  58750.0     Lahore
3   Usman  28.0  55000.0  Islamabad
4  Ayesha  28.0  70000.0     Lahore

     Name        Age   Salary       City
0     Ali  25.000000  50000.0     Lahore
1   Ahmed  27.666667  60000.0    Karachi
2    Sara  30.000000  58750.0        NaN
3   Usman  28.000000  55000.0  Islamabad
4  Ayesha  27.666667  70000.0     Lahore

  Department    Salary
0         IT   90000.0
1         IT  100000.0
2         HR   60000.0
3         HR   62000.0
4         IT  110000.0
5         HR   64000.0

   Name   Age  Salary City
2  Sara  30.0     NaN  NaN

     Name   Age   Salary       City
0     Ali  25.0  50000.0     Lahore
1   Ahmed   NaN  60000.0    Karachi
3   Usman  28.0  55000.0  Islamabad
4  Ayesha   NaN  70000.0     Lahore

original still has 2 missing ages; copy has 0

<a id="p-31"></a>
### Practice 31 — Complete workflow

Using the original sample data, inspect it, create a missing-value report, choose appropriate strategies, create a cleaned DataFrame, and verify the result. Do not modify the original `df`.

> 🧩 *Re-creates the data this problem uses (exactly as it was at this point of the lesson).*

In [32]:
import pandas as pd
import numpy as np

df = pd.DataFrame({
    "Name": [
        "Ali", "Sara", "Ahmed", "Ayesha", "Usman",
        "Hassan", "Fatima", "Bilal", "Zainab", "Hamza",
        "Omar", "Mariam", "Saad", "Hira", "Talha",
        "Noor", "Danish", "Iqra", "Fahad", "Sana",
        "Kamran", "Laiba", "Raza", "Anum", "Waleed",
        "Mahnoor", "Salman", "Eman", "Arslan", "Areeba"
    ],

    "Age": [
        23, np.nan, 30, 27, np.nan,
        35, 24, np.nan, 29, 31,
        np.nan, 26, 40, np.nan, 28,
        33, 22, np.nan, 36, 25,
        29, np.nan, 34, 27, np.nan,
        31, 24, np.nan, 38, 26
    ],

    "Salary": [
        90000, 75000, np.nan, 85000, 65000,
        np.nan, 72000, 95000, np.nan, 88000,
        70000, np.nan, 120000, 68000, np.nan,
        105000, 60000, 78000, np.nan, 82000,
        91000, np.nan, 99000, 73000, 67000,
        np.nan, 86000, 71000, np.nan, 80000
    ],

    "Department": [
        "IT", "HR", np.nan, "IT", "Finance",
        "Marketing", "HR", np.nan, "IT", "Finance",
        "Sales", "HR", "IT", np.nan, "Marketing",
        "IT", "Finance", "Sales", np.nan, "HR",
        "IT", "Finance", np.nan, "HR", "Sales",
        "IT", np.nan, "Marketing", "Finance", "HR"
    ]
})

print(df)

       Name   Age    Salary Department
0       Ali  23.0   90000.0         IT
1      Sara   NaN   75000.0         HR
2     Ahmed  30.0       NaN        NaN
3    Ayesha  27.0   85000.0         IT
4     Usman   NaN   65000.0    Finance
5    Hassan  35.0       NaN  Marketing
6    Fatima  24.0   72000.0         HR
7     Bilal   NaN   95000.0        NaN
8    Zainab  29.0       NaN         IT
9     Hamza  31.0   88000.0    Finance
10     Omar   NaN   70000.0      Sales
11   Mariam  26.0       NaN         HR
12     Saad  40.0  120000.0         IT
13     Hira   NaN   68000.0        NaN
14    Talha  28.0       NaN  Marketing
15     Noor  33.0  105000.0         IT
16   Danish  22.0   60000.0    Finance
17     Iqra   NaN   78000.0      Sales
18    Fahad  36.0       NaN        NaN
19     Sana  25.0   82000.0         HR
20   Kamran  29.0   91000.0         IT
21    Laiba   NaN       NaN    Finance
22     Raza  34.0   99000.0        NaN
23     Anum  27.0   73000.0         HR
24   Waleed   NaN   67000.0      Sales
25  Mahnoor  31.0       NaN         IT
26   Salman  24.0   86000.0        NaN
27     Eman   NaN   71000.0  Marketing
28   Arslan  38.0       NaN    Finance
29   Areeba  26.0   80000.0         HR

In [33]:
data= df.copy()

# print(data.info())
# print(data.dtypes)
print(data.columns)

print(data.isna().sum())


data["Age"] = data["Age"].fillna(data["Age"].median())
data["Salary"] = data["Salary"].fillna(data["Salary"].median())
data["Department"] = data["Department"].fillna(data["Department"].mode()[0])

print("\nRemaining missing values:")
print(workflow_df.isna().sum())

Index(['Name', 'Age', 'Salary', 'Department'], dtype='str')
Name          0
Age           9
Salary        9
Department    6
dtype: int64

Remaining missing values:
Name          0
Age           0
Salary        0
Department    0
dtype: int64

## ✅ Solution — Practice 31 — Complete workflow on the original sample

In [34]:
df = fresh_df()
before = df.isna().sum()

cleaned = df.copy()
cleaned["Age"] = cleaned["Age"].fillna(cleaned["Age"].median())        # few values -> median is robust
cleaned["Salary"] = cleaned["Salary"].fillna(cleaned["Salary"].median())
cleaned["City"] = cleaned["City"].fillna("Unknown")                     # don't invent a city

print(pd.DataFrame({"before": before, "after": cleaned.isna().sum()}))
cleaned

        before  after
Name         0      0
Age          2      0
Salary       1      0
City         1      0

     Name   Age   Salary       City
0     Ali  25.0  50000.0     Lahore
1   Ahmed  28.0  60000.0    Karachi
2    Sara  30.0  57500.0    Unknown
3   Usman  28.0  55000.0  Islamabad
4  Ayesha  28.0  70000.0     Lahore

<a id="p-32"></a>
## 32. Comprehensive Practice Dataset

In [35]:
sales_data = {
    "Customer": ["Ali", "Sara", "Ahmed", "Usman", "Ayesha", "Hamza", "Zain", "Hina", "Bilal", "Mariam"],
    "Age": [25, np.nan, 31, 29, np.nan, 42, 35, 28, np.nan, 30],
    "Salary": [50000, 65000, np.nan, 72000, 58000, np.nan, 80000, 55000, 62000, np.nan],
    "Department": ["IT", "HR", "IT", np.nan, "Finance", "IT", "Finance", "HR", np.nan, "IT"],
    "City": ["Lahore", "Karachi", "Lahore", "Islamabad", np.nan, "Karachi", "Lahore", "Karachi", "Islamabad", np.nan],
    "Experience": [2, 5, np.nan, 7, 3, np.nan, 10, 4, 6, np.nan]
}

sales_df = pd.DataFrame(sales_data)
print(sales_df)

  Customer   Age   Salary Department       City  Experience
0      Ali  25.0  50000.0         IT     Lahore         2.0
1     Sara   NaN  65000.0         HR    Karachi         5.0
2    Ahmed  31.0      NaN         IT     Lahore         NaN
3    Usman  29.0  72000.0        NaN  Islamabad         7.0
4   Ayesha   NaN  58000.0    Finance        NaN         3.0
5    Hamza  42.0      NaN         IT    Karachi         NaN
6     Zain  35.0  80000.0    Finance     Lahore        10.0
7     Hina  28.0  55000.0         HR    Karachi         4.0
8    Bilal   NaN  62000.0        NaN  Islamabad         6.0
9   Mariam  30.0      NaN         IT        NaN         NaN

<a id="p-33"></a>
### Practice 32 — Full analysis challenge

1. Display the first 5 rows.
2. Display shape and dtypes.
3. Count missing values per column.
4. Calculate missing percentages.
5. Create a missing-value report.
6. Find rows containing missing values.
7. Fill `Age` with median.
8. Fill `Salary` with median.
9. Fill `Department` with mode.
10. Fill `City` with mode.
11. Fill `Experience` with median.
12. Verify no missing values remain.
13. Display the final DataFrame.
14. Create another version where missing categorical values use `Unknown` instead of mode.

In [36]:
print(sales_df.head())
print(sales_df.shape)
print(sales_df.dtypes)
print(sales_df.isna().sum())
print(sales_df.isna().median())


report = pd.DataFrame({"Missing Count": sales_df.isna().sum(),
                       "Missing Percentage": (sales_df.isna().mean() * 100).round(1)})
# report

print(sales_df[sales_df.isna().any(axis=1)])

print(sales_df[sales_df.notna().all(axis=1)])

sales_df["Age"] = sales_df["Age"].fillna(sales_df["Age"].median())
sales_df["Salary"] = sales_df["Salary"].fillna(sales_df["Salary"].median())
sales_df["City"] = sales_df["City"].fillna(sales_df["City"].mode()[0])
sales_df["Department"] = sales_df["Department"].fillna(sales_df["Department"].mode()[0])

sales_df["Experience"] = sales_df["Experience"].fillna(sales_df["Experience"].median())

print("missing",sales_df.isna().sum().sum())
# print(sales_df.isna().sum())
df_unknown["Department"] = df_unknown["Department"].fillna("Unknown")

  Customer   Age   Salary Department       City  Experience
0      Ali  25.0  50000.0         IT     Lahore         2.0
1     Sara   NaN  65000.0         HR    Karachi         5.0
2    Ahmed  31.0      NaN         IT     Lahore         NaN
3    Usman  29.0  72000.0        NaN  Islamabad         7.0
4   Ayesha   NaN  58000.0    Finance        NaN         3.0
(10, 6)
Customer          str
Age           float64
Salary        float64
Department        str
City              str
Experience    float64
dtype: object
Customer      0
Age           3
Salary        3
Department    2
City          2
Experience    3
dtype: int64
Customer      0.0
Age           0.0
Salary        0.0
Department    0.0
City          0.0
Experience    0.0
dtype: float64

  Customer   Age   Salary Department       City  Experience
1     Sara   NaN  65000.0         HR    Karachi         5.0
2    Ahmed  31.0      NaN         IT     Lahore         NaN
3    Usman  29.0  72000.0        NaN  Islamabad         7.0
4   Ayesha   NaN  58000.0    Finance        NaN         3.0
5    Hamza  42.0      NaN         IT    Karachi         NaN
8    Bilal   NaN  62000.0        NaN  Islamabad         6.0
9   Mariam  30.0      NaN         IT        NaN         NaN
  Customer   Age   Salary Department     City  Experience
0      Ali  25.0  50000.0         IT   Lahore         2.0
6     Zain  35.0  80000.0    Finance   Lahore        10.0
7     Hina  28.0  55000.0         HR  Karachi         4.0

missing 0

## ✅ Solution — Practice 32 — Full analysis challenge

In [37]:
sales_df = pd.DataFrame({
    "Customer": ["Ali", "Sara", "Ahmed", "Usman", "Ayesha", "Hamza", "Zain", "Hina", "Bilal", "Mariam"],
    "Age": [25, np.nan, 31, 29, np.nan, 42, 35, 28, np.nan, 30],
    "Salary": [50000, 65000, np.nan, 72000, 58000, np.nan, 80000, 55000, 62000, np.nan],
    "Department": ["IT", "HR", "IT", np.nan, "Finance", "IT", "Finance", "HR", np.nan, "IT"],
    "City": ["Lahore", "Karachi", "Lahore", "Islamabad", np.nan, "Karachi", "Lahore", "Karachi", "Islamabad", np.nan],
    "Experience": [2, 5, np.nan, 7, 3, np.nan, 10, 4, 6, np.nan]
})
print(sales_df.head(), sales_df.shape, sales_df.dtypes, sep="\n\n")               # 1-2
rep = pd.DataFrame({"count": sales_df.isna().sum(),
                    "pct": (sales_df.isna().mean() * 100).round(1)})               # 3-5
print(rep)
print(sales_df[sales_df.isna().any(axis=1)])                                       # 6

filled = sales_df.copy()
for col in ["Age", "Salary", "Experience"]:                                        # 7, 8, 11
    filled[col] = filled[col].fillna(filled[col].median())
for col in ["Department", "City"]:                                                 # 9, 10
    filled[col] = filled[col].fillna(filled[col].mode()[0])
print("remaining missing:", filled.isna().sum().sum())                             # 12
print(filled)                                                                      # 13

unknown_version = sales_df.copy()                                                  # 14
unknown_version[["Department", "City"]] = unknown_version[["Department", "City"]].fillna("Unknown")
for col in ["Age", "Salary", "Experience"]:
    unknown_version[col] = unknown_version[col].fillna(unknown_version[col].median())
unknown_version

  Customer   Age   Salary Department       City  Experience
0      Ali  25.0  50000.0         IT     Lahore         2.0
1     Sara   NaN  65000.0         HR    Karachi         5.0
2    Ahmed  31.0      NaN         IT     Lahore         NaN
3    Usman  29.0  72000.0        NaN  Islamabad         7.0
4   Ayesha   NaN  58000.0    Finance        NaN         3.0

(10, 6)

Customer          str
Age           float64
Salary        float64
Department        str
City              str
Experience    float64
dtype: object
            count   pct
Customer        0   0.0
Age             3  30.0
Salary          3  30.0
Department      2  20.0
City            2  20.0
Experience      3  30.0

  Customer   Age   Salary Department       City  Experience
1     Sara   NaN  65000.0         HR    Karachi         5.0
2    Ahmed  31.0      NaN         IT     Lahore         NaN
3    Usman  29.0  72000.0        NaN  Islamabad         7.0
4   Ayesha   NaN  58000.0    Finance        NaN         3.0
5    Hamza  42.0      NaN         IT    Karachi         NaN
8    Bilal   NaN  62000.0        NaN  Islamabad         6.0
9   Mariam  30.0      NaN         IT        NaN         NaN
remaining missing: 0
  Customer   Age   Salary Department       City  Experience
0      Ali  25.0  50000.0         IT     Lahore         2.0
1     Sara  30.0  65000.0         HR    Karachi         5.0
2    Ahmed  31.0  62000.0         IT     Lahore         5.0
3    Usman  29.0  72000.0         IT  Islamabad         7.0
4   Ayesha  30.0  58000.0    Finance    Karachi         3.0
5    Hamza  42.0  62000.0         IT    Karachi         5.0
6     Zain  35.0  80000.0    Finance     Lahore        10.0
7     Hina  28.0  55000.0         HR    Karachi         4.0
8    Bilal  30.0  62000.0         IT  Islamabad         6.0
9   Mariam  30.0  62000.0         IT    Karachi         5.0

  Customer   Age   Salary Department       City  Experience
0      Ali  25.0  50000.0         IT     Lahore         2.0
1     Sara  30.0  65000.0         HR    Karachi         5.0
2    Ahmed  31.0  62000.0         IT     Lahore         5.0
3    Usman  29.0  72000.0    Unknown  Islamabad         7.0
4   Ayesha  30.0  58000.0    Finance    Unknown         3.0
5    Hamza  42.0  62000.0         IT    Karachi         5.0
6     Zain  35.0  80000.0    Finance     Lahore        10.0
7     Hina  28.0  55000.0         HR    Karachi         4.0
8    Bilal  30.0  62000.0    Unknown  Islamabad         6.0
9   Mariam  30.0  62000.0         IT    Unknown         5.0

<a id="p-34"></a>
### Practice 32b-1 — Missingness type

For each case write MCAR, MAR or MNAR and one sentence why:
1. A weather sensor loses readings whenever the Wi-Fi drops.
2. Patients with severe symptoms are too ill to fill the "exercise hours" question.
3. Employees with low performance ratings leave the "Rating" field blank in a self-review.

In [38]:
# ✍️ Your answer here

## ✅ Solution — Practice 32b-1 — Missingness type

1. **MCAR** — Wi-Fi drops have nothing to do with the temperature value.
2. **MAR** — missingness depends on symptom severity, which is recorded in another column.
3. **MNAR** — the rating is missing *because* it is low; the missing value itself causes the missingness.

In [39]:
from sklearn.model_selection import train_test_split
from sklearn.impute import SimpleImputer, KNNImputer

num = sales_df[["Age", "Salary", "Experience"]]
tr, te = train_test_split(num, test_size=0.3, random_state=1)
imp = SimpleImputer(strategy="median", add_indicator=True).fit(tr)            # 32b-2
print("medians learned from train:", dict(zip(num.columns, imp.statistics_)))
print(pd.DataFrame(imp.transform(te), columns=imp.get_feature_names_out(), index=te.index))

med = num["Salary"].fillna(num["Salary"].median())                            # 32b-3
knn = pd.DataFrame(KNNImputer(n_neighbors=3).fit_transform(num), columns=num.columns, index=num.index)
mask = num["Salary"].isna()
pd.DataFrame({"Age": num["Age"], "Experience": num["Experience"],
              "median_fill": med, "knn_fill": knn["Salary"].round(0)})[mask]

medians learned from train: {'Age': np.float64(28.5), 'Salary': np.float64(60000.0), 'Experience': np.float64(4.5)}
    Age   Salary  Experience  missingindicator_Age  missingindicator_Salary  \
2  31.0  60000.0         4.5                   0.0                      1.0
9  30.0  60000.0         4.5                   0.0                      1.0
6  35.0  80000.0        10.0                   0.0                      0.0

   missingindicator_Experience
2                          1.0
9                          1.0
6                          0.0

    Age  Experience  median_fill  knn_fill
2  31.0         NaN      62000.0   69000.0
5  42.0         NaN      62000.0   69000.0
9  30.0         NaN      62000.0   59000.0

<a id="p-35"></a>
### Practice 32b-2 — SimpleImputer without leakage

Using `sales_df` from section 32: split into train/test (`test_size=0.3, random_state=1`), fit a
`SimpleImputer(strategy="median", add_indicator=True)` on the numeric train columns only, and transform both sets.
Print the learned medians.

> 🧩 *Re-creates the data this problem uses (exactly as it was at this point of the lesson).*

In [40]:
sales_data = {
    "Customer": ["Ali", "Sara", "Ahmed", "Usman", "Ayesha", "Hamza", "Zain", "Hina", "Bilal", "Mariam"],
    "Age": [25, np.nan, 31, 29, np.nan, 42, 35, 28, np.nan, 30],
    "Salary": [50000, 65000, np.nan, 72000, 58000, np.nan, 80000, 55000, 62000, np.nan],
    "Department": ["IT", "HR", "IT", np.nan, "Finance", "IT", "Finance", "HR", np.nan, "IT"],
    "City": ["Lahore", "Karachi", "Lahore", "Islamabad", np.nan, "Karachi", "Lahore", "Karachi", "Islamabad", np.nan],
    "Experience": [2, 5, np.nan, 7, 3, np.nan, 10, 4, 6, np.nan]
}

sales_df = pd.DataFrame(sales_data)
print(sales_df)

  Customer   Age   Salary Department       City  Experience
0      Ali  25.0  50000.0         IT     Lahore         2.0
1     Sara   NaN  65000.0         HR    Karachi         5.0
2    Ahmed  31.0      NaN         IT     Lahore         NaN
3    Usman  29.0  72000.0        NaN  Islamabad         7.0
4   Ayesha   NaN  58000.0    Finance        NaN         3.0
5    Hamza  42.0      NaN         IT    Karachi         NaN
6     Zain  35.0  80000.0    Finance     Lahore        10.0
7     Hina  28.0  55000.0         HR    Karachi         4.0
8    Bilal   NaN  62000.0        NaN  Islamabad         6.0
9   Mariam  30.0      NaN         IT        NaN         NaN

In [41]:
# ✍️ Your answer here
data_df = sales_df[["Age","Salary","Experience"]];

X_train ,X_test =train_test_split(data_df,test_size=3,
    random_state=1)
# print(X_test)
imp = SimpleImputer(
    strategy="median",
    add_indicator=True
)
imp.fit(X_train)
print(imp.statistics_)
print(imp.get_feature_names_out())
imp.transform(X_test)

pd.DataFrame(
    imp.transform(X_test),
    columns=imp.get_feature_names_out(),
    index=X_test.index
)

[2.85e+01 6.00e+04 4.50e+00]
['Age' 'Salary' 'Experience' 'missingindicator_Age'
 'missingindicator_Salary' 'missingindicator_Experience']

,Age,Salary,Experience,missingindicator_Age,missingindicator_Salary,missingindicator_Experience
2,31.0,60000.0,4.5,0.0,1.0,1.0
9,30.0,60000.0,4.5,0.0,1.0,1.0
6,35.0,80000.0,10.0,0.0,0.0,0.0

<a id="p-36"></a>
### Practice 32b-3 — KNN vs median

On the numeric columns of `sales_df`, fill `Salary` with (a) the median and (b) `KNNImputer(n_neighbors=3)`.
Show both versions side by side for the rows where `Salary` was missing.

In [42]:
# ✍️ Your answer here

<a id="p-37"></a>
## 33. Advanced Decision-Making Challenge

For each situation, decide the technique you would use and explain why in comments.

1. `Salary` has 2% missing values and several very high salaries.
2. `City` has 1% missing values.
3. Hourly sensor temperatures have gaps between known readings.
4. A column is 95% missing.
5. A row contains only 1 valid value out of 10 columns.
6. `Department` is missing and should not be guessed.

Think about the meaning of the missing data, not just the Pandas syntax.

## 33 — Advanced decision-making (suggested answers)

1. **Salary, 2% missing, some very high values** → median (robust to the outliers), or group median by Department.
2. **City, 1% missing** → mode, or `"Unknown"` if guessing would be misleading.
3. **Hourly sensor temperatures with gaps** → `interpolate()` (time-ordered, smooth signal); `ffill` for short gaps.
4. **Column 95% missing** → usually drop it; if the fact of being missing matters, keep only a 0/1 "has value" flag.
5. **Row with 1 of 10 values** → drop the row (`dropna(thresh=...)`) — filling 9 values would mostly be invention.
6. **Department missing and must not be guessed** → fill with `"Unknown"` (a separate category), never the mode.

<a id="p-38"></a>
# 34. Final Exam — No Hints

Create a new DataFrame with at least 15 rows and these columns:

- `Name`
- `Age`
- `Salary`
- `Department`
- `City`
- `Experience`
- `Performance`

Intentionally include missing values.

### Part A — Detection
- Inspect the DataFrame.
- Count missing values.
- Calculate percentages.
- Identify incomplete rows.

### Part B — Cleaning
- Remove rows using `dropna()` in one experiment.
- Fill numerical columns using appropriate statistics.
- Fill categorical columns using an appropriate strategy.
- Demonstrate `ffill()`.
- Demonstrate `bfill()`.
- Demonstrate interpolation on a numerical Series.

### Part C — Advanced
- Use group-based imputation.
- Compare mean vs median.
- Create a before/after missing-value report.

### Part D — Verification
- Confirm remaining missing values.
- Display the final cleaned dataset.

Try to complete this section without referring back to earlier cells.

In [43]:
data =pd.read_csv("../data/sales_data.csv")
# print(data.info())
print(pd.DataFrame({
    "total":data.isna().sum(),"percent":data.isna().mean()}
))
print(data[data.isna().any(axis=1)])

             total  percent
Name             0     0.00
Age              3     0.15
Salary           5     0.25
Department       3     0.15
City             3     0.15
Experience       4     0.20
Performance      5     0.25
      Name   Age    Salary Department       City  Experience  Performance
1     Sara  30.0       NaN         HR    Karachi         5.0         91.0
2    Ahmed   NaN   72000.0    Finance  Islamabad         NaN         88.0
3   Ayesha  28.0   68000.0        NaN     Lahore         4.0         76.0
4    Bilal  35.0   95000.0         IT        NaN        10.0         88.0
5     Hina  24.0   48000.0  Marketing    Karachi         1.0          NaN
6    Usman  40.0       NaN    Finance     Lahore        15.0         95.0
7   Zainab  32.0   82000.0         IT  Islamabad         7.0          NaN
8    Hamza   NaN   60000.0        NaN    Karachi         NaN         73.0
9   Mariam  29.0       NaN         HR        NaN         6.0         85.0
12  Hassan  31.0   75000.0    Finance    Karachi         8.0          NaN
13    Noor   NaN   65000.0         IT     Lahore         NaN         89.0
14  Danish  38.0       NaN         HR  Islamabad        12.0         92.0
15    Sana  26.0   47000.0        NaN    Karachi         2.0         71.0
16    Saad  34.0   88000.0         IT        NaN         9.0          NaN
17    Iqra  23.0       NaN  Marketing     Lahore         1.0         80.0
18   Fahad  42.0  120000.0    Finance    Karachi         NaN         94.0
19    Amna  30.0   70000.0         HR  Islamabad         6.0          NaN

> 🔗 **Related topics (FIX-2026-09-27)**
> - **Topic 5 — Outliers**: why the median is safer than the mean when extreme values exist.
> - **Topic 7 — EDA**: missing-value heatmaps and patterns as part of a full data audit.
> - **Topic 17 — Machine Learning**: imputers inside `Pipeline` + `ColumnTransformer` (no leakage).

## 34 — Final Exam (reference solution)

In [44]:
rng = np.random.default_rng(3)
n = 16
exam = pd.DataFrame({
    "Name": [f"Emp{i:02d}" for i in range(1, n + 1)],
    "Age": rng.integers(22, 58, n).astype(float),
    "Salary": rng.normal(90000, 25000, n).round(-3),
    "Department": rng.choice(["IT", "HR", "Finance"], n),
    "City": rng.choice(["Lahore", "Karachi", "Islamabad"], n),
    "Experience": rng.integers(0, 25, n).astype(float),
    "Performance": rng.normal(3.5, 0.6, n).round(1),
}).astype({"Department": object, "City": object})
exam.loc[15, "Salary"] = 450000                             # one extreme salary
for col, rows in {"Age": [1, 7], "Salary": [3, 9, 12], "Department": [4, 10],
                  "City": [2, 13], "Experience": [5], "Performance": [6, 11]}.items():
    exam.loc[rows, col] = np.nan

# Part A — detection
before = pd.DataFrame({"count": exam.isna().sum(), "pct": (exam.isna().mean() * 100).round(1)})
print(before)
print("incomplete rows:", exam.index[exam.isna().any(axis=1)].tolist())

# Part B — cleaning
print("dropna experiment keeps", len(exam.dropna()), "of", len(exam), "rows")
clean = exam.copy()
print("Salary mean vs median:", round(exam["Salary"].mean()), exam["Salary"].median())   # Part C comparison
clean["Salary"] = clean.groupby("Department")["Salary"].transform(lambda s: s.fillna(s.median()))  # group-based
clean["Salary"] = clean["Salary"].fillna(clean["Salary"].median())       # rows whose Department was missing
clean["Age"] = clean["Age"].fillna(clean["Age"].median())
clean["Experience"] = clean["Experience"].fillna(clean["Experience"].median())
clean["Department"] = clean["Department"].fillna("Unknown")
clean["City"] = clean["City"].fillna(clean["City"].mode()[0])
clean["Performance"] = clean["Performance"].interpolate()                  # interpolation demo

demo = pd.Series([1.0, np.nan, np.nan, 4.0])
print("ffill:", demo.ffill().tolist(), "bfill:", demo.bfill().tolist())

# Part C/D — before/after report + verification
print(pd.DataFrame({"before": exam.isna().sum(), "after": clean.isna().sum()}))
clean

             count   pct
Name             0   0.0
Age              2  12.5
Salary           3  18.8
Department       2  12.5
City             2  12.5
Experience       1   6.2
Performance      2  12.5
incomplete rows: [1, 2, 3, 4, 5, 6, 7, 9, 10, 11, 12, 13]
dropna experiment keeps 4 of 16 rows
Salary mean vs median: 124692 96000.0
ffill: [1.0, 1.0, 1.0, 4.0] bfill: [1.0, 4.0, 4.0, 4.0]
             before  after
Name              0      0
Age               2      0
Salary            3      0
Department        2      0
City              2      0
Experience        1      0
Performance       2      0

     Name   Age    Salary Department       City  Experience  Performance
0   Emp01  51.0   68000.0         IT    Karachi         9.0         3.90
1   Emp02  32.0  173000.0    Finance    Karachi        20.0         3.60
2   Emp03  28.0   96000.0         HR    Karachi        21.0         4.20
3   Emp04  30.0   99000.0         HR  Islamabad        16.0         3.40
4   Emp05  28.0   97500.0    Unknown  Islamabad         0.0         2.90
5   Emp06  50.0   73000.0         HR     Lahore        16.0         3.90
6   Emp07  53.0   64000.0         IT    Karachi         5.0         3.65
7   Emp08  32.0   80000.0    Finance    Karachi        20.0         3.40
8   Emp09  23.0  102000.0         HR     Lahore        22.0         3.00
9   Emp10  25.0   86000.0         IT     Lahore        10.0         3.60
10  Emp11  33.0   97500.0    Unknown    Karachi        23.0         2.00
11  Emp12  37.0   85000.0    Finance  Islamabad        18.0         2.90
12  Emp13  44.0   99000.0         HR     Lahore         8.0         3.80
13  Emp14  39.0  129000.0         HR    Karachi        21.0         2.50
14  Emp15  31.0  104000.0         IT    Karachi         9.0         3.50
15  Emp16  27.0  450000.0         IT     Lahore         2.0         2.90

The mean salary is pulled up by the 450,000 outlier while the median is not — so salary gaps were filled with the
department **median**, which is the robust choice (see Topic 5).